# 4. Basic pandas optimizations

Bab ini menawarkan pengantar singkat tentang cara bekerja secara efisien dengan pandas DataFrames. Anda akan mempelajari berbagai opsi yang Anda miliki untuk iterasi melalui DataFrame. Kemudian, Anda akan belajar cara menerapkan fungsi secara efisien ke data yang disimpan dalam DataFrame.

## Intro to pandas DataFrame iteration

### pandas recap

* Lihat ikhtisar pandas di [Intermediate Python for Data Science](https://github.com/tommypratama/datacamp/tree/master/Intermediate%20Python%20for%20Data%20Science)
* Library yang digunakan untuk analisis data
* Struktur data utama adalah DataFrame
  * Data tabular dengan baris dan kolom berlabel
  * Dibangun di atas struktur NumPy array
* Tujuan Bab:
  * Praktik terbaik untuk iterasi melalui pandas DataFrame

### Baseball stats

In [164]:
import pandas as pd

baseball_df = pd.read_csv("datasets/baseball_stats.csv", usecols=['Team', 'League', 'Year', 'RS', 'RA', 'W', 'G', 'Playoffs'])
baseball_df.head()

  Team League  Year   RS   RA   W  Playoffs    G
0  ARI     NL  2012  734  688  81         0  162
1  ATL     NL  2012  700  600  94         1  162
2  BAL     AL  2012  712  705  93         1  162
3  BOS     AL  2012  734  806  69         0  162
4  CHC     NL  2012  613  759  61         0  162

### Calculating win percentage

In [13]:
import numpy as np

def calc_win_perc(wins, games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)

In [14]:
win_perc = calc_win_perc(50, 100)
print(win_perc)

0.5

### Adding win percentage to DataFrame

In [15]:
win_perc_list = []

for i in range(len(baseball_df)):
    row = baseball_df.iloc[i]
    
    wins = row['W']
    games_played = row['G']
    
    win_perc = calc_win_perc(wins, games_played)
    win_perc_list.append(win_perc)
    
baseball_df['WP'] = win_perc_list

In [16]:
baseball_df.head()

  Team League  Year   RS   RA   W  Playoffs    G    WP
0  ARI     NL  2012  734  688  81         0  162  0.50
1  ATL     NL  2012  700  600  94         1  162  0.58
2  BAL     AL  2012  712  705  93         1  162  0.57
3  BOS     AL  2012  734  806  69         0  162  0.43
4  CHC     NL  2012  613  759  61         0  162  0.38

### Iterating with .iloc

In [17]:
%%timeit
win_perc_list = []

for i in range(len(baseball_df)):
    row = baseball_df.iloc[i]
    
    wins = row['W']
    games_played = row['G']
    
    win_perc = calc_win_perc(wins, games_played)
    win_perc_list.append(win_perc)
    
baseball_df['WP'] = win_perc_list

254 ms ± 2.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### Iterating with .iterrows()

In [21]:
win_perc_list = []

for i,row in baseball_df.iterrows():
    wins = row['W']
    games_played = row['G']
    
    win_perc = calc_win_perc(wins, games_played)
    win_perc_list.append(win_perc)
    
baseball_df['WP'] = win_perc_list

In [23]:
%%timeit
win_perc_list = []

for i,row in baseball_df.iterrows():
    wins = row['W']
    games_played = row['G']
    
    win_perc = calc_win_perc(wins, games_played)
    win_perc_list.append(win_perc)
    
baseball_df['WP'] = win_perc_list

159 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

### Practice: Iterating with .iterrows()

`.iterrows()` mengembalikan setiap baris DataFrame sebagai pasangan tuple (indeks, pandas Series). Tapi apa artinya ini? Mari kita jelajahi dengan beberapa latihan coding.

DataFrame pandas telah dimuat sebagai `pit_df`. DataFrame ini berisi statistik untuk tim Baseball Liga Utama bernama Pittsburgh Pirates (disingkat `'PIT'`) dari tahun 2008 hingga tahun 2012.

In [27]:
# Create dataframe
pit_df = baseball_df[['Team', 'League', 'Year', 'RS', 'RA', 'W', 'G', 'Playoffs']]

In [32]:
# Iterate over pit_df and print each row
for i,row in pit_df.iterrows():
    print(row)

Team         ARI
League        NL
Year        2012
RS           734
RA           688
W             81
G            162
Playoffs       0
Name: 0, dtype: object
Team         ATL
League        NL
Year        2012
RS           700
RA           600
W             94
G            162
Playoffs       1
Name: 1, dtype: object
Team         BAL
League        AL
Year        2012
RS           712
RA           705
W             93
G            162
Playoffs       1
Name: 2, dtype: object
Team         BOS
League        AL
Year        2012
RS           734
RA           806
W             69
G            162
Playoffs       0
Name: 3, dtype: object
Team         CHC
League        NL
Year        2012
RS           613
RA           759
W             61
G            162
Playoffs       0
Name: 4, dtype: object
Team         CHW
League        AL
Year        2012
RS           748
RA           676
W             85
G            162
Playoffs       0
Name: 5, dtype: object
Team         CIN
League        NL
Year        2012
RS           669
RA           588
W             97
G            162
Playoffs       1
Name: 6, dtype: object
Team         CLE
League        AL
Year        2012
RS           667
RA           845
W             68
G            162
Playoffs       0
Name: 7, dtype: object
Team         COL
League        NL
Year        2012
RS           758
RA           890
W             64
G            162
Playoffs       0
Name: 8, dtype: object
Team         DET
League        AL
Year        2012
RS           726
RA           670
W             88
G            162
Playoffs       1
Name: 9, dtype: object
Team         HOU
League        NL
Year        2012
RS           583
RA           794
W             55
G            162
Playoffs       0
Name: 10, dtype: object
Team         KCR
League        AL
Year        2012
RS           676
RA           746
W             72
G            162
Playoffs       0
Name: 11, dtype: object
Team         LAA
League        AL
Year        2012
RS           767
RA           699
W             89
G            162
Playoffs       0
Name: 12, dtype: object
Team         LAD
League        NL
Year        2012
RS           637
RA           597
W             86
G            162
Playoffs       0
Name: 13, dtype: object
Team         MIA
League        NL
Year        2012
RS           609
RA           724
W             69
G            162
Playoffs       0
Name: 14, dtype: object
Team         MIL
League        NL
Year        2012
RS           776
RA           733
W             83
G            162
Playoffs       0
Name: 15, dtype: object
Team         MIN
League        AL
Year        2012
RS           701
RA           832
W             66
G            162
Playoffs       0
Name: 16, dtype: object
Team         NYM
League        NL
Year        2012
RS           650
RA           709
W             74
G            162
Playoffs       0
Name: 17, dtype: object
Team         NYY
League        AL
Year        2012
RS           804
RA           668
W             95
G            162
Playoffs       1
Name: 18, dtype: object
Team         OAK
League        AL
Year        2012
RS           713
RA           614
W             94
G            162
Playoffs       1
Name: 19, dtype: object
Team         PHI
League        NL
Year        2012
RS           684
RA           680
W             81
G            162
Playoffs       0
Name: 20, dtype: object
Team         PIT
League        NL
Year        2012
RS           651
RA           674
W             79
G            162
Playoffs       0
Name: 21, dtype: object
Team         SDP
League        NL
Year        2012
RS           651
RA           710
W             76
G            162
Playoffs       0
Name: 22, dtype: object
Team         SEA
League        AL
Year        2012
RS           619
RA           651
W             75
G            162
Playoffs       0
Name: 23, dtype: object
Team         SFG
League        NL
Year        2012
RS           718
RA           649
W             94
G            162
Playoffs       1
Name: 24, dtype: object
Team         STL
League        NL
Year        2012
RS           765
RA           648
W             88
G            162
Playoffs       1
Name: 25, dtype: object
Team         TBR
League        AL
Year        2012
RS           697
RA           577
W             90
G            162
Playoffs       0
Name: 26, dtype: object
Team         TEX
League        AL
Year        2012
RS           808
RA           707
W             93
G            162
Playoffs       1
Name: 27, dtype: object
Team         TOR
League        AL
Year        2012
RS           716
RA           784
W             73
G            162
Playoffs       0
Name: 28, dtype: object
Team         WSN
League        NL
Year        2012
RS           731
RA           594
W             98
G            162
Playoffs       1
Name: 29, dtype: object
Team         ARI
League        NL
Year        2011
RS           731
RA           662
W             94
G            162
Playoffs       1
Name: 30, dtype: object
Team         ATL
League        NL
Year        2011
RS           641
RA           605
W             89
G            162
Playoffs       0
Name: 31, dtype: object
Team         BAL
League        AL
Year        2011
RS           708
RA           860
W             69
G            162
Playoffs       0
Name: 32, dtype: object
Team         BOS
League        AL
Year        2011
RS           875
RA           737
W             90
G            162
Playoffs       0
Name: 33, dtype: object
Team         CHC
League        NL
Year        2011
RS           654
RA           756
W             71
G            162
Playoffs       0
Name: 34, dtype: object
Team         CHW
League        AL
Year        2011
RS           654
RA           706
W             79
G            162
Playoffs       0
Name: 35, dtype: object
Team         CIN
League        NL
Year        2011
RS           735
RA           720
W             79
G            162
Playoffs       0
Name: 36, dtype: object
Team         CLE
League        AL
Year        2011
RS           704
RA           760
W             80
G            162
Playoffs       0
Name: 37, dtype: object
Team         COL
League        NL
Year        2011
RS           735
RA           774
W             73
G            162
Playoffs       0
Name: 38, dtype: object
Team         DET
League        AL
Year        2011
RS           787
RA           711
W             95
G            162
Playoffs       1
Name: 39, dtype: object
Team         FLA
League        NL
Year        2011
RS           625
RA           702
W             72
G            162
Playoffs       0
Name: 40, dtype: object
Team         HOU
League        NL
Year        2011
RS           615
RA           796
W             56
G            162
Playoffs       0
Name: 41, dtype: object
Team         KCR
League        AL
Year        2011
RS           730
RA           762
W             71
G            162
Playoffs       0
Name: 42, dtype: object
Team         LAA
League        AL
Year        2011
RS           667
RA           633
W             86
G            162
Playoffs       0
Name: 43, dtype: object
Team         LAD
League        NL
Year        2011
RS           644
RA           612
W             82
G            161
Playoffs       0
Name: 44, dtype: object
Team         MIL
League        NL
Year        2011
RS           721
RA           638
W             96
G            162
Playoffs       1
Name: 45, dtype: object
Team         MIN
League        AL
Year        2011
RS           619
RA           804
W             63
G            162
Playoffs       0
Name: 46, dtype: object
Team         NYM
League        NL
Year        2011
RS           718
RA           742
W             77
G            162
Playoffs       0
Name: 47, dtype: object
Team         NYY
League        AL
Year        2011
RS           867
RA           657
W             97
G            162
Playoffs       1
Name: 48, dtype: object
Team         OAK
League        AL
Year        2011
RS           645
RA           679
W             74
G            162
Playoffs       0
Name: 49, dtype: object
Team         PHI
League        NL
Year        2011
RS           713
RA           529
W            102
G            162
Playoffs       1
Name: 50, dtype: object
Team         PIT
League        NL
Year        2011
RS           610
RA           712
W             72
G            162
Playoffs       0
Name: 51, dtype: object
Team         SDP
League        NL
Year        2011
RS           593
RA           611
W             71
G            162
Playoffs       0
Name: 52, dtype: object
Team         SEA
League        AL
Year        2011
RS           556
RA           675
W             67
G            162
Playoffs       0
Name: 53, dtype: object
Team         SFG
League        NL
Year        2011
RS           570
RA           578
W             86
G            162
Playoffs       0
Name: 54, dtype: object
Team         STL
League        NL
Year        2011
RS           762
RA           692
W             90
G            162
Playoffs       1
Name: 55, dtype: object
Team         TBR
League        AL
Year        2011
RS           707
RA           614
W             91
G            162
Playoffs       1
Name: 56, dtype: object
Team         TEX
League        AL
Year        2011
RS           855
RA           677
W             96
G            162
Playoffs       1
Name: 57, dtype: object
Team         TOR
League        AL
Year        2011
RS           743
RA           761
W             81
G            162
Playoffs       0
Name: 58, dtype: object
Team         WSN
League        NL
Year        2011
RS           624
RA           643
W             80
G            161
Playoffs       0
Name: 59, dtype: object
Team         ARI
League        NL
Year        2010
RS           713
RA           836
W             65
G            162
Playoffs       0
Name: 60, dtype: object
Team         ATL
League        NL
Year        2010
RS           738
RA           629
W             91
G            162
Playoffs       1
Name: 61, dtype: object
Team         BAL
League        AL
Year        2010
RS           613
RA           785
W             66
G            162
Playoffs       0
Name: 62, dtype: object
Team         BOS
League        AL
Year        2010
RS           818
RA           744
W             89
G            162
Playoffs       0
Name: 63, dtype: object
Team         CHC
League        NL
Year        2010
RS           685
RA           767
W             75
G            162
Playoffs       0
Name: 64, dtype: object
Team         CHW
League        AL
Year        2010
RS           752
RA           704
W             88
G            162
Playoffs       0
Name: 65, dtype: object
Team         CIN
League        NL
Year        2010
RS           790
RA           685
W             91
G            162
Playoffs       1
Name: 66, dtype: object
Team         CLE
League        AL
Year        2010
RS           646
RA           752
W             69
G            162
Playoffs       0
Name: 67, dtype: object
Team         COL
League        NL
Year        2010
RS           770
RA           717
W             83
G            162
Playoffs       0
Name: 68, dtype: object
Team         DET
League        AL
Year        2010
RS           751
RA           743
W             81
G            162
Playoffs       0
Name: 69, dtype: object
Team         FLA
League        NL
Year        2010
RS           719
RA           717
W             80
G            162
Playoffs       0
Name: 70, dtype: object
Team         HOU
League        NL
Year        2010
RS           611
RA           729
W             76
G            162
Playoffs       0
Name: 71, dtype: object
Team         KCR
League        AL
Year        2010
RS           676
RA           845
W             67
G            162
Playoffs       0
Name: 72, dtype: object
Team         LAA
League        AL
Year        2010
RS           681
RA           702
W             80
G            162
Playoffs       0
Name: 73, dtype: object
Team         LAD
League        NL
Year        2010
RS           667
RA           692
W             80
G            162
Playoffs       0
Name: 74, dtype: object
Team         MIL
League        NL
Year        2010
RS           750
RA           804
W             77
G            162
Playoffs       0
Name: 75, dtype: object
Team         MIN
League        AL
Year        2010
RS           781
RA           671
W             94
G            162
Playoffs       1
Name: 76, dtype: object
Team         NYM
League        NL
Year        2010
RS           656
RA           652
W             79
G            162
Playoffs       0
Name: 77, dtype: object
Team         NYY
League        AL
Year        2010
RS           859
RA           693
W             95
G            162
Playoffs       1
Name: 78, dtype: object
Team         OAK
League        AL
Year        2010
RS           663
RA           626
W             81
G            162
Playoffs       0
Name: 79, dtype: object
Team         PHI
League        NL
Year        2010
RS           772
RA           640
W             97
G            162
Playoffs       1
Name: 80, dtype: object
Team         PIT
League        NL
Year        2010
RS           587
RA           866
W             57
G            162
Playoffs       0
Name: 81, dtype: object
Team         SDP
League        NL
Year        2010
RS           665
RA           581
W             90
G            162
Playoffs       0
Name: 82, dtype: object
Team         SEA
League        AL
Year        2010
RS           513
RA           698
W             61
G            162
Playoffs       0
Name: 83, dtype: object
Team         SFG
League        NL
Year        2010
RS           697
RA           583
W             92
G            162
Playoffs       1
Name: 84, dtype: object
Team         STL
League        NL
Year        2010
RS           736
RA           641
W             86
G            162
Playoffs       0
Name: 85, dtype: object
Team         TBR
League        AL
Year        2010
RS           802
RA           649
W             96
G            162
Playoffs       1
Name: 86, dtype: object
Team         TEX
League        AL
Year        2010
RS           787
RA           687
W             90
G            162
Playoffs       1
Name: 87, dtype: object
Team         TOR
League        AL
Year        2010
RS           755
RA           728
W             85
G            162
Playoffs       0
Name: 88, dtype: object
Team         WSN
League        NL
Year        2010
RS           655
RA           742
W             69
G            162
Playoffs       0
Name: 89, dtype: object
Team         ARI
League        NL
Year        2009
RS           720
RA           782
W             70
G            162
Playoffs       0
Name: 90, dtype: object
Team         ATL
League        NL
Year        2009
RS           735
RA           641
W             86
G            162
Playoffs       0
Name: 91, dtype: object
Team         BAL
League        AL
Year        2009
RS           741
RA           876
W             64
G            162
Playoffs       0
Name: 92, dtype: object
Team         BOS
League        AL
Year        2009
RS           872
RA           736
W             95
G            162
Playoffs       1
Name: 93, dtype: object
Team         CHC
League        NL
Year        2009
RS           707
RA           672
W             83
G            161
Playoffs       0
Name: 94, dtype: object
Team         CHW
League        AL
Year        2009
RS           724
RA           732
W             79
G            162
Playoffs       0
Name: 95, dtype: object
Team         CIN
League        NL
Year        2009
RS           673
RA           723
W             78
G            162
Playoffs       0
Name: 96, dtype: object
Team         CLE
League        AL
Year        2009
RS           773
RA           865
W             65
G            162
Playoffs       0
Name: 97, dtype: object
Team         COL
League        NL
Year        2009
RS           804
RA           715
W             92
G            162
Playoffs       1
Name: 98, dtype: object
Team         DET
League        AL
Year        2009
RS           743
RA           745
W             86
G            163
Playoffs       0
Name: 99, dtype: object
Team         FLA
League        NL
Year        2009
RS           772
RA           766
W             87
G            162
Playoffs       0
Name: 100, dtype: object
Team         HOU
League        NL
Year        2009
RS           643
RA           770
W             74
G            162
Playoffs       0
Name: 101, dtype: object
Team         KCR
League        AL
Year        2009
RS           686
RA           842
W             65
G            162
Playoffs       0
Name: 102, dtype: object
Team         LAA
League        AL
Year        2009
RS           883
RA           761
W             97
G            162
Playoffs       1
Name: 103, dtype: object
Team         LAD
League        NL
Year        2009
RS           780
RA           611
W             95
G            162
Playoffs       1
Name: 104, dtype: object
Team         MIL
League        NL
Year        2009
RS           785
RA           818
W             80
G            162
Playoffs       0
Name: 105, dtype: object
Team         MIN
League        AL
Year        2009
RS           817
RA           765
W             87
G            163
Playoffs       1
Name: 106, dtype: object
Team         NYM
League        NL
Year        2009
RS           671
RA           757
W             70
G            162
Playoffs       0
Name: 107, dtype: object
Team         NYY
League        AL
Year        2009
RS           915
RA           753
W            103
G            162
Playoffs       1
Name: 108, dtype: object
Team         OAK
League        AL
Year        2009
RS           759
RA           761
W             75
G            162
Playoffs       0
Name: 109, dtype: object
Team         PHI
League        NL
Year        2009
RS           820
RA           709
W             93
G            162
Playoffs       1
Name: 110, dtype: object
Team         PIT
League        NL
Year        2009
RS           636
RA           768
W             62
G            161
Playoffs       0
Name: 111, dtype: object
Team         SDP
League        NL
Year        2009
RS           638
RA           769
W             75
G            162
Playoffs       0
Name: 112, dtype: object
Team         SEA
League        AL
Year        2009
RS           640
RA           692
W             85
G            162
Playoffs       0
Name: 113, dtype: object
Team         SFG
League        NL
Year        2009
RS           657
RA           611
W             88
G            162
Playoffs       0
Name: 114, dtype: object
Team         STL
League        NL
Year        2009
RS           730
RA           640
W             91
G            162
Playoffs       1
Name: 115, dtype: object
Team         TBR
League        AL
Year        2009
RS           803
RA           754
W             84
G            162
Playoffs       0
Name: 116, dtype: object
Team         TEX
League        AL
Year        2009
RS           784
RA           740
W             87
G            162
Playoffs       0
Name: 117, dtype: object
Team         TOR
League        AL
Year        2009
RS           798
RA           771
W             75
G            162
Playoffs       0
Name: 118, dtype: object
Team         WSN
League        NL
Year        2009
RS           710
RA           874
W             59
G            162
Playoffs       0
Name: 119, dtype: object
Team         ARI
League        NL
Year        2008
RS           720
RA           706
W             82
G            162
Playoffs       0
Name: 120, dtype: object
Team         ATL
League        NL
Year        2008
RS           753
RA           778
W             72
G            162
Playoffs       0
Name: 121, dtype: object
Team         BAL
League        AL
Year        2008
RS           782
RA           869
W             68
G            161
Playoffs       0
Name: 122, dtype: object
Team         BOS
League        AL
Year        2008
RS           845
RA           694
W             95
G            162
Playoffs       1
Name: 123, dtype: object
Team         CHC
League        NL
Year        2008
RS           855
RA           671
W             97
G            161
Playoffs       1

Name: 257, dtype: object
Team         NYM
League        NL
Year        2004
RS           684
RA           731
W             71
G            162
Playoffs       0
Name: 258, dtype: object
Team         NYY
League        AL
Year        2004
RS           897
RA           808
W            101
G            162
Playoffs       1
Name: 259, dtype: object
Team         OAK
League        AL
Year        2004
RS           793
RA           742
W             91
G            162
Playoffs       0
Name: 260, dtype: object
Team         PHI
League        NL
Year        2004
RS           840
RA           781
W             86
G            162
Playoffs       0
Name: 261, dtype: object
Team         PIT
League        NL
Year        2004
RS           680
RA           744
W             72
G            161
Playoffs       0
Name: 262, dtype: object
Team         SDP
League        NL
Year        2004
RS           768
RA           705
W             87
G            162
Playoffs       0
Name: 263, dtype: object
Team         SEA
League        AL
Year        2004
RS           698
RA           823
W             63
G            162
Playoffs       0
Name: 264, dtype: object
Team         SFG
League        NL
Year        2004
RS           850
RA           770
W             91
G            162
Playoffs       0
Name: 265, dtype: object
Team         STL
League        NL
Year        2004
RS           855
RA           659
W            105
G            162
Playoffs       1
Name: 266, dtype: object
Team         TBD
League        AL
Year        2004
RS           714
RA           842
W             70
G            161
Playoffs       0
Name: 267, dtype: object
Team         TEX
League        AL
Year        2004
RS           860
RA           794
W             89
G            162
Playoffs       0
Name: 268, dtype: object
Team         TOR
League        AL
Year        2004
RS           719
RA           823
W             67
G            161
Playoffs       0
Name: 269, dtype: object
Team         ANA
League        AL
Year        2003
RS           736
RA           743
W             77
G            162
Playoffs       0
Name: 270, dtype: object
Team         ARI
League        NL
Year        2003
RS           717
RA           685
W             84
G            162
Playoffs       0
Name: 271, dtype: object
Team         ATL
League        NL
Year        2003
RS           907
RA           740
W            101
G            162
Playoffs       1
Name: 272, dtype: object
Team         BAL
League        AL
Year        2003
RS           743
RA           820
W             71
G            163
Playoffs       0
Name: 273, dtype: object
Team         BOS
League        AL
Year        2003
RS           961
RA           809
W             95
G            162
Playoffs       1
Name: 274, dtype: object
Team         CHC
League        NL
Year        2003
RS           724
RA           683
W             88
G            162
Playoffs       1
Name: 275, dtype: object
Team         CHW
League        AL
Year        2003
RS           791
RA           715
W             86
G            162
Playoffs       0
Name: 276, dtype: object
Team         CIN
League        NL
Year        2003
RS           694
RA           886
W             69
G            162
Playoffs       0
Name: 277, dtype: object
Team         CLE
League        AL
Year        2003
RS           699
RA           778
W             68
G            162
Playoffs       0
Name: 278, dtype: object
Team         COL
League        NL
Year        2003
RS           853
RA           892
W             74
G            162
Playoffs       0
Name: 279, dtype: object
Team         DET
League        AL
Year        2003
RS           591
RA           928
W             43
G            162
Playoffs       0
Name: 280, dtype: object
Team         FLA
League        NL
Year        2003
RS           751
RA           692
W             91
G            162
Playoffs       1
Name: 281, dtype: object
Team         HOU
League        NL
Year        2003
RS           805
RA           677
W             87
G            162
Playoffs       0
Name: 282, dtype: object
Team         KCR
League        AL
Year        2003
RS           836
RA           867
W             83
G            162
Playoffs       0
Name: 283, dtype: object
Team         LAD
League        NL
Year        2003
RS           574
RA           556
W             85
G            162
Playoffs       0
Name: 284, dtype: object
Team         MIL
League        NL
Year        2003
RS           714
RA           873
W             68
G            162
Playoffs       0
Name: 285, dtype: object
Team         MIN
League        AL
Year        2003
RS           801
RA           758
W             90
G            162
Playoffs       1
Name: 286, dtype: object
Team         MON
League        NL
Year        2003
RS           711
RA           716
W             83
G            162
Playoffs       0
Name: 287, dtype: object
Team         NYM
League        NL
Year        2003
RS           642
RA           754
W             66
G            161
Playoffs       0
Name: 288, dtype: object
Team         NYY
League        AL
Year        2003
RS           877
RA           716
W            101
G            163
Playoffs       1
Name: 289, dtype: object
Team         OAK
League        AL
Year        2003
RS           768
RA           643
W             96
G            162
Playoffs       1
Name: 290, dtype: object
Team         PHI
League        NL
Year        2003
RS           791
RA           697
W             86
G            162
Playoffs       0
Name: 291, dtype: object
Team         PIT
League        NL
Year        2003
RS           753
RA           801
W             75
G            162
Playoffs       0
Name: 292, dtype: object
Team         SDP
League        NL
Year        2003
RS           678
RA           831
W             64
G            162
Playoffs       0
Name: 293, dtype: object
Team         SEA
League        AL
Year        2003
RS           795
RA           637
W             93
G            162
Playoffs       0
Name: 294, dtype: object
Team         SFG
League        NL
Year        2003
RS           755
RA           638
W            100
G            161
Playoffs       1
Name: 295, dtype: object
Team         STL
League        NL
Year        2003
RS           876
RA           796
W             85
G            162
Playoffs       0
Name: 296, dtype: object
Team         TBD
League        AL
Year        2003
RS           715
RA           852
W             63
G            162
Playoffs       0
Name: 297, dtype: object
Team         TEX
League        AL
Year        2003
RS           826
RA           969
W             71
G            162
Playoffs       0
Name: 298, dtype: object
Team         TOR
League        AL
Year        2003
RS           894
RA           826
W             86
G            162
Playoffs       0
Name: 299, dtype: object
Team         ANA
League        AL
Year        2002
RS           851
RA           644
W             99
G            162
Playoffs       1
Name: 300, dtype: object
Team         ARI
League        NL
Year        2002
RS           819
RA           674
W             98
G            162
Playoffs       1
Name: 301, dtype: object
Team         ATL
League        NL
Year        2002
RS           708
RA           565
W            101
G            161
Playoffs       1
Name: 302, dtype: object
Team         BAL
League        AL
Year        2002
RS           667
RA           773
W             67
G            162
Playoffs       0
Name: 303, dtype: object
Team         BOS
League        AL
Year        2002
RS           859
RA           665
W             93
G            162
Playoffs       0
Name: 304, dtype: object
Team         CHC
League        NL
Year        2002
RS           706
RA           759
W             67
G            162
Playoffs       0
Name: 305, dtype: object
Team         CHW
League        AL
Year        2002
RS           856
RA           798
W             81
G            162
Playoffs       0
Name: 306, dtype: object
Team         CIN
League        NL
Year        2002
RS           709
RA           774
W             78
G            162
Playoffs       0
Name: 307, dtype: object
Team         CLE
League        AL
Year        2002
RS           739
RA           837
W             74
G            162
Playoffs       0
Name: 308, dtype: object
Team         COL
League        NL
Year        2002
RS           778
RA           898
W             73
G            162
Playoffs       0
Name: 309, dtype: object
Team         DET
League        AL
Year        2002
RS           575
RA           864
W             55
G            161
Playoffs       0
Name: 310, dtype: object
Team         FLA
League        NL
Year        2002
RS           699
RA           763
W             79
G            162
Playoffs       0
Name: 311, dtype: object
Team         HOU
League        NL
Year        2002
RS           749
RA           695
W             84
G            162
Playoffs       0
Name: 312, dtype: object
Team         KCR
League        AL
Year        2002
RS           737
RA           891
W             62
G            162
Playoffs       0
Name: 313, dtype: object
Team         LAD
League        NL
Year        2002
RS           713
RA           643
W             92
G            162
Playoffs       0
Name: 314, dtype: object
Team         MIL
League        NL
Year        2002
RS           627
RA           821
W             56
G            162
Playoffs       0
Name: 315, dtype: object
Team         MIN
League        AL
Year        2002
RS           768
RA           712
W             94
G            161
Playoffs       1
Name: 316, dtype: object
Team         MON
League        NL
Year        2002
RS           735
RA           718
W             83
G            162
Playoffs       0
Name: 317, dtype: object
Team         NYM
League        NL
Year        2002
RS           690
RA           703
W             75
G            161
Playoffs       0
Name: 318, dtype: object
Team         NYY
League        AL
Year        2002
RS           897
RA           697
W            103
G            161
Playoffs       1
Name: 319, dtype: object
Team         OAK
League        AL
Year        2002
RS           800
RA           654
W            103
G            162
Playoffs       1
Name: 320, dtype: object
Team         PHI
League        NL
Year        2002
RS           710
RA           724
W             80
G            161
Playoffs       0
Name: 321, dtype: object
Team         PIT
League        NL
Year        2002
RS           641
RA           730
W             72
G            161
Playoffs       0
Name: 322, dtype: object
Team         SDP
League        NL
Year        2002
RS           662
RA           815
W             66
G            162
Playoffs       0
Name: 323, dtype: object
Team         SEA
League        AL
Year        2002
RS           814
RA           699
W             93
G            162
Playoffs       0
Name: 324, dtype: object
Team         SFG
League        NL
Year        2002
RS           783
RA           616
W             95
G            162
Playoffs       1
Name: 325, dtype: object
Team         STL
League        NL
Year        2002
RS           787
RA           648
W             97
G            162
Playoffs       1
Name: 326, dtype: object
Team         TBD
League        AL
Year        2002
RS           673
RA           918
W             55
G            161
Playoffs       0
Name: 327, dtype: object
Team         TEX
League        AL
Year        2002
RS           843
RA           882
W             72
G            162
Playoffs       0
Name: 328, dtype: object
Team         TOR
League        AL
Year        2002
RS           813
RA           828
W             78
G            162
Playoffs       0
Name: 329, dtype: object
Team         ANA
League        AL
Year        2001
RS           691
RA           730
W             75
G            162
Playoffs       0
Name: 330, dtype: object
Team         ARI
League        NL
Year        2001
RS           818
RA           677
W             92
G            162
Playoffs       1
Name: 331, dtype: object
Team         ATL
League        NL
Year        2001
RS           729
RA           643
W             88
G            162
Playoffs       1
Name: 332, dtype: object
Team         BAL
League        AL
Year        2001
RS           687
RA           829
W             63
G            162
Playoffs       0
Name: 333, dtype: object
Team         BOS
League        AL
Year        2001
RS           772
RA           745
W             82
G            161
Playoffs       0
Name: 334, dtype: object
Team         CHC
League        NL
Year        2001
RS           777
RA           701
W             88
G            162
Playoffs       0
Name: 335, dtype: object
Team         CHW
League        AL
Year        2001
RS           798
RA           795
W             83
G            162
Playoffs       0
Name: 336, dtype: object
Team         CIN
League        NL
Year        2001
RS           735
RA           850
W             66
G            162
Playoffs       0
Name: 337, dtype: object
Team         CLE
League        AL
Year        2001
RS           897
RA           821
W             91
G            162
Playoffs       1
Name: 338, dtype: object
Team         COL
League        NL
Year        2001
RS           923
RA           906
W             73
G            162
Playoffs       0
Name: 339, dtype: object
Team         DET
League        AL
Year        2001
RS           724
RA           876
W             66
G            162
Playoffs       0
Name: 340, dtype: object
Team         FLA
League        NL
Year        2001
RS           742
RA           744
W             76
G            162
Playoffs       0
Name: 341, dtype: object
Team         HOU
League        NL
Year        2001
RS           847
RA           769
W             93
G            162
Playoffs       1
Name: 342, dtype: object
Team         KCR
League        AL
Year        2001
RS           729
RA           858
W             65
G            162
Playoffs       0
Name: 343, dtype: object
Team         LAD
League        NL
Year        2001
RS           758
RA           744
W             86
G            162
Playoffs       0
Name: 344, dtype: object
Team         MIL
League        NL
Year        2001
RS           740
RA           806
W             68
G            162
Playoffs       0
Name: 345, dtype: object
Team         MIN
League        AL
Year        2001
RS           771
RA           766
W             85
G            162
Playoffs       0
Name: 346, dtype: object
Team         MON
League        NL
Year        2001
RS           670
RA           812
W             68
G            162
Playoffs       0
Name: 347, dtype: object
Team         NYM
League        NL
Year        2001
RS           642
RA           713
W             82
G            162
Playoffs       0
Name: 348, dtype: object
Team         NYY
League        AL
Year        2001
RS           804
RA           713
W             95
G            161
Playoffs       1
Name: 349, dtype: object
Team         OAK
League        AL
Year        2001
RS           884
RA           645
W            102
G            162
Playoffs       1
Name: 350, dtype: object
Team         PHI
League        NL
Year        2001
RS           746
RA           719
W             86
G            162
Playoffs       0
Name: 351, dtype: object
Team         PIT
League        NL
Year        2001
RS           657
RA           858
W             62
G            162
Playoffs       0
Name: 352, dtype: object
Team         SDP
League        NL
Year        2001
RS           789
RA           812
W             79
G            162
Playoffs       0
Name: 353, dtype: object
Team         SEA
League        AL
Year        2001
RS           927
RA           627
W            116
G            162
Playoffs       1
Name: 354, dtype: object
Team         SFG
League        NL
Year        2001
RS           799
RA           748
W             90
G            162
Playoffs       0
Name: 355, dtype: object
Team         STL
League        NL
Year        2001
RS           814
RA           684
W             93
G            162
Playoffs       1
Name: 356, dtype: object
Team         TBD
League        AL
Year        2001
RS           672
RA           887
W             62
G            162
Playoffs       0
Name: 357, dtype: object
Team         TEX
League        AL
Year        2001
RS           890
RA           968
W             73
G            162
Playoffs       0
Name: 358, dtype: object
Team         TOR
League        AL
Year        2001
RS           767
RA           753
W             80
G            162
Playoffs       0
Name: 359, dtype: object
Team         ANA
League        AL
Year        2000
RS           864
RA           869
W             82
G            162
Playoffs       0
Name: 360, dtype: object
Team         ARI
League        NL
Year        2000
RS           792
RA           754
W             85
G            162
Playoffs       0
Name: 361, dtype: object
Team         ATL
League        NL
Year        2000
RS           810
RA           714
W             95
G            162
Playoffs       1
Name: 362, dtype: object
Team         BAL
League        AL
Year        2000
RS           794
RA           913
W             74
G            162
Playoffs       0
Name: 363, dtype: object
Team         BOS
League        AL
Year        2000
RS           792
RA           745
W             85
G            162
Playoffs       0
Name: 364, dtype: object
Team         CHC
League        NL
Year        2000
RS           764
RA           904
W             65
G            162
Playoffs       0
Name: 365, dtype: object
Team         CHW
League        AL
Year        2000
RS           978
RA           839
W             95
G            162
Playoffs       1
Name: 366, dtype: object
Team         CIN
League        NL
Year        2000
RS           825
RA           765
W             85
G            163
Playoffs       0
Name: 367, dtype: object
Team         CLE
League        AL
Year        2000
RS           950
RA           816
W             90
G            162
Playoffs       0
Name: 368, dtype: object
Team         COL
League        NL
Year        2000
RS           968
RA           897
W             82
G            162
Playoffs       0
Name: 369, dtype: object
Team         DET
League        AL
Year        2000
RS           823
RA           827
W             79
G            162
Playoffs       0
Name: 370, dtype: object
Team         FLA
League        NL
Year        2000
RS           731
RA           797
W             79
G            161
Playoffs       0
Name: 371, dtype: object
Team         HOU
League        NL
Year        2000
RS           938
RA           944
W             72
G            162
Playoffs       0
Name: 372, dtype: object
Team         KCR
League        AL
Year        2000
RS           879
RA           930
W             77
G            162
Playoffs       0
Name: 373, dtype: object
Team         LAD
League        NL
Year        2000
RS           798
RA           729
W             86
G            162
Playoffs       0
Name: 374, dtype: object
Team         MIL
League        NL
Year        2000
RS           740
RA           826
W             73
G            163
Playoffs       0
Name: 375, dtype: object
Team         MIN
League        AL
Year        2000
RS           748
RA           880
W             69
G            162
Playoffs       0
Name: 376, dtype: object
Team         MON
League        NL
Year        2000
RS           738
RA           902
W             67
G            162
Playoffs       0
Name: 377, dtype: object
Team         NYM
League        NL
Year        2000
RS           807
RA           738
W             94
G            162
Playoffs       1
Name: 378, dtype: object
Team         NYY
League        AL
Year        2000
RS           871
RA           814
W             87
G            161
Playoffs       1
Name: 379, dtype: object
Team         OAK
League        AL
Year        2000
RS           947
RA           813
W             91
G            161
Playoffs       1
Name: 380, dtype: object
Team         PHI
League        NL
Year        2000
RS           708
RA           830
W             65
G            162
Playoffs       0
Name: 381, dtype: object

Name: 515, dtype: object
Team         FLA
League        NL
Year        1993
RS           581
RA           724
W             64
G            162
Playoffs       0
Name: 516, dtype: object
Team         HOU
League        NL
Year        1993
RS           716
RA           630
W             85
G            162
Playoffs       0
Name: 517, dtype: object
Team         KCR
League        AL
Year        1993
RS           675
RA           694
W             84
G            162
Playoffs       0
Name: 518, dtype: object
Team         LAD
League        NL
Year        1993
RS           675
RA           662
W             81
G            162
Playoffs       0
Name: 519, dtype: object
Team         MIL
League        AL
Year        1993
RS           733
RA           792
W             69
G            162
Playoffs       0
Name: 520, dtype: object
Team         MIN
League        AL
Year        1993
RS           693
RA           830
W             71
G            162
Playoffs       0
Name: 521, dtype: object
Team         MON
League        NL
Year        1993
RS           732
RA           682
W             94
G            163
Playoffs       0
Name: 522, dtype: object
Team         NYM
League        NL
Year        1993
RS           672
RA           744
W             59
G            162
Playoffs       0
Name: 523, dtype: object
Team         NYY
League        AL
Year        1993
RS           821
RA           761
W             88
G            162
Playoffs       0
Name: 524, dtype: object
Team         OAK
League        AL
Year        1993
RS           715
RA           846
W             68
G            162
Playoffs       0
Name: 525, dtype: object
Team         PHI
League        NL
Year        1993
RS           877
RA           740
W             97
G            162
Playoffs       1
Name: 526, dtype: object
Team         PIT
League        NL
Year        1993
RS           707
RA           806
W             75
G            162
Playoffs       0
Name: 527, dtype: object
Team         SDP
League        NL
Year        1993
RS           679
RA           772
W             61
G            162
Playoffs       0
Name: 528, dtype: object
Team         SEA
League        AL
Year        1993
RS           734
RA           731
W             82
G            162
Playoffs       0
Name: 529, dtype: object
Team         SFG
League        NL
Year        1993
RS           808
RA           636
W            103
G            162
Playoffs       0
Name: 530, dtype: object
Team         STL
League        NL
Year        1993
RS           758
RA           744
W             87
G            162
Playoffs       0
Name: 531, dtype: object
Team         TEX
League        AL
Year        1993
RS           835
RA           751
W             86
G            162
Playoffs       0
Name: 532, dtype: object
Team         TOR
League        AL
Year        1993
RS           847
RA           742
W             95
G            162
Playoffs       1
Name: 533, dtype: object
Team         ATL
League        NL
Year        1992
RS           682
RA           569
W             98
G            162
Playoffs       1
Name: 534, dtype: object
Team         BAL
League        AL
Year        1992
RS           705
RA           656
W             89
G            162
Playoffs       0
Name: 535, dtype: object
Team         BOS
League        AL
Year        1992
RS           599
RA           669
W             73
G            162
Playoffs       0
Name: 536, dtype: object
Team         CAL
League        AL
Year        1992
RS           579
RA           671
W             72
G            162
Playoffs       0
Name: 537, dtype: object
Team         CHC
League        NL
Year        1992
RS           593
RA           624
W             78
G            162
Playoffs       0
Name: 538, dtype: object
Team         CHW
League        AL
Year        1992
RS           738
RA           690
W             86
G            162
Playoffs       0
Name: 539, dtype: object
Team         CIN
League        NL
Year        1992
RS           660
RA           609
W             90
G            162
Playoffs       0
Name: 540, dtype: object
Team         CLE
League        AL
Year        1992
RS           674
RA           746
W             76
G            162
Playoffs       0
Name: 541, dtype: object
Team         DET
League        AL
Year        1992
RS           791
RA           794
W             75
G            162
Playoffs       0
Name: 542, dtype: object
Team         HOU
League        NL
Year        1992
RS           608
RA           668
W             81
G            162
Playoffs       0
Name: 543, dtype: object
Team         KCR
League        AL
Year        1992
RS           610
RA           667
W             72
G            162
Playoffs       0
Name: 544, dtype: object
Team         LAD
League        NL
Year        1992
RS           548
RA           636
W             63
G            162
Playoffs       0
Name: 545, dtype: object
Team         MIL
League        AL
Year        1992
RS           740
RA           604
W             92
G            162
Playoffs       0
Name: 546, dtype: object
Team         MIN
League        AL
Year        1992
RS           747
RA           653
W             90
G            162
Playoffs       0
Name: 547, dtype: object
Team         MON
League        NL
Year        1992
RS           648
RA           581
W             87
G            162
Playoffs       0
Name: 548, dtype: object
Team         NYM
League        NL
Year        1992
RS           599
RA           653
W             72
G            162
Playoffs       0
Name: 549, dtype: object
Team         NYY
League        AL
Year        1992
RS           733
RA           746
W             76
G            162
Playoffs       0
Name: 550, dtype: object
Team         OAK
League        AL
Year        1992
RS           745
RA           672
W             96
G            162
Playoffs       1
Name: 551, dtype: object
Team         PHI
League        NL
Year        1992
RS           686
RA           717
W             70
G            162
Playoffs       0
Name: 552, dtype: object
Team         PIT
League        NL
Year        1992
RS           693
RA           595
W             96
G            162
Playoffs       1
Name: 553, dtype: object
Team         SDP
League        NL
Year        1992
RS           617
RA           636
W             82
G            162
Playoffs       0
Name: 554, dtype: object
Team         SEA
League        AL
Year        1992
RS           679
RA           799
W             64
G            162
Playoffs       0
Name: 555, dtype: object
Team         SFG
League        NL
Year        1992
RS           574
RA           647
W             72
G            162
Playoffs       0
Name: 556, dtype: object
Team         STL
League        NL
Year        1992
RS           631
RA           604
W             83
G            162
Playoffs       0
Name: 557, dtype: object
Team         TEX
League        AL
Year        1992
RS           682
RA           753
W             77
G            162
Playoffs       0
Name: 558, dtype: object
Team         TOR
League        AL
Year        1992
RS           780
RA           682
W             96
G            162
Playoffs       1
Name: 559, dtype: object
Team         ATL
League        NL
Year        1991
RS           749
RA           644
W             94
G            162
Playoffs       1
Name: 560, dtype: object
Team         BAL
League        AL
Year        1991
RS           686
RA           796
W             67
G            162
Playoffs       0
Name: 561, dtype: object
Team         BOS
League        AL
Year        1991
RS           731
RA           712
W             84
G            162
Playoffs       0
Name: 562, dtype: object
Team         CAL
League        AL
Year        1991
RS           653
RA           649
W             81
G            162
Playoffs       0
Name: 563, dtype: object
Team         CHC
League        NL
Year        1991
RS           695
RA           734
W             77
G            160
Playoffs       0
Name: 564, dtype: object
Team         CHW
League        AL
Year        1991
RS           758
RA           681
W             87
G            162
Playoffs       0
Name: 565, dtype: object
Team         CIN
League        NL
Year        1991
RS           689
RA           691
W             74
G            162
Playoffs       0
Name: 566, dtype: object
Team         CLE
League        AL
Year        1991
RS           576
RA           759
W             57
G            162
Playoffs       0
Name: 567, dtype: object
Team         DET
League        AL
Year        1991
RS           817
RA           794
W             84
G            162
Playoffs       0
Name: 568, dtype: object
Team         HOU
League        NL
Year        1991
RS           605
RA           717
W             65
G            162
Playoffs       0
Name: 569, dtype: object
Team         KCR
League        AL
Year        1991
RS           727
RA           722
W             82
G            162
Playoffs       0
Name: 570, dtype: object
Team         LAD
League        NL
Year        1991
RS           665
RA           565
W             93
G            162
Playoffs       0
Name: 571, dtype: object
Team         MIL
League        AL
Year        1991
RS           799
RA           744
W             83
G            162
Playoffs       0
Name: 572, dtype: object
Team         MIN
League        AL
Year        1991
RS           776
RA           652
W             95
G            162
Playoffs       1
Name: 573, dtype: object
Team         MON
League        NL
Year        1991
RS           579
RA           655
W             71
G            161
Playoffs       0
Name: 574, dtype: object
Team         NYM
League        NL
Year        1991
RS           640
RA           646
W             77
G            161
Playoffs       0
Name: 575, dtype: object
Team         NYY
League        AL
Year        1991
RS           674
RA           777
W             71
G            162
Playoffs       0
Name: 576, dtype: object
Team         OAK
League        AL
Year        1991
RS           760
RA           776
W             84
G            162
Playoffs       0
Name: 577, dtype: object
Team         PHI
League        NL
Year        1991
RS           629
RA           680
W             78
G            162
Playoffs       0
Name: 578, dtype: object
Team         PIT
League        NL
Year        1991
RS           768
RA           632
W             98
G            162
Playoffs       1
Name: 579, dtype: object
Team         SDP
League        NL
Year        1991
RS           636
RA           646
W             84
G            162
Playoffs       0
Name: 580, dtype: object
Team         SEA
League        AL
Year        1991
RS           702
RA           674
W             83
G            162
Playoffs       0
Name: 581, dtype: object
Team         SFG
League        NL
Year        1991
RS           649
RA           697
W             75
G            162
Playoffs       0
Name: 582, dtype: object
Team         STL
League        NL
Year        1991
RS           651
RA           648
W             84
G            162
Playoffs       0
Name: 583, dtype: object
Team         TEX
League        AL
Year        1991
RS           829
RA           814
W             85
G            162
Playoffs       0
Name: 584, dtype: object
Team         TOR
League        AL
Year        1991
RS           684
RA           622
W             91
G            162
Playoffs       1
Name: 585, dtype: object
Team         ATL
League        NL
Year        1990
RS           682
RA           821
W             65
G            162
Playoffs       0
Name: 586, dtype: object
Team         BAL
League        AL
Year        1990
RS           669
RA           698
W             76
G            161
Playoffs       0
Name: 587, dtype: object
Team         BOS
League        AL
Year        1990
RS           699
RA           664
W             88
G            162
Playoffs       1
Name: 588, dtype: object
Team         CAL
League        AL
Year        1990
RS           690
RA           706
W             80
G            162
Playoffs       0
Name: 589, dtype: object
Team         CHC
League        NL
Year        1990
RS           690
RA           774
W             77
G            162
Playoffs       0
Name: 590, dtype: object
Team         CHW
League        AL
Year        1990
RS           682
RA           633
W             94
G            162
Playoffs       0
Name: 591, dtype: object
Team         CIN
League        NL
Year        1990
RS           693
RA           597
W             91
G            162
Playoffs       1
Name: 592, dtype: object
Team         CLE
League        AL
Year        1990
RS           732
RA           737
W             77
G            162
Playoffs       0
Name: 593, dtype: object
Team         DET
League        AL
Year        1990
RS           750
RA           754
W             79
G            162
Playoffs       0
Name: 594, dtype: object
Team         HOU
League        NL
Year        1990
RS           573
RA           656
W             75
G            162
Playoffs       0
Name: 595, dtype: object
Team         KCR
League        AL
Year        1990
RS           707
RA           709
W             75
G            161
Playoffs       0
Name: 596, dtype: object
Team         LAD
League        NL
Year        1990
RS           728
RA           685
W             86
G            162
Playoffs       0
Name: 597, dtype: object
Team         MIL
League        AL
Year        1990
RS           732
RA           760
W             74
G            162
Playoffs       0
Name: 598, dtype: object
Team         MIN
League        AL
Year        1990
RS           666
RA           729
W             74
G            162
Playoffs       0
Name: 599, dtype: object
Team         MON
League        NL
Year        1990
RS           662
RA           598
W             85
G            162
Playoffs       0
Name: 600, dtype: object
Team         NYM
League        NL
Year        1990
RS           775
RA           613
W             91
G            162
Playoffs       0
Name: 601, dtype: object
Team         NYY
League        AL
Year        1990
RS           603
RA           749
W             67
G            162
Playoffs       0
Name: 602, dtype: object
Team         OAK
League        AL
Year        1990
RS           733
RA           570
W            103
G            162
Playoffs       1
Name: 603, dtype: object
Team         PHI
League        NL
Year        1990
RS           646
RA           729
W             77
G            162
Playoffs       0
Name: 604, dtype: object
Team         PIT
League        NL
Year        1990
RS           733
RA           619
W             95
G            162
Playoffs       1
Name: 605, dtype: object
Team         SDP
League        NL
Year        1990
RS           673
RA           673
W             75
G            162
Playoffs       0
Name: 606, dtype: object
Team         SEA
League        AL
Year        1990
RS           640
RA           680
W             77
G            162
Playoffs       0
Name: 607, dtype: object
Team         SFG
League        NL
Year        1990
RS           719
RA           710
W             85
G            162
Playoffs       0
Name: 608, dtype: object
Team         STL
League        NL
Year        1990
RS           599
RA           698
W             70
G            162
Playoffs       0
Name: 609, dtype: object
Team         TEX
League        AL
Year        1990
RS           676
RA           696
W             83
G            162
Playoffs       0
Name: 610, dtype: object
Team         TOR
League        AL
Year        1990
RS           767
RA           661
W             86
G            162
Playoffs       0
Name: 611, dtype: object
Team         ATL
League        NL
Year        1989
RS           584
RA           680
W             63
G            161
Playoffs       0
Name: 612, dtype: object
Team         BAL
League        AL
Year        1989
RS           708
RA           686
W             87
G            162
Playoffs       0
Name: 613, dtype: object
Team         BOS
League        AL
Year        1989
RS           774
RA           735
W             83
G            162
Playoffs       0
Name: 614, dtype: object
Team         CAL
League        AL
Year        1989
RS           669
RA           578
W             91
G            162
Playoffs       0
Name: 615, dtype: object
Team         CHC
League        NL
Year        1989
RS           702
RA           623
W             93
G            162
Playoffs       1
Name: 616, dtype: object
Team         CHW
League        AL
Year        1989
RS           693
RA           750
W             69
G            161
Playoffs       0
Name: 617, dtype: object
Team         CIN
League        NL
Year        1989
RS           632
RA           691
W             75
G            162
Playoffs       0
Name: 618, dtype: object
Team         CLE
League        AL
Year        1989
RS           604
RA           654
W             73
G            162
Playoffs       0
Name: 619, dtype: object
Team         DET
League        AL
Year        1989
RS           617
RA           816
W             59
G            162
Playoffs       0
Name: 620, dtype: object
Team         HOU
League        NL
Year        1989
RS           647
RA           669
W             86
G            162
Playoffs       0
Name: 621, dtype: object
Team         KCR
League        AL
Year        1989
RS           690
RA           635
W             92
G            162
Playoffs       0
Name: 622, dtype: object
Team         LAD
League        NL
Year        1989
RS           554
RA           536
W             77
G            160
Playoffs       0
Name: 623, dtype: object
Team         MIL
League        AL
Year        1989
RS           707
RA           679
W             81
G            162
Playoffs       0
Name: 624, dtype: object
Team         MIN
League        AL
Year        1989
RS           740
RA           738
W             80
G            162
Playoffs       0
Name: 625, dtype: object
Team         MON
League        NL
Year        1989
RS           632
RA           630
W             81
G            162
Playoffs       0
Name: 626, dtype: object
Team         NYM
League        NL
Year        1989
RS           683
RA           595
W             87
G            162
Playoffs       0
Name: 627, dtype: object
Team         NYY
League        AL
Year        1989
RS           698
RA           792
W             74
G            161
Playoffs       0
Name: 628, dtype: object
Team         OAK
League        AL
Year        1989
RS           712
RA           576
W             99
G            162
Playoffs       1
Name: 629, dtype: object
Team         PHI
League        NL
Year        1989
RS           629
RA           735
W             67
G            163
Playoffs       0
Name: 630, dtype: object
Team         PIT
League        NL
Year        1989
RS           637
RA           680
W             74
G            164
Playoffs       0
Name: 631, dtype: object
Team         SDP
League        NL
Year        1989
RS           642
RA           626
W             89
G            162
Playoffs       0
Name: 632, dtype: object
Team         SEA
League        AL
Year        1989
RS           694
RA           728
W             73
G            162
Playoffs       0
Name: 633, dtype: object
Team         SFG
League        NL
Year        1989
RS           699
RA           600
W             92
G            162
Playoffs       1
Name: 634, dtype: object
Team         STL
League        NL
Year        1989
RS           632
RA           608
W             86
G            164
Playoffs       0
Name: 635, dtype: object
Team         TEX
League        AL
Year        1989
RS           695
RA           714
W             83
G            162
Playoffs       0
Name: 636, dtype: object
Team         TOR
League        AL
Year        1989
RS           731
RA           651
W             89
G            162
Playoffs       1
Name: 637, dtype: object
Team         ATL
League        NL
Year        1988
RS           555
RA           741
W             54
G            160
Playoffs       0
Name: 638, dtype: object
Team         BAL
League        AL
Year        1988
RS           550
RA           789
W             54
G            161
Playoffs       0
Name: 639, dtype: object

Name: 771, dtype: object
Team         CHC
League        NL
Year        1983
RS           701
RA           719
W             71
G            162
Playoffs       0
Name: 772, dtype: object
Team         CHW
League        AL
Year        1983
RS           800
RA           650
W             99
G            162
Playoffs       1
Name: 773, dtype: object
Team         CIN
League        NL
Year        1983
RS           623
RA           710
W             74
G            162
Playoffs       0
Name: 774, dtype: object
Team         CLE
League        AL
Year        1983
RS           704
RA           785
W             70
G            162
Playoffs       0
Name: 775, dtype: object
Team         DET
League        AL
Year        1983
RS           789
RA           679
W             92
G            162
Playoffs       0
Name: 776, dtype: object
Team         HOU
League        NL
Year        1983
RS           643
RA           646
W             85
G            162
Playoffs       0
Name: 777, dtype: object
Team         KCR
League        AL
Year        1983
RS           696
RA           767
W             79
G            163
Playoffs       0
Name: 778, dtype: object
Team         LAD
League        NL
Year        1983
RS           654
RA           609
W             91
G            163
Playoffs       1
Name: 779, dtype: object
Team         MIL
League        AL
Year        1983
RS           764
RA           708
W             87
G            162
Playoffs       0
Name: 780, dtype: object
Team         MIN
League        AL
Year        1983
RS           709
RA           822
W             70
G            162
Playoffs       0
Name: 781, dtype: object
Team         MON
League        NL
Year        1983
RS           677
RA           646
W             82
G            163
Playoffs       0
Name: 782, dtype: object
Team         NYM
League        NL
Year        1983
RS           575
RA           680
W             68
G            162
Playoffs       0
Name: 783, dtype: object
Team         NYY
League        AL
Year        1983
RS           770
RA           703
W             91
G            162
Playoffs       0
Name: 784, dtype: object
Team         OAK
League        AL
Year        1983
RS           708
RA           782
W             74
G            162
Playoffs       0
Name: 785, dtype: object
Team         PHI
League        NL
Year        1983
RS           696
RA           635
W             90
G            163
Playoffs       1
Name: 786, dtype: object
Team         PIT
League        NL
Year        1983
RS           659
RA           648
W             84
G            162
Playoffs       0
Name: 787, dtype: object
Team         SDP
League        NL
Year        1983
RS           653
RA           653
W             81
G            163
Playoffs       0
Name: 788, dtype: object
Team         SEA
League        AL
Year        1983
RS           558
RA           740
W             60
G            162
Playoffs       0
Name: 789, dtype: object
Team         SFG
League        NL
Year        1983
RS           687
RA           697
W             79
G            162
Playoffs       0
Name: 790, dtype: object
Team         STL
League        NL
Year        1983
RS           679
RA           710
W             79
G            162
Playoffs       0
Name: 791, dtype: object
Team         TEX
League        AL
Year        1983
RS           639
RA           609
W             77
G            163
Playoffs       0
Name: 792, dtype: object
Team         TOR
League        AL
Year        1983
RS           795
RA           726
W             89
G            162
Playoffs       0
Name: 793, dtype: object
Team         ATL
League        NL
Year        1982
RS           739
RA           702
W             89
G            162
Playoffs       1
Name: 794, dtype: object
Team         BAL
League        AL
Year        1982
RS           774
RA           687
W             94
G            163
Playoffs       0
Name: 795, dtype: object
Team         BOS
League        AL
Year        1982
RS           753
RA           713
W             89
G            162
Playoffs       0
Name: 796, dtype: object
Team         CAL
League        AL
Year        1982
RS           814
RA           670
W             93
G            162
Playoffs       1
Name: 797, dtype: object
Team         CHC
League        NL
Year        1982
RS           676
RA           709
W             73
G            162
Playoffs       0
Name: 798, dtype: object
Team         CHW
League        AL
Year        1982
RS           786
RA           710
W             87
G            162
Playoffs       0
Name: 799, dtype: object
Team         CIN
League        NL
Year        1982
RS           545
RA           661
W             61
G            162
Playoffs       0
Name: 800, dtype: object
Team         CLE
League        AL
Year        1982
RS           683
RA           748
W             78
G            162
Playoffs       0
Name: 801, dtype: object
Team         DET
League        AL
Year        1982
RS           729
RA           685
W             83
G            162
Playoffs       0
Name: 802, dtype: object
Team         HOU
League        NL
Year        1982
RS           569
RA           620
W             77
G            162
Playoffs       0
Name: 803, dtype: object
Team         KCR
League        AL
Year        1982
RS           784
RA           717
W             90
G            162
Playoffs       0
Name: 804, dtype: object
Team         LAD
League        NL
Year        1982
RS           691
RA           612
W             88
G            162
Playoffs       0
Name: 805, dtype: object
Team         MIL
League        AL
Year        1982
RS           891
RA           717
W             95
G            163
Playoffs       1
Name: 806, dtype: object
Team         MIN
League        AL
Year        1982
RS           657
RA           819
W             60
G            162
Playoffs       0
Name: 807, dtype: object
Team         MON
League        NL
Year        1982
RS           697
RA           616
W             86
G            162
Playoffs       0
Name: 808, dtype: object
Team         NYM
League        NL
Year        1982
RS           609
RA           723
W             65
G            162
Playoffs       0
Name: 809, dtype: object
Team         NYY
League        AL
Year        1982
RS           709
RA           716
W             79
G            162
Playoffs       0
Name: 810, dtype: object
Team         OAK
League        AL
Year        1982
RS           691
RA           819
W             68
G            162
Playoffs       0
Name: 811, dtype: object
Team         PHI
League        NL
Year        1982
RS           664
RA           654
W             89
G            162
Playoffs       0
Name: 812, dtype: object
Team         PIT
League        NL
Year        1982
RS           724
RA           696
W             84
G            162
Playoffs       0
Name: 813, dtype: object
Team         SDP
League        NL
Year        1982
RS           675
RA           658
W             81
G            162
Playoffs       0
Name: 814, dtype: object
Team         SEA
League        AL
Year        1982
RS           651
RA           712
W             76
G            162
Playoffs       0
Name: 815, dtype: object
Team         SFG
League        NL
Year        1982
RS           673
RA           687
W             87
G            162
Playoffs       0
Name: 816, dtype: object
Team         STL
League        NL
Year        1982
RS           685
RA           609
W             92
G            162
Playoffs       1
Name: 817, dtype: object
Team         TEX
League        AL
Year        1982
RS           590
RA           749
W             64
G            162
Playoffs       0
Name: 818, dtype: object
Team         TOR
League        AL
Year        1982
RS           651
RA           701
W             78
G            162
Playoffs       0
Name: 819, dtype: object
Team         ATL
League        NL
Year        1980
RS           630
RA           660
W             81
G            161
Playoffs       0
Name: 820, dtype: object
Team         BAL
League        AL
Year        1980
RS           805
RA           640
W            100
G            162
Playoffs       0
Name: 821, dtype: object
Team         BOS
League        AL
Year        1980
RS           757
RA           767
W             83
G            160
Playoffs       0
Name: 822, dtype: object
Team         CAL
League        AL
Year        1980
RS           698
RA           797
W             65
G            160
Playoffs       0
Name: 823, dtype: object
Team         CHC
League        NL
Year        1980
RS           614
RA           728
W             64
G            162
Playoffs       0
Name: 824, dtype: object
Team         CHW
League        AL
Year        1980
RS           587
RA           722
W             70
G            162
Playoffs       0
Name: 825, dtype: object
Team         CIN
League        NL
Year        1980
RS           707
RA           670
W             89
G            163
Playoffs       0
Name: 826, dtype: object
Team         CLE
League        AL
Year        1980
RS           738
RA           807
W             79
G            160
Playoffs       0
Name: 827, dtype: object
Team         DET
League        AL
Year        1980
RS           830
RA           757
W             84
G            163
Playoffs       0
Name: 828, dtype: object
Team         HOU
League        NL
Year        1980
RS           637
RA           589
W             93
G            163
Playoffs       1
Name: 829, dtype: object
Team         KCR
League        AL
Year        1980
RS           809
RA           694
W             97
G            162
Playoffs       1
Name: 830, dtype: object
Team         LAD
League        NL
Year        1980
RS           663
RA           591
W             92
G            163
Playoffs       0
Name: 831, dtype: object
Team         MIL
League        AL
Year        1980
RS           811
RA           682
W             86
G            162
Playoffs       0
Name: 832, dtype: object
Team         MIN
League        AL
Year        1980
RS           670
RA           724
W             77
G            161
Playoffs       0
Name: 833, dtype: object
Team         MON
League        NL
Year        1980
RS           694
RA           629
W             90
G            162
Playoffs       0
Name: 834, dtype: object
Team         NYM
League        NL
Year        1980
RS           611
RA           702
W             67
G            162
Playoffs       0
Name: 835, dtype: object
Team         NYY
League        AL
Year        1980
RS           820
RA           662
W            103
G            162
Playoffs       1
Name: 836, dtype: object
Team         OAK
League        AL
Year        1980
RS           686
RA           642
W             83
G            162
Playoffs       0
Name: 837, dtype: object
Team         PHI
League        NL
Year        1980
RS           728
RA           639
W             91
G            162
Playoffs       1
Name: 838, dtype: object
Team         PIT
League        NL
Year        1980
RS           666
RA           646
W             83
G            162
Playoffs       0
Name: 839, dtype: object
Team         SDP
League        NL
Year        1980
RS           591
RA           654
W             73
G            163
Playoffs       0
Name: 840, dtype: object
Team         SEA
League        AL
Year        1980
RS           610
RA           793
W             59
G            163
Playoffs       0
Name: 841, dtype: object
Team         SFG
League        NL
Year        1980
RS           573
RA           634
W             75
G            161
Playoffs       0
Name: 842, dtype: object
Team         STL
League        NL
Year        1980
RS           738
RA           710
W             74
G            162
Playoffs       0
Name: 843, dtype: object
Team         TEX
League        AL
Year        1980
RS           756
RA           752
W             76
G            163
Playoffs       0
Name: 844, dtype: object
Team         TOR
League        AL
Year        1980
RS           624
RA           762
W             67
G            162
Playoffs       0
Name: 845, dtype: object
Team         ATL
League        NL
Year        1979
RS           669
RA           763
W             66
G            160
Playoffs       0
Name: 846, dtype: object
Team         BAL
League        AL
Year        1979
RS           757
RA           582
W            102
G            159
Playoffs       1
Name: 847, dtype: object
Team         BOS
League        AL
Year        1979
RS           841
RA           711
W             91
G            160
Playoffs       0
Name: 848, dtype: object
Team         CAL
League        AL
Year        1979
RS           866
RA           768
W             88
G            162
Playoffs       1
Name: 849, dtype: object
Team         CHC
League        NL
Year        1979
RS           706
RA           707
W             80
G            162
Playoffs       0
Name: 850, dtype: object
Team         CHW
League        AL
Year        1979
RS           730
RA           748
W             73
G            160
Playoffs       0
Name: 851, dtype: object
Team         CIN
League        NL
Year        1979
RS           731
RA           644
W             90
G            161
Playoffs       1
Name: 852, dtype: object
Team         CLE
League        AL
Year        1979
RS           760
RA           805
W             81
G            161
Playoffs       0
Name: 853, dtype: object
Team         DET
League        AL
Year        1979
RS           770
RA           738
W             84
G            161
Playoffs       0
Name: 854, dtype: object
Team         HOU
League        NL
Year        1979
RS           583
RA           582
W             89
G            162
Playoffs       0
Name: 855, dtype: object
Team         KCR
League        AL
Year        1979
RS           851
RA           816
W             85
G            162
Playoffs       0
Name: 856, dtype: object
Team         LAD
League        NL
Year        1979
RS           739
RA           717
W             79
G            162
Playoffs       0
Name: 857, dtype: object
Team         MIL
League        AL
Year        1979
RS           807
RA           722
W             95
G            161
Playoffs       0
Name: 858, dtype: object
Team         MIN
League        AL
Year        1979
RS           764
RA           725
W             82
G            162
Playoffs       0
Name: 859, dtype: object
Team         MON
League        NL
Year        1979
RS           701
RA           581
W             95
G            160
Playoffs       0
Name: 860, dtype: object
Team         NYM
League        NL
Year        1979
RS           593
RA           706
W             63
G            163
Playoffs       0
Name: 861, dtype: object
Team         NYY
League        AL
Year        1979
RS           734
RA           672
W             89
G            160
Playoffs       0
Name: 862, dtype: object
Team         OAK
League        AL
Year        1979
RS           573
RA           860
W             54
G            162
Playoffs       0
Name: 863, dtype: object
Team         PHI
League        NL
Year        1979
RS           683
RA           718
W             84
G            163
Playoffs       0
Name: 864, dtype: object
Team         PIT
League        NL
Year        1979
RS           775
RA           643
W             98
G            163
Playoffs       1
Name: 865, dtype: object
Team         SDP
League        NL
Year        1979
RS           603
RA           681
W             68
G            161
Playoffs       0
Name: 866, dtype: object
Team         SEA
League        AL
Year        1979
RS           711
RA           820
W             67
G            162
Playoffs       0
Name: 867, dtype: object
Team         SFG
League        NL
Year        1979
RS           672
RA           751
W             71
G            162
Playoffs       0
Name: 868, dtype: object
Team         STL
League        NL
Year        1979
RS           731
RA           693
W             86
G            163
Playoffs       0
Name: 869, dtype: object
Team         TEX
League        AL
Year        1979
RS           750
RA           698
W             83
G            162
Playoffs       0
Name: 870, dtype: object
Team         TOR
League        AL
Year        1979
RS           613
RA           862
W             53
G            162
Playoffs       0
Name: 871, dtype: object
Team         ATL
League        NL
Year        1978
RS           600
RA           750
W             69
G            162
Playoffs       0
Name: 872, dtype: object
Team         BAL
League        AL
Year        1978
RS           659
RA           633
W             90
G            161
Playoffs       0
Name: 873, dtype: object
Team         BOS
League        AL
Year        1978
RS           796
RA           657
W             99
G            163
Playoffs       0
Name: 874, dtype: object
Team         CAL
League        AL
Year        1978
RS           691
RA           666
W             87
G            162
Playoffs       0
Name: 875, dtype: object
Team         CHC
League        NL
Year        1978
RS           664
RA           724
W             79
G            162
Playoffs       0
Name: 876, dtype: object
Team         CHW
League        AL
Year        1978
RS           634
RA           731
W             71
G            161
Playoffs       0
Name: 877, dtype: object
Team         CIN
League        NL
Year        1978
RS           710
RA           688
W             92
G            161
Playoffs       0
Name: 878, dtype: object
Team         CLE
League        AL
Year        1978
RS           639
RA           694
W             69
G            159
Playoffs       0
Name: 879, dtype: object
Team         DET
League        AL
Year        1978
RS           714
RA           653
W             86
G            162
Playoffs       0
Name: 880, dtype: object
Team         HOU
League        NL
Year        1978
RS           605
RA           634
W             74
G            162
Playoffs       0
Name: 881, dtype: object
Team         KCR
League        AL
Year        1978
RS           743
RA           634
W             92
G            162
Playoffs       1
Name: 882, dtype: object
Team         LAD
League        NL
Year        1978
RS           727
RA           573
W             95
G            162
Playoffs       1
Name: 883, dtype: object
Team         MIL
League        AL
Year        1978
RS           804
RA           650
W             93
G            162
Playoffs       0
Name: 884, dtype: object
Team         MIN
League        AL
Year        1978
RS           666
RA           678
W             73
G            162
Playoffs       0
Name: 885, dtype: object
Team         MON
League        NL
Year        1978
RS           633
RA           611
W             76
G            162
Playoffs       0
Name: 886, dtype: object
Team         NYM
League        NL
Year        1978
RS           607
RA           690
W             66
G            162
Playoffs       0
Name: 887, dtype: object
Team         NYY
League        AL
Year        1978
RS           735
RA           582
W            100
G            163
Playoffs       1
Name: 888, dtype: object
Team         OAK
League        AL
Year        1978
RS           532
RA           690
W             69
G            162
Playoffs       0
Name: 889, dtype: object
Team         PHI
League        NL
Year        1978
RS           708
RA           586
W             90
G            162
Playoffs       1
Name: 890, dtype: object
Team         PIT
League        NL
Year        1978
RS           684
RA           637
W             88
G            161
Playoffs       0
Name: 891, dtype: object
Team         SDP
League        NL
Year        1978
RS           591
RA           598
W             84
G            162
Playoffs       0
Name: 892, dtype: object
Team         SEA
League        AL
Year        1978
RS           614
RA           834
W             56
G            160
Playoffs       0
Name: 893, dtype: object
Team         SFG
League        NL
Year        1978
RS           613
RA           594
W             89
G            162
Playoffs       0
Name: 894, dtype: object
Team         STL
League        NL
Year        1978
RS           600
RA           657
W             69
G            162
Playoffs       0
Name: 895, dtype: object

Name: 1029, dtype: object
Team         KCR
League        AL
Year        1971
RS           603
RA           566
W             85
G            161
Playoffs       0
Name: 1030, dtype: object
Team         LAD
League        NL
Year        1971
RS           663
RA           587
W             89
G            162
Playoffs       0
Name: 1031, dtype: object
Team         MIL
League        AL
Year        1971
RS           534
RA           609
W             69
G            161
Playoffs       0
Name: 1032, dtype: object
Team         MIN
League        AL
Year        1971
RS           654
RA           670
W             74
G            160
Playoffs       0
Name: 1033, dtype: object
Team         MON
League        NL
Year        1971
RS           622
RA           729
W             71
G            162
Playoffs       0
Name: 1034, dtype: object
Team         NYM
League        NL
Year        1971
RS           588
RA           550
W             83
G            162
Playoffs       0
Name: 1035, dtype: object
Team         NYY
League        AL
Year        1971
RS           648
RA           641
W             81
G            162
Playoffs       0
Name: 1036, dtype: object
Team         OAK
League        AL
Year        1971
RS           691
RA           564
W            101
G            161
Playoffs       1
Name: 1037, dtype: object
Team         PHI
League        NL
Year        1971
RS           558
RA           688
W             67
G            162
Playoffs       0
Name: 1038, dtype: object
Team         PIT
League        NL
Year        1971
RS           788
RA           599
W             97
G            162
Playoffs       1
Name: 1039, dtype: object
Team         SDP
League        NL
Year        1971
RS           486
RA           610
W             61
G            161
Playoffs       0
Name: 1040, dtype: object
Team         SFG
League        NL
Year        1971
RS           706
RA           644
W             90
G            162
Playoffs       1
Name: 1041, dtype: object
Team         STL
League        NL
Year        1971
RS           739
RA           699
W             90
G            163
Playoffs       0
Name: 1042, dtype: object
Team         WSA
League        AL
Year        1971
RS           537
RA           660
W             63
G            159
Playoffs       0
Name: 1043, dtype: object
Team         ATL
League        NL
Year        1970
RS           736
RA           772
W             76
G            162
Playoffs       0
Name: 1044, dtype: object
Team         BAL
League        AL
Year        1970
RS           792
RA           574
W            108
G            162
Playoffs       1
Name: 1045, dtype: object
Team         BOS
League        AL
Year        1970
RS           786
RA           722
W             87
G            162
Playoffs       0
Name: 1046, dtype: object
Team         CAL
League        AL
Year        1970
RS           631
RA           630
W             86
G            162
Playoffs       0
Name: 1047, dtype: object
Team         CHC
League        NL
Year        1970
RS           806
RA           679
W             84
G            162
Playoffs       0
Name: 1048, dtype: object
Team         CHW
League        AL
Year        1970
RS           633
RA           822
W             56
G            162
Playoffs       0
Name: 1049, dtype: object
Team         CIN
League        NL
Year        1970
RS           775
RA           681
W            102
G            162
Playoffs       1
Name: 1050, dtype: object
Team         CLE
League        AL
Year        1970
RS           649
RA           675
W             76
G            162
Playoffs       0
Name: 1051, dtype: object
Team         DET
League        AL
Year        1970
RS           666
RA           731
W             79
G            162
Playoffs       0
Name: 1052, dtype: object
Team         HOU
League        NL
Year        1970
RS           744
RA           763
W             79
G            162
Playoffs       0
Name: 1053, dtype: object
Team         KCR
League        AL
Year        1970
RS           611
RA           705
W             65
G            162
Playoffs       0
Name: 1054, dtype: object
Team         LAD
League        NL
Year        1970
RS           749
RA           684
W             87
G            161
Playoffs       0
Name: 1055, dtype: object
Team         MIL
League        AL
Year        1970
RS           613
RA           751
W             65
G            163
Playoffs       0
Name: 1056, dtype: object
Team         MIN
League        AL
Year        1970
RS           744
RA           605
W             98
G            162
Playoffs       1
Name: 1057, dtype: object
Team         MON
League        NL
Year        1970
RS           687
RA           807
W             73
G            162
Playoffs       0
Name: 1058, dtype: object
Team         NYM
League        NL
Year        1970
RS           695
RA           630
W             83
G            162
Playoffs       0
Name: 1059, dtype: object
Team         NYY
League        AL
Year        1970
RS           680
RA           612
W             93
G            163
Playoffs       0
Name: 1060, dtype: object
Team         OAK
League        AL
Year        1970
RS           678
RA           593
W             89
G            162
Playoffs       0
Name: 1061, dtype: object
Team         PHI
League        NL
Year        1970
RS           594
RA           730
W             73
G            161
Playoffs       0
Name: 1062, dtype: object
Team         PIT
League        NL
Year        1970
RS           729
RA           664
W             89
G            162
Playoffs       1
Name: 1063, dtype: object
Team         SDP
League        NL
Year        1970
RS           681
RA           788
W             63
G            162
Playoffs       0
Name: 1064, dtype: object
Team         SFG
League        NL
Year        1970
RS           831
RA           826
W             86
G            162
Playoffs       0
Name: 1065, dtype: object
Team         STL
League        NL
Year        1970
RS           744
RA           747
W             76
G            162
Playoffs       0
Name: 1066, dtype: object
Team         WSA
League        AL
Year        1970
RS           626
RA           689
W             70
G            162
Playoffs       0
Name: 1067, dtype: object
Team         ATL
League        NL
Year        1969
RS           691
RA           631
W             93
G            162
Playoffs       1
Name: 1068, dtype: object
Team         BAL
League        AL
Year        1969
RS           779
RA           517
W            109
G            162
Playoffs       1
Name: 1069, dtype: object
Team         BOS
League        AL
Year        1969
RS           743
RA           736
W             87
G            162
Playoffs       0
Name: 1070, dtype: object
Team         CAL
League        AL
Year        1969
RS           528
RA           652
W             71
G            163
Playoffs       0
Name: 1071, dtype: object
Team         CHC
League        NL
Year        1969
RS           720
RA           611
W             92
G            163
Playoffs       0
Name: 1072, dtype: object
Team         CHW
League        AL
Year        1969
RS           625
RA           723
W             68
G            162
Playoffs       0
Name: 1073, dtype: object
Team         CIN
League        NL
Year        1969
RS           798
RA           768
W             89
G            163
Playoffs       0
Name: 1074, dtype: object
Team         CLE
League        AL
Year        1969
RS           573
RA           717
W             62
G            161
Playoffs       0
Name: 1075, dtype: object
Team         DET
League        AL
Year        1969
RS           701
RA           601
W             90
G            162
Playoffs       0
Name: 1076, dtype: object
Team         HOU
League        NL
Year        1969
RS           676
RA           668
W             81
G            162
Playoffs       0
Name: 1077, dtype: object
Team         KCR
League        AL
Year        1969
RS           586
RA           688
W             69
G            163
Playoffs       0
Name: 1078, dtype: object
Team         LAD
League        NL
Year        1969
RS           645
RA           561
W             85
G            162
Playoffs       0
Name: 1079, dtype: object
Team         MIN
League        AL
Year        1969
RS           790
RA           618
W             97
G            162
Playoffs       1
Name: 1080, dtype: object
Team         MON
League        NL
Year        1969
RS           582
RA           791
W             52
G            162
Playoffs       0
Name: 1081, dtype: object
Team         NYM
League        NL
Year        1969
RS           632
RA           541
W            100
G            162
Playoffs       1
Name: 1082, dtype: object
Team         NYY
League        AL
Year        1969
RS           562
RA           587
W             80
G            162
Playoffs       0
Name: 1083, dtype: object
Team         OAK
League        AL
Year        1969
RS           740
RA           678
W             88
G            162
Playoffs       0
Name: 1084, dtype: object
Team         PHI
League        NL
Year        1969
RS           645
RA           745
W             63
G            162
Playoffs       0
Name: 1085, dtype: object
Team         PIT
League        NL
Year        1969
RS           725
RA           652
W             88
G            162
Playoffs       0
Name: 1086, dtype: object
Team         SDP
League        NL
Year        1969
RS           468
RA           746
W             52
G            162
Playoffs       0
Name: 1087, dtype: object
Team         SEP
League        AL
Year        1969
RS           639
RA           799
W             64
G            163
Playoffs       0
Name: 1088, dtype: object
Team         SFG
League        NL
Year        1969
RS           713
RA           636
W             90
G            162
Playoffs       0
Name: 1089, dtype: object
Team         STL
League        NL
Year        1969
RS           595
RA           540
W             87
G            162
Playoffs       0
Name: 1090, dtype: object
Team         WSA
League        AL
Year        1969
RS           694
RA           644
W             86
G            162
Playoffs       0
Name: 1091, dtype: object
Team         ATL
League        NL
Year        1968
RS           514
RA           549
W             81
G            163
Playoffs       0
Name: 1092, dtype: object
Team         BAL
League        AL
Year        1968
RS           579
RA           497
W             91
G            162
Playoffs       0
Name: 1093, dtype: object
Team         BOS
League        AL
Year        1968
RS           614
RA           611
W             86
G            162
Playoffs       0
Name: 1094, dtype: object
Team         CAL
League        AL
Year        1968
RS           498
RA           615
W             67
G            162
Playoffs       0
Name: 1095, dtype: object
Team         CHC
League        NL
Year        1968
RS           612
RA           611
W             84
G            163
Playoffs       0
Name: 1096, dtype: object
Team         CHW
League        AL
Year        1968
RS           463
RA           527
W             67
G            162
Playoffs       0
Name: 1097, dtype: object
Team         CIN
League        NL
Year        1968
RS           690
RA           673
W             83
G            163
Playoffs       0
Name: 1098, dtype: object
Team         CLE
League        AL
Year        1968
RS           516
RA           504
W             86
G            162
Playoffs       0
Name: 1099, dtype: object
Team         DET
League        AL
Year        1968
RS           671
RA           492
W            103
G            164
Playoffs       1
Name: 1100, dtype: object
Team         HOU
League        NL
Year        1968
RS           510
RA           588
W             72
G            162
Playoffs       0
Name: 1101, dtype: object
Team         LAD
League        NL
Year        1968
RS           470
RA           509
W             76
G            162
Playoffs       0
Name: 1102, dtype: object
Team         MIN
League        AL
Year        1968
RS           562
RA           546
W             79
G            162
Playoffs       0
Name: 1103, dtype: object
Team         NYM
League        NL
Year        1968
RS           473
RA           499
W             73
G            163
Playoffs       0
Name: 1104, dtype: object
Team         NYY
League        AL
Year        1968
RS           536
RA           531
W             83
G            164
Playoffs       0
Name: 1105, dtype: object
Team         OAK
League        AL
Year        1968
RS           569
RA           544
W             82
G            163
Playoffs       0
Name: 1106, dtype: object
Team         PHI
League        NL
Year        1968
RS           543
RA           615
W             76
G            162
Playoffs       0
Name: 1107, dtype: object
Team         PIT
League        NL
Year        1968
RS           583
RA           532
W             80
G            163
Playoffs       0
Name: 1108, dtype: object
Team         SFG
League        NL
Year        1968
RS           599
RA           529
W             88
G            163
Playoffs       0
Name: 1109, dtype: object
Team         STL
League        NL
Year        1968
RS           583
RA           472
W             97
G            162
Playoffs       1
Name: 1110, dtype: object
Team         WSA
League        AL
Year        1968
RS           524
RA           665
W             65
G            161
Playoffs       0
Name: 1111, dtype: object
Team         ATL
League        NL
Year        1967
RS           631
RA           640
W             77
G            162
Playoffs       0
Name: 1112, dtype: object
Team         BAL
League        AL
Year        1967
RS           654
RA           592
W             76
G            161
Playoffs       0
Name: 1113, dtype: object
Team         BOS
League        AL
Year        1967
RS           722
RA           614
W             92
G            162
Playoffs       1
Name: 1114, dtype: object
Team         CAL
League        AL
Year        1967
RS           567
RA           587
W             84
G            161
Playoffs       0
Name: 1115, dtype: object
Team         CHC
League        NL
Year        1967
RS           702
RA           624
W             87
G            162
Playoffs       0
Name: 1116, dtype: object
Team         CHW
League        AL
Year        1967
RS           531
RA           491
W             89
G            162
Playoffs       0
Name: 1117, dtype: object
Team         CIN
League        NL
Year        1967
RS           604
RA           563
W             87
G            162
Playoffs       0
Name: 1118, dtype: object
Team         CLE
League        AL
Year        1967
RS           559
RA           613
W             75
G            162
Playoffs       0
Name: 1119, dtype: object
Team         DET
League        AL
Year        1967
RS           683
RA           587
W             91
G            163
Playoffs       0
Name: 1120, dtype: object
Team         HOU
League        NL
Year        1967
RS           626
RA           742
W             69
G            162
Playoffs       0
Name: 1121, dtype: object
Team         KCA
League        AL
Year        1967
RS           533
RA           660
W             62
G            161
Playoffs       0
Name: 1122, dtype: object
Team         LAD
League        NL
Year        1967
RS           519
RA           595
W             73
G            162
Playoffs       0
Name: 1123, dtype: object
Team         MIN
League        AL
Year        1967
RS           671
RA           590
W             91
G            164
Playoffs       0
Name: 1124, dtype: object
Team         NYM
League        NL
Year        1967
RS           498
RA           672
W             61
G            162
Playoffs       0
Name: 1125, dtype: object
Team         NYY
League        AL
Year        1967
RS           522
RA           621
W             72
G            163
Playoffs       0
Name: 1126, dtype: object
Team         PHI
League        NL
Year        1967
RS           612
RA           581
W             82
G            162
Playoffs       0
Name: 1127, dtype: object
Team         PIT
League        NL
Year        1967
RS           679
RA           693
W             81
G            163
Playoffs       0
Name: 1128, dtype: object
Team         SFG
League        NL
Year        1967
RS           652
RA           551
W             91
G            162
Playoffs       0
Name: 1129, dtype: object
Team         STL
League        NL
Year        1967
RS           695
RA           557
W            101
G            161
Playoffs       1
Name: 1130, dtype: object
Team         WSA
League        AL
Year        1967
RS           550
RA           637
W             76
G            161
Playoffs       0
Name: 1131, dtype: object
Team         ATL
League        NL
Year        1966
RS           782
RA           683
W             85
G            163
Playoffs       0
Name: 1132, dtype: object
Team         BAL
League        AL
Year        1966
RS           755
RA           601
W             97
G            160
Playoffs       1
Name: 1133, dtype: object
Team         BOS
League        AL
Year        1966
RS           655
RA           731
W             72
G            162
Playoffs       0
Name: 1134, dtype: object
Team         CAL
League        AL
Year        1966
RS           604
RA           643
W             80
G            162
Playoffs       0
Name: 1135, dtype: object
Team         CHC
League        NL
Year        1966
RS           644
RA           809
W             59
G            162
Playoffs       0
Name: 1136, dtype: object
Team         CHW
League        AL
Year        1966
RS           574
RA           517
W             83
G            163
Playoffs       0
Name: 1137, dtype: object
Team         CIN
League        NL
Year        1966
RS           692
RA           702
W             76
G            160
Playoffs       0
Name: 1138, dtype: object
Team         CLE
League        AL
Year        1966
RS           574
RA           586
W             81
G            162
Playoffs       0
Name: 1139, dtype: object
Team         DET
League        AL
Year        1966
RS           719
RA           698
W             88
G            162
Playoffs       0
Name: 1140, dtype: object
Team         HOU
League        NL
Year        1966
RS           612
RA           695
W             72
G            163
Playoffs       0
Name: 1141, dtype: object
Team         KCA
League        AL
Year        1966
RS           564
RA           648
W             74
G            160
Playoffs       0
Name: 1142, dtype: object
Team         LAD
League        NL
Year        1966
RS           606
RA           490
W             95
G            162
Playoffs       1
Name: 1143, dtype: object
Team         MIN
League        AL
Year        1966
RS           663
RA           581
W             89
G            162
Playoffs       0
Name: 1144, dtype: object
Team         NYM
League        NL
Year        1966
RS           587
RA           761
W             66
G            161
Playoffs       0
Name: 1145, dtype: object
Team         NYY
League        AL
Year        1966
RS           611
RA           612
W             70
G            160
Playoffs       0
Name: 1146, dtype: object
Team         PHI
League        NL
Year        1966
RS           696
RA           640
W             87
G            162
Playoffs       0
Name: 1147, dtype: object
Team         PIT
League        NL
Year        1966
RS           759
RA           641
W             92
G            162
Playoffs       0
Name: 1148, dtype: object
Team         SFG
League        NL
Year        1966
RS           675
RA           626
W             93
G            161
Playoffs       0
Name: 1149, dtype: object
Team         STL
League        NL
Year        1966
RS           571
RA           577
W             83
G            162
Playoffs       0
Name: 1150, dtype: object
Team         WSA
League        AL
Year        1966
RS           557
RA           659
W             71
G            159
Playoffs       0
Name: 1151, dtype: object
Team         BAL
League        AL
Year        1965
RS           641
RA           578
W             94
G            162
Playoffs       0
Name: 1152, dtype: object
Team         BOS
League        AL

In [33]:
# Iterate over pit_df and print each index variable and then each row
for i,row in pit_df.iterrows():
    print(i)
    print(row)
    print(type(row))

0
Team         ARI
League        NL
Year        2012
RS           734
RA           688
W             81
G            162
Playoffs       0
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
1
Team         ATL
League        NL
Year        2012
RS           700
RA           600
W             94
G            162
Playoffs       1
Name: 1, dtype: object
<class 'pandas.core.series.Series'>
2
Team         BAL
League        AL
Year        2012
RS           712
RA           705
W             93
G            162
Playoffs       1
Name: 2, dtype: object
<class 'pandas.core.series.Series'>
3
Team         BOS
League        AL
Year        2012
RS           734
RA           806
W             69
G            162
Playoffs       0
Name: 3, dtype: object
<class 'pandas.core.series.Series'>
4
Team         CHC
League        NL
Year        2012
RS           613
RA           759
W             61
G            162
Playoffs       0
Name: 4, dtype: object
<class 'pandas.core.series.Series'>
5
Team         CHW
League        AL
Year        2012
RS           748
RA           676
W             85
G            162
Playoffs       0
Name: 5, dtype: object
<class 'pandas.core.series.Series'>
6
Team         CIN
League        NL
Year        2012
RS           669
RA           588
W             97
G            162
Playoffs       1
Name: 6, dtype: object
<class 'pandas.core.series.Series'>
7
Team         CLE
League        AL
Year        2012
RS           667
RA           845
W             68
G            162
Playoffs       0
Name: 7, dtype: object
<class 'pandas.core.series.Series'>
8
Team         COL
League        NL
Year        2012
RS           758
RA           890
W             64
G            162
Playoffs       0
Name: 8, dtype: object
<class 'pandas.core.series.Series'>
9
Team         DET
League        AL
Year        2012
RS           726
RA           670
W             88
G            162
Playoffs       1
Name: 9, dtype: object
<class 'pandas.core.series.Series'>
10
Team         HOU
League        NL
Year        2012
RS           583
RA           794
W             55
G            162
Playoffs       0
Name: 10, dtype: object
<class 'pandas.core.series.Series'>
11
Team         KCR
League        AL
Year        2012
RS           676
RA           746
W             72
G            162
Playoffs       0
Name: 11, dtype: object
<class 'pandas.core.series.Series'>
12
Team         LAA
League        AL
Year        2012
RS           767
RA           699
W             89
G            162
Playoffs       0
Name: 12, dtype: object
<class 'pandas.core.series.Series'>
13
Team         LAD
League        NL
Year        2012
RS           637
RA           597
W             86
G            162
Playoffs       0
Name: 13, dtype: object
<class 'pandas.core.series.Series'>
14
Team         MIA
League        NL
Year        2012
RS           609
RA           724
W             69
G            162
Playoffs       0
Name: 14, dtype: object
<class 'pandas.core.series.Series'>
15
Team         MIL
League        NL
Year        2012
RS           776
RA           733
W             83
G            162
Playoffs       0
Name: 15, dtype: object
<class 'pandas.core.series.Series'>
16
Team         MIN
League        AL
Year        2012
RS           701
RA           832
W             66
G            162
Playoffs       0
Name: 16, dtype: object
<class 'pandas.core.series.Series'>
17
Team         NYM
League        NL
Year        2012
RS           650
RA           709
W             74
G            162
Playoffs       0
Name: 17, dtype: object
<class 'pandas.core.series.Series'>
18
Team         NYY
League        AL
Year        2012
RS           804
RA           668
W             95
G            162
Playoffs       1
Name: 18, dtype: object
<class 'pandas.core.series.Series'>
19
Team         OAK
League        AL
Year        2012
RS           713
RA           614
W             94
G            162
Playoffs       1
Name: 19, dtype: object
<class 'pandas.core.series.Series'>
20
Team         PHI
League        NL
Year        2012
RS           684
RA           680
W             81
G            162
Playoffs       0
Name: 20, dtype: object
<class 'pandas.core.series.Series'>
21
Team         PIT
League        NL
Year        2012
RS           651
RA           674
W             79
G            162
Playoffs       0
Name: 21, dtype: object
<class 'pandas.core.series.Series'>
22
Team         SDP
League        NL
Year        2012
RS           651
RA           710
W             76
G            162
Playoffs       0
Name: 22, dtype: object
<class 'pandas.core.series.Series'>
23
Team         SEA
League        AL
Year        2012
RS           619
RA           651
W             75
G            162
Playoffs       0
Name: 23, dtype: object
<class 'pandas.core.series.Series'>
24
Team         SFG
League        NL
Year        2012
RS           718
RA           649
W             94
G            162
Playoffs       1
Name: 24, dtype: object
<class 'pandas.core.series.Series'>
25
Team         STL
League        NL
Year        2012
RS           765
RA           648
W             88
G            162
Playoffs       1
Name: 25, dtype: object
<class 'pandas.core.series.Series'>
26
Team         TBR
League        AL
Year        2012
RS           697
RA           577
W             90
G            162
Playoffs       0
Name: 26, dtype: object
<class 'pandas.core.series.Series'>
27
Team         TEX
League        AL
Year        2012
RS           808
RA           707
W             93
G            162
Playoffs       1
Name: 27, dtype: object
<class 'pandas.core.series.Series'>
28
Team         TOR
League        AL
Year        2012
RS           716
RA           784
W             73
G            162
Playoffs       0
Name: 28, dtype: object
<class 'pandas.core.series.Series'>
29
Team         WSN
League        NL
Year        2012
RS           731
RA           594
W             98
G            162
Playoffs       1
Name: 29, dtype: object
<class 'pandas.core.series.Series'>
30
Team         ARI
League        NL
Year        2011
RS           731
RA           662
W             94
G            162
Playoffs       1
Name: 30, dtype: object
<class 'pandas.core.series.Series'>
31
Team         ATL
League        NL
Year        2011
RS           641
RA           605
W             89
G            162
Playoffs       0
Name: 31, dtype: object
<class 'pandas.core.series.Series'>
32
Team         BAL
League        AL
Year        2011
RS           708
RA           860
W             69
G            162
Playoffs       0
Name: 32, dtype: object
<class 'pandas.core.series.Series'>
33
Team         BOS
League        AL
Year        2011
RS           875
RA           737
W             90
G            162
Playoffs       0
Name: 33, dtype: object
<class 'pandas.core.series.Series'>
34
Team         CHC
League        NL
Year        2011
RS           654
RA           756
W             71
G            162
Playoffs       0
Name: 34, dtype: object
<class 'pandas.core.series.Series'>
35
Team         CHW
League        AL
Year        2011
RS           654
RA           706
W             79
G            162
Playoffs       0
Name: 35, dtype: object
<class 'pandas.core.series.Series'>
36
Team         CIN
League        NL
Year        2011
RS           735
RA           720
W             79
G            162
Playoffs       0
Name: 36, dtype: object
<class 'pandas.core.series.Series'>
37
Team         CLE
League        AL
Year        2011
RS           704
RA           760
W             80
G            162
Playoffs       0
Name: 37, dtype: object
<class 'pandas.core.series.Series'>
38
Team         COL
League        NL
Year        2011
RS           735
RA           774
W             73
G            162
Playoffs       0
Name: 38, dtype: object
<class 'pandas.core.series.Series'>
39
Team         DET
League        AL
Year        2011
RS           787
RA           711
W             95
G            162
Playoffs       1
Name: 39, dtype: object
<class 'pandas.core.series.Series'>
40
Team         FLA
League        NL
Year        2011
RS           625
RA           702
W             72
G            162
Playoffs       0
Name: 40, dtype: object
<class 'pandas.core.series.Series'>
41
Team         HOU
League        NL
Year        2011
RS           615
RA           796
W             56
G            162
Playoffs       0
Name: 41, dtype: object
<class 'pandas.core.series.Series'>
42
Team         KCR
League        AL
Year        2011
RS           730
RA           762
W             71
G            162
Playoffs       0
Name: 42, dtype: object
<class 'pandas.core.series.Series'>
43
Team         LAA
League        AL
Year        2011
RS           667
RA           633
W             86
G            162
Playoffs       0
Name: 43, dtype: object
<class 'pandas.core.series.Series'>
44
Team         LAD
League        NL
Year        2011
RS           644
RA           612
W             82
G            161
Playoffs       0
Name: 44, dtype: object
<class 'pandas.core.series.Series'>
45
Team         MIL
League        NL
Year        2011
RS           721
RA           638
W             96
G            162
Playoffs       1
Name: 45, dtype: object
<class 'pandas.core.series.Series'>
46
Team         MIN
League        AL
Year        2011
RS           619
RA           804
W             63
G            162
Playoffs       0
Name: 46, dtype: object
<class 'pandas.core.series.Series'>
47
Team         NYM
League        NL
Year        2011
RS           718
RA           742
W             77
G            162
Playoffs       0
Name: 47, dtype: object
<class 'pandas.core.series.Series'>
48
Team         NYY
League        AL
Year        2011
RS           867
RA           657
W             97
G            162
Playoffs       1
Name: 48, dtype: object
<class 'pandas.core.series.Series'>
49
Team         OAK
League        AL
Year        2011
RS           645
RA           679
W             74
G            162
Playoffs       0
Name: 49, dtype: object
<class 'pandas.core.series.Series'>
50
Team         PHI
League        NL
Year        2011
RS           713
RA           529
W            102
G            162
Playoffs       1
Name: 50, dtype: object
<class 'pandas.core.series.Series'>
51
Team         PIT
League        NL
Year        2011
RS           610
RA           712
W             72
G            162
Playoffs       0
Name: 51, dtype: object
<class 'pandas.core.series.Series'>
52
Team         SDP
League        NL
Year        2011
RS           593
RA           611
W             71
G            162
Playoffs       0
Name: 52, dtype: object
<class 'pandas.core.series.Series'>
53
Team         SEA
League        AL
Year        2011
RS           556
RA           675
W             67
G            162
Playoffs       0
Name: 53, dtype: object
<class 'pandas.core.series.Series'>
54
Team         SFG
League        NL
Year        2011
RS           570
RA           578
W             86
G            162
Playoffs       0
Name: 54, dtype: object
<class 'pandas.core.series.Series'>
55
Team         STL
League        NL
Year        2011
RS           762
RA           692
W             90
G            162
Playoffs       1
Name: 55, dtype: object
<class 'pandas.core.series.Series'>
56
Team         TBR
League        AL
Year        2011
RS           707
RA           614
W             91
G            162
Playoffs       1
Name: 56, dtype: object
<class 'pandas.core.series.Series'>
57
Team         TEX
League        AL
Year        2011
RS           855
RA           677
W             96
G            162
Playoffs       1
Name: 57, dtype: object
<class 'pandas.core.series.Series'>
58
Team         TOR
League        AL
Year        2011
RS           743
RA           761
W             81
G            162
Playoffs       0
Name: 58, dtype: object
<class 'pandas.core.series.Series'>
59
Team         WSN
League        NL
Year        2011
RS           624
RA           643
W             80
G            161
Playoffs       0
Name: 59, dtype: object
<class 'pandas.core.series.Series'>
60
Team         ARI
League        NL
Year        2010
RS           713
RA           836
W             65
G            162
Playoffs       0
Name: 60, dtype: object
<class 'pandas.core.series.Series'>
61
Team         ATL
League        NL
Year        2010
RS           738
RA           629
W             91
G            162
Playoffs       1
Name: 61, dtype: object
<class 'pandas.core.series.Series'>
62
Team         BAL
League        AL
Year        2010
RS           613
RA           785
W             66
G            162
Playoffs       0
Name: 62, dtype: object
<class 'pandas.core.series.Series'>
63
Team         BOS
League        AL
Year        2010
RS           818
RA           744
W             89
G            162
Playoffs       0
Name: 63, dtype: object
<class 'pandas.core.series.Series'>
64
Team         CHC
League        NL
Year        2010
RS           685
RA           767
W             75
G            162
Playoffs       0
Name: 64, dtype: object
<class 'pandas.core.series.Series'>
65
Team         CHW
League        AL
Year        2010
RS           752
RA           704
W             88
G            162
Playoffs       0
Name: 65, dtype: object
<class 'pandas.core.series.Series'>
66
Team         CIN
League        NL
Year        2010
RS           790
RA           685
W             91
G            162
Playoffs       1
Name: 66, dtype: object
<class 'pandas.core.series.Series'>
67
Team         CLE
League        AL
Year        2010
RS           646
RA           752
W             69
G            162
Playoffs       0
Name: 67, dtype: object
<class 'pandas.core.series.Series'>
68
Team         COL
League        NL
Year        2010
RS           770
RA           717
W             83
G            162
Playoffs       0
Name: 68, dtype: object
<class 'pandas.core.series.Series'>
69
Team         DET
League        AL
Year        2010
RS           751
RA           743
W             81
G            162
Playoffs       0
Name: 69, dtype: object
<class 'pandas.core.series.Series'>
70
Team         FLA
League        NL
Year        2010
RS           719
RA           717
W             80
G            162
Playoffs       0
Name: 70, dtype: object
<class 'pandas.core.series.Series'>
71
Team         HOU
League        NL
Year        2010
RS           611
RA           729
W             76
G            162
Playoffs       0
Name: 71, dtype: object
<class 'pandas.core.series.Series'>
72
Team         KCR
League        AL
Year        2010
RS           676
RA           845
W             67
G            162
Playoffs       0
Name: 72, dtype: object
<class 'pandas.core.series.Series'>
73
Team         LAA
League        AL
Year        2010
RS           681
RA           702
W             80
G            162
Playoffs       0
Name: 73, dtype: object
<class 'pandas.core.series.Series'>
74
Team         LAD
League        NL
Year        2010
RS           667
RA           692
W             80
G            162
Playoffs       0
Name: 74, dtype: object
<class 'pandas.core.series.Series'>
75
Team         MIL
League        NL
Year        2010
RS           750
RA           804
W             77
G            162
Playoffs       0
Name: 75, dtype: object
<class 'pandas.core.series.Series'>
76
Team         MIN
League        AL
Year        2010
RS           781
RA           671
W             94
G            162
Playoffs       1
Name: 76, dtype: object
<class 'pandas.core.series.Series'>
77
Team         NYM
League        NL
Year        2010
RS           656
RA           652
W             79
G            162
Playoffs       0
Name: 77, dtype: object
<class 'pandas.core.series.Series'>
78
Team         NYY
League        AL
Year        2010
RS           859
RA           693
W             95
G            162
Playoffs       1
Name: 78, dtype: object
<class 'pandas.core.series.Series'>
79
Team         OAK
League        AL
Year        2010
RS           663
RA           626
W             81
G            162
Playoffs       0
Name: 79, dtype: object
<class 'pandas.core.series.Series'>
80
Team         PHI
League        NL
Year        2010
RS           772
RA           640
W             97
G            162
Playoffs       1
Name: 80, dtype: object
<class 'pandas.core.series.Series'>
81
Team         PIT
League        NL
Year        2010
RS           587
RA           866
W             57
G            162
Playoffs       0
Name: 81, dtype: object
<class 'pandas.core.series.Series'>
82
Team         SDP
League        NL
Year        2010
RS           665
RA           581
W             90
G            162
Playoffs       0
Name: 82, dtype: object
<class 'pandas.core.series.Series'>
83
Team         SEA
League        AL
Year        2010
RS           513
RA           698
W             61
G            162
Playoffs       0
Name: 83, dtype: object
<class 'pandas.core.series.Series'>
84
Team         SFG
League        NL
Year        2010
RS           697
RA           583
W             92
G            162
Playoffs       1
Name: 84, dtype: object
<class 'pandas.core.series.Series'>
85
Team         STL
League        NL
Year        2010
RS           736
RA           641
W             86
G            162
Playoffs       0
Name: 85, dtype: object
<class 'pandas.core.series.Series'>
86
Team         TBR
League        AL
Year        2010
RS           802
RA           649
W             96
G            162
Playoffs       1
Name: 86, dtype: object
<class 'pandas.core.series.Series'>
87
Team         TEX
League        AL
Year        2010
RS           787
RA           687
W             90
G            162
Playoffs       1
Name: 87, dtype: object
<class 'pandas.core.series.Series'>
88
Team         TOR
League        AL
Year        2010
RS           755
RA           728
W             85
G            162
Playoffs       0
Name: 88, dtype: object
<class 'pandas.core.series.Series'>
89
Team         WSN
League        NL
Year        2010
RS           655
RA           742
W             69
G            162
Playoffs       0
Name: 89, dtype: object
<class 'pandas.core.series.Series'>
90
Team         ARI
League        NL
Year        2009
RS           720
RA           782
W             70
G            162
Playoffs       0
Name: 90, dtype: object
<class 'pandas.core.series.Series'>
91
Team         ATL
League        NL
Year        2009
RS           735
RA           641
W             86
G            162
Playoffs       0
Name: 91, dtype: object
<class 'pandas.core.series.Series'>
92
Team         BAL
League        AL
Year        2009
RS           741
RA           876
W             64
G            162
Playoffs       0
Name: 92, dtype: object
<class 'pandas.core.series.Series'>
93
Team         BOS
League        AL
Year        2009
RS           872
RA           736
W             95
G            162
Playoffs       1
Name: 93, dtype: object
<class 'pandas.core.series.Series'>
94
Team         CHC
League        NL
Year        2009
RS           707
RA           672
W             83
G            161
Playoffs       0
Name: 94, dtype: object
<class 'pandas.core.series.Series'>
95
Team         CHW
League        AL
Year        2009
RS           724
RA           732
W             79
G            162
Playoffs       0
Name: 95, dtype: object
<class 'pandas.core.series.Series'>
96
Team         CIN
League        NL
Year        2009
RS           673
RA           723
W             78
G            162
Playoffs       0
Name: 96, dtype: object
<class 'pandas.core.series.Series'>
97
Team         CLE
League        AL
Year        2009
RS           773
RA           865
W             65
G            162
Playoffs       0
Name: 97, dtype: object
<class 'pandas.core.series.Series'>
98
Team         COL
League        NL
Year        2009
RS           804
RA           715
W             92
G            162
Playoffs       1
Name: 98, dtype: object
<class 'pandas.core.series.Series'>
99
Team         DET
League        AL
Year        2009
RS           743
RA           745
W             86
G            163
Playoffs       0
Name: 99, dtype: object
<class 'pandas.core.series.Series'>
100
Team         FLA
League        NL
Year        2009
RS           772
RA           766
W             87

Name: 176, dtype: object
<class 'pandas.core.series.Series'>
177
Team         TEX
League        AL
Year        2007
RS           816
RA           844
W             75
G            162
Playoffs       0
Name: 177, dtype: object
<class 'pandas.core.series.Series'>
178
Team         TOR
League        AL
Year        2007
RS           753
RA           699
W             83
G            162
Playoffs       0
Name: 178, dtype: object
<class 'pandas.core.series.Series'>
179
Team         WSN
League        NL
Year        2007
RS           673
RA           783
W             73
G            162
Playoffs       0
Name: 179, dtype: object
<class 'pandas.core.series.Series'>
180
Team         ARI
League        NL
Year        2006
RS           773
RA           788
W             76
G            162
Playoffs       0
Name: 180, dtype: object
<class 'pandas.core.series.Series'>
181
Team         ATL
League        NL
Year        2006
RS           849
RA           805
W             79
G            162
Playoffs       0
Name: 181, dtype: object
<class 'pandas.core.series.Series'>
182
Team         BAL
League        AL
Year        2006
RS           768
RA           899
W             70
G            162
Playoffs       0
Name: 182, dtype: object
<class 'pandas.core.series.Series'>
183
Team         BOS
League        AL
Year        2006
RS           820
RA           825
W             86
G            162
Playoffs       0
Name: 183, dtype: object
<class 'pandas.core.series.Series'>
184
Team         CHC
League        NL
Year        2006
RS           716
RA           834
W             66
G            162
Playoffs       0
Name: 184, dtype: object
<class 'pandas.core.series.Series'>
185
Team         CHW
League        AL
Year        2006
RS           868
RA           794
W             90
G            162
Playoffs       0
Name: 185, dtype: object
<class 'pandas.core.series.Series'>
186
Team         CIN
League        NL
Year        2006
RS           749
RA           801
W             80
G            162
Playoffs       0
Name: 186, dtype: object
<class 'pandas.core.series.Series'>
187
Team         CLE
League        AL
Year        2006
RS           870
RA           782
W             78
G            162
Playoffs       0
Name: 187, dtype: object
<class 'pandas.core.series.Series'>
188
Team         COL
League        NL
Year        2006
RS           813
RA           812
W             76
G            162
Playoffs       0
Name: 188, dtype: object
<class 'pandas.core.series.Series'>
189
Team         DET
League        AL
Year        2006
RS           822
RA           675
W             95
G            162
Playoffs       1
Name: 189, dtype: object
<class 'pandas.core.series.Series'>
190
Team         FLA
League        NL
Year        2006
RS           758
RA           772
W             78
G            162
Playoffs       0
Name: 190, dtype: object
<class 'pandas.core.series.Series'>
191
Team         HOU
League        NL
Year        2006
RS           735
RA           719
W             82
G            162
Playoffs       0
Name: 191, dtype: object
<class 'pandas.core.series.Series'>
192
Team         KCR
League        AL
Year        2006
RS           757
RA           971
W             62
G            162
Playoffs       0
Name: 192, dtype: object
<class 'pandas.core.series.Series'>
193
Team         LAA
League        AL
Year        2006
RS           766
RA           732
W             89
G            162
Playoffs       0
Name: 193, dtype: object
<class 'pandas.core.series.Series'>
194
Team         LAD
League        NL
Year        2006
RS           820
RA           751
W             88
G            162
Playoffs       1
Name: 194, dtype: object
<class 'pandas.core.series.Series'>
195
Team         MIL
League        NL
Year        2006
RS           730
RA           833
W             75
G            162
Playoffs       0
Name: 195, dtype: object
<class 'pandas.core.series.Series'>
196
Team         MIN
League        AL
Year        2006
RS           801
RA           683
W             96
G            162
Playoffs       1
Name: 196, dtype: object
<class 'pandas.core.series.Series'>
197
Team         NYM
League        NL
Year        2006
RS           834
RA           731
W             97
G            162
Playoffs       1
Name: 197, dtype: object
<class 'pandas.core.series.Series'>
198
Team         NYY
League        AL
Year        2006
RS           930
RA           767
W             97
G            162
Playoffs       1
Name: 198, dtype: object
<class 'pandas.core.series.Series'>
199
Team         OAK
League        AL
Year        2006
RS           771
RA           727
W             93
G            162
Playoffs       1
Name: 199, dtype: object
<class 'pandas.core.series.Series'>
200
Team         PHI
League        NL
Year        2006
RS           865
RA           812
W             85
G            162
Playoffs       0
Name: 200, dtype: object
<class 'pandas.core.series.Series'>
201
Team         PIT
League        NL
Year        2006
RS           691
RA           797
W             67
G            162
Playoffs       0
Name: 201, dtype: object
<class 'pandas.core.series.Series'>
202
Team         SDP
League        NL
Year        2006
RS           731
RA           679
W             88
G            162
Playoffs       1
Name: 202, dtype: object
<class 'pandas.core.series.Series'>
203
Team         SEA
League        AL
Year        2006
RS           756
RA           792
W             78
G            162
Playoffs       0
Name: 203, dtype: object
<class 'pandas.core.series.Series'>
204
Team         SFG
League        NL
Year        2006
RS           746
RA           790
W             76
G            161
Playoffs       0
Name: 204, dtype: object
<class 'pandas.core.series.Series'>
205
Team         STL
League        NL
Year        2006
RS           781
RA           762
W             83
G            161
Playoffs       1
Name: 205, dtype: object
<class 'pandas.core.series.Series'>
206
Team         TBD
League        AL
Year        2006
RS           689
RA           856
W             61
G            162
Playoffs       0
Name: 206, dtype: object
<class 'pandas.core.series.Series'>
207
Team         TEX
League        AL
Year        2006
RS           835
RA           784
W             80
G            162
Playoffs       0
Name: 207, dtype: object
<class 'pandas.core.series.Series'>
208
Team         TOR
League        AL
Year        2006
RS           809
RA           754
W             87
G            162
Playoffs       0
Name: 208, dtype: object
<class 'pandas.core.series.Series'>
209
Team         WSN
League        NL
Year        2006
RS           746
RA           872
W             71
G            162
Playoffs       0
Name: 209, dtype: object
<class 'pandas.core.series.Series'>
210
Team         ARI
League        NL
Year        2005
RS           696
RA           856
W             77
G            162
Playoffs       0
Name: 210, dtype: object
<class 'pandas.core.series.Series'>
211
Team         ATL
League        NL
Year        2005
RS           769
RA           674
W             90
G            162
Playoffs       1
Name: 211, dtype: object
<class 'pandas.core.series.Series'>
212
Team         BAL
League        AL
Year        2005
RS           729
RA           800
W             74
G            162
Playoffs       0
Name: 212, dtype: object
<class 'pandas.core.series.Series'>
213
Team         BOS
League        AL
Year        2005
RS           910
RA           805
W             95
G            162
Playoffs       1
Name: 213, dtype: object
<class 'pandas.core.series.Series'>
214
Team         CHC
League        NL
Year        2005
RS           703
RA           714
W             79
G            162
Playoffs       0
Name: 214, dtype: object
<class 'pandas.core.series.Series'>
215
Team         CHW
League        AL
Year        2005
RS           741
RA           645
W             99
G            162
Playoffs       1
Name: 215, dtype: object
<class 'pandas.core.series.Series'>
216
Team         CIN
League        NL
Year        2005
RS           820
RA           889
W             73
G            163
Playoffs       0
Name: 216, dtype: object
<class 'pandas.core.series.Series'>
217
Team         CLE
League        AL
Year        2005
RS           790
RA           642
W             93
G            162
Playoffs       0
Name: 217, dtype: object
<class 'pandas.core.series.Series'>
218
Team         COL
League        NL
Year        2005
RS           740
RA           862
W             67
G            162
Playoffs       0
Name: 218, dtype: object
<class 'pandas.core.series.Series'>
219
Team         DET
League        AL
Year        2005
RS           723
RA           787
W             71
G            162
Playoffs       0
Name: 219, dtype: object
<class 'pandas.core.series.Series'>
220
Team         FLA
League        NL
Year        2005
RS           717
RA           732
W             83
G            162
Playoffs       0
Name: 220, dtype: object
<class 'pandas.core.series.Series'>
221
Team         HOU
League        NL
Year        2005
RS           693
RA           609
W             89
G            163
Playoffs       1
Name: 221, dtype: object
<class 'pandas.core.series.Series'>
222
Team         KCR
League        AL
Year        2005
RS           701
RA           935
W             56
G            162
Playoffs       0
Name: 222, dtype: object
<class 'pandas.core.series.Series'>
223
Team         LAA
League        AL
Year        2005
RS           761
RA           643
W             95
G            162
Playoffs       1
Name: 223, dtype: object
<class 'pandas.core.series.Series'>
224
Team         LAD
League        NL
Year        2005
RS           685
RA           755
W             71
G            162
Playoffs       0
Name: 224, dtype: object
<class 'pandas.core.series.Series'>
225
Team         MIL
League        NL
Year        2005
RS           726
RA           697
W             81
G            162
Playoffs       0
Name: 225, dtype: object
<class 'pandas.core.series.Series'>
226
Team         MIN
League        AL
Year        2005
RS           688
RA           662
W             83
G            162
Playoffs       0
Name: 226, dtype: object
<class 'pandas.core.series.Series'>
227
Team         NYM
League        NL
Year        2005
RS           722
RA           648
W             83
G            162
Playoffs       0
Name: 227, dtype: object
<class 'pandas.core.series.Series'>
228
Team         NYY
League        AL
Year        2005
RS           886
RA           789
W             95
G            162
Playoffs       1
Name: 228, dtype: object
<class 'pandas.core.series.Series'>
229
Team         OAK
League        AL
Year        2005
RS           772
RA           658
W             88
G            162
Playoffs       0
Name: 229, dtype: object
<class 'pandas.core.series.Series'>
230
Team         PHI
League        NL
Year        2005
RS           807
RA           726
W             88
G            162
Playoffs       0
Name: 230, dtype: object
<class 'pandas.core.series.Series'>
231
Team         PIT
League        NL
Year        2005
RS           680
RA           769
W             67
G            162
Playoffs       0
Name: 231, dtype: object
<class 'pandas.core.series.Series'>
232
Team         SDP
League        NL
Year        2005
RS           684
RA           726
W             82
G            162
Playoffs       1
Name: 232, dtype: object
<class 'pandas.core.series.Series'>
233
Team         SEA
League        AL
Year        2005
RS           699
RA           751
W             69
G            162
Playoffs       0
Name: 233, dtype: object
<class 'pandas.core.series.Series'>
234
Team         SFG
League        NL
Year        2005
RS           649
RA           745
W             75
G            162
Playoffs       0
Name: 234, dtype: object
<class 'pandas.core.series.Series'>
235
Team         STL
League        NL
Year        2005
RS           805
RA           634
W            100
G            162
Playoffs       1
Name: 235, dtype: object
<class 'pandas.core.series.Series'>
236
Team         TBD
League        AL
Year        2005
RS           750
RA           936
W             67
G            162
Playoffs       0
Name: 236, dtype: object
<class 'pandas.core.series.Series'>
237
Team         TEX
League        AL
Year        2005
RS           865
RA           858
W             79
G            162
Playoffs       0
Name: 237, dtype: object
<class 'pandas.core.series.Series'>
238
Team         TOR
League        AL
Year        2005
RS           775
RA           705
W             80
G            162
Playoffs       0
Name: 238, dtype: object
<class 'pandas.core.series.Series'>
239
Team         WSN
League        NL
Year        2005
RS           639
RA           673
W             81
G            162
Playoffs       0
Name: 239, dtype: object
<class 'pandas.core.series.Series'>
240
Team         ANA
League        AL
Year        2004
RS           836
RA           734
W             92
G            162
Playoffs       1
Name: 240, dtype: object
<class 'pandas.core.series.Series'>
241
Team         ARI
League        NL
Year        2004
RS           615
RA           899
W             51
G            162
Playoffs       0
Name: 241, dtype: object
<class 'pandas.core.series.Series'>
242
Team         ATL
League        NL
Year        2004
RS           803
RA           668
W             96
G            162
Playoffs       1
Name: 242, dtype: object
<class 'pandas.core.series.Series'>
243
Team         BAL
League        AL
Year        2004
RS           842
RA           830
W             78
G            162
Playoffs       0
Name: 243, dtype: object
<class 'pandas.core.series.Series'>
244
Team         BOS
League        AL
Year        2004
RS           949
RA           768
W             98
G            162
Playoffs       1
Name: 244, dtype: object
<class 'pandas.core.series.Series'>
245
Team         CHC
League        NL
Year        2004
RS           789
RA           665
W             89
G            162
Playoffs       0
Name: 245, dtype: object
<class 'pandas.core.series.Series'>
246
Team         CHW
League        AL
Year        2004
RS           865
RA           831
W             83
G            162
Playoffs       0
Name: 246, dtype: object
<class 'pandas.core.series.Series'>
247
Team         CIN
League        NL
Year        2004
RS           750
RA           907
W             76
G            162
Playoffs       0
Name: 247, dtype: object
<class 'pandas.core.series.Series'>
248
Team         CLE
League        AL
Year        2004
RS           858
RA           857
W             80
G            162
Playoffs       0
Name: 248, dtype: object
<class 'pandas.core.series.Series'>
249
Team         COL
League        NL
Year        2004
RS           833
RA           923
W             68
G            162
Playoffs       0
Name: 249, dtype: object
<class 'pandas.core.series.Series'>
250
Team         DET
League        AL
Year        2004
RS           827
RA           844
W             72
G            162
Playoffs       0
Name: 250, dtype: object
<class 'pandas.core.series.Series'>
251
Team         FLA
League        NL
Year        2004
RS           718
RA           700
W             83
G            162
Playoffs       0
Name: 251, dtype: object
<class 'pandas.core.series.Series'>
252
Team         HOU
League        NL
Year        2004
RS           803
RA           698
W             92
G            162
Playoffs       1
Name: 252, dtype: object
<class 'pandas.core.series.Series'>
253
Team         KCR
League        AL
Year        2004
RS           720
RA           905
W             58
G            162
Playoffs       0
Name: 253, dtype: object
<class 'pandas.core.series.Series'>
254
Team         LAD
League        NL
Year        2004
RS           761
RA           684
W             93
G            162
Playoffs       1
Name: 254, dtype: object
<class 'pandas.core.series.Series'>
255
Team         MIL
League        NL
Year        2004
RS           634
RA           757
W             67
G            161
Playoffs       0
Name: 255, dtype: object
<class 'pandas.core.series.Series'>
256
Team         MIN
League        AL
Year        2004
RS           780
RA           715
W             92
G            162
Playoffs       1
Name: 256, dtype: object
<class 'pandas.core.series.Series'>
257
Team         MON
League        NL
Year        2004
RS           635
RA           769
W             67
G            162
Playoffs       0
Name: 257, dtype: object
<class 'pandas.core.series.Series'>
258
Team         NYM
League        NL
Year        2004
RS           684
RA           731
W             71
G            162
Playoffs       0
Name: 258, dtype: object
<class 'pandas.core.series.Series'>
259
Team         NYY
League        AL
Year        2004
RS           897
RA           808
W            101
G            162
Playoffs       1
Name: 259, dtype: object
<class 'pandas.core.series.Series'>
260
Team         OAK
League        AL
Year        2004
RS           793
RA           742
W             91
G            162
Playoffs       0
Name: 260, dtype: object
<class 'pandas.core.series.Series'>
261
Team         PHI
League        NL
Year        2004
RS           840
RA           781
W             86
G            162
Playoffs       0
Name: 261, dtype: object
<class 'pandas.core.series.Series'>
262
Team         PIT
League        NL
Year        2004
RS           680
RA           744
W             72
G            161
Playoffs       0
Name: 262, dtype: object
<class 'pandas.core.series.Series'>
263
Team         SDP
League        NL
Year        2004
RS           768
RA           705
W             87
G            162
Playoffs       0
Name: 263, dtype: object
<class 'pandas.core.series.Series'>
264
Team         SEA
League        AL
Year        2004
RS           698
RA           823
W             63
G            162
Playoffs       0
Name: 264, dtype: object
<class 'pandas.core.series.Series'>
265
Team         SFG
League        NL
Year        2004
RS           850
RA           770
W             91
G            162
Playoffs       0
Name: 265, dtype: object
<class 'pandas.core.series.Series'>
266
Team         STL
League        NL
Year        2004
RS           855
RA           659
W            105
G            162
Playoffs       1
Name: 266, dtype: object
<class 'pandas.core.series.Series'>
267
Team         TBD
League        AL
Year        2004
RS           714
RA           842
W             70
G            161
Playoffs       0
Name: 267, dtype: object
<class 'pandas.core.series.Series'>
268
Team         TEX
League        AL
Year        2004
RS           860
RA           794
W             89
G            162
Playoffs       0
Name: 268, dtype: object
<class 'pandas.core.series.Series'>
269
Team         TOR
League        AL
Year        2004
RS           719
RA           823
W             67
G            161
Playoffs       0
Name: 269, dtype: object
<class 'pandas.core.series.Series'>
270
Team         ANA
League        AL
Year        2003
RS           736
RA           743
W             77
G            162
Playoffs       0
Name: 270, dtype: object
<class 'pandas.core.series.Series'>
271
Team         ARI
League        NL
Year        2003
RS           717
RA           685
W             84
G            162
Playoffs       0
Name: 271, dtype: object
<class 'pandas.core.series.Series'>
272
Team         ATL
League        NL
Year        2003
RS           907
RA           740
W            101
G            162
Playoffs       1
Name: 272, dtype: object
<class 'pandas.core.series.Series'>
273
Team         BAL
League        AL
Year        2003
RS           743
RA           820
W             71
G            163
Playoffs       0
Name: 273, dtype: object
<class 'pandas.core.series.Series'>
274
Team         BOS
League        AL
Year        2003
RS           961
RA           809
W             95
G            162
Playoffs       1
Name: 274, dtype: object
<class 'pandas.core.series.Series'>
275
Team         CHC
League        NL
Year        2003
RS           724
RA           683
W             88
G            162
Playoffs       1
Name: 275, dtype: object
<class 'pandas.core.series.Series'>
276
Team         CHW
League        AL

Name: 371, dtype: object
<class 'pandas.core.series.Series'>
372
Team         HOU
League        NL
Year        2000
RS           938
RA           944
W             72
G            162
Playoffs       0
Name: 372, dtype: object
<class 'pandas.core.series.Series'>
373
Team         KCR
League        AL
Year        2000
RS           879
RA           930
W             77
G            162
Playoffs       0
Name: 373, dtype: object
<class 'pandas.core.series.Series'>
374
Team         LAD
League        NL
Year        2000
RS           798
RA           729
W             86
G            162
Playoffs       0
Name: 374, dtype: object
<class 'pandas.core.series.Series'>
375
Team         MIL
League        NL
Year        2000
RS           740
RA           826
W             73
G            163
Playoffs       0
Name: 375, dtype: object
<class 'pandas.core.series.Series'>
376
Team         MIN
League        AL
Year        2000
RS           748
RA           880
W             69
G            162
Playoffs       0
Name: 376, dtype: object
<class 'pandas.core.series.Series'>
377
Team         MON
League        NL
Year        2000
RS           738
RA           902
W             67
G            162
Playoffs       0
Name: 377, dtype: object
<class 'pandas.core.series.Series'>
378
Team         NYM
League        NL
Year        2000
RS           807
RA           738
W             94
G            162
Playoffs       1
Name: 378, dtype: object
<class 'pandas.core.series.Series'>
379
Team         NYY
League        AL
Year        2000
RS           871
RA           814
W             87
G            161
Playoffs       1
Name: 379, dtype: object
<class 'pandas.core.series.Series'>
380
Team         OAK
League        AL
Year        2000
RS           947
RA           813
W             91
G            161
Playoffs       1
Name: 380, dtype: object
<class 'pandas.core.series.Series'>
381
Team         PHI
League        NL
Year        2000
RS           708
RA           830
W             65
G            162
Playoffs       0
Name: 381, dtype: object
<class 'pandas.core.series.Series'>
382
Team         PIT
League        NL
Year        2000
RS           793
RA           888
W             69
G            162
Playoffs       0
Name: 382, dtype: object
<class 'pandas.core.series.Series'>
383
Team         SDP
League        NL
Year        2000
RS           752
RA           815
W             76
G            162
Playoffs       0
Name: 383, dtype: object
<class 'pandas.core.series.Series'>
384
Team         SEA
League        AL
Year        2000
RS           907
RA           780
W             91
G            162
Playoffs       1
Name: 384, dtype: object
<class 'pandas.core.series.Series'>
385
Team         SFG
League        NL
Year        2000
RS           925
RA           747
W             97
G            162
Playoffs       1
Name: 385, dtype: object
<class 'pandas.core.series.Series'>
386
Team         STL
League        NL
Year        2000
RS           887
RA           771
W             95
G            162
Playoffs       1
Name: 386, dtype: object
<class 'pandas.core.series.Series'>
387
Team         TBD
League        AL
Year        2000
RS           733
RA           842
W             69
G            161
Playoffs       0
Name: 387, dtype: object
<class 'pandas.core.series.Series'>
388
Team         TEX
League        AL
Year        2000
RS           848
RA           974
W             71
G            162
Playoffs       0
Name: 388, dtype: object
<class 'pandas.core.series.Series'>
389
Team         TOR
League        AL
Year        2000
RS           861
RA           908
W             83
G            162
Playoffs       0
Name: 389, dtype: object
<class 'pandas.core.series.Series'>
390
Team         ANA
League        AL
Year        1999
RS           711
RA           826
W             70
G            162
Playoffs       0
Name: 390, dtype: object
<class 'pandas.core.series.Series'>
391
Team         ARI
League        NL
Year        1999
RS           908
RA           676
W            100
G            162
Playoffs       1
Name: 391, dtype: object
<class 'pandas.core.series.Series'>
392
Team         ATL
League        NL
Year        1999
RS           840
RA           661
W            103
G            162
Playoffs       1
Name: 392, dtype: object
<class 'pandas.core.series.Series'>
393
Team         BAL
League        AL
Year        1999
RS           851
RA           815
W             78
G            162
Playoffs       0
Name: 393, dtype: object
<class 'pandas.core.series.Series'>
394
Team         BOS
League        AL
Year        1999
RS           836
RA           718
W             94
G            162
Playoffs       1
Name: 394, dtype: object
<class 'pandas.core.series.Series'>
395
Team         CHC
League        NL
Year        1999
RS           747
RA           920
W             67
G            162
Playoffs       0
Name: 395, dtype: object
<class 'pandas.core.series.Series'>
396
Team         CHW
League        AL
Year        1999
RS           777
RA           870
W             75
G            162
Playoffs       0
Name: 396, dtype: object
<class 'pandas.core.series.Series'>
397
Team         CIN
League        NL
Year        1999
RS           865
RA           711
W             96
G            163
Playoffs       0
Name: 397, dtype: object
<class 'pandas.core.series.Series'>
398
Team         CLE
League        AL
Year        1999
RS          1009
RA           860
W             97
G            162
Playoffs       1
Name: 398, dtype: object
<class 'pandas.core.series.Series'>
399
Team         COL
League        NL
Year        1999
RS           906
RA          1028
W             72
G            162
Playoffs       0
Name: 399, dtype: object
<class 'pandas.core.series.Series'>
400
Team         DET
League        AL
Year        1999
RS           747
RA           882
W             69
G            161
Playoffs       0
Name: 400, dtype: object
<class 'pandas.core.series.Series'>
401
Team         FLA
League        NL
Year        1999
RS           691
RA           852
W             64
G            162
Playoffs       0
Name: 401, dtype: object
<class 'pandas.core.series.Series'>
402
Team         HOU
League        NL
Year        1999
RS           823
RA           675
W             97
G            162
Playoffs       1
Name: 402, dtype: object
<class 'pandas.core.series.Series'>
403
Team         KCR
League        AL
Year        1999
RS           856
RA           921
W             64
G            161
Playoffs       0
Name: 403, dtype: object
<class 'pandas.core.series.Series'>
404
Team         LAD
League        NL
Year        1999
RS           793
RA           787
W             77
G            162
Playoffs       0
Name: 404, dtype: object
<class 'pandas.core.series.Series'>
405
Team         MIL
League        NL
Year        1999
RS           815
RA           886
W             74
G            161
Playoffs       0
Name: 405, dtype: object
<class 'pandas.core.series.Series'>
406
Team         MIN
League        AL
Year        1999
RS           686
RA           845
W             63
G            161
Playoffs       0
Name: 406, dtype: object
<class 'pandas.core.series.Series'>
407
Team         MON
League        NL
Year        1999
RS           718
RA           853
W             68
G            162
Playoffs       0
Name: 407, dtype: object
<class 'pandas.core.series.Series'>
408
Team         NYM
League        NL
Year        1999
RS           853
RA           711
W             97
G            163
Playoffs       1
Name: 408, dtype: object
<class 'pandas.core.series.Series'>
409
Team         NYY
League        AL
Year        1999
RS           900
RA           731
W             98
G            162
Playoffs       1
Name: 409, dtype: object
<class 'pandas.core.series.Series'>
410
Team         OAK
League        AL
Year        1999
RS           893
RA           846
W             87
G            162
Playoffs       0
Name: 410, dtype: object
<class 'pandas.core.series.Series'>
411
Team         PHI
League        NL
Year        1999
RS           841
RA           846
W             77
G            162
Playoffs       0
Name: 411, dtype: object
<class 'pandas.core.series.Series'>
412
Team         PIT
League        NL
Year        1999
RS           775
RA           782
W             78
G            161
Playoffs       0
Name: 412, dtype: object
<class 'pandas.core.series.Series'>
413
Team         SDP
League        NL
Year        1999
RS           710
RA           781
W             74
G            162
Playoffs       0
Name: 413, dtype: object
<class 'pandas.core.series.Series'>
414
Team         SEA
League        AL
Year        1999
RS           859
RA           905
W             79
G            162
Playoffs       0
Name: 414, dtype: object
<class 'pandas.core.series.Series'>
415
Team         SFG
League        NL
Year        1999
RS           872
RA           831
W             86
G            162
Playoffs       0
Name: 415, dtype: object
<class 'pandas.core.series.Series'>
416
Team         STL
League        NL
Year        1999
RS           809
RA           838
W             75
G            161
Playoffs       0
Name: 416, dtype: object
<class 'pandas.core.series.Series'>
417
Team         TBD
League        AL
Year        1999
RS           772
RA           913
W             69
G            162
Playoffs       0
Name: 417, dtype: object
<class 'pandas.core.series.Series'>
418
Team         TEX
League        AL
Year        1999
RS           945
RA           859
W             95
G            162
Playoffs       1
Name: 418, dtype: object
<class 'pandas.core.series.Series'>
419
Team         TOR
League        AL
Year        1999
RS           883
RA           862
W             84
G            162
Playoffs       0
Name: 419, dtype: object
<class 'pandas.core.series.Series'>
420
Team         ANA
League        AL
Year        1998
RS           787
RA           783
W             85
G            162
Playoffs       0
Name: 420, dtype: object
<class 'pandas.core.series.Series'>
421
Team         ARI
League        NL
Year        1998
RS           665
RA           812
W             65
G            162
Playoffs       0
Name: 421, dtype: object
<class 'pandas.core.series.Series'>
422
Team         ATL
League        NL
Year        1998
RS           826
RA           581
W            106
G            162
Playoffs       1
Name: 422, dtype: object
<class 'pandas.core.series.Series'>
423
Team         BAL
League        AL
Year        1998
RS           817
RA           785
W             79
G            162
Playoffs       0
Name: 423, dtype: object
<class 'pandas.core.series.Series'>
424
Team         BOS
League        AL
Year        1998
RS           876
RA           729
W             92
G            162
Playoffs       1
Name: 424, dtype: object
<class 'pandas.core.series.Series'>
425
Team         CHC
League        NL
Year        1998
RS           831
RA           792
W             90
G            163
Playoffs       1
Name: 425, dtype: object
<class 'pandas.core.series.Series'>
426
Team         CHW
League        AL
Year        1998
RS           861
RA           931
W             80
G            163
Playoffs       0
Name: 426, dtype: object
<class 'pandas.core.series.Series'>
427
Team         CIN
League        NL
Year        1998
RS           750
RA           760
W             77
G            162
Playoffs       0
Name: 427, dtype: object
<class 'pandas.core.series.Series'>
428
Team         CLE
League        AL
Year        1998
RS           850
RA           779
W             89
G            162
Playoffs       1
Name: 428, dtype: object
<class 'pandas.core.series.Series'>
429
Team         COL
League        NL
Year        1998
RS           826
RA           855
W             77
G            162
Playoffs       0
Name: 429, dtype: object
<class 'pandas.core.series.Series'>
430
Team         DET
League        AL
Year        1998
RS           722
RA           863
W             65
G            162
Playoffs       0
Name: 430, dtype: object
<class 'pandas.core.series.Series'>
431
Team         FLA
League        NL
Year        1998
RS           667
RA           923
W             54
G            162
Playoffs       0
Name: 431, dtype: object
<class 'pandas.core.series.Series'>
432
Team         HOU
League        NL
Year        1998
RS           874
RA           620
W            102
G            162
Playoffs       1
Name: 432, dtype: object
<class 'pandas.core.series.Series'>
433
Team         KCR
League        AL
Year        1998
RS           714
RA           899
W             72
G            161
Playoffs       0
Name: 433, dtype: object
<class 'pandas.core.series.Series'>
434
Team         LAD
League        NL
Year        1998
RS           669
RA           678
W             83
G            162
Playoffs       0
Name: 434, dtype: object
<class 'pandas.core.series.Series'>
435
Team         MIL
League        NL
Year        1998
RS           707
RA           812
W             74
G            162
Playoffs       0
Name: 435, dtype: object
<class 'pandas.core.series.Series'>
436
Team         MIN
League        AL
Year        1998
RS           734
RA           818
W             70
G            162
Playoffs       0
Name: 436, dtype: object
<class 'pandas.core.series.Series'>
437
Team         MON
League        NL
Year        1998
RS           644
RA           783
W             65
G            162
Playoffs       0
Name: 437, dtype: object
<class 'pandas.core.series.Series'>
438
Team         NYM
League        NL
Year        1998
RS           706
RA           645
W             88
G            162
Playoffs       0
Name: 438, dtype: object
<class 'pandas.core.series.Series'>
439
Team         NYY
League        AL
Year        1998
RS           965
RA           656
W            114
G            162
Playoffs       1
Name: 439, dtype: object
<class 'pandas.core.series.Series'>
440
Team         OAK
League        AL
Year        1998
RS           804
RA           866
W             74
G            162
Playoffs       0
Name: 440, dtype: object
<class 'pandas.core.series.Series'>
441
Team         PHI
League        NL
Year        1998
RS           713
RA           808
W             75
G            162
Playoffs       0
Name: 441, dtype: object
<class 'pandas.core.series.Series'>
442
Team         PIT
League        NL
Year        1998
RS           650
RA           718
W             69
G            163
Playoffs       0
Name: 442, dtype: object
<class 'pandas.core.series.Series'>
443
Team         SDP
League        NL
Year        1998
RS           749
RA           635
W             98
G            162
Playoffs       1
Name: 443, dtype: object
<class 'pandas.core.series.Series'>
444
Team         SEA
League        AL
Year        1998
RS           859
RA           855
W             76
G            161
Playoffs       0
Name: 444, dtype: object
<class 'pandas.core.series.Series'>
445
Team         SFG
League        NL
Year        1998
RS           845
RA           739
W             89
G            163
Playoffs       0
Name: 445, dtype: object
<class 'pandas.core.series.Series'>
446
Team         STL
League        NL
Year        1998
RS           810
RA           782
W             83
G            163
Playoffs       0
Name: 446, dtype: object
<class 'pandas.core.series.Series'>
447
Team         TBD
League        AL
Year        1998
RS           620
RA           751
W             63
G            162
Playoffs       0
Name: 447, dtype: object
<class 'pandas.core.series.Series'>
448
Team         TEX
League        AL
Year        1998
RS           940
RA           871
W             88
G            162
Playoffs       1
Name: 448, dtype: object
<class 'pandas.core.series.Series'>
449
Team         TOR
League        AL
Year        1998
RS           816
RA           768
W             88
G            163
Playoffs       0
Name: 449, dtype: object
<class 'pandas.core.series.Series'>
450
Team         ANA
League        AL
Year        1997
RS           829
RA           794
W             84
G            162
Playoffs       0
Name: 450, dtype: object
<class 'pandas.core.series.Series'>
451
Team         ATL
League        NL
Year        1997
RS           791
RA           581
W            101
G            162
Playoffs       1
Name: 451, dtype: object
<class 'pandas.core.series.Series'>
452
Team         BAL
League        AL
Year        1997
RS           812
RA           681
W             98
G            162
Playoffs       1
Name: 452, dtype: object
<class 'pandas.core.series.Series'>
453
Team         BOS
League        AL
Year        1997
RS           851
RA           857
W             78
G            162
Playoffs       0
Name: 453, dtype: object
<class 'pandas.core.series.Series'>
454
Team         CHC
League        NL
Year        1997
RS           687
RA           759
W             68
G            162
Playoffs       0
Name: 454, dtype: object
<class 'pandas.core.series.Series'>
455
Team         CHW
League        AL
Year        1997
RS           779
RA           833
W             80
G            161
Playoffs       0
Name: 455, dtype: object
<class 'pandas.core.series.Series'>
456
Team         CIN
League        NL
Year        1997
RS           651
RA           764
W             76
G            162
Playoffs       0
Name: 456, dtype: object
<class 'pandas.core.series.Series'>
457
Team         CLE
League        AL
Year        1997
RS           868
RA           815
W             86
G            161
Playoffs       1
Name: 457, dtype: object
<class 'pandas.core.series.Series'>
458
Team         COL
League        NL
Year        1997
RS           923
RA           908
W             83
G            162
Playoffs       0
Name: 458, dtype: object
<class 'pandas.core.series.Series'>
459
Team         DET
League        AL
Year        1997
RS           784
RA           790
W             79
G            162
Playoffs       0
Name: 459, dtype: object
<class 'pandas.core.series.Series'>
460
Team         FLA
League        NL
Year        1997
RS           740
RA           669
W             92
G            162
Playoffs       1
Name: 460, dtype: object
<class 'pandas.core.series.Series'>
461
Team         HOU
League        NL
Year        1997
RS           777
RA           660
W             84
G            162
Playoffs       1
Name: 461, dtype: object
<class 'pandas.core.series.Series'>
462
Team         KCR
League        AL
Year        1997
RS           747
RA           820
W             67
G            161
Playoffs       0
Name: 462, dtype: object
<class 'pandas.core.series.Series'>
463
Team         LAD
League        NL
Year        1997
RS           742
RA           645
W             88
G            162
Playoffs       0
Name: 463, dtype: object
<class 'pandas.core.series.Series'>
464
Team         MIL
League        AL
Year        1997
RS           681
RA           742
W             78
G            161
Playoffs       0
Name: 464, dtype: object
<class 'pandas.core.series.Series'>
465
Team         MIN
League        AL
Year        1997
RS           772
RA           861
W             68
G            162
Playoffs       0
Name: 465, dtype: object
<class 'pandas.core.series.Series'>
466
Team         MON
League        NL
Year        1997
RS           691
RA           740
W             78
G            162
Playoffs       0
Name: 466, dtype: object
<class 'pandas.core.series.Series'>
467
Team         NYM
League        NL
Year        1997
RS           777
RA           709
W             88
G            162
Playoffs       0
Name: 467, dtype: object
<class 'pandas.core.series.Series'>
468
Team         NYY
League        AL
Year        1997
RS           891
RA           688
W             96
G            162
Playoffs       1
Name: 468, dtype: object
<class 'pandas.core.series.Series'>
469
Team         OAK
League        AL
Year        1997
RS           764
RA           946
W             65
G            162
Playoffs       0
Name: 469, dtype: object
<class 'pandas.core.series.Series'>
470
Team         PHI
League        NL
Year        1997
RS           668
RA           840
W             68
G            162
Playoffs       0
Name: 470, dtype: object
<class 'pandas.core.series.Series'>
471
Team         PIT
League        NL

Name: 555, dtype: object
<class 'pandas.core.series.Series'>
556
Team         SFG
League        NL
Year        1992
RS           574
RA           647
W             72
G            162
Playoffs       0
Name: 556, dtype: object
<class 'pandas.core.series.Series'>
557
Team         STL
League        NL
Year        1992
RS           631
RA           604
W             83
G            162
Playoffs       0
Name: 557, dtype: object
<class 'pandas.core.series.Series'>
558
Team         TEX
League        AL
Year        1992
RS           682
RA           753
W             77
G            162
Playoffs       0
Name: 558, dtype: object
<class 'pandas.core.series.Series'>
559
Team         TOR
League        AL
Year        1992
RS           780
RA           682
W             96
G            162
Playoffs       1
Name: 559, dtype: object
<class 'pandas.core.series.Series'>
560
Team         ATL
League        NL
Year        1991
RS           749
RA           644
W             94
G            162
Playoffs       1
Name: 560, dtype: object
<class 'pandas.core.series.Series'>
561
Team         BAL
League        AL
Year        1991
RS           686
RA           796
W             67
G            162
Playoffs       0
Name: 561, dtype: object
<class 'pandas.core.series.Series'>
562
Team         BOS
League        AL
Year        1991
RS           731
RA           712
W             84
G            162
Playoffs       0
Name: 562, dtype: object
<class 'pandas.core.series.Series'>
563
Team         CAL
League        AL
Year        1991
RS           653
RA           649
W             81
G            162
Playoffs       0
Name: 563, dtype: object
<class 'pandas.core.series.Series'>
564
Team         CHC
League        NL
Year        1991
RS           695
RA           734
W             77
G            160
Playoffs       0
Name: 564, dtype: object
<class 'pandas.core.series.Series'>
565
Team         CHW
League        AL
Year        1991
RS           758
RA           681
W             87
G            162
Playoffs       0
Name: 565, dtype: object
<class 'pandas.core.series.Series'>
566
Team         CIN
League        NL
Year        1991
RS           689
RA           691
W             74
G            162
Playoffs       0
Name: 566, dtype: object
<class 'pandas.core.series.Series'>
567
Team         CLE
League        AL
Year        1991
RS           576
RA           759
W             57
G            162
Playoffs       0
Name: 567, dtype: object
<class 'pandas.core.series.Series'>
568
Team         DET
League        AL
Year        1991
RS           817
RA           794
W             84
G            162
Playoffs       0
Name: 568, dtype: object
<class 'pandas.core.series.Series'>
569
Team         HOU
League        NL
Year        1991
RS           605
RA           717
W             65
G            162
Playoffs       0
Name: 569, dtype: object
<class 'pandas.core.series.Series'>
570
Team         KCR
League        AL
Year        1991
RS           727
RA           722
W             82
G            162
Playoffs       0
Name: 570, dtype: object
<class 'pandas.core.series.Series'>
571
Team         LAD
League        NL
Year        1991
RS           665
RA           565
W             93
G            162
Playoffs       0
Name: 571, dtype: object
<class 'pandas.core.series.Series'>
572
Team         MIL
League        AL
Year        1991
RS           799
RA           744
W             83
G            162
Playoffs       0
Name: 572, dtype: object
<class 'pandas.core.series.Series'>
573
Team         MIN
League        AL
Year        1991
RS           776
RA           652
W             95
G            162
Playoffs       1
Name: 573, dtype: object
<class 'pandas.core.series.Series'>
574
Team         MON
League        NL
Year        1991
RS           579
RA           655
W             71
G            161
Playoffs       0
Name: 574, dtype: object
<class 'pandas.core.series.Series'>
575
Team         NYM
League        NL
Year        1991
RS           640
RA           646
W             77
G            161
Playoffs       0
Name: 575, dtype: object
<class 'pandas.core.series.Series'>
576
Team         NYY
League        AL
Year        1991
RS           674
RA           777
W             71
G            162
Playoffs       0
Name: 576, dtype: object
<class 'pandas.core.series.Series'>
577
Team         OAK
League        AL
Year        1991
RS           760
RA           776
W             84
G            162
Playoffs       0
Name: 577, dtype: object
<class 'pandas.core.series.Series'>
578
Team         PHI
League        NL
Year        1991
RS           629
RA           680
W             78
G            162
Playoffs       0
Name: 578, dtype: object
<class 'pandas.core.series.Series'>
579
Team         PIT
League        NL
Year        1991
RS           768
RA           632
W             98
G            162
Playoffs       1
Name: 579, dtype: object
<class 'pandas.core.series.Series'>
580
Team         SDP
League        NL
Year        1991
RS           636
RA           646
W             84
G            162
Playoffs       0
Name: 580, dtype: object
<class 'pandas.core.series.Series'>
581
Team         SEA
League        AL
Year        1991
RS           702
RA           674
W             83
G            162
Playoffs       0
Name: 581, dtype: object
<class 'pandas.core.series.Series'>
582
Team         SFG
League        NL
Year        1991
RS           649
RA           697
W             75
G            162
Playoffs       0
Name: 582, dtype: object
<class 'pandas.core.series.Series'>
583
Team         STL
League        NL
Year        1991
RS           651
RA           648
W             84
G            162
Playoffs       0
Name: 583, dtype: object
<class 'pandas.core.series.Series'>
584
Team         TEX
League        AL
Year        1991
RS           829
RA           814
W             85
G            162
Playoffs       0
Name: 584, dtype: object
<class 'pandas.core.series.Series'>
585
Team         TOR
League        AL
Year        1991
RS           684
RA           622
W             91
G            162
Playoffs       1
Name: 585, dtype: object
<class 'pandas.core.series.Series'>
586
Team         ATL
League        NL
Year        1990
RS           682
RA           821
W             65
G            162
Playoffs       0
Name: 586, dtype: object
<class 'pandas.core.series.Series'>
587
Team         BAL
League        AL
Year        1990
RS           669
RA           698
W             76
G            161
Playoffs       0
Name: 587, dtype: object
<class 'pandas.core.series.Series'>
588
Team         BOS
League        AL
Year        1990
RS           699
RA           664
W             88
G            162
Playoffs       1
Name: 588, dtype: object
<class 'pandas.core.series.Series'>
589
Team         CAL
League        AL
Year        1990
RS           690
RA           706
W             80
G            162
Playoffs       0
Name: 589, dtype: object
<class 'pandas.core.series.Series'>
590
Team         CHC
League        NL
Year        1990
RS           690
RA           774
W             77
G            162
Playoffs       0
Name: 590, dtype: object
<class 'pandas.core.series.Series'>
591
Team         CHW
League        AL
Year        1990
RS           682
RA           633
W             94
G            162
Playoffs       0
Name: 591, dtype: object
<class 'pandas.core.series.Series'>
592
Team         CIN
League        NL
Year        1990
RS           693
RA           597
W             91
G            162
Playoffs       1
Name: 592, dtype: object
<class 'pandas.core.series.Series'>
593
Team         CLE
League        AL
Year        1990
RS           732
RA           737
W             77
G            162
Playoffs       0
Name: 593, dtype: object
<class 'pandas.core.series.Series'>
594
Team         DET
League        AL
Year        1990
RS           750
RA           754
W             79
G            162
Playoffs       0
Name: 594, dtype: object
<class 'pandas.core.series.Series'>
595
Team         HOU
League        NL
Year        1990
RS           573
RA           656
W             75
G            162
Playoffs       0
Name: 595, dtype: object
<class 'pandas.core.series.Series'>
596
Team         KCR
League        AL
Year        1990
RS           707
RA           709
W             75
G            161
Playoffs       0
Name: 596, dtype: object
<class 'pandas.core.series.Series'>
597
Team         LAD
League        NL
Year        1990
RS           728
RA           685
W             86
G            162
Playoffs       0
Name: 597, dtype: object
<class 'pandas.core.series.Series'>
598
Team         MIL
League        AL
Year        1990
RS           732
RA           760
W             74
G            162
Playoffs       0
Name: 598, dtype: object
<class 'pandas.core.series.Series'>
599
Team         MIN
League        AL
Year        1990
RS           666
RA           729
W             74
G            162
Playoffs       0
Name: 599, dtype: object
<class 'pandas.core.series.Series'>
600
Team         MON
League        NL
Year        1990
RS           662
RA           598
W             85
G            162
Playoffs       0
Name: 600, dtype: object
<class 'pandas.core.series.Series'>
601
Team         NYM
League        NL
Year        1990
RS           775
RA           613
W             91
G            162
Playoffs       0
Name: 601, dtype: object
<class 'pandas.core.series.Series'>
602
Team         NYY
League        AL
Year        1990
RS           603
RA           749
W             67
G            162
Playoffs       0
Name: 602, dtype: object
<class 'pandas.core.series.Series'>
603
Team         OAK
League        AL
Year        1990
RS           733
RA           570
W            103
G            162
Playoffs       1
Name: 603, dtype: object
<class 'pandas.core.series.Series'>
604
Team         PHI
League        NL
Year        1990
RS           646
RA           729
W             77
G            162
Playoffs       0
Name: 604, dtype: object
<class 'pandas.core.series.Series'>
605
Team         PIT
League        NL
Year        1990
RS           733
RA           619
W             95
G            162
Playoffs       1
Name: 605, dtype: object
<class 'pandas.core.series.Series'>
606
Team         SDP
League        NL
Year        1990
RS           673
RA           673
W             75
G            162
Playoffs       0
Name: 606, dtype: object
<class 'pandas.core.series.Series'>
607
Team         SEA
League        AL
Year        1990
RS           640
RA           680
W             77
G            162
Playoffs       0
Name: 607, dtype: object
<class 'pandas.core.series.Series'>
608
Team         SFG
League        NL
Year        1990
RS           719
RA           710
W             85
G            162
Playoffs       0
Name: 608, dtype: object
<class 'pandas.core.series.Series'>
609
Team         STL
League        NL
Year        1990
RS           599
RA           698
W             70
G            162
Playoffs       0
Name: 609, dtype: object
<class 'pandas.core.series.Series'>
610
Team         TEX
League        AL
Year        1990
RS           676
RA           696
W             83
G            162
Playoffs       0
Name: 610, dtype: object
<class 'pandas.core.series.Series'>
611
Team         TOR
League        AL
Year        1990
RS           767
RA           661
W             86
G            162
Playoffs       0
Name: 611, dtype: object
<class 'pandas.core.series.Series'>
612
Team         ATL
League        NL
Year        1989
RS           584
RA           680
W             63
G            161
Playoffs       0
Name: 612, dtype: object
<class 'pandas.core.series.Series'>
613
Team         BAL
League        AL
Year        1989
RS           708
RA           686
W             87
G            162
Playoffs       0
Name: 613, dtype: object
<class 'pandas.core.series.Series'>
614
Team         BOS
League        AL
Year        1989
RS           774
RA           735
W             83
G            162
Playoffs       0
Name: 614, dtype: object
<class 'pandas.core.series.Series'>
615
Team         CAL
League        AL
Year        1989
RS           669
RA           578
W             91
G            162
Playoffs       0
Name: 615, dtype: object
<class 'pandas.core.series.Series'>
616
Team         CHC
League        NL
Year        1989
RS           702
RA           623
W             93
G            162
Playoffs       1
Name: 616, dtype: object
<class 'pandas.core.series.Series'>
617
Team         CHW
League        AL
Year        1989
RS           693
RA           750
W             69
G            161
Playoffs       0
Name: 617, dtype: object
<class 'pandas.core.series.Series'>
618
Team         CIN
League        NL
Year        1989
RS           632
RA           691
W             75
G            162
Playoffs       0
Name: 618, dtype: object
<class 'pandas.core.series.Series'>
619
Team         CLE
League        AL
Year        1989
RS           604
RA           654
W             73
G            162
Playoffs       0
Name: 619, dtype: object
<class 'pandas.core.series.Series'>
620
Team         DET
League        AL
Year        1989
RS           617
RA           816
W             59
G            162
Playoffs       0
Name: 620, dtype: object
<class 'pandas.core.series.Series'>
621
Team         HOU
League        NL
Year        1989
RS           647
RA           669
W             86
G            162
Playoffs       0
Name: 621, dtype: object
<class 'pandas.core.series.Series'>
622
Team         KCR
League        AL
Year        1989
RS           690
RA           635
W             92
G            162
Playoffs       0
Name: 622, dtype: object
<class 'pandas.core.series.Series'>
623
Team         LAD
League        NL
Year        1989
RS           554
RA           536
W             77
G            160
Playoffs       0
Name: 623, dtype: object
<class 'pandas.core.series.Series'>
624
Team         MIL
League        AL
Year        1989
RS           707
RA           679
W             81
G            162
Playoffs       0
Name: 624, dtype: object
<class 'pandas.core.series.Series'>
625
Team         MIN
League        AL
Year        1989
RS           740
RA           738
W             80
G            162
Playoffs       0
Name: 625, dtype: object
<class 'pandas.core.series.Series'>
626
Team         MON
League        NL
Year        1989
RS           632
RA           630
W             81
G            162
Playoffs       0
Name: 626, dtype: object
<class 'pandas.core.series.Series'>
627
Team         NYM
League        NL
Year        1989
RS           683
RA           595
W             87
G            162
Playoffs       0
Name: 627, dtype: object
<class 'pandas.core.series.Series'>
628
Team         NYY
League        AL
Year        1989
RS           698
RA           792
W             74
G            161
Playoffs       0
Name: 628, dtype: object
<class 'pandas.core.series.Series'>
629
Team         OAK
League        AL
Year        1989
RS           712
RA           576
W             99
G            162
Playoffs       1
Name: 629, dtype: object
<class 'pandas.core.series.Series'>
630
Team         PHI
League        NL
Year        1989
RS           629
RA           735
W             67
G            163
Playoffs       0
Name: 630, dtype: object
<class 'pandas.core.series.Series'>
631
Team         PIT
League        NL
Year        1989
RS           637
RA           680
W             74
G            164
Playoffs       0
Name: 631, dtype: object
<class 'pandas.core.series.Series'>
632
Team         SDP
League        NL
Year        1989
RS           642
RA           626
W             89
G            162
Playoffs       0
Name: 632, dtype: object
<class 'pandas.core.series.Series'>
633
Team         SEA
League        AL
Year        1989
RS           694
RA           728
W             73
G            162
Playoffs       0
Name: 633, dtype: object
<class 'pandas.core.series.Series'>
634
Team         SFG
League        NL
Year        1989
RS           699
RA           600
W             92
G            162
Playoffs       1
Name: 634, dtype: object
<class 'pandas.core.series.Series'>
635
Team         STL
League        NL
Year        1989
RS           632
RA           608
W             86
G            164
Playoffs       0
Name: 635, dtype: object
<class 'pandas.core.series.Series'>
636
Team         TEX
League        AL
Year        1989
RS           695
RA           714
W             83
G            162
Playoffs       0
Name: 636, dtype: object
<class 'pandas.core.series.Series'>
637
Team         TOR
League        AL
Year        1989
RS           731
RA           651
W             89
G            162
Playoffs       1
Name: 637, dtype: object
<class 'pandas.core.series.Series'>
638
Team         ATL
League        NL
Year        1988
RS           555
RA           741
W             54
G            160
Playoffs       0
Name: 638, dtype: object
<class 'pandas.core.series.Series'>
639
Team         BAL
League        AL
Year        1988
RS           550
RA           789
W             54
G            161
Playoffs       0
Name: 639, dtype: object
<class 'pandas.core.series.Series'>
640
Team         BOS
League        AL
Year        1988
RS           813
RA           689
W             89
G            162
Playoffs       1
Name: 640, dtype: object
<class 'pandas.core.series.Series'>
641
Team         CAL
League        AL
Year        1988
RS           714
RA           771
W             75
G            162
Playoffs       0
Name: 641, dtype: object
<class 'pandas.core.series.Series'>
642
Team         CHC
League        NL
Year        1988
RS           660
RA           694
W             77
G            163
Playoffs       0
Name: 642, dtype: object
<class 'pandas.core.series.Series'>
643
Team         CHW
League        AL
Year        1988
RS           631
RA           757
W             71
G            161
Playoffs       0
Name: 643, dtype: object
<class 'pandas.core.series.Series'>
644
Team         CIN
League        NL
Year        1988
RS           641
RA           596
W             87
G            161
Playoffs       0
Name: 644, dtype: object
<class 'pandas.core.series.Series'>
645
Team         CLE
League        AL
Year        1988
RS           666
RA           731
W             78
G            162
Playoffs       0
Name: 645, dtype: object
<class 'pandas.core.series.Series'>
646
Team         DET
League        AL
Year        1988
RS           703
RA           658
W             88
G            162
Playoffs       0
Name: 646, dtype: object
<class 'pandas.core.series.Series'>
647
Team         HOU
League        NL
Year        1988
RS           617
RA           631
W             82
G            162
Playoffs       0
Name: 647, dtype: object
<class 'pandas.core.series.Series'>
648
Team         KCR
League        AL
Year        1988
RS           704
RA           648
W             84
G            161
Playoffs       0
Name: 648, dtype: object
<class 'pandas.core.series.Series'>
649
Team         LAD
League        NL
Year        1988
RS           628
RA           544
W             94
G            162
Playoffs       1
Name: 649, dtype: object
<class 'pandas.core.series.Series'>
650
Team         MIL
League        AL
Year        1988
RS           682
RA           616
W             87
G            162
Playoffs       0
Name: 650, dtype: object
<class 'pandas.core.series.Series'>
651
Team         MIN
League        AL
Year        1988
RS           759
RA           672
W             91
G            162
Playoffs       0
Name: 651, dtype: object
<class 'pandas.core.series.Series'>
652
Team         MON
League        NL
Year        1988
RS           628
RA           592
W             81
G            163
Playoffs       0
Name: 652, dtype: object
<class 'pandas.core.series.Series'>
653
Team         NYM
League        NL
Year        1988
RS           703
RA           532
W            100
G            160
Playoffs       1
Name: 653, dtype: object
<class 'pandas.core.series.Series'>
654
Team         NYY
League        AL
Year        1988
RS           772
RA           748
W             85
G            161
Playoffs       0
Name: 654, dtype: object
<class 'pandas.core.series.Series'>
655
Team         OAK
League        AL

Name: 748, dtype: object
<class 'pandas.core.series.Series'>
749
Team         CLE
League        AL
Year        1984
RS           761
RA           766
W             75
G            163
Playoffs       0
Name: 749, dtype: object
<class 'pandas.core.series.Series'>
750
Team         DET
League        AL
Year        1984
RS           829
RA           643
W            104
G            162
Playoffs       1
Name: 750, dtype: object
<class 'pandas.core.series.Series'>
751
Team         HOU
League        NL
Year        1984
RS           693
RA           630
W             80
G            162
Playoffs       0
Name: 751, dtype: object
<class 'pandas.core.series.Series'>
752
Team         KCR
League        AL
Year        1984
RS           673
RA           686
W             84
G            162
Playoffs       1
Name: 752, dtype: object
<class 'pandas.core.series.Series'>
753
Team         LAD
League        NL
Year        1984
RS           580
RA           600
W             79
G            162
Playoffs       0
Name: 753, dtype: object
<class 'pandas.core.series.Series'>
754
Team         MIL
League        AL
Year        1984
RS           641
RA           734
W             67
G            161
Playoffs       0
Name: 754, dtype: object
<class 'pandas.core.series.Series'>
755
Team         MIN
League        AL
Year        1984
RS           673
RA           675
W             81
G            162
Playoffs       0
Name: 755, dtype: object
<class 'pandas.core.series.Series'>
756
Team         MON
League        NL
Year        1984
RS           593
RA           585
W             78
G            161
Playoffs       0
Name: 756, dtype: object
<class 'pandas.core.series.Series'>
757
Team         NYM
League        NL
Year        1984
RS           652
RA           676
W             90
G            162
Playoffs       0
Name: 757, dtype: object
<class 'pandas.core.series.Series'>
758
Team         NYY
League        AL
Year        1984
RS           758
RA           679
W             87
G            162
Playoffs       0
Name: 758, dtype: object
<class 'pandas.core.series.Series'>
759
Team         OAK
League        AL
Year        1984
RS           738
RA           796
W             77
G            162
Playoffs       0
Name: 759, dtype: object
<class 'pandas.core.series.Series'>
760
Team         PHI
League        NL
Year        1984
RS           720
RA           690
W             81
G            162
Playoffs       0
Name: 760, dtype: object
<class 'pandas.core.series.Series'>
761
Team         PIT
League        NL
Year        1984
RS           615
RA           567
W             75
G            162
Playoffs       0
Name: 761, dtype: object
<class 'pandas.core.series.Series'>
762
Team         SDP
League        NL
Year        1984
RS           686
RA           634
W             92
G            162
Playoffs       1
Name: 762, dtype: object
<class 'pandas.core.series.Series'>
763
Team         SEA
League        AL
Year        1984
RS           682
RA           774
W             74
G            162
Playoffs       0
Name: 763, dtype: object
<class 'pandas.core.series.Series'>
764
Team         SFG
League        NL
Year        1984
RS           682
RA           807
W             66
G            162
Playoffs       0
Name: 764, dtype: object
<class 'pandas.core.series.Series'>
765
Team         STL
League        NL
Year        1984
RS           652
RA           645
W             84
G            162
Playoffs       0
Name: 765, dtype: object
<class 'pandas.core.series.Series'>
766
Team         TEX
League        AL
Year        1984
RS           656
RA           714
W             69
G            161
Playoffs       0
Name: 766, dtype: object
<class 'pandas.core.series.Series'>
767
Team         TOR
League        AL
Year        1984
RS           750
RA           696
W             89
G            163
Playoffs       0
Name: 767, dtype: object
<class 'pandas.core.series.Series'>
768
Team         ATL
League        NL
Year        1983
RS           746
RA           640
W             88
G            162
Playoffs       0
Name: 768, dtype: object
<class 'pandas.core.series.Series'>
769
Team         BAL
League        AL
Year        1983
RS           799
RA           652
W             98
G            162
Playoffs       1
Name: 769, dtype: object
<class 'pandas.core.series.Series'>
770
Team         BOS
League        AL
Year        1983
RS           724
RA           775
W             78
G            162
Playoffs       0
Name: 770, dtype: object
<class 'pandas.core.series.Series'>
771
Team         CAL
League        AL
Year        1983
RS           722
RA           779
W             70
G            162
Playoffs       0
Name: 771, dtype: object
<class 'pandas.core.series.Series'>
772
Team         CHC
League        NL
Year        1983
RS           701
RA           719
W             71
G            162
Playoffs       0
Name: 772, dtype: object
<class 'pandas.core.series.Series'>
773
Team         CHW
League        AL
Year        1983
RS           800
RA           650
W             99
G            162
Playoffs       1
Name: 773, dtype: object
<class 'pandas.core.series.Series'>
774
Team         CIN
League        NL
Year        1983
RS           623
RA           710
W             74
G            162
Playoffs       0
Name: 774, dtype: object
<class 'pandas.core.series.Series'>
775
Team         CLE
League        AL
Year        1983
RS           704
RA           785
W             70
G            162
Playoffs       0
Name: 775, dtype: object
<class 'pandas.core.series.Series'>
776
Team         DET
League        AL
Year        1983
RS           789
RA           679
W             92
G            162
Playoffs       0
Name: 776, dtype: object
<class 'pandas.core.series.Series'>
777
Team         HOU
League        NL
Year        1983
RS           643
RA           646
W             85
G            162
Playoffs       0
Name: 777, dtype: object
<class 'pandas.core.series.Series'>
778
Team         KCR
League        AL
Year        1983
RS           696
RA           767
W             79
G            163
Playoffs       0
Name: 778, dtype: object
<class 'pandas.core.series.Series'>
779
Team         LAD
League        NL
Year        1983
RS           654
RA           609
W             91
G            163
Playoffs       1
Name: 779, dtype: object
<class 'pandas.core.series.Series'>
780
Team         MIL
League        AL
Year        1983
RS           764
RA           708
W             87
G            162
Playoffs       0
Name: 780, dtype: object
<class 'pandas.core.series.Series'>
781
Team         MIN
League        AL
Year        1983
RS           709
RA           822
W             70
G            162
Playoffs       0
Name: 781, dtype: object
<class 'pandas.core.series.Series'>
782
Team         MON
League        NL
Year        1983
RS           677
RA           646
W             82
G            163
Playoffs       0
Name: 782, dtype: object
<class 'pandas.core.series.Series'>
783
Team         NYM
League        NL
Year        1983
RS           575
RA           680
W             68
G            162
Playoffs       0
Name: 783, dtype: object
<class 'pandas.core.series.Series'>
784
Team         NYY
League        AL
Year        1983
RS           770
RA           703
W             91
G            162
Playoffs       0
Name: 784, dtype: object
<class 'pandas.core.series.Series'>
785
Team         OAK
League        AL
Year        1983
RS           708
RA           782
W             74
G            162
Playoffs       0
Name: 785, dtype: object
<class 'pandas.core.series.Series'>
786
Team         PHI
League        NL
Year        1983
RS           696
RA           635
W             90
G            163
Playoffs       1
Name: 786, dtype: object
<class 'pandas.core.series.Series'>
787
Team         PIT
League        NL
Year        1983
RS           659
RA           648
W             84
G            162
Playoffs       0
Name: 787, dtype: object
<class 'pandas.core.series.Series'>
788
Team         SDP
League        NL
Year        1983
RS           653
RA           653
W             81
G            163
Playoffs       0
Name: 788, dtype: object
<class 'pandas.core.series.Series'>
789
Team         SEA
League        AL
Year        1983
RS           558
RA           740
W             60
G            162
Playoffs       0
Name: 789, dtype: object
<class 'pandas.core.series.Series'>
790
Team         SFG
League        NL
Year        1983
RS           687
RA           697
W             79
G            162
Playoffs       0
Name: 790, dtype: object
<class 'pandas.core.series.Series'>
791
Team         STL
League        NL
Year        1983
RS           679
RA           710
W             79
G            162
Playoffs       0
Name: 791, dtype: object
<class 'pandas.core.series.Series'>
792
Team         TEX
League        AL
Year        1983
RS           639
RA           609
W             77
G            163
Playoffs       0
Name: 792, dtype: object
<class 'pandas.core.series.Series'>
793
Team         TOR
League        AL
Year        1983
RS           795
RA           726
W             89
G            162
Playoffs       0
Name: 793, dtype: object
<class 'pandas.core.series.Series'>
794
Team         ATL
League        NL
Year        1982
RS           739
RA           702
W             89
G            162
Playoffs       1
Name: 794, dtype: object
<class 'pandas.core.series.Series'>
795
Team         BAL
League        AL
Year        1982
RS           774
RA           687
W             94
G            163
Playoffs       0
Name: 795, dtype: object
<class 'pandas.core.series.Series'>
796
Team         BOS
League        AL
Year        1982
RS           753
RA           713
W             89
G            162
Playoffs       0
Name: 796, dtype: object
<class 'pandas.core.series.Series'>
797
Team         CAL
League        AL
Year        1982
RS           814
RA           670
W             93
G            162
Playoffs       1
Name: 797, dtype: object
<class 'pandas.core.series.Series'>
798
Team         CHC
League        NL
Year        1982
RS           676
RA           709
W             73
G            162
Playoffs       0
Name: 798, dtype: object
<class 'pandas.core.series.Series'>
799
Team         CHW
League        AL
Year        1982
RS           786
RA           710
W             87
G            162
Playoffs       0
Name: 799, dtype: object
<class 'pandas.core.series.Series'>
800
Team         CIN
League        NL
Year        1982
RS           545
RA           661
W             61
G            162
Playoffs       0
Name: 800, dtype: object
<class 'pandas.core.series.Series'>
801
Team         CLE
League        AL
Year        1982
RS           683
RA           748
W             78
G            162
Playoffs       0
Name: 801, dtype: object
<class 'pandas.core.series.Series'>
802
Team         DET
League        AL
Year        1982
RS           729
RA           685
W             83
G            162
Playoffs       0
Name: 802, dtype: object
<class 'pandas.core.series.Series'>
803
Team         HOU
League        NL
Year        1982
RS           569
RA           620
W             77
G            162
Playoffs       0
Name: 803, dtype: object
<class 'pandas.core.series.Series'>
804
Team         KCR
League        AL
Year        1982
RS           784
RA           717
W             90
G            162
Playoffs       0
Name: 804, dtype: object
<class 'pandas.core.series.Series'>
805
Team         LAD
League        NL
Year        1982
RS           691
RA           612
W             88
G            162
Playoffs       0
Name: 805, dtype: object
<class 'pandas.core.series.Series'>
806
Team         MIL
League        AL
Year        1982
RS           891
RA           717
W             95
G            163
Playoffs       1
Name: 806, dtype: object
<class 'pandas.core.series.Series'>
807
Team         MIN
League        AL
Year        1982
RS           657
RA           819
W             60
G            162
Playoffs       0
Name: 807, dtype: object
<class 'pandas.core.series.Series'>
808
Team         MON
League        NL
Year        1982
RS           697
RA           616
W             86
G            162
Playoffs       0
Name: 808, dtype: object
<class 'pandas.core.series.Series'>
809
Team         NYM
League        NL
Year        1982
RS           609
RA           723
W             65
G            162
Playoffs       0
Name: 809, dtype: object
<class 'pandas.core.series.Series'>
810
Team         NYY
League        AL
Year        1982
RS           709
RA           716
W             79
G            162
Playoffs       0
Name: 810, dtype: object
<class 'pandas.core.series.Series'>
811
Team         OAK
League        AL
Year        1982
RS           691
RA           819
W             68
G            162
Playoffs       0
Name: 811, dtype: object
<class 'pandas.core.series.Series'>
812
Team         PHI
League        NL
Year        1982
RS           664
RA           654
W             89
G            162
Playoffs       0
Name: 812, dtype: object
<class 'pandas.core.series.Series'>
813
Team         PIT
League        NL
Year        1982
RS           724
RA           696
W             84
G            162
Playoffs       0
Name: 813, dtype: object
<class 'pandas.core.series.Series'>
814
Team         SDP
League        NL
Year        1982
RS           675
RA           658
W             81
G            162
Playoffs       0
Name: 814, dtype: object
<class 'pandas.core.series.Series'>
815
Team         SEA
League        AL
Year        1982
RS           651
RA           712
W             76
G            162
Playoffs       0
Name: 815, dtype: object
<class 'pandas.core.series.Series'>
816
Team         SFG
League        NL
Year        1982
RS           673
RA           687
W             87
G            162
Playoffs       0
Name: 816, dtype: object
<class 'pandas.core.series.Series'>
817
Team         STL
League        NL
Year        1982
RS           685
RA           609
W             92
G            162
Playoffs       1
Name: 817, dtype: object
<class 'pandas.core.series.Series'>
818
Team         TEX
League        AL
Year        1982
RS           590
RA           749
W             64
G            162
Playoffs       0
Name: 818, dtype: object
<class 'pandas.core.series.Series'>
819
Team         TOR
League        AL
Year        1982
RS           651
RA           701
W             78
G            162
Playoffs       0
Name: 819, dtype: object
<class 'pandas.core.series.Series'>
820
Team         ATL
League        NL
Year        1980
RS           630
RA           660
W             81
G            161
Playoffs       0
Name: 820, dtype: object
<class 'pandas.core.series.Series'>
821
Team         BAL
League        AL
Year        1980
RS           805
RA           640
W            100
G            162
Playoffs       0
Name: 821, dtype: object
<class 'pandas.core.series.Series'>
822
Team         BOS
League        AL
Year        1980
RS           757
RA           767
W             83
G            160
Playoffs       0
Name: 822, dtype: object
<class 'pandas.core.series.Series'>
823
Team         CAL
League        AL
Year        1980
RS           698
RA           797
W             65
G            160
Playoffs       0
Name: 823, dtype: object
<class 'pandas.core.series.Series'>
824
Team         CHC
League        NL
Year        1980
RS           614
RA           728
W             64
G            162
Playoffs       0
Name: 824, dtype: object
<class 'pandas.core.series.Series'>
825
Team         CHW
League        AL
Year        1980
RS           587
RA           722
W             70
G            162
Playoffs       0
Name: 825, dtype: object
<class 'pandas.core.series.Series'>
826
Team         CIN
League        NL
Year        1980
RS           707
RA           670
W             89
G            163
Playoffs       0
Name: 826, dtype: object
<class 'pandas.core.series.Series'>
827
Team         CLE
League        AL
Year        1980
RS           738
RA           807
W             79
G            160
Playoffs       0
Name: 827, dtype: object
<class 'pandas.core.series.Series'>
828
Team         DET
League        AL
Year        1980
RS           830
RA           757
W             84
G            163
Playoffs       0
Name: 828, dtype: object
<class 'pandas.core.series.Series'>
829
Team         HOU
League        NL
Year        1980
RS           637
RA           589
W             93
G            163
Playoffs       1
Name: 829, dtype: object
<class 'pandas.core.series.Series'>
830
Team         KCR
League        AL
Year        1980
RS           809
RA           694
W             97
G            162
Playoffs       1
Name: 830, dtype: object
<class 'pandas.core.series.Series'>
831
Team         LAD
League        NL
Year        1980
RS           663
RA           591
W             92
G            163
Playoffs       0
Name: 831, dtype: object
<class 'pandas.core.series.Series'>
832
Team         MIL
League        AL
Year        1980
RS           811
RA           682
W             86
G            162
Playoffs       0
Name: 832, dtype: object
<class 'pandas.core.series.Series'>
833
Team         MIN
League        AL
Year        1980
RS           670
RA           724
W             77
G            161
Playoffs       0
Name: 833, dtype: object
<class 'pandas.core.series.Series'>
834
Team         MON
League        NL
Year        1980
RS           694
RA           629
W             90
G            162
Playoffs       0
Name: 834, dtype: object
<class 'pandas.core.series.Series'>
835
Team         NYM
League        NL
Year        1980
RS           611
RA           702
W             67
G            162
Playoffs       0
Name: 835, dtype: object
<class 'pandas.core.series.Series'>
836
Team         NYY
League        AL
Year        1980
RS           820
RA           662
W            103
G            162
Playoffs       1
Name: 836, dtype: object
<class 'pandas.core.series.Series'>
837
Team         OAK
League        AL
Year        1980
RS           686
RA           642
W             83
G            162
Playoffs       0
Name: 837, dtype: object
<class 'pandas.core.series.Series'>
838
Team         PHI
League        NL
Year        1980
RS           728
RA           639
W             91
G            162
Playoffs       1
Name: 838, dtype: object
<class 'pandas.core.series.Series'>
839
Team         PIT
League        NL
Year        1980
RS           666
RA           646
W             83
G            162
Playoffs       0
Name: 839, dtype: object
<class 'pandas.core.series.Series'>
840
Team         SDP
League        NL
Year        1980
RS           591
RA           654
W             73
G            163
Playoffs       0
Name: 840, dtype: object
<class 'pandas.core.series.Series'>
841
Team         SEA
League        AL
Year        1980
RS           610
RA           793
W             59
G            163
Playoffs       0
Name: 841, dtype: object
<class 'pandas.core.series.Series'>
842
Team         SFG
League        NL
Year        1980
RS           573
RA           634
W             75
G            161
Playoffs       0
Name: 842, dtype: object
<class 'pandas.core.series.Series'>
843
Team         STL
League        NL
Year        1980
RS           738
RA           710
W             74
G            162
Playoffs       0
Name: 843, dtype: object
<class 'pandas.core.series.Series'>
844
Team         TEX
League        AL
Year        1980
RS           756
RA           752
W             76
G            163
Playoffs       0
Name: 844, dtype: object
<class 'pandas.core.series.Series'>
845
Team         TOR
League        AL
Year        1980
RS           624
RA           762
W             67
G            162
Playoffs       0
Name: 845, dtype: object
<class 'pandas.core.series.Series'>
846
Team         ATL
League        NL
Year        1979
RS           669
RA           763
W             66
G            160
Playoffs       0
Name: 846, dtype: object
<class 'pandas.core.series.Series'>
847
Team         BAL
League        AL
Year        1979
RS           757
RA           582
W            102
G            159
Playoffs       1
Name: 847, dtype: object
<class 'pandas.core.series.Series'>
848
Team         BOS
League        AL

Name: 944, dtype: object
<class 'pandas.core.series.Series'>
945
Team         SFG
League        NL
Year        1976
RS           595
RA           686
W             74
G            162
Playoffs       0
Name: 945, dtype: object
<class 'pandas.core.series.Series'>
946
Team         STL
League        NL
Year        1976
RS           629
RA           671
W             72
G            162
Playoffs       0
Name: 946, dtype: object
<class 'pandas.core.series.Series'>
947
Team         TEX
League        AL
Year        1976
RS           616
RA           652
W             76
G            162
Playoffs       0
Name: 947, dtype: object
<class 'pandas.core.series.Series'>
948
Team         ATL
League        NL
Year        1975
RS           583
RA           739
W             67
G            161
Playoffs       0
Name: 948, dtype: object
<class 'pandas.core.series.Series'>
949
Team         BAL
League        AL
Year        1975
RS           682
RA           553
W             90
G            159
Playoffs       0
Name: 949, dtype: object
<class 'pandas.core.series.Series'>
950
Team         BOS
League        AL
Year        1975
RS           796
RA           709
W             95
G            160
Playoffs       1
Name: 950, dtype: object
<class 'pandas.core.series.Series'>
951
Team         CAL
League        AL
Year        1975
RS           628
RA           723
W             72
G            161
Playoffs       0
Name: 951, dtype: object
<class 'pandas.core.series.Series'>
952
Team         CHC
League        NL
Year        1975
RS           712
RA           827
W             75
G            162
Playoffs       0
Name: 952, dtype: object
<class 'pandas.core.series.Series'>
953
Team         CHW
League        AL
Year        1975
RS           655
RA           703
W             75
G            161
Playoffs       0
Name: 953, dtype: object
<class 'pandas.core.series.Series'>
954
Team         CIN
League        NL
Year        1975
RS           840
RA           586
W            108
G            162
Playoffs       1
Name: 954, dtype: object
<class 'pandas.core.series.Series'>
955
Team         CLE
League        AL
Year        1975
RS           688
RA           703
W             79
G            159
Playoffs       0
Name: 955, dtype: object
<class 'pandas.core.series.Series'>
956
Team         DET
League        AL
Year        1975
RS           570
RA           786
W             57
G            159
Playoffs       0
Name: 956, dtype: object
<class 'pandas.core.series.Series'>
957
Team         HOU
League        NL
Year        1975
RS           664
RA           711
W             64
G            162
Playoffs       0
Name: 957, dtype: object
<class 'pandas.core.series.Series'>
958
Team         KCR
League        AL
Year        1975
RS           710
RA           649
W             91
G            162
Playoffs       0
Name: 958, dtype: object
<class 'pandas.core.series.Series'>
959
Team         LAD
League        NL
Year        1975
RS           648
RA           534
W             88
G            162
Playoffs       0
Name: 959, dtype: object
<class 'pandas.core.series.Series'>
960
Team         MIL
League        AL
Year        1975
RS           675
RA           792
W             68
G            162
Playoffs       0
Name: 960, dtype: object
<class 'pandas.core.series.Series'>
961
Team         MIN
League        AL
Year        1975
RS           724
RA           736
W             76
G            159
Playoffs       0
Name: 961, dtype: object
<class 'pandas.core.series.Series'>
962
Team         MON
League        NL
Year        1975
RS           601
RA           690
W             75
G            162
Playoffs       0
Name: 962, dtype: object
<class 'pandas.core.series.Series'>
963
Team         NYM
League        NL
Year        1975
RS           646
RA           625
W             82
G            162
Playoffs       0
Name: 963, dtype: object
<class 'pandas.core.series.Series'>
964
Team         NYY
League        AL
Year        1975
RS           681
RA           588
W             83
G            160
Playoffs       0
Name: 964, dtype: object
<class 'pandas.core.series.Series'>
965
Team         OAK
League        AL
Year        1975
RS           758
RA           606
W             98
G            162
Playoffs       1
Name: 965, dtype: object
<class 'pandas.core.series.Series'>
966
Team         PHI
League        NL
Year        1975
RS           735
RA           694
W             86
G            162
Playoffs       0
Name: 966, dtype: object
<class 'pandas.core.series.Series'>
967
Team         PIT
League        NL
Year        1975
RS           712
RA           565
W             92
G            161
Playoffs       1
Name: 967, dtype: object
<class 'pandas.core.series.Series'>
968
Team         SDP
League        NL
Year        1975
RS           552
RA           683
W             71
G            162
Playoffs       0
Name: 968, dtype: object
<class 'pandas.core.series.Series'>
969
Team         SFG
League        NL
Year        1975
RS           659
RA           671
W             80
G            161
Playoffs       0
Name: 969, dtype: object
<class 'pandas.core.series.Series'>
970
Team         STL
League        NL
Year        1975
RS           662
RA           689
W             82
G            163
Playoffs       0
Name: 970, dtype: object
<class 'pandas.core.series.Series'>
971
Team         TEX
League        AL
Year        1975
RS           714
RA           733
W             79
G            162
Playoffs       0
Name: 971, dtype: object
<class 'pandas.core.series.Series'>
972
Team         ATL
League        NL
Year        1974
RS           661
RA           563
W             88
G            163
Playoffs       0
Name: 972, dtype: object
<class 'pandas.core.series.Series'>
973
Team         BAL
League        AL
Year        1974
RS           659
RA           612
W             91
G            162
Playoffs       1
Name: 973, dtype: object
<class 'pandas.core.series.Series'>
974
Team         BOS
League        AL
Year        1974
RS           696
RA           661
W             84
G            162
Playoffs       0
Name: 974, dtype: object
<class 'pandas.core.series.Series'>
975
Team         CAL
League        AL
Year        1974
RS           618
RA           657
W             68
G            163
Playoffs       0
Name: 975, dtype: object
<class 'pandas.core.series.Series'>
976
Team         CHC
League        NL
Year        1974
RS           669
RA           826
W             66
G            162
Playoffs       0
Name: 976, dtype: object
<class 'pandas.core.series.Series'>
977
Team         CHW
League        AL
Year        1974
RS           684
RA           721
W             80
G            163
Playoffs       0
Name: 977, dtype: object
<class 'pandas.core.series.Series'>
978
Team         CIN
League        NL
Year        1974
RS           776
RA           631
W             98
G            163
Playoffs       0
Name: 978, dtype: object
<class 'pandas.core.series.Series'>
979
Team         CLE
League        AL
Year        1974
RS           662
RA           694
W             77
G            162
Playoffs       0
Name: 979, dtype: object
<class 'pandas.core.series.Series'>
980
Team         DET
League        AL
Year        1974
RS           620
RA           768
W             72
G            162
Playoffs       0
Name: 980, dtype: object
<class 'pandas.core.series.Series'>
981
Team         HOU
League        NL
Year        1974
RS           653
RA           632
W             81
G            162
Playoffs       0
Name: 981, dtype: object
<class 'pandas.core.series.Series'>
982
Team         KCR
League        AL
Year        1974
RS           667
RA           662
W             77
G            162
Playoffs       0
Name: 982, dtype: object
<class 'pandas.core.series.Series'>
983
Team         LAD
League        NL
Year        1974
RS           798
RA           561
W            102
G            162
Playoffs       1
Name: 983, dtype: object
<class 'pandas.core.series.Series'>
984
Team         MIL
League        AL
Year        1974
RS           647
RA           660
W             76
G            162
Playoffs       0
Name: 984, dtype: object
<class 'pandas.core.series.Series'>
985
Team         MIN
League        AL
Year        1974
RS           673
RA           669
W             82
G            163
Playoffs       0
Name: 985, dtype: object
<class 'pandas.core.series.Series'>
986
Team         MON
League        NL
Year        1974
RS           662
RA           657
W             79
G            161
Playoffs       0
Name: 986, dtype: object
<class 'pandas.core.series.Series'>
987
Team         NYM
League        NL
Year        1974
RS           572
RA           646
W             71
G            162
Playoffs       0
Name: 987, dtype: object
<class 'pandas.core.series.Series'>
988
Team         NYY
League        AL
Year        1974
RS           671
RA           623
W             89
G            162
Playoffs       0
Name: 988, dtype: object
<class 'pandas.core.series.Series'>
989
Team         OAK
League        AL
Year        1974
RS           689
RA           551
W             90
G            162
Playoffs       1
Name: 989, dtype: object
<class 'pandas.core.series.Series'>
990
Team         PHI
League        NL
Year        1974
RS           676
RA           701
W             80
G            162
Playoffs       0
Name: 990, dtype: object
<class 'pandas.core.series.Series'>
991
Team         PIT
League        NL
Year        1974
RS           751
RA           657
W             88
G            162
Playoffs       1
Name: 991, dtype: object
<class 'pandas.core.series.Series'>
992
Team         SDP
League        NL
Year        1974
RS           541
RA           830
W             60
G            162
Playoffs       0
Name: 992, dtype: object
<class 'pandas.core.series.Series'>
993
Team         SFG
League        NL
Year        1974
RS           634
RA           723
W             72
G            162
Playoffs       0
Name: 993, dtype: object
<class 'pandas.core.series.Series'>
994
Team         STL
League        NL
Year        1974
RS           677
RA           643
W             86
G            161
Playoffs       0
Name: 994, dtype: object
<class 'pandas.core.series.Series'>
995
Team         TEX
League        AL
Year        1974
RS           690
RA           698
W             83
G            161
Playoffs       0
Name: 995, dtype: object
<class 'pandas.core.series.Series'>
996
Team         ATL
League        NL
Year        1973
RS           799
RA           774
W             76
G            162
Playoffs       0
Name: 996, dtype: object
<class 'pandas.core.series.Series'>
997
Team         BAL
League        AL
Year        1973
RS           754
RA           561
W             97
G            162
Playoffs       1
Name: 997, dtype: object
<class 'pandas.core.series.Series'>
998
Team         BOS
League        AL
Year        1973
RS           738
RA           647
W             89
G            162
Playoffs       0
Name: 998, dtype: object
<class 'pandas.core.series.Series'>
999
Team         CAL
League        AL
Year        1973
RS           629
RA           657
W             79
G            162
Playoffs       0
Name: 999, dtype: object
<class 'pandas.core.series.Series'>
1000
Team         CHC
League        NL
Year        1973
RS           614
RA           655
W             77
G            161
Playoffs       0
Name: 1000, dtype: object
<class 'pandas.core.series.Series'>
1001
Team         CHW
League        AL
Year        1973
RS           652
RA           705
W             77
G            162
Playoffs       0
Name: 1001, dtype: object
<class 'pandas.core.series.Series'>
1002
Team         CIN
League        NL
Year        1973
RS           741
RA           621
W             99
G            162
Playoffs       1
Name: 1002, dtype: object
<class 'pandas.core.series.Series'>
1003
Team         CLE
League        AL
Year        1973
RS           680
RA           826
W             71
G            162
Playoffs       0
Name: 1003, dtype: object
<class 'pandas.core.series.Series'>
1004
Team         DET
League        AL
Year        1973
RS           642
RA           674
W             85
G            162
Playoffs       0
Name: 1004, dtype: object
<class 'pandas.core.series.Series'>
1005
Team         HOU
League        NL
Year        1973
RS           681
RA           672
W             82
G            162
Playoffs       0
Name: 1005, dtype: object
<class 'pandas.core.series.Series'>
1006
Team         KCR
League        AL
Year        1973
RS           755
RA           752
W             88
G            162
Playoffs       0
Name: 1006, dtype: object
<class 'pandas.core.series.Series'>
1007
Team         LAD
League        NL
Year        1973
RS           675
RA           565
W             95
G            162
Playoffs       0
Name: 1007, dtype: object
<class 'pandas.core.series.Series'>
1008
Team         MIL
League        AL
Year        1973
RS           708
RA           731
W             74
G            162
Playoffs       0
Name: 1008, dtype: object
<class 'pandas.core.series.Series'>
1009
Team         MIN
League        AL
Year        1973
RS           738
RA           692
W             81
G            162
Playoffs       0
Name: 1009, dtype: object
<class 'pandas.core.series.Series'>
1010
Team         MON
League        NL
Year        1973
RS           668
RA           702
W             79
G            162
Playoffs       0
Name: 1010, dtype: object
<class 'pandas.core.series.Series'>
1011
Team         NYM
League        NL
Year        1973
RS           608
RA           588
W             82
G            161
Playoffs       1
Name: 1011, dtype: object
<class 'pandas.core.series.Series'>
1012
Team         NYY
League        AL
Year        1973
RS           641
RA           610
W             80
G            162
Playoffs       0
Name: 1012, dtype: object
<class 'pandas.core.series.Series'>
1013
Team         OAK
League        AL
Year        1973
RS           758
RA           615
W             94
G            162
Playoffs       1
Name: 1013, dtype: object
<class 'pandas.core.series.Series'>
1014
Team         PHI
League        NL
Year        1973
RS           642
RA           717
W             71
G            162
Playoffs       0
Name: 1014, dtype: object
<class 'pandas.core.series.Series'>
1015
Team         PIT
League        NL
Year        1973
RS           704
RA           693
W             80
G            162
Playoffs       0
Name: 1015, dtype: object
<class 'pandas.core.series.Series'>
1016
Team         SDP
League        NL
Year        1973
RS           548
RA           770
W             60
G            162
Playoffs       0
Name: 1016, dtype: object
<class 'pandas.core.series.Series'>
1017
Team         SFG
League        NL
Year        1973
RS           739
RA           702
W             88
G            162
Playoffs       0
Name: 1017, dtype: object
<class 'pandas.core.series.Series'>
1018
Team         STL
League        NL
Year        1973
RS           643
RA           603
W             81
G            162
Playoffs       0
Name: 1018, dtype: object
<class 'pandas.core.series.Series'>
1019
Team         TEX
League        AL
Year        1973
RS           619
RA           844
W             57
G            162
Playoffs       0
Name: 1019, dtype: object
<class 'pandas.core.series.Series'>
1020
Team         ATL
League        NL
Year        1971
RS           643
RA           699
W             82
G            162
Playoffs       0
Name: 1020, dtype: object
<class 'pandas.core.series.Series'>
1021
Team         BAL
League        AL
Year        1971
RS           742
RA           530
W            101
G            158
Playoffs       1
Name: 1021, dtype: object
<class 'pandas.core.series.Series'>
1022
Team         BOS
League        AL
Year        1971
RS           691
RA           667
W             85
G            162
Playoffs       0
Name: 1022, dtype: object
<class 'pandas.core.series.Series'>
1023
Team         CAL
League        AL
Year        1971
RS           511
RA           576
W             76
G            162
Playoffs       0
Name: 1023, dtype: object
<class 'pandas.core.series.Series'>
1024
Team         CHC
League        NL
Year        1971
RS           637
RA           648
W             83
G            162
Playoffs       0
Name: 1024, dtype: object
<class 'pandas.core.series.Series'>
1025
Team         CHW
League        AL
Year        1971
RS           617
RA           597
W             79
G            162
Playoffs       0
Name: 1025, dtype: object
<class 'pandas.core.series.Series'>
1026
Team         CIN
League        NL
Year        1971
RS           586
RA           581
W             79
G            162
Playoffs       0
Name: 1026, dtype: object
<class 'pandas.core.series.Series'>
1027
Team         CLE
League        AL
Year        1971
RS           543
RA           747
W             60
G            162
Playoffs       0
Name: 1027, dtype: object
<class 'pandas.core.series.Series'>
1028
Team         DET
League        AL
Year        1971
RS           701
RA           645
W             91
G            162
Playoffs       0
Name: 1028, dtype: object
<class 'pandas.core.series.Series'>
1029
Team         HOU
League        NL
Year        1971
RS           585
RA           567
W             79
G            162
Playoffs       0
Name: 1029, dtype: object
<class 'pandas.core.series.Series'>
1030
Team         KCR
League        AL
Year        1971
RS           603
RA           566
W             85
G            161
Playoffs       0
Name: 1030, dtype: object
<class 'pandas.core.series.Series'>
1031
Team         LAD
League        NL
Year        1971
RS           663
RA           587
W             89
G            162
Playoffs       0
Name: 1031, dtype: object
<class 'pandas.core.series.Series'>
1032
Team         MIL
League        AL
Year        1971
RS           534
RA           609
W             69
G            161
Playoffs       0
Name: 1032, dtype: object
<class 'pandas.core.series.Series'>
1033
Team         MIN
League        AL
Year        1971
RS           654
RA           670
W             74
G            160
Playoffs       0
Name: 1033, dtype: object
<class 'pandas.core.series.Series'>
1034
Team         MON
League        NL
Year        1971
RS           622
RA           729
W             71
G            162
Playoffs       0
Name: 1034, dtype: object
<class 'pandas.core.series.Series'>
1035
Team         NYM
League        NL
Year        1971
RS           588
RA           550
W             83
G            162
Playoffs       0
Name: 1035, dtype: object
<class 'pandas.core.series.Series'>
1036
Team         NYY
League        AL
Year        1971
RS           648
RA           641
W             81
G            162
Playoffs       0
Name: 1036, dtype: object
<class 'pandas.core.series.Series'>
1037
Team         OAK
League        AL
Year        1971
RS           691
RA           564
W            101
G            161
Playoffs       1
Name: 1037, dtype: object
<class 'pandas.core.series.Series'>
1038
Team         PHI
League        NL
Year        1971
RS           558
RA           688
W             67
G            162
Playoffs       0
Name: 1038, dtype: object
<class 'pandas.core.series.Series'>
1039
Team         PIT
League        NL
Year        1971
RS           788
RA           599
W             97
G            162
Playoffs       1
Name: 1039, dtype: object
<class 'pandas.core.series.Series'>
1040
Team         SDP
League        NL
Year        1971
RS           486
RA           610
W             61
G            161
Playoffs       0
Name: 1040, dtype: object
<class 'pandas.core.series.Series'>
1041
Team         SFG
League        NL
Year        1971
RS           706
RA           644
W             90
G            162
Playoffs       1
Name: 1041, dtype: object
<class 'pandas.core.series.Series'>
1042
Team         STL
League        NL
Year        1971
RS           739
RA           699
W             90
G            163
Playoffs       0
Name: 1042, dtype: object
<class 'pandas.core.series.Series'>
1043
Team         WSA
League        AL
Year        1971
RS           537
RA           660
W             63
G            159
Playoffs       0

Name: 1135, dtype: object
<class 'pandas.core.series.Series'>
1136
Team         CHC
League        NL
Year        1966
RS           644
RA           809
W             59
G            162
Playoffs       0
Name: 1136, dtype: object
<class 'pandas.core.series.Series'>
1137
Team         CHW
League        AL
Year        1966
RS           574
RA           517
W             83
G            163
Playoffs       0
Name: 1137, dtype: object
<class 'pandas.core.series.Series'>
1138
Team         CIN
League        NL
Year        1966
RS           692
RA           702
W             76
G            160
Playoffs       0
Name: 1138, dtype: object
<class 'pandas.core.series.Series'>
1139
Team         CLE
League        AL
Year        1966
RS           574
RA           586
W             81
G            162
Playoffs       0
Name: 1139, dtype: object
<class 'pandas.core.series.Series'>
1140
Team         DET
League        AL
Year        1966
RS           719
RA           698
W             88
G            162
Playoffs       0
Name: 1140, dtype: object
<class 'pandas.core.series.Series'>
1141
Team         HOU
League        NL
Year        1966
RS           612
RA           695
W             72
G            163
Playoffs       0
Name: 1141, dtype: object
<class 'pandas.core.series.Series'>
1142
Team         KCA
League        AL
Year        1966
RS           564
RA           648
W             74
G            160
Playoffs       0
Name: 1142, dtype: object
<class 'pandas.core.series.Series'>
1143
Team         LAD
League        NL
Year        1966
RS           606
RA           490
W             95
G            162
Playoffs       1
Name: 1143, dtype: object
<class 'pandas.core.series.Series'>
1144
Team         MIN
League        AL
Year        1966
RS           663
RA           581
W             89
G            162
Playoffs       0
Name: 1144, dtype: object
<class 'pandas.core.series.Series'>
1145
Team         NYM
League        NL
Year        1966
RS           587
RA           761
W             66
G            161
Playoffs       0
Name: 1145, dtype: object
<class 'pandas.core.series.Series'>
1146
Team         NYY
League        AL
Year        1966
RS           611
RA           612
W             70
G            160
Playoffs       0
Name: 1146, dtype: object
<class 'pandas.core.series.Series'>
1147
Team         PHI
League        NL
Year        1966
RS           696
RA           640
W             87
G            162
Playoffs       0
Name: 1147, dtype: object
<class 'pandas.core.series.Series'>
1148
Team         PIT
League        NL
Year        1966
RS           759
RA           641
W             92
G            162
Playoffs       0
Name: 1148, dtype: object
<class 'pandas.core.series.Series'>
1149
Team         SFG
League        NL
Year        1966
RS           675
RA           626
W             93
G            161
Playoffs       0
Name: 1149, dtype: object
<class 'pandas.core.series.Series'>
1150
Team         STL
League        NL
Year        1966
RS           571
RA           577
W             83
G            162
Playoffs       0
Name: 1150, dtype: object
<class 'pandas.core.series.Series'>
1151
Team         WSA
League        AL
Year        1966
RS           557
RA           659
W             71
G            159
Playoffs       0
Name: 1151, dtype: object
<class 'pandas.core.series.Series'>
1152
Team         BAL
League        AL
Year        1965
RS           641
RA           578
W             94
G            162
Playoffs       0
Name: 1152, dtype: object
<class 'pandas.core.series.Series'>
1153
Team         BOS
League        AL
Year        1965
RS           669
RA           791
W             62
G            162
Playoffs       0
Name: 1153, dtype: object
<class 'pandas.core.series.Series'>
1154
Team         CAL
League        AL
Year        1965
RS           527
RA           569
W             75
G            162
Playoffs       0
Name: 1154, dtype: object
<class 'pandas.core.series.Series'>
1155
Team         CHC
League        NL
Year        1965
RS           635
RA           723
W             72
G            164
Playoffs       0
Name: 1155, dtype: object
<class 'pandas.core.series.Series'>
1156
Team         CHW
League        AL
Year        1965
RS           647
RA           555
W             95
G            162
Playoffs       0
Name: 1156, dtype: object
<class 'pandas.core.series.Series'>
1157
Team         CIN
League        NL
Year        1965
RS           825
RA           704
W             89
G            162
Playoffs       0
Name: 1157, dtype: object
<class 'pandas.core.series.Series'>
1158
Team         CLE
League        AL
Year        1965
RS           663
RA           613
W             87
G            162
Playoffs       0
Name: 1158, dtype: object
<class 'pandas.core.series.Series'>
1159
Team         DET
League        AL
Year        1965
RS           680
RA           602
W             89
G            162
Playoffs       0
Name: 1159, dtype: object
<class 'pandas.core.series.Series'>
1160
Team         HOU
League        NL
Year        1965
RS           569
RA           711
W             65
G            162
Playoffs       0
Name: 1160, dtype: object
<class 'pandas.core.series.Series'>
1161
Team         KCA
League        AL
Year        1965
RS           585
RA           755
W             59
G            162
Playoffs       0
Name: 1161, dtype: object
<class 'pandas.core.series.Series'>
1162
Team         LAD
League        NL
Year        1965
RS           608
RA           521
W             97
G            162
Playoffs       1
Name: 1162, dtype: object
<class 'pandas.core.series.Series'>
1163
Team         MIN
League        AL
Year        1965
RS           774
RA           600
W            102
G            162
Playoffs       1
Name: 1163, dtype: object
<class 'pandas.core.series.Series'>
1164
Team         MLN
League        NL
Year        1965
RS           708
RA           633
W             86
G            162
Playoffs       0
Name: 1164, dtype: object
<class 'pandas.core.series.Series'>
1165
Team         NYM
League        NL
Year        1965
RS           495
RA           752
W             50
G            164
Playoffs       0
Name: 1165, dtype: object
<class 'pandas.core.series.Series'>
1166
Team         NYY
League        AL
Year        1965
RS           611
RA           604
W             77
G            162
Playoffs       0
Name: 1166, dtype: object
<class 'pandas.core.series.Series'>
1167
Team         PHI
League        NL
Year        1965
RS           654
RA           667
W             85
G            162
Playoffs       0
Name: 1167, dtype: object
<class 'pandas.core.series.Series'>
1168
Team         PIT
League        NL
Year        1965
RS           675
RA           580
W             90
G            163
Playoffs       0
Name: 1168, dtype: object
<class 'pandas.core.series.Series'>
1169
Team         SFG
League        NL
Year        1965
RS           682
RA           593
W             95
G            163
Playoffs       0
Name: 1169, dtype: object
<class 'pandas.core.series.Series'>
1170
Team         STL
League        NL
Year        1965
RS           707
RA           674
W             80
G            162
Playoffs       0
Name: 1170, dtype: object
<class 'pandas.core.series.Series'>
1171
Team         WSA
League        AL
Year        1965
RS           591
RA           721
W             70
G            162
Playoffs       0
Name: 1171, dtype: object
<class 'pandas.core.series.Series'>
1172
Team         BAL
League        AL
Year        1964
RS           679
RA           567
W             97
G            163
Playoffs       0
Name: 1172, dtype: object
<class 'pandas.core.series.Series'>
1173
Team         BOS
League        AL
Year        1964
RS           688
RA           793
W             72
G            162
Playoffs       0
Name: 1173, dtype: object
<class 'pandas.core.series.Series'>
1174
Team         CHC
League        NL
Year        1964
RS           649
RA           724
W             76
G            162
Playoffs       0
Name: 1174, dtype: object
<class 'pandas.core.series.Series'>
1175
Team         CHW
League        AL
Year        1964
RS           642
RA           501
W             98
G            162
Playoffs       0
Name: 1175, dtype: object
<class 'pandas.core.series.Series'>
1176
Team         CIN
League        NL
Year        1964
RS           660
RA           566
W             92
G            163
Playoffs       0
Name: 1176, dtype: object
<class 'pandas.core.series.Series'>
1177
Team         CLE
League        AL
Year        1964
RS           689
RA           693
W             79
G            164
Playoffs       0
Name: 1177, dtype: object
<class 'pandas.core.series.Series'>
1178
Team         DET
League        AL
Year        1964
RS           699
RA           678
W             85
G            163
Playoffs       0
Name: 1178, dtype: object
<class 'pandas.core.series.Series'>
1179
Team         HOU
League        NL
Year        1964
RS           495
RA           628
W             66
G            162
Playoffs       0
Name: 1179, dtype: object
<class 'pandas.core.series.Series'>
1180
Team         KCA
League        AL
Year        1964
RS           621
RA           836
W             57
G            163
Playoffs       0
Name: 1180, dtype: object
<class 'pandas.core.series.Series'>
1181
Team         LAA
League        AL
Year        1964
RS           544
RA           551
W             82
G            162
Playoffs       0
Name: 1181, dtype: object
<class 'pandas.core.series.Series'>
1182
Team         LAD
League        NL
Year        1964
RS           614
RA           572
W             80
G            164
Playoffs       0
Name: 1182, dtype: object
<class 'pandas.core.series.Series'>
1183
Team         MIN
League        AL
Year        1964
RS           737
RA           678
W             79
G            163
Playoffs       0
Name: 1183, dtype: object
<class 'pandas.core.series.Series'>
1184
Team         MLN
League        NL
Year        1964
RS           803
RA           744
W             88
G            162
Playoffs       0
Name: 1184, dtype: object
<class 'pandas.core.series.Series'>
1185
Team         NYM
League        NL
Year        1964
RS           569
RA           776
W             53
G            163
Playoffs       0
Name: 1185, dtype: object
<class 'pandas.core.series.Series'>
1186
Team         NYY
League        AL
Year        1964
RS           730
RA           577
W             99
G            164
Playoffs       1
Name: 1186, dtype: object
<class 'pandas.core.series.Series'>
1187
Team         PHI
League        NL
Year        1964
RS           693
RA           632
W             92
G            162
Playoffs       0
Name: 1187, dtype: object
<class 'pandas.core.series.Series'>
1188
Team         PIT
League        NL
Year        1964
RS           663
RA           636
W             80
G            162
Playoffs       0
Name: 1188, dtype: object
<class 'pandas.core.series.Series'>
1189
Team         SFG
League        NL
Year        1964
RS           656
RA           587
W             90
G            162
Playoffs       0
Name: 1189, dtype: object
<class 'pandas.core.series.Series'>
1190
Team         STL
League        NL
Year        1964
RS           715
RA           652
W             93
G            162
Playoffs       1
Name: 1190, dtype: object
<class 'pandas.core.series.Series'>
1191
Team         WSA
League        AL
Year        1964
RS           578
RA           733
W             62
G            162
Playoffs       0
Name: 1191, dtype: object
<class 'pandas.core.series.Series'>
1192
Team         BAL
League        AL
Year        1963
RS           644
RA           621
W             86
G            162
Playoffs       0
Name: 1192, dtype: object
<class 'pandas.core.series.Series'>
1193
Team         BOS
League        AL
Year        1963
RS           666
RA           704
W             76
G            161
Playoffs       0
Name: 1193, dtype: object
<class 'pandas.core.series.Series'>
1194
Team         CHC
League        NL
Year        1963
RS           570
RA           578
W             82
G            162
Playoffs       0
Name: 1194, dtype: object
<class 'pandas.core.series.Series'>
1195
Team         CHW
League        AL
Year        1963
RS           683
RA           544
W             94
G            162
Playoffs       0
Name: 1195, dtype: object
<class 'pandas.core.series.Series'>
1196
Team         CIN
League        NL
Year        1963
RS           648
RA           594
W             86
G            162
Playoffs       0
Name: 1196, dtype: object
<class 'pandas.core.series.Series'>
1197
Team         CLE
League        AL
Year        1963
RS           635
RA           702
W             79
G            162
Playoffs       0
Name: 1197, dtype: object
<class 'pandas.core.series.Series'>
1198
Team         DET
League        AL
Year        1963
RS           700
RA           703
W             79
G            162
Playoffs       0
Name: 1198, dtype: object
<class 'pandas.core.series.Series'>
1199
Team         HOU
League        NL
Year        1963
RS           464
RA           640
W             66
G            162
Playoffs       0
Name: 1199, dtype: object
<class 'pandas.core.series.Series'>
1200
Team         KCA
League        AL
Year        1963
RS           615
RA           704
W             73
G            162
Playoffs       0
Name: 1200, dtype: object
<class 'pandas.core.series.Series'>
1201
Team         LAA
League        AL
Year        1963
RS           597
RA           660
W             70
G            161
Playoffs       0
Name: 1201, dtype: object
<class 'pandas.core.series.Series'>
1202
Team         LAD
League        NL
Year        1963
RS           640
RA           550
W             99
G            163
Playoffs       1
Name: 1202, dtype: object
<class 'pandas.core.series.Series'>
1203
Team         MIN
League        AL
Year        1963
RS           767
RA           602
W             91
G            161
Playoffs       0
Name: 1203, dtype: object
<class 'pandas.core.series.Series'>
1204
Team         MLN
League        NL
Year        1963
RS           677
RA           603
W             84
G            163
Playoffs       0
Name: 1204, dtype: object
<class 'pandas.core.series.Series'>
1205
Team         NYM
League        NL
Year        1963
RS           501
RA           774
W             51
G            162
Playoffs       0
Name: 1205, dtype: object
<class 'pandas.core.series.Series'>
1206
Team         NYY
League        AL
Year        1963
RS           714
RA           547
W            104
G            161
Playoffs       1
Name: 1206, dtype: object
<class 'pandas.core.series.Series'>
1207
Team         PHI
League        NL
Year        1963
RS           642
RA           578
W             87
G            162
Playoffs       0
Name: 1207, dtype: object
<class 'pandas.core.series.Series'>
1208
Team         PIT
League        NL
Year        1963
RS           567
RA           595
W             74
G            162
Playoffs       0
Name: 1208, dtype: object
<class 'pandas.core.series.Series'>
1209
Team         SFG
League        NL
Year        1963
RS           725
RA           641
W             88
G            162
Playoffs       0
Name: 1209, dtype: object
<class 'pandas.core.series.Series'>
1210
Team         STL
League        NL
Year        1963
RS           747
RA           628
W             93
G            162
Playoffs       0
Name: 1210, dtype: object
<class 'pandas.core.series.Series'>
1211
Team         WSA
League        AL
Year        1963
RS           578
RA           812
W             56
G            162
Playoffs       0
Name: 1211, dtype: object
<class 'pandas.core.series.Series'>
1212
Team         BAL
League        AL
Year        1962
RS           652
RA           680
W             77
G            162
Playoffs       0
Name: 1212, dtype: object
<class 'pandas.core.series.Series'>
1213
Team         BOS
League        AL
Year        1962
RS           707
RA           756
W             76
G            160
Playoffs       0
Name: 1213, dtype: object
<class 'pandas.core.series.Series'>
1214
Team         CHC
League        NL
Year        1962
RS           632
RA           827
W             59
G            162
Playoffs       0
Name: 1214, dtype: object
<class 'pandas.core.series.Series'>
1215
Team         CHW
League        AL
Year        1962
RS           707
RA           658
W             85
G            162
Playoffs       0
Name: 1215, dtype: object
<class 'pandas.core.series.Series'>
1216
Team         CIN
League        NL
Year        1962
RS           802
RA           685
W             98
G            162
Playoffs       0
Name: 1216, dtype: object
<class 'pandas.core.series.Series'>
1217
Team         CLE
League        AL
Year        1962
RS           682
RA           745
W             80
G            162
Playoffs       0
Name: 1217, dtype: object
<class 'pandas.core.series.Series'>
1218
Team         DET
League        AL
Year        1962
RS           758
RA           692
W             85
G            161
Playoffs       0
Name: 1218, dtype: object
<class 'pandas.core.series.Series'>
1219
Team         HOU
League        NL
Year        1962
RS           592
RA           717
W             64
G            162
Playoffs       0
Name: 1219, dtype: object
<class 'pandas.core.series.Series'>
1220
Team         KCA
League        AL
Year        1962
RS           745
RA           837
W             72
G            162
Playoffs       0
Name: 1220, dtype: object
<class 'pandas.core.series.Series'>
1221
Team         LAA
League        AL
Year        1962
RS           718
RA           706
W             86
G            162
Playoffs       0
Name: 1221, dtype: object
<class 'pandas.core.series.Series'>
1222
Team         LAD
League        NL
Year        1962
RS           842
RA           697
W            102
G            165
Playoffs       0
Name: 1222, dtype: object
<class 'pandas.core.series.Series'>
1223
Team         MIN
League        AL
Year        1962
RS           798
RA           713
W             91
G            163
Playoffs       0
Name: 1223, dtype: object
<class 'pandas.core.series.Series'>
1224
Team         MLN
League        NL
Year        1962
RS           730
RA           665
W             86
G            162
Playoffs       0
Name: 1224, dtype: object
<class 'pandas.core.series.Series'>
1225
Team         NYM
League        NL
Year        1962
RS           617
RA           948
W             40
G            161
Playoffs       0
Name: 1225, dtype: object
<class 'pandas.core.series.Series'>
1226
Team         NYY
League        AL
Year        1962
RS           817
RA           680
W             96
G            162
Playoffs       1
Name: 1226, dtype: object
<class 'pandas.core.series.Series'>
1227
Team         PHI
League        NL
Year        1962
RS           705
RA           759
W             81
G            161
Playoffs       0
Name: 1227, dtype: object
<class 'pandas.core.series.Series'>
1228
Team         PIT
League        NL
Year        1962
RS           706
RA           626
W             93
G            161
Playoffs       0
Name: 1228, dtype: object
<class 'pandas.core.series.Series'>
1229
Team         SFG
League        NL
Year        1962
RS           878
RA           690
W            103
G            165
Playoffs       1
Name: 1229, dtype: object
<class 'pandas.core.series.Series'>
1230
Team         STL
League        NL
Year        1962
RS           774
RA           664
W             84
G            163
Playoffs       0
Name: 1230, dtype: object
<class 'pandas.core.series.Series'>
1231
Team         WSA
League        AL
Year        1962
RS           599
RA           716
W             60
G            162
Playoffs       0
Name: 1231, dtype: object
<class 'pandas.core.series.Series'>

In [34]:
# Use one variable instead of two to store the result of .iterrows()
for row_tuple in pit_df.iterrows():
    print(row_tuple)

(0, Team         ARI
League        NL
Year        2012
RS           734
RA           688
W             81
G            162
Playoffs       0
Name: 0, dtype: object)
(1, Team         ATL
League        NL
Year        2012
RS           700
RA           600
W             94
G            162
Playoffs       1
Name: 1, dtype: object)
(2, Team         BAL
League        AL
Year        2012
RS           712
RA           705
W             93
G            162
Playoffs       1
Name: 2, dtype: object)
(3, Team         BOS
League        AL
Year        2012
RS           734
RA           806
W             69
G            162
Playoffs       0
Name: 3, dtype: object)
(4, Team         CHC
League        NL
Year        2012
RS           613
RA           759
W             61
G            162
Playoffs       0
Name: 4, dtype: object)
(5, Team         CHW
League        AL
Year        2012
RS           748
RA           676
W             85
G            162
Playoffs       0
Name: 5, dtype: object)
(6, Team         CIN
League        NL
Year        2012
RS           669
RA           588
W             97
G            162
Playoffs       1
Name: 6, dtype: object)
(7, Team         CLE
League        AL
Year        2012
RS           667
RA           845
W             68
G            162
Playoffs       0
Name: 7, dtype: object)
(8, Team         COL
League        NL
Year        2012
RS           758
RA           890
W             64
G            162
Playoffs       0
Name: 8, dtype: object)
(9, Team         DET
League        AL
Year        2012
RS           726
RA           670
W             88
G            162
Playoffs       1
Name: 9, dtype: object)
(10, Team         HOU
League        NL
Year        2012
RS           583
RA           794
W             55
G            162
Playoffs       0
Name: 10, dtype: object)
(11, Team         KCR
League        AL
Year        2012
RS           676
RA           746
W             72
G            162
Playoffs       0
Name: 11, dtype: object)
(12, Team         LAA
League        AL
Year        2012
RS           767
RA           699
W             89
G            162
Playoffs       0
Name: 12, dtype: object)
(13, Team         LAD
League        NL
Year        2012
RS           637
RA           597
W             86
G            162
Playoffs       0
Name: 13, dtype: object)
(14, Team         MIA
League        NL
Year        2012
RS           609
RA           724
W             69
G            162
Playoffs       0
Name: 14, dtype: object)
(15, Team         MIL
League        NL
Year        2012
RS           776
RA           733
W             83
G            162
Playoffs       0
Name: 15, dtype: object)
(16, Team         MIN
League        AL
Year        2012
RS           701
RA           832
W             66
G            162
Playoffs       0
Name: 16, dtype: object)
(17, Team         NYM
League        NL
Year        2012
RS           650
RA           709
W             74
G            162
Playoffs       0
Name: 17, dtype: object)
(18, Team         NYY
League        AL
Year        2012
RS           804
RA           668
W             95
G            162
Playoffs       1
Name: 18, dtype: object)
(19, Team         OAK
League        AL
Year        2012
RS           713
RA           614
W             94
G            162
Playoffs       1
Name: 19, dtype: object)
(20, Team         PHI
League        NL
Year        2012
RS           684
RA           680
W             81
G            162
Playoffs       0
Name: 20, dtype: object)
(21, Team         PIT
League        NL
Year        2012
RS           651
RA           674
W             79
G            162
Playoffs       0
Name: 21, dtype: object)
(22, Team         SDP
League        NL
Year        2012
RS           651
RA           710
W             76
G            162
Playoffs       0
Name: 22, dtype: object)
(23, Team         SEA
League        AL
Year        2012
RS           619
RA           651
W             75
G            162
Playoffs       0
Name: 23, dtype: object)
(24, Team         SFG
League        NL
Year        2012
RS           718
RA           649
W             94
G            162
Playoffs       1
Name: 24, dtype: object)
(25, Team         STL
League        NL
Year        2012
RS           765
RA           648
W             88
G            162
Playoffs       1
Name: 25, dtype: object)
(26, Team         TBR
League        AL
Year        2012
RS           697
RA           577
W             90
G            162
Playoffs       0
Name: 26, dtype: object)
(27, Team         TEX
League        AL
Year        2012
RS           808
RA           707
W             93
G            162
Playoffs       1
Name: 27, dtype: object)
(28, Team         TOR
League        AL
Year        2012
RS           716
RA           784
W             73
G            162
Playoffs       0
Name: 28, dtype: object)
(29, Team         WSN
League        NL
Year        2012
RS           731
RA           594
W             98
G            162
Playoffs       1
Name: 29, dtype: object)
(30, Team         ARI
League        NL
Year        2011
RS           731
RA           662
W             94
G            162
Playoffs       1
Name: 30, dtype: object)
(31, Team         ATL
League        NL
Year        2011
RS           641
RA           605
W             89
G            162
Playoffs       0
Name: 31, dtype: object)
(32, Team         BAL
League        AL
Year        2011
RS           708
RA           860
W             69
G            162
Playoffs       0
Name: 32, dtype: object)
(33, Team         BOS
League        AL
Year        2011
RS           875
RA           737
W             90
G            162
Playoffs       0
Name: 33, dtype: object)
(34, Team         CHC
League        NL
Year        2011
RS           654
RA           756
W             71
G            162
Playoffs       0
Name: 34, dtype: object)
(35, Team         CHW
League        AL
Year        2011
RS           654
RA           706
W             79
G            162
Playoffs       0
Name: 35, dtype: object)
(36, Team         CIN
League        NL
Year        2011
RS           735
RA           720
W             79
G            162
Playoffs       0
Name: 36, dtype: object)
(37, Team         CLE
League        AL
Year        2011
RS           704
RA           760
W             80
G            162
Playoffs       0
Name: 37, dtype: object)
(38, Team         COL
League        NL
Year        2011
RS           735
RA           774
W             73
G            162
Playoffs       0
Name: 38, dtype: object)
(39, Team         DET
League        AL
Year        2011
RS           787
RA           711
W             95
G            162
Playoffs       1
Name: 39, dtype: object)
(40, Team         FLA
League        NL
Year        2011
RS           625
RA           702
W             72
G            162
Playoffs       0
Name: 40, dtype: object)
(41, Team         HOU
League        NL
Year        2011
RS           615
RA           796
W             56
G            162
Playoffs       0
Name: 41, dtype: object)
(42, Team         KCR
League        AL
Year        2011
RS           730
RA           762
W             71
G            162
Playoffs       0
Name: 42, dtype: object)
(43, Team         LAA
League        AL
Year        2011
RS           667
RA           633
W             86
G            162
Playoffs       0
Name: 43, dtype: object)
(44, Team         LAD
League        NL
Year        2011
RS           644
RA           612
W             82
G            161
Playoffs       0
Name: 44, dtype: object)
(45, Team         MIL
League        NL
Year        2011
RS           721
RA           638
W             96
G            162
Playoffs       1
Name: 45, dtype: object)
(46, Team         MIN
League        AL
Year        2011
RS           619
RA           804
W             63
G            162
Playoffs       0
Name: 46, dtype: object)
(47, Team         NYM
League        NL
Year        2011
RS           718
RA           742
W             77
G            162
Playoffs       0
Name: 47, dtype: object)
(48, Team         NYY
League        AL
Year        2011
RS           867
RA           657
W             97
G            162
Playoffs       1
Name: 48, dtype: object)
(49, Team         OAK
League        AL
Year        2011
RS           645
RA           679
W             74
G            162
Playoffs       0
Name: 49, dtype: object)
(50, Team         PHI
League        NL
Year        2011
RS           713
RA           529
W            102
G            162
Playoffs       1
Name: 50, dtype: object)
(51, Team         PIT
League        NL
Year        2011
RS           610
RA           712
W             72
G            162
Playoffs       0
Name: 51, dtype: object)
(52, Team         SDP
League        NL
Year        2011
RS           593
RA           611
W             71
G            162
Playoffs       0
Name: 52, dtype: object)
(53, Team         SEA
League        AL
Year        2011
RS           556
RA           675
W             67
G            162
Playoffs       0
Name: 53, dtype: object)
(54, Team         SFG
League        NL
Year        2011
RS           570
RA           578
W             86
G            162
Playoffs       0
Name: 54, dtype: object)
(55, Team         STL
League        NL
Year        2011
RS           762
RA           692
W             90
G            162
Playoffs       1
Name: 55, dtype: object)
(56, Team         TBR
League        AL
Year        2011
RS           707
RA           614
W             91
G            162
Playoffs       1
Name: 56, dtype: object)
(57, Team         TEX
League        AL
Year        2011
RS           855
RA           677
W             96
G            162
Playoffs       1
Name: 57, dtype: object)
(58, Team         TOR
League        AL
Year        2011
RS           743
RA           761
W             81
G            162
Playoffs       0
Name: 58, dtype: object)
(59, Team         WSN
League        NL
Year        2011
RS           624
RA           643
W             80
G            161
Playoffs       0
Name: 59, dtype: object)
(60, Team         ARI
League        NL
Year        2010
RS           713
RA           836
W             65
G            162
Playoffs       0
Name: 60, dtype: object)
(61, Team         ATL
League        NL
Year        2010
RS           738
RA           629
W             91
G            162
Playoffs       1
Name: 61, dtype: object)
(62, Team         BAL
League        AL
Year        2010
RS           613
RA           785
W             66
G            162
Playoffs       0
Name: 62, dtype: object)
(63, Team         BOS
League        AL
Year        2010
RS           818
RA           744
W             89
G            162
Playoffs       0
Name: 63, dtype: object)
(64, Team         CHC
League        NL
Year        2010
RS           685
RA           767
W             75
G            162
Playoffs       0
Name: 64, dtype: object)
(65, Team         CHW
League        AL
Year        2010
RS           752
RA           704
W             88
G            162
Playoffs       0
Name: 65, dtype: object)
(66, Team         CIN
League        NL
Year        2010
RS           790
RA           685
W             91
G            162
Playoffs       1
Name: 66, dtype: object)
(67, Team         CLE
League        AL
Year        2010
RS           646
RA           752
W             69
G            162
Playoffs       0
Name: 67, dtype: object)
(68, Team         COL
League        NL
Year        2010
RS           770
RA           717
W             83
G            162
Playoffs       0
Name: 68, dtype: object)
(69, Team         DET
League        AL
Year        2010
RS           751
RA           743
W             81
G            162
Playoffs       0
Name: 69, dtype: object)
(70, Team         FLA
League        NL
Year        2010
RS           719
RA           717
W             80
G            162
Playoffs       0
Name: 70, dtype: object)
(71, Team         HOU
League        NL
Year        2010
RS           611
RA           729
W             76
G            162
Playoffs       0
Name: 71, dtype: object)
(72, Team         KCR
League        AL
Year        2010
RS           676
RA           845
W             67
G            162
Playoffs       0
Name: 72, dtype: object)
(73, Team         LAA
League        AL
Year        2010
RS           681
RA           702
W             80
G            162
Playoffs       0
Name: 73, dtype: object)
(74, Team         LAD
League        NL
Year        2010
RS           667
RA           692
W             80
G            162
Playoffs       0
Name: 74, dtype: object)
(75, Team         MIL
League        NL
Year        2010
RS           750
RA           804
W             77
G            162
Playoffs       0
Name: 75, dtype: object)
(76, Team         MIN
League        AL
Year        2010
RS           781
RA           671
W             94
G            162
Playoffs       1
Name: 76, dtype: object)
(77, Team         NYM
League        NL
Year        2010
RS           656
RA           652
W             79
G            162
Playoffs       0
Name: 77, dtype: object)
(78, Team         NYY
League        AL
Year        2010
RS           859
RA           693
W             95
G            162
Playoffs       1
Name: 78, dtype: object)
(79, Team         OAK
League        AL
Year        2010
RS           663
RA           626
W             81
G            162
Playoffs       0
Name: 79, dtype: object)
(80, Team         PHI
League        NL
Year        2010
RS           772
RA           640
W             97
G            162
Playoffs       1
Name: 80, dtype: object)
(81, Team         PIT
League        NL
Year        2010
RS           587
RA           866
W             57
G            162
Playoffs       0
Name: 81, dtype: object)
(82, Team         SDP
League        NL
Year        2010
RS           665
RA           581
W             90
G            162
Playoffs       0
Name: 82, dtype: object)
(83, Team         SEA
League        AL
Year        2010
RS           513
RA           698
W             61
G            162
Playoffs       0
Name: 83, dtype: object)
(84, Team         SFG
League        NL
Year        2010
RS           697
RA           583
W             92
G            162
Playoffs       1
Name: 84, dtype: object)
(85, Team         STL
League        NL
Year        2010
RS           736
RA           641
W             86
G            162
Playoffs       0
Name: 85, dtype: object)
(86, Team         TBR
League        AL
Year        2010
RS           802
RA           649
W             96
G            162
Playoffs       1
Name: 86, dtype: object)
(87, Team         TEX
League        AL
Year        2010
RS           787
RA           687
W             90
G            162
Playoffs       1
Name: 87, dtype: object)
(88, Team         TOR
League        AL
Year        2010
RS           755
RA           728
W             85
G            162
Playoffs       0
Name: 88, dtype: object)
(89, Team         WSN
League        NL
Year        2010
RS           655
RA           742
W             69
G            162
Playoffs       0
Name: 89, dtype: object)
(90, Team         ARI
League        NL
Year        2009
RS           720
RA           782
W             70
G            162
Playoffs       0
Name: 90, dtype: object)
(91, Team         ATL
League        NL
Year        2009
RS           735
RA           641
W             86
G            162
Playoffs       0
Name: 91, dtype: object)
(92, Team         BAL
League        AL
Year        2009
RS           741
RA           876
W             64
G            162
Playoffs       0
Name: 92, dtype: object)
(93, Team         BOS
League        AL
Year        2009
RS           872
RA           736
W             95
G            162
Playoffs       1
Name: 93, dtype: object)
(94, Team         CHC
League        NL
Year        2009
RS           707
RA           672
W             83
G            161
Playoffs       0
Name: 94, dtype: object)
(95, Team         CHW
League        AL
Year        2009
RS           724
RA           732
W             79
G            162
Playoffs       0
Name: 95, dtype: object)
(96, Team         CIN
League        NL
Year        2009
RS           673
RA           723
W             78
G            162
Playoffs       0
Name: 96, dtype: object)
(97, Team         CLE
League        AL
Year        2009
RS           773
RA           865
W             65
G            162
Playoffs       0
Name: 97, dtype: object)
(98, Team         COL
League        NL
Year        2009
RS           804
RA           715
W             92
G            162
Playoffs       1
Name: 98, dtype: object)
(99, Team         DET
League        AL
Year        2009
RS           743
RA           745
W             86
G            163
Playoffs       0
Name: 99, dtype: object)
(100, Team         FLA
League        NL
Year        2009
RS           772
RA           766
W             87
G            162
Playoffs       0
Name: 100, dtype: object)
(101, Team         HOU
League        NL
Year        2009
RS           643
RA           770
W             74
G            162
Playoffs       0
Name: 101, dtype: object)
(102, Team         KCR
League        AL
Year        2009
RS           686
RA           842
W             65
G            162
Playoffs       0
Name: 102, dtype: object)
(103, Team         LAA
League        AL
Year        2009
RS           883
RA           761
W             97
G            162
Playoffs       1
Name: 103, dtype: object)
(104, Team         LAD
League        NL
Year        2009
RS           780
RA           611
W             95
G            162
Playoffs       1
Name: 104, dtype: object)
(105, Team         MIL
League        NL
Year        2009
RS           785
RA           818
W             80
G            162
Playoffs       0
Name: 105, dtype: object)
(106, Team         MIN
League        AL
Year        2009
RS           817
RA           765
W             87
G            163
Playoffs       1
Name: 106, dtype: object)
(107, Team         NYM
League        NL
Year        2009
RS           671
RA           757
W             70
G            162
Playoffs       0
Name: 107, dtype: object)
(108, Team         NYY
League        AL
Year        2009
RS           915
RA           753
W            103
G            162
Playoffs       1
Name: 108, dtype: object)
(109, Team         OAK
League        AL
Year        2009
RS           759
RA           761
W             75
G            162
Playoffs       0
Name: 109, dtype: object)
(110, Team         PHI
League        NL
Year        2009
RS           820
RA           709
W             93
G            162
Playoffs       1
Name: 110, dtype: object)
(111, Team         PIT
League        NL
Year        2009
RS           636
RA           768
W             62
G            161
Playoffs       0
Name: 111, dtype: object)
(112, Team         SDP
League        NL
Year        2009
RS           638
RA           769
W             75
G            162
Playoffs       0
Name: 112, dtype: object)
(113, Team         SEA
League        AL
Year        2009
RS           640
RA           692
W             85
G            162
Playoffs       0
Name: 113, dtype: object)
(114, Team         SFG
League        NL
Year        2009
RS           657
RA           611
W             88
G            162
Playoffs       0
Name: 114, dtype: object)
(115, Team         STL
League        NL
Year        2009
RS           730
RA           640
W             91
G            162
Playoffs       1
Name: 115, dtype: object)
(116, Team         TBR
League        AL
Year        2009
RS           803
RA           754
W             84
G            162
Playoffs       0
Name: 116, dtype: object)
(117, Team         TEX
League        AL
Year        2009
RS           784
RA           740
W             87
G            162
Playoffs       0
Name: 117, dtype: object)
(118, Team         TOR
League        AL
Year        2009
RS           798
RA           771
W             75
G            162
Playoffs       0
Name: 118, dtype: object)
(119, Team         WSN
League        NL
Year        2009
RS           710
RA           874
W             59
G            162
Playoffs       0
Name: 119, dtype: object)
(120, Team         ARI
League        NL
Year        2008

(256, Team         MIN
League        AL
Year        2004
RS           780
RA           715
W             92
G            162
Playoffs       1
Name: 256, dtype: object)
(257, Team         MON
League        NL
Year        2004
RS           635
RA           769
W             67
G            162
Playoffs       0
Name: 257, dtype: object)
(258, Team         NYM
League        NL
Year        2004
RS           684
RA           731
W             71
G            162
Playoffs       0
Name: 258, dtype: object)
(259, Team         NYY
League        AL
Year        2004
RS           897
RA           808
W            101
G            162
Playoffs       1
Name: 259, dtype: object)
(260, Team         OAK
League        AL
Year        2004
RS           793
RA           742
W             91
G            162
Playoffs       0
Name: 260, dtype: object)
(261, Team         PHI
League        NL
Year        2004
RS           840
RA           781
W             86
G            162
Playoffs       0
Name: 261, dtype: object)
(262, Team         PIT
League        NL
Year        2004
RS           680
RA           744
W             72
G            161
Playoffs       0
Name: 262, dtype: object)
(263, Team         SDP
League        NL
Year        2004
RS           768
RA           705
W             87
G            162
Playoffs       0
Name: 263, dtype: object)
(264, Team         SEA
League        AL
Year        2004
RS           698
RA           823
W             63
G            162
Playoffs       0
Name: 264, dtype: object)
(265, Team         SFG
League        NL
Year        2004
RS           850
RA           770
W             91
G            162
Playoffs       0
Name: 265, dtype: object)
(266, Team         STL
League        NL
Year        2004
RS           855
RA           659
W            105
G            162
Playoffs       1
Name: 266, dtype: object)
(267, Team         TBD
League        AL
Year        2004
RS           714
RA           842
W             70
G            161
Playoffs       0
Name: 267, dtype: object)
(268, Team         TEX
League        AL
Year        2004
RS           860
RA           794
W             89
G            162
Playoffs       0
Name: 268, dtype: object)
(269, Team         TOR
League        AL
Year        2004
RS           719
RA           823
W             67
G            161
Playoffs       0
Name: 269, dtype: object)
(270, Team         ANA
League        AL
Year        2003
RS           736
RA           743
W             77
G            162
Playoffs       0
Name: 270, dtype: object)
(271, Team         ARI
League        NL
Year        2003
RS           717
RA           685
W             84
G            162
Playoffs       0
Name: 271, dtype: object)
(272, Team         ATL
League        NL
Year        2003
RS           907
RA           740
W            101
G            162
Playoffs       1
Name: 272, dtype: object)
(273, Team         BAL
League        AL
Year        2003
RS           743
RA           820
W             71
G            163
Playoffs       0
Name: 273, dtype: object)
(274, Team         BOS
League        AL
Year        2003
RS           961
RA           809
W             95
G            162
Playoffs       1
Name: 274, dtype: object)
(275, Team         CHC
League        NL
Year        2003
RS           724
RA           683
W             88
G            162
Playoffs       1
Name: 275, dtype: object)
(276, Team         CHW
League        AL
Year        2003
RS           791
RA           715
W             86
G            162
Playoffs       0
Name: 276, dtype: object)
(277, Team         CIN
League        NL
Year        2003
RS           694
RA           886
W             69
G            162
Playoffs       0
Name: 277, dtype: object)
(278, Team         CLE
League        AL
Year        2003
RS           699
RA           778
W             68
G            162
Playoffs       0
Name: 278, dtype: object)
(279, Team         COL
League        NL
Year        2003
RS           853
RA           892
W             74
G            162
Playoffs       0
Name: 279, dtype: object)
(280, Team         DET
League        AL
Year        2003
RS           591
RA           928
W             43
G            162
Playoffs       0
Name: 280, dtype: object)
(281, Team         FLA
League        NL
Year        2003
RS           751
RA           692
W             91
G            162
Playoffs       1
Name: 281, dtype: object)
(282, Team         HOU
League        NL
Year        2003
RS           805
RA           677
W             87
G            162
Playoffs       0
Name: 282, dtype: object)
(283, Team         KCR
League        AL
Year        2003
RS           836
RA           867
W             83
G            162
Playoffs       0
Name: 283, dtype: object)
(284, Team         LAD
League        NL
Year        2003
RS           574
RA           556
W             85
G            162
Playoffs       0
Name: 284, dtype: object)
(285, Team         MIL
League        NL
Year        2003
RS           714
RA           873
W             68
G            162
Playoffs       0
Name: 285, dtype: object)
(286, Team         MIN
League        AL
Year        2003
RS           801
RA           758
W             90
G            162
Playoffs       1
Name: 286, dtype: object)
(287, Team         MON
League        NL
Year        2003
RS           711
RA           716
W             83
G            162
Playoffs       0
Name: 287, dtype: object)
(288, Team         NYM
League        NL
Year        2003
RS           642
RA           754
W             66
G            161
Playoffs       0
Name: 288, dtype: object)
(289, Team         NYY
League        AL
Year        2003
RS           877
RA           716
W            101
G            163
Playoffs       1
Name: 289, dtype: object)
(290, Team         OAK
League        AL
Year        2003
RS           768
RA           643
W             96
G            162
Playoffs       1
Name: 290, dtype: object)
(291, Team         PHI
League        NL
Year        2003
RS           791
RA           697
W             86
G            162
Playoffs       0
Name: 291, dtype: object)
(292, Team         PIT
League        NL
Year        2003
RS           753
RA           801
W             75
G            162
Playoffs       0
Name: 292, dtype: object)
(293, Team         SDP
League        NL
Year        2003
RS           678
RA           831
W             64
G            162
Playoffs       0
Name: 293, dtype: object)
(294, Team         SEA
League        AL
Year        2003
RS           795
RA           637
W             93
G            162
Playoffs       0
Name: 294, dtype: object)
(295, Team         SFG
League        NL
Year        2003
RS           755
RA           638
W            100
G            161
Playoffs       1
Name: 295, dtype: object)
(296, Team         STL
League        NL
Year        2003
RS           876
RA           796
W             85
G            162
Playoffs       0
Name: 296, dtype: object)
(297, Team         TBD
League        AL
Year        2003
RS           715
RA           852
W             63
G            162
Playoffs       0
Name: 297, dtype: object)
(298, Team         TEX
League        AL
Year        2003
RS           826
RA           969
W             71
G            162
Playoffs       0
Name: 298, dtype: object)
(299, Team         TOR
League        AL
Year        2003
RS           894
RA           826
W             86
G            162
Playoffs       0
Name: 299, dtype: object)
(300, Team         ANA
League        AL
Year        2002
RS           851
RA           644
W             99
G            162
Playoffs       1
Name: 300, dtype: object)
(301, Team         ARI
League        NL
Year        2002
RS           819
RA           674
W             98
G            162
Playoffs       1
Name: 301, dtype: object)
(302, Team         ATL
League        NL
Year        2002
RS           708
RA           565
W            101
G            161
Playoffs       1
Name: 302, dtype: object)
(303, Team         BAL
League        AL
Year        2002
RS           667
RA           773
W             67
G            162
Playoffs       0
Name: 303, dtype: object)
(304, Team         BOS
League        AL
Year        2002
RS           859
RA           665
W             93
G            162
Playoffs       0
Name: 304, dtype: object)
(305, Team         CHC
League        NL
Year        2002
RS           706
RA           759
W             67
G            162
Playoffs       0
Name: 305, dtype: object)
(306, Team         CHW
League        AL
Year        2002
RS           856
RA           798
W             81
G            162
Playoffs       0
Name: 306, dtype: object)
(307, Team         CIN
League        NL
Year        2002
RS           709
RA           774
W             78
G            162
Playoffs       0
Name: 307, dtype: object)
(308, Team         CLE
League        AL
Year        2002
RS           739
RA           837
W             74
G            162
Playoffs       0
Name: 308, dtype: object)
(309, Team         COL
League        NL
Year        2002
RS           778
RA           898
W             73
G            162
Playoffs       0
Name: 309, dtype: object)
(310, Team         DET
League        AL
Year        2002
RS           575
RA           864
W             55
G            161
Playoffs       0
Name: 310, dtype: object)
(311, Team         FLA
League        NL
Year        2002
RS           699
RA           763
W             79
G            162
Playoffs       0
Name: 311, dtype: object)
(312, Team         HOU
League        NL
Year        2002
RS           749
RA           695
W             84
G            162
Playoffs       0
Name: 312, dtype: object)
(313, Team         KCR
League        AL
Year        2002
RS           737
RA           891
W             62
G            162
Playoffs       0
Name: 313, dtype: object)
(314, Team         LAD
League        NL
Year        2002
RS           713
RA           643
W             92
G            162
Playoffs       0
Name: 314, dtype: object)
(315, Team         MIL
League        NL
Year        2002
RS           627
RA           821
W             56
G            162
Playoffs       0
Name: 315, dtype: object)
(316, Team         MIN
League        AL
Year        2002
RS           768
RA           712
W             94
G            161
Playoffs       1
Name: 316, dtype: object)
(317, Team         MON
League        NL
Year        2002
RS           735
RA           718
W             83
G            162
Playoffs       0
Name: 317, dtype: object)
(318, Team         NYM
League        NL
Year        2002
RS           690
RA           703
W             75
G            161
Playoffs       0
Name: 318, dtype: object)
(319, Team         NYY
League        AL
Year        2002
RS           897
RA           697
W            103
G            161
Playoffs       1
Name: 319, dtype: object)
(320, Team         OAK
League        AL
Year        2002
RS           800
RA           654
W            103
G            162
Playoffs       1
Name: 320, dtype: object)
(321, Team         PHI
League        NL
Year        2002
RS           710
RA           724
W             80
G            161
Playoffs       0
Name: 321, dtype: object)
(322, Team         PIT
League        NL
Year        2002
RS           641
RA           730
W             72
G            161
Playoffs       0
Name: 322, dtype: object)
(323, Team         SDP
League        NL
Year        2002
RS           662
RA           815
W             66
G            162
Playoffs       0
Name: 323, dtype: object)
(324, Team         SEA
League        AL
Year        2002
RS           814
RA           699
W             93
G            162
Playoffs       0
Name: 324, dtype: object)
(325, Team         SFG
League        NL
Year        2002
RS           783
RA           616
W             95
G            162
Playoffs       1
Name: 325, dtype: object)
(326, Team         STL
League        NL
Year        2002
RS           787
RA           648
W             97
G            162
Playoffs       1
Name: 326, dtype: object)
(327, Team         TBD
League        AL
Year        2002
RS           673
RA           918
W             55
G            161
Playoffs       0
Name: 327, dtype: object)
(328, Team         TEX
League        AL
Year        2002
RS           843
RA           882
W             72
G            162
Playoffs       0
Name: 328, dtype: object)
(329, Team         TOR
League        AL
Year        2002
RS           813
RA           828
W             78
G            162
Playoffs       0
Name: 329, dtype: object)
(330, Team         ANA
League        AL
Year        2001
RS           691
RA           730
W             75
G            162
Playoffs       0
Name: 330, dtype: object)
(331, Team         ARI
League        NL
Year        2001
RS           818
RA           677
W             92
G            162
Playoffs       1
Name: 331, dtype: object)
(332, Team         ATL
League        NL
Year        2001
RS           729
RA           643
W             88
G            162
Playoffs       1
Name: 332, dtype: object)
(333, Team         BAL
League        AL
Year        2001
RS           687
RA           829
W             63
G            162
Playoffs       0
Name: 333, dtype: object)
(334, Team         BOS
League        AL
Year        2001
RS           772
RA           745
W             82
G            161
Playoffs       0
Name: 334, dtype: object)
(335, Team         CHC
League        NL
Year        2001
RS           777
RA           701
W             88
G            162
Playoffs       0
Name: 335, dtype: object)
(336, Team         CHW
League        AL
Year        2001
RS           798
RA           795
W             83
G            162
Playoffs       0
Name: 336, dtype: object)
(337, Team         CIN
League        NL
Year        2001
RS           735
RA           850
W             66
G            162
Playoffs       0
Name: 337, dtype: object)
(338, Team         CLE
League        AL
Year        2001
RS           897
RA           821
W             91
G            162
Playoffs       1
Name: 338, dtype: object)
(339, Team         COL
League        NL
Year        2001
RS           923
RA           906
W             73
G            162
Playoffs       0
Name: 339, dtype: object)
(340, Team         DET
League        AL
Year        2001
RS           724
RA           876
W             66
G            162
Playoffs       0
Name: 340, dtype: object)
(341, Team         FLA
League        NL
Year        2001
RS           742
RA           744
W             76
G            162
Playoffs       0
Name: 341, dtype: object)
(342, Team         HOU
League        NL
Year        2001
RS           847
RA           769
W             93
G            162
Playoffs       1
Name: 342, dtype: object)
(343, Team         KCR
League        AL
Year        2001
RS           729
RA           858
W             65
G            162
Playoffs       0
Name: 343, dtype: object)
(344, Team         LAD
League        NL
Year        2001
RS           758
RA           744
W             86
G            162
Playoffs       0
Name: 344, dtype: object)
(345, Team         MIL
League        NL
Year        2001
RS           740
RA           806
W             68
G            162
Playoffs       0
Name: 345, dtype: object)
(346, Team         MIN
League        AL
Year        2001
RS           771
RA           766
W             85
G            162
Playoffs       0
Name: 346, dtype: object)
(347, Team         MON
League        NL
Year        2001
RS           670
RA           812
W             68
G            162
Playoffs       0
Name: 347, dtype: object)
(348, Team         NYM
League        NL
Year        2001
RS           642
RA           713
W             82
G            162
Playoffs       0
Name: 348, dtype: object)
(349, Team         NYY
League        AL
Year        2001
RS           804
RA           713
W             95
G            161
Playoffs       1
Name: 349, dtype: object)
(350, Team         OAK
League        AL
Year        2001
RS           884
RA           645
W            102
G            162
Playoffs       1
Name: 350, dtype: object)
(351, Team         PHI
League        NL
Year        2001
RS           746
RA           719
W             86
G            162
Playoffs       0
Name: 351, dtype: object)
(352, Team         PIT
League        NL
Year        2001
RS           657
RA           858
W             62
G            162
Playoffs       0
Name: 352, dtype: object)
(353, Team         SDP
League        NL
Year        2001
RS           789
RA           812
W             79
G            162
Playoffs       0
Name: 353, dtype: object)
(354, Team         SEA
League        AL
Year        2001
RS           927
RA           627
W            116
G            162
Playoffs       1
Name: 354, dtype: object)
(355, Team         SFG
League        NL
Year        2001
RS           799
RA           748
W             90
G            162
Playoffs       0
Name: 355, dtype: object)
(356, Team         STL
League        NL
Year        2001
RS           814
RA           684
W             93
G            162
Playoffs       1
Name: 356, dtype: object)
(357, Team         TBD
League        AL
Year        2001
RS           672
RA           887
W             62
G            162
Playoffs       0
Name: 357, dtype: object)
(358, Team         TEX
League        AL
Year        2001
RS           890
RA           968
W             73
G            162
Playoffs       0
Name: 358, dtype: object)
(359, Team         TOR
League        AL
Year        2001
RS           767
RA           753
W             80
G            162
Playoffs       0
Name: 359, dtype: object)
(360, Team         ANA
League        AL
Year        2000
RS           864
RA           869
W             82
G            162
Playoffs       0
Name: 360, dtype: object)
(361, Team         ARI
League        NL
Year        2000
RS           792
RA           754
W             85
G            162
Playoffs       0
Name: 361, dtype: object)
(362, Team         ATL
League        NL
Year        2000
RS           810
RA           714
W             95
G            162
Playoffs       1
Name: 362, dtype: object)
(363, Team         BAL
League        AL
Year        2000
RS           794
RA           913
W             74
G            162
Playoffs       0
Name: 363, dtype: object)
(364, Team         BOS
League        AL
Year        2000
RS           792
RA           745
W             85
G            162
Playoffs       0
Name: 364, dtype: object)
(365, Team         CHC
League        NL
Year        2000
RS           764
RA           904
W             65
G            162
Playoffs       0
Name: 365, dtype: object)
(366, Team         CHW
League        AL
Year        2000
RS           978
RA           839
W             95
G            162
Playoffs       1
Name: 366, dtype: object)
(367, Team         CIN
League        NL
Year        2000
RS           825
RA           765
W             85
G            163
Playoffs       0
Name: 367, dtype: object)
(368, Team         CLE
League        AL
Year        2000
RS           950
RA           816
W             90
G            162
Playoffs       0
Name: 368, dtype: object)
(369, Team         COL
League        NL
Year        2000
RS           968
RA           897
W             82
G            162
Playoffs       0
Name: 369, dtype: object)
(370, Team         DET
League        AL
Year        2000
RS           823
RA           827
W             79
G            162
Playoffs       0
Name: 370, dtype: object)
(371, Team         FLA
League        NL
Year        2000
RS           731
RA           797
W             79
G            161
Playoffs       0
Name: 371, dtype: object)
(372, Team         HOU
League        NL
Year        2000
RS           938
RA           944
W             72
G            162
Playoffs       0
Name: 372, dtype: object)
(373, Team         KCR
League        AL
Year        2000
RS           879
RA           930
W             77
G            162
Playoffs       0
Name: 373, dtype: object)
(374, Team         LAD
League        NL
Year        2000
RS           798
RA           729
W             86
G            162
Playoffs       0
Name: 374, dtype: object)

Name: 512, dtype: object)
(513, Team         CLE
League        AL
Year        1993
RS           790
RA           813
W             76
G            162
Playoffs       0
Name: 513, dtype: object)
(514, Team         COL
League        NL
Year        1993
RS           758
RA           967
W             67
G            162
Playoffs       0
Name: 514, dtype: object)
(515, Team         DET
League        AL
Year        1993
RS           899
RA           837
W             85
G            162
Playoffs       0
Name: 515, dtype: object)
(516, Team         FLA
League        NL
Year        1993
RS           581
RA           724
W             64
G            162
Playoffs       0
Name: 516, dtype: object)
(517, Team         HOU
League        NL
Year        1993
RS           716
RA           630
W             85
G            162
Playoffs       0
Name: 517, dtype: object)
(518, Team         KCR
League        AL
Year        1993
RS           675
RA           694
W             84
G            162
Playoffs       0
Name: 518, dtype: object)
(519, Team         LAD
League        NL
Year        1993
RS           675
RA           662
W             81
G            162
Playoffs       0
Name: 519, dtype: object)
(520, Team         MIL
League        AL
Year        1993
RS           733
RA           792
W             69
G            162
Playoffs       0
Name: 520, dtype: object)
(521, Team         MIN
League        AL
Year        1993
RS           693
RA           830
W             71
G            162
Playoffs       0
Name: 521, dtype: object)
(522, Team         MON
League        NL
Year        1993
RS           732
RA           682
W             94
G            163
Playoffs       0
Name: 522, dtype: object)
(523, Team         NYM
League        NL
Year        1993
RS           672
RA           744
W             59
G            162
Playoffs       0
Name: 523, dtype: object)
(524, Team         NYY
League        AL
Year        1993
RS           821
RA           761
W             88
G            162
Playoffs       0
Name: 524, dtype: object)
(525, Team         OAK
League        AL
Year        1993
RS           715
RA           846
W             68
G            162
Playoffs       0
Name: 525, dtype: object)
(526, Team         PHI
League        NL
Year        1993
RS           877
RA           740
W             97
G            162
Playoffs       1
Name: 526, dtype: object)
(527, Team         PIT
League        NL
Year        1993
RS           707
RA           806
W             75
G            162
Playoffs       0
Name: 527, dtype: object)
(528, Team         SDP
League        NL
Year        1993
RS           679
RA           772
W             61
G            162
Playoffs       0
Name: 528, dtype: object)
(529, Team         SEA
League        AL
Year        1993
RS           734
RA           731
W             82
G            162
Playoffs       0
Name: 529, dtype: object)
(530, Team         SFG
League        NL
Year        1993
RS           808
RA           636
W            103
G            162
Playoffs       0
Name: 530, dtype: object)
(531, Team         STL
League        NL
Year        1993
RS           758
RA           744
W             87
G            162
Playoffs       0
Name: 531, dtype: object)
(532, Team         TEX
League        AL
Year        1993
RS           835
RA           751
W             86
G            162
Playoffs       0
Name: 532, dtype: object)
(533, Team         TOR
League        AL
Year        1993
RS           847
RA           742
W             95
G            162
Playoffs       1
Name: 533, dtype: object)
(534, Team         ATL
League        NL
Year        1992
RS           682
RA           569
W             98
G            162
Playoffs       1
Name: 534, dtype: object)
(535, Team         BAL
League        AL
Year        1992
RS           705
RA           656
W             89
G            162
Playoffs       0
Name: 535, dtype: object)
(536, Team         BOS
League        AL
Year        1992
RS           599
RA           669
W             73
G            162
Playoffs       0
Name: 536, dtype: object)
(537, Team         CAL
League        AL
Year        1992
RS           579
RA           671
W             72
G            162
Playoffs       0
Name: 537, dtype: object)
(538, Team         CHC
League        NL
Year        1992
RS           593
RA           624
W             78
G            162
Playoffs       0
Name: 538, dtype: object)
(539, Team         CHW
League        AL
Year        1992
RS           738
RA           690
W             86
G            162
Playoffs       0
Name: 539, dtype: object)
(540, Team         CIN
League        NL
Year        1992
RS           660
RA           609
W             90
G            162
Playoffs       0
Name: 540, dtype: object)
(541, Team         CLE
League        AL
Year        1992
RS           674
RA           746
W             76
G            162
Playoffs       0
Name: 541, dtype: object)
(542, Team         DET
League        AL
Year        1992
RS           791
RA           794
W             75
G            162
Playoffs       0
Name: 542, dtype: object)
(543, Team         HOU
League        NL
Year        1992
RS           608
RA           668
W             81
G            162
Playoffs       0
Name: 543, dtype: object)
(544, Team         KCR
League        AL
Year        1992
RS           610
RA           667
W             72
G            162
Playoffs       0
Name: 544, dtype: object)
(545, Team         LAD
League        NL
Year        1992
RS           548
RA           636
W             63
G            162
Playoffs       0
Name: 545, dtype: object)
(546, Team         MIL
League        AL
Year        1992
RS           740
RA           604
W             92
G            162
Playoffs       0
Name: 546, dtype: object)
(547, Team         MIN
League        AL
Year        1992
RS           747
RA           653
W             90
G            162
Playoffs       0
Name: 547, dtype: object)
(548, Team         MON
League        NL
Year        1992
RS           648
RA           581
W             87
G            162
Playoffs       0
Name: 548, dtype: object)
(549, Team         NYM
League        NL
Year        1992
RS           599
RA           653
W             72
G            162
Playoffs       0
Name: 549, dtype: object)
(550, Team         NYY
League        AL
Year        1992
RS           733
RA           746
W             76
G            162
Playoffs       0
Name: 550, dtype: object)
(551, Team         OAK
League        AL
Year        1992
RS           745
RA           672
W             96
G            162
Playoffs       1
Name: 551, dtype: object)
(552, Team         PHI
League        NL
Year        1992
RS           686
RA           717
W             70
G            162
Playoffs       0
Name: 552, dtype: object)
(553, Team         PIT
League        NL
Year        1992
RS           693
RA           595
W             96
G            162
Playoffs       1
Name: 553, dtype: object)
(554, Team         SDP
League        NL
Year        1992
RS           617
RA           636
W             82
G            162
Playoffs       0
Name: 554, dtype: object)
(555, Team         SEA
League        AL
Year        1992
RS           679
RA           799
W             64
G            162
Playoffs       0
Name: 555, dtype: object)
(556, Team         SFG
League        NL
Year        1992
RS           574
RA           647
W             72
G            162
Playoffs       0
Name: 556, dtype: object)
(557, Team         STL
League        NL
Year        1992
RS           631
RA           604
W             83
G            162
Playoffs       0
Name: 557, dtype: object)
(558, Team         TEX
League        AL
Year        1992
RS           682
RA           753
W             77
G            162
Playoffs       0
Name: 558, dtype: object)
(559, Team         TOR
League        AL
Year        1992
RS           780
RA           682
W             96
G            162
Playoffs       1
Name: 559, dtype: object)
(560, Team         ATL
League        NL
Year        1991
RS           749
RA           644
W             94
G            162
Playoffs       1
Name: 560, dtype: object)
(561, Team         BAL
League        AL
Year        1991
RS           686
RA           796
W             67
G            162
Playoffs       0
Name: 561, dtype: object)
(562, Team         BOS
League        AL
Year        1991
RS           731
RA           712
W             84
G            162
Playoffs       0
Name: 562, dtype: object)
(563, Team         CAL
League        AL
Year        1991
RS           653
RA           649
W             81
G            162
Playoffs       0
Name: 563, dtype: object)
(564, Team         CHC
League        NL
Year        1991
RS           695
RA           734
W             77
G            160
Playoffs       0
Name: 564, dtype: object)
(565, Team         CHW
League        AL
Year        1991
RS           758
RA           681
W             87
G            162
Playoffs       0
Name: 565, dtype: object)
(566, Team         CIN
League        NL
Year        1991
RS           689
RA           691
W             74
G            162
Playoffs       0
Name: 566, dtype: object)
(567, Team         CLE
League        AL
Year        1991
RS           576
RA           759
W             57
G            162
Playoffs       0
Name: 567, dtype: object)
(568, Team         DET
League        AL
Year        1991
RS           817
RA           794
W             84
G            162
Playoffs       0
Name: 568, dtype: object)
(569, Team         HOU
League        NL
Year        1991
RS           605
RA           717
W             65
G            162
Playoffs       0
Name: 569, dtype: object)
(570, Team         KCR
League        AL
Year        1991
RS           727
RA           722
W             82
G            162
Playoffs       0
Name: 570, dtype: object)
(571, Team         LAD
League        NL
Year        1991
RS           665
RA           565
W             93
G            162
Playoffs       0
Name: 571, dtype: object)
(572, Team         MIL
League        AL
Year        1991
RS           799
RA           744
W             83
G            162
Playoffs       0
Name: 572, dtype: object)
(573, Team         MIN
League        AL
Year        1991
RS           776
RA           652
W             95
G            162
Playoffs       1
Name: 573, dtype: object)
(574, Team         MON
League        NL
Year        1991
RS           579
RA           655
W             71
G            161
Playoffs       0
Name: 574, dtype: object)
(575, Team         NYM
League        NL
Year        1991
RS           640
RA           646
W             77
G            161
Playoffs       0
Name: 575, dtype: object)
(576, Team         NYY
League        AL
Year        1991
RS           674
RA           777
W             71
G            162
Playoffs       0
Name: 576, dtype: object)
(577, Team         OAK
League        AL
Year        1991
RS           760
RA           776
W             84
G            162
Playoffs       0
Name: 577, dtype: object)
(578, Team         PHI
League        NL
Year        1991
RS           629
RA           680
W             78
G            162
Playoffs       0
Name: 578, dtype: object)
(579, Team         PIT
League        NL
Year        1991
RS           768
RA           632
W             98
G            162
Playoffs       1
Name: 579, dtype: object)
(580, Team         SDP
League        NL
Year        1991
RS           636
RA           646
W             84
G            162
Playoffs       0
Name: 580, dtype: object)
(581, Team         SEA
League        AL
Year        1991
RS           702
RA           674
W             83
G            162
Playoffs       0
Name: 581, dtype: object)
(582, Team         SFG
League        NL
Year        1991
RS           649
RA           697
W             75
G            162
Playoffs       0
Name: 582, dtype: object)
(583, Team         STL
League        NL
Year        1991
RS           651
RA           648
W             84
G            162
Playoffs       0
Name: 583, dtype: object)
(584, Team         TEX
League        AL
Year        1991
RS           829
RA           814
W             85
G            162
Playoffs       0
Name: 584, dtype: object)
(585, Team         TOR
League        AL
Year        1991
RS           684
RA           622
W             91
G            162
Playoffs       1
Name: 585, dtype: object)
(586, Team         ATL
League        NL
Year        1990
RS           682
RA           821
W             65
G            162
Playoffs       0
Name: 586, dtype: object)
(587, Team         BAL
League        AL
Year        1990
RS           669
RA           698
W             76
G            161
Playoffs       0
Name: 587, dtype: object)
(588, Team         BOS
League        AL
Year        1990
RS           699
RA           664
W             88
G            162
Playoffs       1
Name: 588, dtype: object)
(589, Team         CAL
League        AL
Year        1990
RS           690
RA           706
W             80
G            162
Playoffs       0
Name: 589, dtype: object)
(590, Team         CHC
League        NL
Year        1990
RS           690
RA           774
W             77
G            162
Playoffs       0
Name: 590, dtype: object)
(591, Team         CHW
League        AL
Year        1990
RS           682
RA           633
W             94
G            162
Playoffs       0
Name: 591, dtype: object)
(592, Team         CIN
League        NL
Year        1990
RS           693
RA           597
W             91
G            162
Playoffs       1
Name: 592, dtype: object)
(593, Team         CLE
League        AL
Year        1990
RS           732
RA           737
W             77
G            162
Playoffs       0
Name: 593, dtype: object)
(594, Team         DET
League        AL
Year        1990
RS           750
RA           754
W             79
G            162
Playoffs       0
Name: 594, dtype: object)
(595, Team         HOU
League        NL
Year        1990
RS           573
RA           656
W             75
G            162
Playoffs       0
Name: 595, dtype: object)
(596, Team         KCR
League        AL
Year        1990
RS           707
RA           709
W             75
G            161
Playoffs       0
Name: 596, dtype: object)
(597, Team         LAD
League        NL
Year        1990
RS           728
RA           685
W             86
G            162
Playoffs       0
Name: 597, dtype: object)
(598, Team         MIL
League        AL
Year        1990
RS           732
RA           760
W             74
G            162
Playoffs       0
Name: 598, dtype: object)
(599, Team         MIN
League        AL
Year        1990
RS           666
RA           729
W             74
G            162
Playoffs       0
Name: 599, dtype: object)
(600, Team         MON
League        NL
Year        1990
RS           662
RA           598
W             85
G            162
Playoffs       0
Name: 600, dtype: object)
(601, Team         NYM
League        NL
Year        1990
RS           775
RA           613
W             91
G            162
Playoffs       0
Name: 601, dtype: object)
(602, Team         NYY
League        AL
Year        1990
RS           603
RA           749
W             67
G            162
Playoffs       0
Name: 602, dtype: object)
(603, Team         OAK
League        AL
Year        1990
RS           733
RA           570
W            103
G            162
Playoffs       1
Name: 603, dtype: object)
(604, Team         PHI
League        NL
Year        1990
RS           646
RA           729
W             77
G            162
Playoffs       0
Name: 604, dtype: object)
(605, Team         PIT
League        NL
Year        1990
RS           733
RA           619
W             95
G            162
Playoffs       1
Name: 605, dtype: object)
(606, Team         SDP
League        NL
Year        1990
RS           673
RA           673
W             75
G            162
Playoffs       0
Name: 606, dtype: object)
(607, Team         SEA
League        AL
Year        1990
RS           640
RA           680
W             77
G            162
Playoffs       0
Name: 607, dtype: object)
(608, Team         SFG
League        NL
Year        1990
RS           719
RA           710
W             85
G            162
Playoffs       0
Name: 608, dtype: object)
(609, Team         STL
League        NL
Year        1990
RS           599
RA           698
W             70
G            162
Playoffs       0
Name: 609, dtype: object)
(610, Team         TEX
League        AL
Year        1990
RS           676
RA           696
W             83
G            162
Playoffs       0
Name: 610, dtype: object)
(611, Team         TOR
League        AL
Year        1990
RS           767
RA           661
W             86
G            162
Playoffs       0
Name: 611, dtype: object)
(612, Team         ATL
League        NL
Year        1989
RS           584
RA           680
W             63
G            161
Playoffs       0
Name: 612, dtype: object)
(613, Team         BAL
League        AL
Year        1989
RS           708
RA           686
W             87
G            162
Playoffs       0
Name: 613, dtype: object)
(614, Team         BOS
League        AL
Year        1989
RS           774
RA           735
W             83
G            162
Playoffs       0
Name: 614, dtype: object)
(615, Team         CAL
League        AL
Year        1989
RS           669
RA           578
W             91
G            162
Playoffs       0
Name: 615, dtype: object)
(616, Team         CHC
League        NL
Year        1989
RS           702
RA           623
W             93
G            162
Playoffs       1
Name: 616, dtype: object)
(617, Team         CHW
League        AL
Year        1989
RS           693
RA           750
W             69
G            161
Playoffs       0
Name: 617, dtype: object)
(618, Team         CIN
League        NL
Year        1989
RS           632
RA           691
W             75
G            162
Playoffs       0
Name: 618, dtype: object)
(619, Team         CLE
League        AL
Year        1989
RS           604
RA           654
W             73
G            162
Playoffs       0
Name: 619, dtype: object)
(620, Team         DET
League        AL
Year        1989
RS           617
RA           816
W             59
G            162
Playoffs       0
Name: 620, dtype: object)
(621, Team         HOU
League        NL
Year        1989
RS           647
RA           669
W             86
G            162
Playoffs       0
Name: 621, dtype: object)
(622, Team         KCR
League        AL
Year        1989
RS           690
RA           635
W             92
G            162
Playoffs       0
Name: 622, dtype: object)
(623, Team         LAD
League        NL
Year        1989
RS           554
RA           536
W             77
G            160
Playoffs       0
Name: 623, dtype: object)
(624, Team         MIL
League        AL
Year        1989
RS           707
RA           679
W             81
G            162
Playoffs       0
Name: 624, dtype: object)
(625, Team         MIN
League        AL
Year        1989
RS           740
RA           738
W             80
G            162
Playoffs       0
Name: 625, dtype: object)
(626, Team         MON
League        NL
Year        1989
RS           632
RA           630
W             81
G            162
Playoffs       0
Name: 626, dtype: object)
(627, Team         NYM
League        NL
Year        1989
RS           683
RA           595
W             87
G            162
Playoffs       0
Name: 627, dtype: object)
(628, Team         NYY
League        AL
Year        1989
RS           698
RA           792
W             74
G            161
Playoffs       0
Name: 628, dtype: object)
(629, Team         OAK
League        AL
Year        1989
RS           712
RA           576
W             99
G            162
Playoffs       1
Name: 629, dtype: object)
(630, Team         PHI
League        NL
Year        1989
RS           629
RA           735
W             67
G            163
Playoffs       0
Name: 630, dtype: object)
(631, Team         PIT
League        NL
Year        1989
RS           637
RA           680
W             74
G            164
Playoffs       0

(777, Team         HOU
League        NL
Year        1983
RS           643
RA           646
W             85
G            162
Playoffs       0
Name: 777, dtype: object)
(778, Team         KCR
League        AL
Year        1983
RS           696
RA           767
W             79
G            163
Playoffs       0
Name: 778, dtype: object)
(779, Team         LAD
League        NL
Year        1983
RS           654
RA           609
W             91
G            163
Playoffs       1
Name: 779, dtype: object)
(780, Team         MIL
League        AL
Year        1983
RS           764
RA           708
W             87
G            162
Playoffs       0
Name: 780, dtype: object)
(781, Team         MIN
League        AL
Year        1983
RS           709
RA           822
W             70
G            162
Playoffs       0
Name: 781, dtype: object)
(782, Team         MON
League        NL
Year        1983
RS           677
RA           646
W             82
G            163
Playoffs       0
Name: 782, dtype: object)
(783, Team         NYM
League        NL
Year        1983
RS           575
RA           680
W             68
G            162
Playoffs       0
Name: 783, dtype: object)
(784, Team         NYY
League        AL
Year        1983
RS           770
RA           703
W             91
G            162
Playoffs       0
Name: 784, dtype: object)
(785, Team         OAK
League        AL
Year        1983
RS           708
RA           782
W             74
G            162
Playoffs       0
Name: 785, dtype: object)
(786, Team         PHI
League        NL
Year        1983
RS           696
RA           635
W             90
G            163
Playoffs       1
Name: 786, dtype: object)
(787, Team         PIT
League        NL
Year        1983
RS           659
RA           648
W             84
G            162
Playoffs       0
Name: 787, dtype: object)
(788, Team         SDP
League        NL
Year        1983
RS           653
RA           653
W             81
G            163
Playoffs       0
Name: 788, dtype: object)
(789, Team         SEA
League        AL
Year        1983
RS           558
RA           740
W             60
G            162
Playoffs       0
Name: 789, dtype: object)
(790, Team         SFG
League        NL
Year        1983
RS           687
RA           697
W             79
G            162
Playoffs       0
Name: 790, dtype: object)
(791, Team         STL
League        NL
Year        1983
RS           679
RA           710
W             79
G            162
Playoffs       0
Name: 791, dtype: object)
(792, Team         TEX
League        AL
Year        1983
RS           639
RA           609
W             77
G            163
Playoffs       0
Name: 792, dtype: object)
(793, Team         TOR
League        AL
Year        1983
RS           795
RA           726
W             89
G            162
Playoffs       0
Name: 793, dtype: object)
(794, Team         ATL
League        NL
Year        1982
RS           739
RA           702
W             89
G            162
Playoffs       1
Name: 794, dtype: object)
(795, Team         BAL
League        AL
Year        1982
RS           774
RA           687
W             94
G            163
Playoffs       0
Name: 795, dtype: object)
(796, Team         BOS
League        AL
Year        1982
RS           753
RA           713
W             89
G            162
Playoffs       0
Name: 796, dtype: object)
(797, Team         CAL
League        AL
Year        1982
RS           814
RA           670
W             93
G            162
Playoffs       1
Name: 797, dtype: object)
(798, Team         CHC
League        NL
Year        1982
RS           676
RA           709
W             73
G            162
Playoffs       0
Name: 798, dtype: object)
(799, Team         CHW
League        AL
Year        1982
RS           786
RA           710
W             87
G            162
Playoffs       0
Name: 799, dtype: object)
(800, Team         CIN
League        NL
Year        1982
RS           545
RA           661
W             61
G            162
Playoffs       0
Name: 800, dtype: object)
(801, Team         CLE
League        AL
Year        1982
RS           683
RA           748
W             78
G            162
Playoffs       0
Name: 801, dtype: object)
(802, Team         DET
League        AL
Year        1982
RS           729
RA           685
W             83
G            162
Playoffs       0
Name: 802, dtype: object)
(803, Team         HOU
League        NL
Year        1982
RS           569
RA           620
W             77
G            162
Playoffs       0
Name: 803, dtype: object)
(804, Team         KCR
League        AL
Year        1982
RS           784
RA           717
W             90
G            162
Playoffs       0
Name: 804, dtype: object)
(805, Team         LAD
League        NL
Year        1982
RS           691
RA           612
W             88
G            162
Playoffs       0
Name: 805, dtype: object)
(806, Team         MIL
League        AL
Year        1982
RS           891
RA           717
W             95
G            163
Playoffs       1
Name: 806, dtype: object)
(807, Team         MIN
League        AL
Year        1982
RS           657
RA           819
W             60
G            162
Playoffs       0
Name: 807, dtype: object)
(808, Team         MON
League        NL
Year        1982
RS           697
RA           616
W             86
G            162
Playoffs       0
Name: 808, dtype: object)
(809, Team         NYM
League        NL
Year        1982
RS           609
RA           723
W             65
G            162
Playoffs       0
Name: 809, dtype: object)
(810, Team         NYY
League        AL
Year        1982
RS           709
RA           716
W             79
G            162
Playoffs       0
Name: 810, dtype: object)
(811, Team         OAK
League        AL
Year        1982
RS           691
RA           819
W             68
G            162
Playoffs       0
Name: 811, dtype: object)
(812, Team         PHI
League        NL
Year        1982
RS           664
RA           654
W             89
G            162
Playoffs       0
Name: 812, dtype: object)
(813, Team         PIT
League        NL
Year        1982
RS           724
RA           696
W             84
G            162
Playoffs       0
Name: 813, dtype: object)
(814, Team         SDP
League        NL
Year        1982
RS           675
RA           658
W             81
G            162
Playoffs       0
Name: 814, dtype: object)
(815, Team         SEA
League        AL
Year        1982
RS           651
RA           712
W             76
G            162
Playoffs       0
Name: 815, dtype: object)
(816, Team         SFG
League        NL
Year        1982
RS           673
RA           687
W             87
G            162
Playoffs       0
Name: 816, dtype: object)
(817, Team         STL
League        NL
Year        1982
RS           685
RA           609
W             92
G            162
Playoffs       1
Name: 817, dtype: object)
(818, Team         TEX
League        AL
Year        1982
RS           590
RA           749
W             64
G            162
Playoffs       0
Name: 818, dtype: object)
(819, Team         TOR
League        AL
Year        1982
RS           651
RA           701
W             78
G            162
Playoffs       0
Name: 819, dtype: object)
(820, Team         ATL
League        NL
Year        1980
RS           630
RA           660
W             81
G            161
Playoffs       0
Name: 820, dtype: object)
(821, Team         BAL
League        AL
Year        1980
RS           805
RA           640
W            100
G            162
Playoffs       0
Name: 821, dtype: object)
(822, Team         BOS
League        AL
Year        1980
RS           757
RA           767
W             83
G            160
Playoffs       0
Name: 822, dtype: object)
(823, Team         CAL
League        AL
Year        1980
RS           698
RA           797
W             65
G            160
Playoffs       0
Name: 823, dtype: object)
(824, Team         CHC
League        NL
Year        1980
RS           614
RA           728
W             64
G            162
Playoffs       0
Name: 824, dtype: object)
(825, Team         CHW
League        AL
Year        1980
RS           587
RA           722
W             70
G            162
Playoffs       0
Name: 825, dtype: object)
(826, Team         CIN
League        NL
Year        1980
RS           707
RA           670
W             89
G            163
Playoffs       0
Name: 826, dtype: object)
(827, Team         CLE
League        AL
Year        1980
RS           738
RA           807
W             79
G            160
Playoffs       0
Name: 827, dtype: object)
(828, Team         DET
League        AL
Year        1980
RS           830
RA           757
W             84
G            163
Playoffs       0
Name: 828, dtype: object)
(829, Team         HOU
League        NL
Year        1980
RS           637
RA           589
W             93
G            163
Playoffs       1
Name: 829, dtype: object)
(830, Team         KCR
League        AL
Year        1980
RS           809
RA           694
W             97
G            162
Playoffs       1
Name: 830, dtype: object)
(831, Team         LAD
League        NL
Year        1980
RS           663
RA           591
W             92
G            163
Playoffs       0
Name: 831, dtype: object)
(832, Team         MIL
League        AL
Year        1980
RS           811
RA           682
W             86
G            162
Playoffs       0
Name: 832, dtype: object)
(833, Team         MIN
League        AL
Year        1980
RS           670
RA           724
W             77
G            161
Playoffs       0
Name: 833, dtype: object)
(834, Team         MON
League        NL
Year        1980
RS           694
RA           629
W             90
G            162
Playoffs       0
Name: 834, dtype: object)
(835, Team         NYM
League        NL
Year        1980
RS           611
RA           702
W             67
G            162
Playoffs       0
Name: 835, dtype: object)
(836, Team         NYY
League        AL
Year        1980
RS           820
RA           662
W            103
G            162
Playoffs       1
Name: 836, dtype: object)
(837, Team         OAK
League        AL
Year        1980
RS           686
RA           642
W             83
G            162
Playoffs       0
Name: 837, dtype: object)
(838, Team         PHI
League        NL
Year        1980
RS           728
RA           639
W             91
G            162
Playoffs       1
Name: 838, dtype: object)
(839, Team         PIT
League        NL
Year        1980
RS           666
RA           646
W             83
G            162
Playoffs       0
Name: 839, dtype: object)
(840, Team         SDP
League        NL
Year        1980
RS           591
RA           654
W             73
G            163
Playoffs       0
Name: 840, dtype: object)
(841, Team         SEA
League        AL
Year        1980
RS           610
RA           793
W             59
G            163
Playoffs       0
Name: 841, dtype: object)
(842, Team         SFG
League        NL
Year        1980
RS           573
RA           634
W             75
G            161
Playoffs       0
Name: 842, dtype: object)
(843, Team         STL
League        NL
Year        1980
RS           738
RA           710
W             74
G            162
Playoffs       0
Name: 843, dtype: object)
(844, Team         TEX
League        AL
Year        1980
RS           756
RA           752
W             76
G            163
Playoffs       0
Name: 844, dtype: object)
(845, Team         TOR
League        AL
Year        1980
RS           624
RA           762
W             67
G            162
Playoffs       0
Name: 845, dtype: object)
(846, Team         ATL
League        NL
Year        1979
RS           669
RA           763
W             66
G            160
Playoffs       0
Name: 846, dtype: object)
(847, Team         BAL
League        AL
Year        1979
RS           757
RA           582
W            102
G            159
Playoffs       1
Name: 847, dtype: object)
(848, Team         BOS
League        AL
Year        1979
RS           841
RA           711
W             91
G            160
Playoffs       0
Name: 848, dtype: object)
(849, Team         CAL
League        AL
Year        1979
RS           866
RA           768
W             88
G            162
Playoffs       1
Name: 849, dtype: object)
(850, Team         CHC
League        NL
Year        1979
RS           706
RA           707
W             80
G            162
Playoffs       0
Name: 850, dtype: object)
(851, Team         CHW
League        AL
Year        1979
RS           730
RA           748
W             73
G            160
Playoffs       0
Name: 851, dtype: object)
(852, Team         CIN
League        NL
Year        1979
RS           731
RA           644
W             90
G            161
Playoffs       1
Name: 852, dtype: object)
(853, Team         CLE
League        AL
Year        1979
RS           760
RA           805
W             81
G            161
Playoffs       0
Name: 853, dtype: object)
(854, Team         DET
League        AL
Year        1979
RS           770
RA           738
W             84
G            161
Playoffs       0
Name: 854, dtype: object)
(855, Team         HOU
League        NL
Year        1979
RS           583
RA           582
W             89
G            162
Playoffs       0
Name: 855, dtype: object)
(856, Team         KCR
League        AL
Year        1979
RS           851
RA           816
W             85
G            162
Playoffs       0
Name: 856, dtype: object)
(857, Team         LAD
League        NL
Year        1979
RS           739
RA           717
W             79
G            162
Playoffs       0
Name: 857, dtype: object)
(858, Team         MIL
League        AL
Year        1979
RS           807
RA           722
W             95
G            161
Playoffs       0
Name: 858, dtype: object)
(859, Team         MIN
League        AL
Year        1979
RS           764
RA           725
W             82
G            162
Playoffs       0
Name: 859, dtype: object)
(860, Team         MON
League        NL
Year        1979
RS           701
RA           581
W             95
G            160
Playoffs       0
Name: 860, dtype: object)
(861, Team         NYM
League        NL
Year        1979
RS           593
RA           706
W             63
G            163
Playoffs       0
Name: 861, dtype: object)
(862, Team         NYY
League        AL
Year        1979
RS           734
RA           672
W             89
G            160
Playoffs       0
Name: 862, dtype: object)
(863, Team         OAK
League        AL
Year        1979
RS           573
RA           860
W             54
G            162
Playoffs       0
Name: 863, dtype: object)
(864, Team         PHI
League        NL
Year        1979
RS           683
RA           718
W             84
G            163
Playoffs       0
Name: 864, dtype: object)
(865, Team         PIT
League        NL
Year        1979
RS           775
RA           643
W             98
G            163
Playoffs       1
Name: 865, dtype: object)
(866, Team         SDP
League        NL
Year        1979
RS           603
RA           681
W             68
G            161
Playoffs       0
Name: 866, dtype: object)
(867, Team         SEA
League        AL
Year        1979
RS           711
RA           820
W             67
G            162
Playoffs       0
Name: 867, dtype: object)
(868, Team         SFG
League        NL
Year        1979
RS           672
RA           751
W             71
G            162
Playoffs       0
Name: 868, dtype: object)
(869, Team         STL
League        NL
Year        1979
RS           731
RA           693
W             86
G            163
Playoffs       0
Name: 869, dtype: object)
(870, Team         TEX
League        AL
Year        1979
RS           750
RA           698
W             83
G            162
Playoffs       0
Name: 870, dtype: object)
(871, Team         TOR
League        AL
Year        1979
RS           613
RA           862
W             53
G            162
Playoffs       0
Name: 871, dtype: object)
(872, Team         ATL
League        NL
Year        1978
RS           600
RA           750
W             69
G            162
Playoffs       0
Name: 872, dtype: object)
(873, Team         BAL
League        AL
Year        1978
RS           659
RA           633
W             90
G            161
Playoffs       0
Name: 873, dtype: object)
(874, Team         BOS
League        AL
Year        1978
RS           796
RA           657
W             99
G            163
Playoffs       0
Name: 874, dtype: object)
(875, Team         CAL
League        AL
Year        1978
RS           691
RA           666
W             87
G            162
Playoffs       0
Name: 875, dtype: object)
(876, Team         CHC
League        NL
Year        1978
RS           664
RA           724
W             79
G            162
Playoffs       0
Name: 876, dtype: object)
(877, Team         CHW
League        AL
Year        1978
RS           634
RA           731
W             71
G            161
Playoffs       0
Name: 877, dtype: object)
(878, Team         CIN
League        NL
Year        1978
RS           710
RA           688
W             92
G            161
Playoffs       0
Name: 878, dtype: object)
(879, Team         CLE
League        AL
Year        1978
RS           639
RA           694
W             69
G            159
Playoffs       0
Name: 879, dtype: object)
(880, Team         DET
League        AL
Year        1978
RS           714
RA           653
W             86
G            162
Playoffs       0
Name: 880, dtype: object)
(881, Team         HOU
League        NL
Year        1978
RS           605
RA           634
W             74
G            162
Playoffs       0
Name: 881, dtype: object)
(882, Team         KCR
League        AL
Year        1978
RS           743
RA           634
W             92
G            162
Playoffs       1
Name: 882, dtype: object)
(883, Team         LAD
League        NL
Year        1978
RS           727
RA           573
W             95
G            162
Playoffs       1
Name: 883, dtype: object)
(884, Team         MIL
League        AL
Year        1978
RS           804
RA           650
W             93
G            162
Playoffs       0
Name: 884, dtype: object)
(885, Team         MIN
League        AL
Year        1978
RS           666
RA           678
W             73
G            162
Playoffs       0
Name: 885, dtype: object)
(886, Team         MON
League        NL
Year        1978
RS           633
RA           611
W             76
G            162
Playoffs       0
Name: 886, dtype: object)
(887, Team         NYM
League        NL
Year        1978
RS           607
RA           690
W             66
G            162
Playoffs       0
Name: 887, dtype: object)
(888, Team         NYY
League        AL
Year        1978
RS           735
RA           582
W            100
G            163
Playoffs       1
Name: 888, dtype: object)
(889, Team         OAK
League        AL
Year        1978
RS           532
RA           690
W             69
G            162
Playoffs       0
Name: 889, dtype: object)
(890, Team         PHI
League        NL
Year        1978
RS           708
RA           586
W             90
G            162
Playoffs       1
Name: 890, dtype: object)
(891, Team         PIT
League        NL
Year        1978
RS           684
RA           637
W             88
G            161
Playoffs       0
Name: 891, dtype: object)
(892, Team         SDP
League        NL
Year        1978
RS           591
RA           598
W             84
G            162
Playoffs       0
Name: 892, dtype: object)
(893, Team         SEA
League        AL
Year        1978
RS           614
RA           834
W             56
G            160
Playoffs       0
Name: 893, dtype: object)
(894, Team         SFG
League        NL
Year        1978
RS           613
RA           594
W             89
G            162
Playoffs       0
Name: 894, dtype: object)
(895, Team         STL
League        NL
Year        1978
RS           600
RA           657
W             69
G            162
Playoffs       0
Name: 895, dtype: object)

(1021, Team         BAL
League        AL
Year        1971
RS           742
RA           530
W            101
G            158
Playoffs       1
Name: 1021, dtype: object)
(1022, Team         BOS
League        AL
Year        1971
RS           691
RA           667
W             85
G            162
Playoffs       0
Name: 1022, dtype: object)
(1023, Team         CAL
League        AL
Year        1971
RS           511
RA           576
W             76
G            162
Playoffs       0
Name: 1023, dtype: object)
(1024, Team         CHC
League        NL
Year        1971
RS           637
RA           648
W             83
G            162
Playoffs       0
Name: 1024, dtype: object)
(1025, Team         CHW
League        AL
Year        1971
RS           617
RA           597
W             79
G            162
Playoffs       0
Name: 1025, dtype: object)
(1026, Team         CIN
League        NL
Year        1971
RS           586
RA           581
W             79
G            162
Playoffs       0
Name: 1026, dtype: object)
(1027, Team         CLE
League        AL
Year        1971
RS           543
RA           747
W             60
G            162
Playoffs       0
Name: 1027, dtype: object)
(1028, Team         DET
League        AL
Year        1971
RS           701
RA           645
W             91
G            162
Playoffs       0
Name: 1028, dtype: object)
(1029, Team         HOU
League        NL
Year        1971
RS           585
RA           567
W             79
G            162
Playoffs       0
Name: 1029, dtype: object)
(1030, Team         KCR
League        AL
Year        1971
RS           603
RA           566
W             85
G            161
Playoffs       0
Name: 1030, dtype: object)
(1031, Team         LAD
League        NL
Year        1971
RS           663
RA           587
W             89
G            162
Playoffs       0
Name: 1031, dtype: object)
(1032, Team         MIL
League        AL
Year        1971
RS           534
RA           609
W             69
G            161
Playoffs       0
Name: 1032, dtype: object)
(1033, Team         MIN
League        AL
Year        1971
RS           654
RA           670
W             74
G            160
Playoffs       0
Name: 1033, dtype: object)
(1034, Team         MON
League        NL
Year        1971
RS           622
RA           729
W             71
G            162
Playoffs       0
Name: 1034, dtype: object)
(1035, Team         NYM
League        NL
Year        1971
RS           588
RA           550
W             83
G            162
Playoffs       0
Name: 1035, dtype: object)
(1036, Team         NYY
League        AL
Year        1971
RS           648
RA           641
W             81
G            162
Playoffs       0
Name: 1036, dtype: object)
(1037, Team         OAK
League        AL
Year        1971
RS           691
RA           564
W            101
G            161
Playoffs       1
Name: 1037, dtype: object)
(1038, Team         PHI
League        NL
Year        1971
RS           558
RA           688
W             67
G            162
Playoffs       0
Name: 1038, dtype: object)
(1039, Team         PIT
League        NL
Year        1971
RS           788
RA           599
W             97
G            162
Playoffs       1
Name: 1039, dtype: object)
(1040, Team         SDP
League        NL
Year        1971
RS           486
RA           610
W             61
G            161
Playoffs       0
Name: 1040, dtype: object)
(1041, Team         SFG
League        NL
Year        1971
RS           706
RA           644
W             90
G            162
Playoffs       1
Name: 1041, dtype: object)
(1042, Team         STL
League        NL
Year        1971
RS           739
RA           699
W             90
G            163
Playoffs       0
Name: 1042, dtype: object)
(1043, Team         WSA
League        AL
Year        1971
RS           537
RA           660
W             63
G            159
Playoffs       0
Name: 1043, dtype: object)
(1044, Team         ATL
League        NL
Year        1970
RS           736
RA           772
W             76
G            162
Playoffs       0
Name: 1044, dtype: object)
(1045, Team         BAL
League        AL
Year        1970
RS           792
RA           574
W            108
G            162
Playoffs       1
Name: 1045, dtype: object)
(1046, Team         BOS
League        AL
Year        1970
RS           786
RA           722
W             87
G            162
Playoffs       0
Name: 1046, dtype: object)
(1047, Team         CAL
League        AL
Year        1970
RS           631
RA           630
W             86
G            162
Playoffs       0
Name: 1047, dtype: object)
(1048, Team         CHC
League        NL
Year        1970
RS           806
RA           679
W             84
G            162
Playoffs       0
Name: 1048, dtype: object)
(1049, Team         CHW
League        AL
Year        1970
RS           633
RA           822
W             56
G            162
Playoffs       0
Name: 1049, dtype: object)
(1050, Team         CIN
League        NL
Year        1970
RS           775
RA           681
W            102
G            162
Playoffs       1
Name: 1050, dtype: object)
(1051, Team         CLE
League        AL
Year        1970
RS           649
RA           675
W             76
G            162
Playoffs       0
Name: 1051, dtype: object)
(1052, Team         DET
League        AL
Year        1970
RS           666
RA           731
W             79
G            162
Playoffs       0
Name: 1052, dtype: object)
(1053, Team         HOU
League        NL
Year        1970
RS           744
RA           763
W             79
G            162
Playoffs       0
Name: 1053, dtype: object)
(1054, Team         KCR
League        AL
Year        1970
RS           611
RA           705
W             65
G            162
Playoffs       0
Name: 1054, dtype: object)
(1055, Team         LAD
League        NL
Year        1970
RS           749
RA           684
W             87
G            161
Playoffs       0
Name: 1055, dtype: object)
(1056, Team         MIL
League        AL
Year        1970
RS           613
RA           751
W             65
G            163
Playoffs       0
Name: 1056, dtype: object)
(1057, Team         MIN
League        AL
Year        1970
RS           744
RA           605
W             98
G            162
Playoffs       1
Name: 1057, dtype: object)
(1058, Team         MON
League        NL
Year        1970
RS           687
RA           807
W             73
G            162
Playoffs       0
Name: 1058, dtype: object)
(1059, Team         NYM
League        NL
Year        1970
RS           695
RA           630
W             83
G            162
Playoffs       0
Name: 1059, dtype: object)
(1060, Team         NYY
League        AL
Year        1970
RS           680
RA           612
W             93
G            163
Playoffs       0
Name: 1060, dtype: object)
(1061, Team         OAK
League        AL
Year        1970
RS           678
RA           593
W             89
G            162
Playoffs       0
Name: 1061, dtype: object)
(1062, Team         PHI
League        NL
Year        1970
RS           594
RA           730
W             73
G            161
Playoffs       0
Name: 1062, dtype: object)
(1063, Team         PIT
League        NL
Year        1970
RS           729
RA           664
W             89
G            162
Playoffs       1
Name: 1063, dtype: object)
(1064, Team         SDP
League        NL
Year        1970
RS           681
RA           788
W             63
G            162
Playoffs       0
Name: 1064, dtype: object)
(1065, Team         SFG
League        NL
Year        1970
RS           831
RA           826
W             86
G            162
Playoffs       0
Name: 1065, dtype: object)
(1066, Team         STL
League        NL
Year        1970
RS           744
RA           747
W             76
G            162
Playoffs       0
Name: 1066, dtype: object)
(1067, Team         WSA
League        AL
Year        1970
RS           626
RA           689
W             70
G            162
Playoffs       0
Name: 1067, dtype: object)
(1068, Team         ATL
League        NL
Year        1969
RS           691
RA           631
W             93
G            162
Playoffs       1
Name: 1068, dtype: object)
(1069, Team         BAL
League        AL
Year        1969
RS           779
RA           517
W            109
G            162
Playoffs       1
Name: 1069, dtype: object)
(1070, Team         BOS
League        AL
Year        1969
RS           743
RA           736
W             87
G            162
Playoffs       0
Name: 1070, dtype: object)
(1071, Team         CAL
League        AL
Year        1969
RS           528
RA           652
W             71
G            163
Playoffs       0
Name: 1071, dtype: object)
(1072, Team         CHC
League        NL
Year        1969
RS           720
RA           611
W             92
G            163
Playoffs       0
Name: 1072, dtype: object)
(1073, Team         CHW
League        AL
Year        1969
RS           625
RA           723
W             68
G            162
Playoffs       0
Name: 1073, dtype: object)
(1074, Team         CIN
League        NL
Year        1969
RS           798
RA           768
W             89
G            163
Playoffs       0
Name: 1074, dtype: object)
(1075, Team         CLE
League        AL
Year        1969
RS           573
RA           717
W             62
G            161
Playoffs       0
Name: 1075, dtype: object)
(1076, Team         DET
League        AL
Year        1969
RS           701
RA           601
W             90
G            162
Playoffs       0
Name: 1076, dtype: object)
(1077, Team         HOU
League        NL
Year        1969
RS           676
RA           668
W             81
G            162
Playoffs       0
Name: 1077, dtype: object)
(1078, Team         KCR
League        AL
Year        1969
RS           586
RA           688
W             69
G            163
Playoffs       0
Name: 1078, dtype: object)
(1079, Team         LAD
League        NL
Year        1969
RS           645
RA           561
W             85
G            162
Playoffs       0
Name: 1079, dtype: object)
(1080, Team         MIN
League        AL
Year        1969
RS           790
RA           618
W             97
G            162
Playoffs       1
Name: 1080, dtype: object)
(1081, Team         MON
League        NL
Year        1969
RS           582
RA           791
W             52
G            162
Playoffs       0
Name: 1081, dtype: object)
(1082, Team         NYM
League        NL
Year        1969
RS           632
RA           541
W            100
G            162
Playoffs       1
Name: 1082, dtype: object)
(1083, Team         NYY
League        AL
Year        1969
RS           562
RA           587
W             80
G            162
Playoffs       0
Name: 1083, dtype: object)
(1084, Team         OAK
League        AL
Year        1969
RS           740
RA           678
W             88
G            162
Playoffs       0
Name: 1084, dtype: object)
(1085, Team         PHI
League        NL
Year        1969
RS           645
RA           745
W             63
G            162
Playoffs       0
Name: 1085, dtype: object)
(1086, Team         PIT
League        NL
Year        1969
RS           725
RA           652
W             88
G            162
Playoffs       0
Name: 1086, dtype: object)
(1087, Team         SDP
League        NL
Year        1969
RS           468
RA           746
W             52
G            162
Playoffs       0
Name: 1087, dtype: object)
(1088, Team         SEP
League        AL
Year        1969
RS           639
RA           799
W             64
G            163
Playoffs       0
Name: 1088, dtype: object)
(1089, Team         SFG
League        NL
Year        1969
RS           713
RA           636
W             90
G            162
Playoffs       0
Name: 1089, dtype: object)
(1090, Team         STL
League        NL
Year        1969
RS           595
RA           540
W             87
G            162
Playoffs       0
Name: 1090, dtype: object)
(1091, Team         WSA
League        AL
Year        1969
RS           694
RA           644
W             86
G            162
Playoffs       0
Name: 1091, dtype: object)
(1092, Team         ATL
League        NL
Year        1968
RS           514
RA           549
W             81
G            163
Playoffs       0
Name: 1092, dtype: object)
(1093, Team         BAL
League        AL
Year        1968
RS           579
RA           497
W             91
G            162
Playoffs       0
Name: 1093, dtype: object)
(1094, Team         BOS
League        AL
Year        1968
RS           614
RA           611
W             86
G            162
Playoffs       0
Name: 1094, dtype: object)
(1095, Team         CAL
League        AL
Year        1968
RS           498
RA           615
W             67
G            162
Playoffs       0
Name: 1095, dtype: object)
(1096, Team         CHC
League        NL
Year        1968
RS           612
RA           611
W             84
G            163
Playoffs       0
Name: 1096, dtype: object)
(1097, Team         CHW
League        AL
Year        1968
RS           463
RA           527
W             67
G            162
Playoffs       0
Name: 1097, dtype: object)
(1098, Team         CIN
League        NL
Year        1968
RS           690
RA           673
W             83
G            163
Playoffs       0
Name: 1098, dtype: object)
(1099, Team         CLE
League        AL
Year        1968
RS           516
RA           504
W             86
G            162
Playoffs       0
Name: 1099, dtype: object)
(1100, Team         DET
League        AL
Year        1968
RS           671
RA           492
W            103
G            164
Playoffs       1
Name: 1100, dtype: object)
(1101, Team         HOU
League        NL
Year        1968
RS           510
RA           588
W             72
G            162
Playoffs       0
Name: 1101, dtype: object)
(1102, Team         LAD
League        NL
Year        1968
RS           470
RA           509
W             76
G            162
Playoffs       0
Name: 1102, dtype: object)
(1103, Team         MIN
League        AL
Year        1968
RS           562
RA           546
W             79
G            162
Playoffs       0
Name: 1103, dtype: object)
(1104, Team         NYM
League        NL
Year        1968
RS           473
RA           499
W             73
G            163
Playoffs       0
Name: 1104, dtype: object)
(1105, Team         NYY
League        AL
Year        1968
RS           536
RA           531
W             83
G            164
Playoffs       0
Name: 1105, dtype: object)
(1106, Team         OAK
League        AL
Year        1968
RS           569
RA           544
W             82
G            163
Playoffs       0
Name: 1106, dtype: object)
(1107, Team         PHI
League        NL
Year        1968
RS           543
RA           615
W             76
G            162
Playoffs       0
Name: 1107, dtype: object)
(1108, Team         PIT
League        NL
Year        1968
RS           583
RA           532
W             80
G            163
Playoffs       0
Name: 1108, dtype: object)
(1109, Team         SFG
League        NL
Year        1968
RS           599
RA           529
W             88
G            163
Playoffs       0
Name: 1109, dtype: object)
(1110, Team         STL
League        NL
Year        1968
RS           583
RA           472
W             97
G            162
Playoffs       1
Name: 1110, dtype: object)
(1111, Team         WSA
League        AL
Year        1968
RS           524
RA           665
W             65
G            161
Playoffs       0
Name: 1111, dtype: object)
(1112, Team         ATL
League        NL
Year        1967
RS           631
RA           640
W             77
G            162
Playoffs       0
Name: 1112, dtype: object)
(1113, Team         BAL
League        AL
Year        1967
RS           654
RA           592
W             76
G            161
Playoffs       0
Name: 1113, dtype: object)
(1114, Team         BOS
League        AL
Year        1967
RS           722
RA           614
W             92
G            162
Playoffs       1
Name: 1114, dtype: object)
(1115, Team         CAL
League        AL
Year        1967
RS           567
RA           587
W             84
G            161
Playoffs       0
Name: 1115, dtype: object)
(1116, Team         CHC
League        NL
Year        1967
RS           702
RA           624
W             87
G            162
Playoffs       0
Name: 1116, dtype: object)
(1117, Team         CHW
League        AL
Year        1967
RS           531
RA           491
W             89
G            162
Playoffs       0
Name: 1117, dtype: object)
(1118, Team         CIN
League        NL
Year        1967
RS           604
RA           563
W             87
G            162
Playoffs       0
Name: 1118, dtype: object)
(1119, Team         CLE
League        AL
Year        1967
RS           559
RA           613
W             75
G            162
Playoffs       0
Name: 1119, dtype: object)
(1120, Team         DET
League        AL
Year        1967
RS           683
RA           587
W             91
G            163
Playoffs       0
Name: 1120, dtype: object)
(1121, Team         HOU
League        NL
Year        1967
RS           626
RA           742
W             69
G            162
Playoffs       0
Name: 1121, dtype: object)
(1122, Team         KCA
League        AL
Year        1967
RS           533
RA           660
W             62
G            161
Playoffs       0
Name: 1122, dtype: object)
(1123, Team         LAD
League        NL
Year        1967
RS           519
RA           595
W             73
G            162
Playoffs       0
Name: 1123, dtype: object)
(1124, Team         MIN
League        AL
Year        1967
RS           671
RA           590
W             91
G            164
Playoffs       0
Name: 1124, dtype: object)
(1125, Team         NYM
League        NL
Year        1967
RS           498
RA           672
W             61
G            162
Playoffs       0
Name: 1125, dtype: object)
(1126, Team         NYY
League        AL
Year        1967
RS           522
RA           621
W             72
G            163
Playoffs       0
Name: 1126, dtype: object)
(1127, Team         PHI
League        NL
Year        1967
RS           612
RA           581
W             82
G            162
Playoffs       0
Name: 1127, dtype: object)
(1128, Team         PIT
League        NL
Year        1967
RS           679
RA           693
W             81
G            163
Playoffs       0
Name: 1128, dtype: object)
(1129, Team         SFG
League        NL
Year        1967
RS           652
RA           551
W             91
G            162
Playoffs       0
Name: 1129, dtype: object)
(1130, Team         STL
League        NL
Year        1967
RS           695
RA           557
W            101
G            161
Playoffs       1
Name: 1130, dtype: object)
(1131, Team         WSA
League        AL
Year        1967
RS           550
RA           637
W             76
G            161
Playoffs       0
Name: 1131, dtype: object)
(1132, Team         ATL
League        NL
Year        1966
RS           782
RA           683
W             85
G            163
Playoffs       0
Name: 1132, dtype: object)
(1133, Team         BAL
League        AL
Year        1966
RS           755
RA           601
W             97
G            160
Playoffs       1
Name: 1133, dtype: object)
(1134, Team         BOS
League        AL
Year        1966
RS           655
RA           731
W             72
G            162
Playoffs       0
Name: 1134, dtype: object)
(1135, Team         CAL
League        AL
Year        1966
RS           604
RA           643
W             80
G            162
Playoffs       0
Name: 1135, dtype: object)
(1136, Team         CHC
League        NL
Year        1966
RS           644
RA           809
W             59
G            162
Playoffs       0
Name: 1136, dtype: object)
(1137, Team         CHW
League        AL
Year        1966
RS           574
RA           517
W             83
G            163
Playoffs       0
Name: 1137, dtype: object)
(1138, Team         CIN
League        NL
Year        1966
RS           692
RA           702
W             76

In [35]:
# Print the row and type of each row
for row_tuple in pit_df.iterrows():
    print(row_tuple)
    print(type(row_tuple))

(0, Team         ARI
League        NL
Year        2012
RS           734
RA           688
W             81
G            162
Playoffs       0
Name: 0, dtype: object)
<class 'tuple'>
(1, Team         ATL
League        NL
Year        2012
RS           700
RA           600
W             94
G            162
Playoffs       1
Name: 1, dtype: object)
<class 'tuple'>
(2, Team         BAL
League        AL
Year        2012
RS           712
RA           705
W             93
G            162
Playoffs       1
Name: 2, dtype: object)
<class 'tuple'>
(3, Team         BOS
League        AL
Year        2012
RS           734
RA           806
W             69
G            162
Playoffs       0
Name: 3, dtype: object)
<class 'tuple'>
(4, Team         CHC
League        NL
Year        2012
RS           613
RA           759
W             61
G            162
Playoffs       0
Name: 4, dtype: object)
<class 'tuple'>
(5, Team         CHW
League        AL
Year        2012
RS           748
RA           676
W             85
G            162
Playoffs       0
Name: 5, dtype: object)
<class 'tuple'>
(6, Team         CIN
League        NL
Year        2012
RS           669
RA           588
W             97
G            162
Playoffs       1
Name: 6, dtype: object)
<class 'tuple'>
(7, Team         CLE
League        AL
Year        2012
RS           667
RA           845
W             68
G            162
Playoffs       0
Name: 7, dtype: object)
<class 'tuple'>
(8, Team         COL
League        NL
Year        2012
RS           758
RA           890
W             64
G            162
Playoffs       0
Name: 8, dtype: object)
<class 'tuple'>
(9, Team         DET
League        AL
Year        2012
RS           726
RA           670
W             88
G            162
Playoffs       1
Name: 9, dtype: object)
<class 'tuple'>
(10, Team         HOU
League        NL
Year        2012
RS           583
RA           794
W             55
G            162
Playoffs       0
Name: 10, dtype: object)
<class 'tuple'>
(11, Team         KCR
League        AL
Year        2012
RS           676
RA           746
W             72
G            162
Playoffs       0
Name: 11, dtype: object)
<class 'tuple'>
(12, Team         LAA
League        AL
Year        2012
RS           767
RA           699
W             89
G            162
Playoffs       0
Name: 12, dtype: object)
<class 'tuple'>
(13, Team         LAD
League        NL
Year        2012
RS           637
RA           597
W             86
G            162
Playoffs       0
Name: 13, dtype: object)
<class 'tuple'>
(14, Team         MIA
League        NL
Year        2012
RS           609
RA           724
W             69
G            162
Playoffs       0
Name: 14, dtype: object)
<class 'tuple'>
(15, Team         MIL
League        NL
Year        2012
RS           776
RA           733
W             83
G            162
Playoffs       0
Name: 15, dtype: object)
<class 'tuple'>
(16, Team         MIN
League        AL
Year        2012
RS           701
RA           832
W             66
G            162
Playoffs       0
Name: 16, dtype: object)
<class 'tuple'>
(17, Team         NYM
League        NL
Year        2012
RS           650
RA           709
W             74
G            162
Playoffs       0
Name: 17, dtype: object)
<class 'tuple'>
(18, Team         NYY
League        AL
Year        2012
RS           804
RA           668
W             95
G            162
Playoffs       1
Name: 18, dtype: object)
<class 'tuple'>
(19, Team         OAK
League        AL
Year        2012
RS           713
RA           614
W             94
G            162
Playoffs       1
Name: 19, dtype: object)
<class 'tuple'>
(20, Team         PHI
League        NL
Year        2012
RS           684
RA           680
W             81
G            162
Playoffs       0
Name: 20, dtype: object)
<class 'tuple'>
(21, Team         PIT
League        NL
Year        2012
RS           651
RA           674
W             79
G            162
Playoffs       0
Name: 21, dtype: object)
<class 'tuple'>
(22, Team         SDP
League        NL
Year        2012
RS           651
RA           710
W             76
G            162
Playoffs       0
Name: 22, dtype: object)
<class 'tuple'>
(23, Team         SEA
League        AL
Year        2012
RS           619
RA           651
W             75
G            162
Playoffs       0
Name: 23, dtype: object)
<class 'tuple'>
(24, Team         SFG
League        NL
Year        2012
RS           718
RA           649
W             94
G            162
Playoffs       1
Name: 24, dtype: object)
<class 'tuple'>
(25, Team         STL
League        NL
Year        2012
RS           765
RA           648
W             88
G            162
Playoffs       1
Name: 25, dtype: object)
<class 'tuple'>
(26, Team         TBR
League        AL
Year        2012
RS           697
RA           577
W             90
G            162
Playoffs       0
Name: 26, dtype: object)
<class 'tuple'>
(27, Team         TEX
League        AL
Year        2012
RS           808
RA           707
W             93
G            162
Playoffs       1
Name: 27, dtype: object)
<class 'tuple'>
(28, Team         TOR
League        AL
Year        2012
RS           716
RA           784
W             73
G            162
Playoffs       0
Name: 28, dtype: object)
<class 'tuple'>
(29, Team         WSN
League        NL
Year        2012
RS           731
RA           594
W             98
G            162
Playoffs       1
Name: 29, dtype: object)
<class 'tuple'>
(30, Team         ARI
League        NL
Year        2011
RS           731
RA           662
W             94
G            162
Playoffs       1
Name: 30, dtype: object)
<class 'tuple'>
(31, Team         ATL
League        NL
Year        2011
RS           641
RA           605
W             89
G            162
Playoffs       0
Name: 31, dtype: object)
<class 'tuple'>
(32, Team         BAL
League        AL
Year        2011
RS           708
RA           860
W             69
G            162
Playoffs       0
Name: 32, dtype: object)
<class 'tuple'>
(33, Team         BOS
League        AL
Year        2011
RS           875
RA           737
W             90
G            162
Playoffs       0
Name: 33, dtype: object)
<class 'tuple'>
(34, Team         CHC
League        NL
Year        2011
RS           654
RA           756
W             71
G            162
Playoffs       0
Name: 34, dtype: object)
<class 'tuple'>
(35, Team         CHW
League        AL
Year        2011
RS           654
RA           706
W             79
G            162
Playoffs       0
Name: 35, dtype: object)
<class 'tuple'>
(36, Team         CIN
League        NL
Year        2011
RS           735
RA           720
W             79
G            162
Playoffs       0
Name: 36, dtype: object)
<class 'tuple'>
(37, Team         CLE
League        AL
Year        2011
RS           704
RA           760
W             80
G            162
Playoffs       0
Name: 37, dtype: object)
<class 'tuple'>
(38, Team         COL
League        NL
Year        2011
RS           735
RA           774
W             73
G            162
Playoffs       0
Name: 38, dtype: object)
<class 'tuple'>
(39, Team         DET
League        AL
Year        2011
RS           787
RA           711
W             95
G            162
Playoffs       1
Name: 39, dtype: object)
<class 'tuple'>
(40, Team         FLA
League        NL
Year        2011
RS           625
RA           702
W             72
G            162
Playoffs       0
Name: 40, dtype: object)
<class 'tuple'>
(41, Team         HOU
League        NL
Year        2011
RS           615
RA           796
W             56
G            162
Playoffs       0
Name: 41, dtype: object)
<class 'tuple'>
(42, Team         KCR
League        AL
Year        2011
RS           730
RA           762
W             71
G            162
Playoffs       0
Name: 42, dtype: object)
<class 'tuple'>
(43, Team         LAA
League        AL
Year        2011
RS           667
RA           633
W             86
G            162
Playoffs       0
Name: 43, dtype: object)
<class 'tuple'>
(44, Team         LAD
League        NL
Year        2011
RS           644
RA           612
W             82
G            161
Playoffs       0
Name: 44, dtype: object)
<class 'tuple'>
(45, Team         MIL
League        NL
Year        2011
RS           721
RA           638
W             96
G            162
Playoffs       1
Name: 45, dtype: object)
<class 'tuple'>
(46, Team         MIN
League        AL
Year        2011
RS           619
RA           804
W             63
G            162
Playoffs       0
Name: 46, dtype: object)
<class 'tuple'>
(47, Team         NYM
League        NL
Year        2011
RS           718
RA           742
W             77
G            162
Playoffs       0
Name: 47, dtype: object)
<class 'tuple'>
(48, Team         NYY
League        AL
Year        2011
RS           867
RA           657
W             97
G            162
Playoffs       1
Name: 48, dtype: object)
<class 'tuple'>
(49, Team         OAK
League        AL
Year        2011
RS           645
RA           679
W             74
G            162
Playoffs       0
Name: 49, dtype: object)
<class 'tuple'>
(50, Team         PHI
League        NL
Year        2011
RS           713
RA           529
W            102
G            162
Playoffs       1
Name: 50, dtype: object)
<class 'tuple'>
(51, Team         PIT
League        NL
Year        2011
RS           610
RA           712
W             72
G            162
Playoffs       0
Name: 51, dtype: object)
<class 'tuple'>
(52, Team         SDP
League        NL
Year        2011
RS           593
RA           611
W             71
G            162
Playoffs       0
Name: 52, dtype: object)
<class 'tuple'>
(53, Team         SEA
League        AL
Year        2011
RS           556
RA           675
W             67
G            162
Playoffs       0
Name: 53, dtype: object)
<class 'tuple'>
(54, Team         SFG
League        NL
Year        2011
RS           570
RA           578
W             86
G            162
Playoffs       0
Name: 54, dtype: object)
<class 'tuple'>
(55, Team         STL
League        NL
Year        2011
RS           762
RA           692
W             90
G            162
Playoffs       1
Name: 55, dtype: object)
<class 'tuple'>
(56, Team         TBR
League        AL
Year        2011
RS           707
RA           614
W             91
G            162
Playoffs       1
Name: 56, dtype: object)
<class 'tuple'>
(57, Team         TEX
League        AL
Year        2011
RS           855
RA           677
W             96
G            162
Playoffs       1
Name: 57, dtype: object)
<class 'tuple'>
(58, Team         TOR
League        AL
Year        2011
RS           743
RA           761
W             81
G            162
Playoffs       0
Name: 58, dtype: object)
<class 'tuple'>
(59, Team         WSN
League        NL
Year        2011
RS           624
RA           643
W             80
G            161
Playoffs       0
Name: 59, dtype: object)
<class 'tuple'>
(60, Team         ARI
League        NL
Year        2010
RS           713
RA           836
W             65
G            162
Playoffs       0
Name: 60, dtype: object)
<class 'tuple'>
(61, Team         ATL
League        NL
Year        2010
RS           738
RA           629
W             91
G            162
Playoffs       1
Name: 61, dtype: object)
<class 'tuple'>
(62, Team         BAL
League        AL
Year        2010
RS           613
RA           785
W             66
G            162
Playoffs       0
Name: 62, dtype: object)
<class 'tuple'>
(63, Team         BOS
League        AL
Year        2010
RS           818
RA           744
W             89
G            162
Playoffs       0
Name: 63, dtype: object)
<class 'tuple'>
(64, Team         CHC
League        NL
Year        2010
RS           685
RA           767
W             75
G            162
Playoffs       0
Name: 64, dtype: object)
<class 'tuple'>
(65, Team         CHW
League        AL
Year        2010
RS           752
RA           704
W             88
G            162
Playoffs       0
Name: 65, dtype: object)
<class 'tuple'>
(66, Team         CIN
League        NL
Year        2010
RS           790
RA           685
W             91
G            162
Playoffs       1
Name: 66, dtype: object)
<class 'tuple'>
(67, Team         CLE
League        AL
Year        2010
RS           646
RA           752
W             69
G            162
Playoffs       0
Name: 67, dtype: object)
<class 'tuple'>
(68, Team         COL
League        NL
Year        2010
RS           770
RA           717
W             83
G            162
Playoffs       0
Name: 68, dtype: object)
<class 'tuple'>
(69, Team         DET
League        AL
Year        2010
RS           751
RA           743
W             81
G            162
Playoffs       0
Name: 69, dtype: object)
<class 'tuple'>
(70, Team         FLA
League        NL
Year        2010
RS           719
RA           717
W             80
G            162
Playoffs       0
Name: 70, dtype: object)
<class 'tuple'>
(71, Team         HOU
League        NL
Year        2010
RS           611
RA           729
W             76
G            162
Playoffs       0
Name: 71, dtype: object)
<class 'tuple'>
(72, Team         KCR
League        AL
Year        2010
RS           676
RA           845
W             67
G            162
Playoffs       0
Name: 72, dtype: object)
<class 'tuple'>
(73, Team         LAA
League        AL
Year        2010
RS           681
RA           702
W             80
G            162
Playoffs       0
Name: 73, dtype: object)
<class 'tuple'>
(74, Team         LAD
League        NL
Year        2010
RS           667
RA           692
W             80
G            162
Playoffs       0
Name: 74, dtype: object)
<class 'tuple'>
(75, Team         MIL
League        NL
Year        2010
RS           750
RA           804
W             77
G            162
Playoffs       0
Name: 75, dtype: object)
<class 'tuple'>
(76, Team         MIN
League        AL
Year        2010
RS           781
RA           671
W             94
G            162
Playoffs       1
Name: 76, dtype: object)
<class 'tuple'>
(77, Team         NYM
League        NL
Year        2010
RS           656
RA           652
W             79
G            162
Playoffs       0
Name: 77, dtype: object)
<class 'tuple'>
(78, Team         NYY
League        AL
Year        2010
RS           859
RA           693
W             95
G            162
Playoffs       1
Name: 78, dtype: object)
<class 'tuple'>
(79, Team         OAK
League        AL
Year        2010
RS           663
RA           626
W             81
G            162
Playoffs       0
Name: 79, dtype: object)
<class 'tuple'>
(80, Team         PHI
League        NL
Year        2010
RS           772
RA           640
W             97
G            162
Playoffs       1
Name: 80, dtype: object)
<class 'tuple'>
(81, Team         PIT
League        NL
Year        2010
RS           587
RA           866
W             57
G            162
Playoffs       0
Name: 81, dtype: object)
<class 'tuple'>
(82, Team         SDP
League        NL
Year        2010
RS           665
RA           581
W             90
G            162
Playoffs       0
Name: 82, dtype: object)
<class 'tuple'>
(83, Team         SEA
League        AL
Year        2010
RS           513
RA           698
W             61
G            162
Playoffs       0
Name: 83, dtype: object)
<class 'tuple'>
(84, Team         SFG
League        NL
Year        2010
RS           697
RA           583
W             92
G            162
Playoffs       1
Name: 84, dtype: object)
<class 'tuple'>
(85, Team         STL
League        NL
Year        2010
RS           736
RA           641
W             86
G            162
Playoffs       0
Name: 85, dtype: object)
<class 'tuple'>
(86, Team         TBR
League        AL
Year        2010
RS           802
RA           649
W             96
G            162
Playoffs       1
Name: 86, dtype: object)
<class 'tuple'>
(87, Team         TEX
League        AL
Year        2010
RS           787
RA           687
W             90
G            162
Playoffs       1
Name: 87, dtype: object)
<class 'tuple'>
(88, Team         TOR
League        AL
Year        2010
RS           755
RA           728
W             85
G            162
Playoffs       0
Name: 88, dtype: object)
<class 'tuple'>
(89, Team         WSN
League        NL
Year        2010
RS           655
RA           742
W             69
G            162
Playoffs       0
Name: 89, dtype: object)
<class 'tuple'>
(90, Team         ARI
League        NL
Year        2009
RS           720
RA           782
W             70
G            162
Playoffs       0
Name: 90, dtype: object)
<class 'tuple'>
(91, Team         ATL
League        NL
Year        2009
RS           735
RA           641
W             86
G            162
Playoffs       0
Name: 91, dtype: object)
<class 'tuple'>
(92, Team         BAL
League        AL
Year        2009
RS           741
RA           876
W             64
G            162
Playoffs       0
Name: 92, dtype: object)
<class 'tuple'>
(93, Team         BOS
League        AL
Year        2009
RS           872
RA           736
W             95
G            162
Playoffs       1
Name: 93, dtype: object)
<class 'tuple'>
(94, Team         CHC
League        NL
Year        2009
RS           707
RA           672
W             83
G            161
Playoffs       0
Name: 94, dtype: object)
<class 'tuple'>
(95, Team         CHW
League        AL
Year        2009
RS           724
RA           732
W             79
G            162
Playoffs       0
Name: 95, dtype: object)
<class 'tuple'>
(96, Team         CIN
League        NL
Year        2009
RS           673
RA           723
W             78
G            162
Playoffs       0
Name: 96, dtype: object)
<class 'tuple'>
(97, Team         CLE
League        AL
Year        2009
RS           773
RA           865
W             65
G            162
Playoffs       0
Name: 97, dtype: object)
<class 'tuple'>
(98, Team         COL
League        NL
Year        2009
RS           804
RA           715
W             92
G            162
Playoffs       1
Name: 98, dtype: object)
<class 'tuple'>
(99, Team         DET
League        AL
Year        2009
RS           743
RA           745
W             86
G            163
Playoffs       0
Name: 99, dtype: object)
<class 'tuple'>
(100, Team         FLA
League        NL
Year        2009
RS           772
RA           766
W             87
G            162
Playoffs       0
Name: 100, dtype: object)
<class 'tuple'>
(101, Team         HOU
League        NL
Year        2009
RS           643
RA           770
W             74
G            162
Playoffs       0
Name: 101, dtype: object)
<class 'tuple'>
(102, Team         KCR
League        AL
Year        2009
RS           686
RA           842
W             65
G            162
Playoffs       0
Name: 102, dtype: object)
<class 'tuple'>
(103, Team         LAA
League        AL
Year        2009
RS           883
RA           761
W             97
G            162
Playoffs       1
Name: 103, dtype: object)
<class 'tuple'>
(104, Team         LAD
League        NL
Year        2009
RS           780
RA           611
W             95
G            162
Playoffs       1
Name: 104, dtype: object)
<class 'tuple'>
(105, Team         MIL
League        NL
Year        2009
RS           785
RA           818
W             80
G            162
Playoffs       0
Name: 105, dtype: object)
<class 'tuple'>
(106, Team         MIN
League        AL
Year        2009
RS           817
RA           765
W             87
G            163
Playoffs       1
Name: 106, dtype: object)
<class 'tuple'>
(107, Team         NYM
League        NL
Year        2009
RS           671
RA           757
W             70
G            162
Playoffs       0
Name: 107, dtype: object)
<class 'tuple'>
(108, Team         NYY
League        AL
Year        2009
RS           915
RA           753
W            103
G            162
Playoffs       1
Name: 108, dtype: object)
<class 'tuple'>
(109, Team         OAK
League        AL
Year        2009
RS           759
RA           761
W             75
G            162
Playoffs       0

Name: 222, dtype: object)
<class 'tuple'>
(223, Team         LAA
League        AL
Year        2005
RS           761
RA           643
W             95
G            162
Playoffs       1
Name: 223, dtype: object)
<class 'tuple'>
(224, Team         LAD
League        NL
Year        2005
RS           685
RA           755
W             71
G            162
Playoffs       0
Name: 224, dtype: object)
<class 'tuple'>
(225, Team         MIL
League        NL
Year        2005
RS           726
RA           697
W             81
G            162
Playoffs       0
Name: 225, dtype: object)
<class 'tuple'>
(226, Team         MIN
League        AL
Year        2005
RS           688
RA           662
W             83
G            162
Playoffs       0
Name: 226, dtype: object)
<class 'tuple'>
(227, Team         NYM
League        NL
Year        2005
RS           722
RA           648
W             83
G            162
Playoffs       0
Name: 227, dtype: object)
<class 'tuple'>
(228, Team         NYY
League        AL
Year        2005
RS           886
RA           789
W             95
G            162
Playoffs       1
Name: 228, dtype: object)
<class 'tuple'>
(229, Team         OAK
League        AL
Year        2005
RS           772
RA           658
W             88
G            162
Playoffs       0
Name: 229, dtype: object)
<class 'tuple'>
(230, Team         PHI
League        NL
Year        2005
RS           807
RA           726
W             88
G            162
Playoffs       0
Name: 230, dtype: object)
<class 'tuple'>
(231, Team         PIT
League        NL
Year        2005
RS           680
RA           769
W             67
G            162
Playoffs       0
Name: 231, dtype: object)
<class 'tuple'>
(232, Team         SDP
League        NL
Year        2005
RS           684
RA           726
W             82
G            162
Playoffs       1
Name: 232, dtype: object)
<class 'tuple'>
(233, Team         SEA
League        AL
Year        2005
RS           699
RA           751
W             69
G            162
Playoffs       0
Name: 233, dtype: object)
<class 'tuple'>
(234, Team         SFG
League        NL
Year        2005
RS           649
RA           745
W             75
G            162
Playoffs       0
Name: 234, dtype: object)
<class 'tuple'>
(235, Team         STL
League        NL
Year        2005
RS           805
RA           634
W            100
G            162
Playoffs       1
Name: 235, dtype: object)
<class 'tuple'>
(236, Team         TBD
League        AL
Year        2005
RS           750
RA           936
W             67
G            162
Playoffs       0
Name: 236, dtype: object)
<class 'tuple'>
(237, Team         TEX
League        AL
Year        2005
RS           865
RA           858
W             79
G            162
Playoffs       0
Name: 237, dtype: object)
<class 'tuple'>
(238, Team         TOR
League        AL
Year        2005
RS           775
RA           705
W             80
G            162
Playoffs       0
Name: 238, dtype: object)
<class 'tuple'>
(239, Team         WSN
League        NL
Year        2005
RS           639
RA           673
W             81
G            162
Playoffs       0
Name: 239, dtype: object)
<class 'tuple'>
(240, Team         ANA
League        AL
Year        2004
RS           836
RA           734
W             92
G            162
Playoffs       1
Name: 240, dtype: object)
<class 'tuple'>
(241, Team         ARI
League        NL
Year        2004
RS           615
RA           899
W             51
G            162
Playoffs       0
Name: 241, dtype: object)
<class 'tuple'>
(242, Team         ATL
League        NL
Year        2004
RS           803
RA           668
W             96
G            162
Playoffs       1
Name: 242, dtype: object)
<class 'tuple'>
(243, Team         BAL
League        AL
Year        2004
RS           842
RA           830
W             78
G            162
Playoffs       0
Name: 243, dtype: object)
<class 'tuple'>
(244, Team         BOS
League        AL
Year        2004
RS           949
RA           768
W             98
G            162
Playoffs       1
Name: 244, dtype: object)
<class 'tuple'>
(245, Team         CHC
League        NL
Year        2004
RS           789
RA           665
W             89
G            162
Playoffs       0
Name: 245, dtype: object)
<class 'tuple'>
(246, Team         CHW
League        AL
Year        2004
RS           865
RA           831
W             83
G            162
Playoffs       0
Name: 246, dtype: object)
<class 'tuple'>
(247, Team         CIN
League        NL
Year        2004
RS           750
RA           907
W             76
G            162
Playoffs       0
Name: 247, dtype: object)
<class 'tuple'>
(248, Team         CLE
League        AL
Year        2004
RS           858
RA           857
W             80
G            162
Playoffs       0
Name: 248, dtype: object)
<class 'tuple'>
(249, Team         COL
League        NL
Year        2004
RS           833
RA           923
W             68
G            162
Playoffs       0
Name: 249, dtype: object)
<class 'tuple'>
(250, Team         DET
League        AL
Year        2004
RS           827
RA           844
W             72
G            162
Playoffs       0
Name: 250, dtype: object)
<class 'tuple'>
(251, Team         FLA
League        NL
Year        2004
RS           718
RA           700
W             83
G            162
Playoffs       0
Name: 251, dtype: object)
<class 'tuple'>
(252, Team         HOU
League        NL
Year        2004
RS           803
RA           698
W             92
G            162
Playoffs       1
Name: 252, dtype: object)
<class 'tuple'>
(253, Team         KCR
League        AL
Year        2004
RS           720
RA           905
W             58
G            162
Playoffs       0
Name: 253, dtype: object)
<class 'tuple'>
(254, Team         LAD
League        NL
Year        2004
RS           761
RA           684
W             93
G            162
Playoffs       1
Name: 254, dtype: object)
<class 'tuple'>
(255, Team         MIL
League        NL
Year        2004
RS           634
RA           757
W             67
G            161
Playoffs       0
Name: 255, dtype: object)
<class 'tuple'>
(256, Team         MIN
League        AL
Year        2004
RS           780
RA           715
W             92
G            162
Playoffs       1
Name: 256, dtype: object)
<class 'tuple'>
(257, Team         MON
League        NL
Year        2004
RS           635
RA           769
W             67
G            162
Playoffs       0
Name: 257, dtype: object)
<class 'tuple'>
(258, Team         NYM
League        NL
Year        2004
RS           684
RA           731
W             71
G            162
Playoffs       0
Name: 258, dtype: object)
<class 'tuple'>
(259, Team         NYY
League        AL
Year        2004
RS           897
RA           808
W            101
G            162
Playoffs       1
Name: 259, dtype: object)
<class 'tuple'>
(260, Team         OAK
League        AL
Year        2004
RS           793
RA           742
W             91
G            162
Playoffs       0
Name: 260, dtype: object)
<class 'tuple'>
(261, Team         PHI
League        NL
Year        2004
RS           840
RA           781
W             86
G            162
Playoffs       0
Name: 261, dtype: object)
<class 'tuple'>
(262, Team         PIT
League        NL
Year        2004
RS           680
RA           744
W             72
G            161
Playoffs       0
Name: 262, dtype: object)
<class 'tuple'>
(263, Team         SDP
League        NL
Year        2004
RS           768
RA           705
W             87
G            162
Playoffs       0
Name: 263, dtype: object)
<class 'tuple'>
(264, Team         SEA
League        AL
Year        2004
RS           698
RA           823
W             63
G            162
Playoffs       0
Name: 264, dtype: object)
<class 'tuple'>
(265, Team         SFG
League        NL
Year        2004
RS           850
RA           770
W             91
G            162
Playoffs       0
Name: 265, dtype: object)
<class 'tuple'>
(266, Team         STL
League        NL
Year        2004
RS           855
RA           659
W            105
G            162
Playoffs       1
Name: 266, dtype: object)
<class 'tuple'>
(267, Team         TBD
League        AL
Year        2004
RS           714
RA           842
W             70
G            161
Playoffs       0
Name: 267, dtype: object)
<class 'tuple'>
(268, Team         TEX
League        AL
Year        2004
RS           860
RA           794
W             89
G            162
Playoffs       0
Name: 268, dtype: object)
<class 'tuple'>
(269, Team         TOR
League        AL
Year        2004
RS           719
RA           823
W             67
G            161
Playoffs       0
Name: 269, dtype: object)
<class 'tuple'>
(270, Team         ANA
League        AL
Year        2003
RS           736
RA           743
W             77
G            162
Playoffs       0
Name: 270, dtype: object)
<class 'tuple'>
(271, Team         ARI
League        NL
Year        2003
RS           717
RA           685
W             84
G            162
Playoffs       0
Name: 271, dtype: object)
<class 'tuple'>
(272, Team         ATL
League        NL
Year        2003
RS           907
RA           740
W            101
G            162
Playoffs       1
Name: 272, dtype: object)
<class 'tuple'>
(273, Team         BAL
League        AL
Year        2003
RS           743
RA           820
W             71
G            163
Playoffs       0
Name: 273, dtype: object)
<class 'tuple'>
(274, Team         BOS
League        AL
Year        2003
RS           961
RA           809
W             95
G            162
Playoffs       1
Name: 274, dtype: object)
<class 'tuple'>
(275, Team         CHC
League        NL
Year        2003
RS           724
RA           683
W             88
G            162
Playoffs       1
Name: 275, dtype: object)
<class 'tuple'>
(276, Team         CHW
League        AL
Year        2003
RS           791
RA           715
W             86
G            162
Playoffs       0
Name: 276, dtype: object)
<class 'tuple'>
(277, Team         CIN
League        NL
Year        2003
RS           694
RA           886
W             69
G            162
Playoffs       0
Name: 277, dtype: object)
<class 'tuple'>
(278, Team         CLE
League        AL
Year        2003
RS           699
RA           778
W             68
G            162
Playoffs       0
Name: 278, dtype: object)
<class 'tuple'>
(279, Team         COL
League        NL
Year        2003
RS           853
RA           892
W             74
G            162
Playoffs       0
Name: 279, dtype: object)
<class 'tuple'>
(280, Team         DET
League        AL
Year        2003
RS           591
RA           928
W             43
G            162
Playoffs       0
Name: 280, dtype: object)
<class 'tuple'>
(281, Team         FLA
League        NL
Year        2003
RS           751
RA           692
W             91
G            162
Playoffs       1
Name: 281, dtype: object)
<class 'tuple'>
(282, Team         HOU
League        NL
Year        2003
RS           805
RA           677
W             87
G            162
Playoffs       0
Name: 282, dtype: object)
<class 'tuple'>
(283, Team         KCR
League        AL
Year        2003
RS           836
RA           867
W             83
G            162
Playoffs       0
Name: 283, dtype: object)
<class 'tuple'>
(284, Team         LAD
League        NL
Year        2003
RS           574
RA           556
W             85
G            162
Playoffs       0
Name: 284, dtype: object)
<class 'tuple'>
(285, Team         MIL
League        NL
Year        2003
RS           714
RA           873
W             68
G            162
Playoffs       0
Name: 285, dtype: object)
<class 'tuple'>
(286, Team         MIN
League        AL
Year        2003
RS           801
RA           758
W             90
G            162
Playoffs       1
Name: 286, dtype: object)
<class 'tuple'>
(287, Team         MON
League        NL
Year        2003
RS           711
RA           716
W             83
G            162
Playoffs       0
Name: 287, dtype: object)
<class 'tuple'>
(288, Team         NYM
League        NL
Year        2003
RS           642
RA           754
W             66
G            161
Playoffs       0
Name: 288, dtype: object)
<class 'tuple'>
(289, Team         NYY
League        AL
Year        2003
RS           877
RA           716
W            101
G            163
Playoffs       1
Name: 289, dtype: object)
<class 'tuple'>
(290, Team         OAK
League        AL
Year        2003
RS           768
RA           643
W             96
G            162
Playoffs       1
Name: 290, dtype: object)
<class 'tuple'>
(291, Team         PHI
League        NL
Year        2003
RS           791
RA           697
W             86
G            162
Playoffs       0
Name: 291, dtype: object)
<class 'tuple'>
(292, Team         PIT
League        NL
Year        2003
RS           753
RA           801
W             75
G            162
Playoffs       0
Name: 292, dtype: object)
<class 'tuple'>
(293, Team         SDP
League        NL
Year        2003
RS           678
RA           831
W             64
G            162
Playoffs       0
Name: 293, dtype: object)
<class 'tuple'>
(294, Team         SEA
League        AL
Year        2003
RS           795
RA           637
W             93
G            162
Playoffs       0
Name: 294, dtype: object)
<class 'tuple'>
(295, Team         SFG
League        NL
Year        2003
RS           755
RA           638
W            100
G            161
Playoffs       1
Name: 295, dtype: object)
<class 'tuple'>
(296, Team         STL
League        NL
Year        2003
RS           876
RA           796
W             85
G            162
Playoffs       0
Name: 296, dtype: object)
<class 'tuple'>
(297, Team         TBD
League        AL
Year        2003
RS           715
RA           852
W             63
G            162
Playoffs       0
Name: 297, dtype: object)
<class 'tuple'>
(298, Team         TEX
League        AL
Year        2003
RS           826
RA           969
W             71
G            162
Playoffs       0
Name: 298, dtype: object)
<class 'tuple'>
(299, Team         TOR
League        AL
Year        2003
RS           894
RA           826
W             86
G            162
Playoffs       0
Name: 299, dtype: object)
<class 'tuple'>
(300, Team         ANA
League        AL
Year        2002
RS           851
RA           644
W             99
G            162
Playoffs       1
Name: 300, dtype: object)
<class 'tuple'>
(301, Team         ARI
League        NL
Year        2002
RS           819
RA           674
W             98
G            162
Playoffs       1
Name: 301, dtype: object)
<class 'tuple'>
(302, Team         ATL
League        NL
Year        2002
RS           708
RA           565
W            101
G            161
Playoffs       1
Name: 302, dtype: object)
<class 'tuple'>
(303, Team         BAL
League        AL
Year        2002
RS           667
RA           773
W             67
G            162
Playoffs       0
Name: 303, dtype: object)
<class 'tuple'>
(304, Team         BOS
League        AL
Year        2002
RS           859
RA           665
W             93
G            162
Playoffs       0
Name: 304, dtype: object)
<class 'tuple'>
(305, Team         CHC
League        NL
Year        2002
RS           706
RA           759
W             67
G            162
Playoffs       0
Name: 305, dtype: object)
<class 'tuple'>
(306, Team         CHW
League        AL
Year        2002
RS           856
RA           798
W             81
G            162
Playoffs       0
Name: 306, dtype: object)
<class 'tuple'>
(307, Team         CIN
League        NL
Year        2002
RS           709
RA           774
W             78
G            162
Playoffs       0
Name: 307, dtype: object)
<class 'tuple'>
(308, Team         CLE
League        AL
Year        2002
RS           739
RA           837
W             74
G            162
Playoffs       0
Name: 308, dtype: object)
<class 'tuple'>
(309, Team         COL
League        NL
Year        2002
RS           778
RA           898
W             73
G            162
Playoffs       0
Name: 309, dtype: object)
<class 'tuple'>
(310, Team         DET
League        AL
Year        2002
RS           575
RA           864
W             55
G            161
Playoffs       0
Name: 310, dtype: object)
<class 'tuple'>
(311, Team         FLA
League        NL
Year        2002
RS           699
RA           763
W             79
G            162
Playoffs       0
Name: 311, dtype: object)
<class 'tuple'>
(312, Team         HOU
League        NL
Year        2002
RS           749
RA           695
W             84
G            162
Playoffs       0
Name: 312, dtype: object)
<class 'tuple'>
(313, Team         KCR
League        AL
Year        2002
RS           737
RA           891
W             62
G            162
Playoffs       0
Name: 313, dtype: object)
<class 'tuple'>
(314, Team         LAD
League        NL
Year        2002
RS           713
RA           643
W             92
G            162
Playoffs       0
Name: 314, dtype: object)
<class 'tuple'>
(315, Team         MIL
League        NL
Year        2002
RS           627
RA           821
W             56
G            162
Playoffs       0
Name: 315, dtype: object)
<class 'tuple'>
(316, Team         MIN
League        AL
Year        2002
RS           768
RA           712
W             94
G            161
Playoffs       1
Name: 316, dtype: object)
<class 'tuple'>
(317, Team         MON
League        NL
Year        2002
RS           735
RA           718
W             83
G            162
Playoffs       0
Name: 317, dtype: object)
<class 'tuple'>
(318, Team         NYM
League        NL
Year        2002
RS           690
RA           703
W             75
G            161
Playoffs       0
Name: 318, dtype: object)
<class 'tuple'>
(319, Team         NYY
League        AL
Year        2002
RS           897
RA           697
W            103
G            161
Playoffs       1
Name: 319, dtype: object)
<class 'tuple'>
(320, Team         OAK
League        AL
Year        2002
RS           800
RA           654
W            103
G            162
Playoffs       1
Name: 320, dtype: object)
<class 'tuple'>
(321, Team         PHI
League        NL
Year        2002
RS           710
RA           724
W             80
G            161
Playoffs       0
Name: 321, dtype: object)
<class 'tuple'>
(322, Team         PIT
League        NL
Year        2002
RS           641
RA           730
W             72
G            161
Playoffs       0
Name: 322, dtype: object)
<class 'tuple'>
(323, Team         SDP
League        NL
Year        2002
RS           662
RA           815
W             66
G            162
Playoffs       0
Name: 323, dtype: object)
<class 'tuple'>
(324, Team         SEA
League        AL
Year        2002
RS           814
RA           699
W             93
G            162
Playoffs       0
Name: 324, dtype: object)
<class 'tuple'>
(325, Team         SFG
League        NL
Year        2002
RS           783
RA           616
W             95
G            162
Playoffs       1
Name: 325, dtype: object)
<class 'tuple'>
(326, Team         STL
League        NL
Year        2002
RS           787
RA           648
W             97
G            162
Playoffs       1
Name: 326, dtype: object)
<class 'tuple'>
(327, Team         TBD
League        AL
Year        2002
RS           673
RA           918
W             55
G            161
Playoffs       0
Name: 327, dtype: object)
<class 'tuple'>
(328, Team         TEX
League        AL
Year        2002
RS           843
RA           882
W             72
G            162
Playoffs       0
Name: 328, dtype: object)
<class 'tuple'>
(329, Team         TOR
League        AL
Year        2002
RS           813
RA           828
W             78
G            162
Playoffs       0
Name: 329, dtype: object)
<class 'tuple'>
(330, Team         ANA
League        AL
Year        2001
RS           691
RA           730
W             75
G            162
Playoffs       0
Name: 330, dtype: object)
<class 'tuple'>
(331, Team         ARI
League        NL
Year        2001
RS           818

Name: 441, dtype: object)
<class 'tuple'>
(442, Team         PIT
League        NL
Year        1998
RS           650
RA           718
W             69
G            163
Playoffs       0
Name: 442, dtype: object)
<class 'tuple'>
(443, Team         SDP
League        NL
Year        1998
RS           749
RA           635
W             98
G            162
Playoffs       1
Name: 443, dtype: object)
<class 'tuple'>
(444, Team         SEA
League        AL
Year        1998
RS           859
RA           855
W             76
G            161
Playoffs       0
Name: 444, dtype: object)
<class 'tuple'>
(445, Team         SFG
League        NL
Year        1998
RS           845
RA           739
W             89
G            163
Playoffs       0
Name: 445, dtype: object)
<class 'tuple'>
(446, Team         STL
League        NL
Year        1998
RS           810
RA           782
W             83
G            163
Playoffs       0
Name: 446, dtype: object)
<class 'tuple'>
(447, Team         TBD
League        AL
Year        1998
RS           620
RA           751
W             63
G            162
Playoffs       0
Name: 447, dtype: object)
<class 'tuple'>
(448, Team         TEX
League        AL
Year        1998
RS           940
RA           871
W             88
G            162
Playoffs       1
Name: 448, dtype: object)
<class 'tuple'>
(449, Team         TOR
League        AL
Year        1998
RS           816
RA           768
W             88
G            163
Playoffs       0
Name: 449, dtype: object)
<class 'tuple'>
(450, Team         ANA
League        AL
Year        1997
RS           829
RA           794
W             84
G            162
Playoffs       0
Name: 450, dtype: object)
<class 'tuple'>
(451, Team         ATL
League        NL
Year        1997
RS           791
RA           581
W            101
G            162
Playoffs       1
Name: 451, dtype: object)
<class 'tuple'>
(452, Team         BAL
League        AL
Year        1997
RS           812
RA           681
W             98
G            162
Playoffs       1
Name: 452, dtype: object)
<class 'tuple'>
(453, Team         BOS
League        AL
Year        1997
RS           851
RA           857
W             78
G            162
Playoffs       0
Name: 453, dtype: object)
<class 'tuple'>
(454, Team         CHC
League        NL
Year        1997
RS           687
RA           759
W             68
G            162
Playoffs       0
Name: 454, dtype: object)
<class 'tuple'>
(455, Team         CHW
League        AL
Year        1997
RS           779
RA           833
W             80
G            161
Playoffs       0
Name: 455, dtype: object)
<class 'tuple'>
(456, Team         CIN
League        NL
Year        1997
RS           651
RA           764
W             76
G            162
Playoffs       0
Name: 456, dtype: object)
<class 'tuple'>
(457, Team         CLE
League        AL
Year        1997
RS           868
RA           815
W             86
G            161
Playoffs       1
Name: 457, dtype: object)
<class 'tuple'>
(458, Team         COL
League        NL
Year        1997
RS           923
RA           908
W             83
G            162
Playoffs       0
Name: 458, dtype: object)
<class 'tuple'>
(459, Team         DET
League        AL
Year        1997
RS           784
RA           790
W             79
G            162
Playoffs       0
Name: 459, dtype: object)
<class 'tuple'>
(460, Team         FLA
League        NL
Year        1997
RS           740
RA           669
W             92
G            162
Playoffs       1
Name: 460, dtype: object)
<class 'tuple'>
(461, Team         HOU
League        NL
Year        1997
RS           777
RA           660
W             84
G            162
Playoffs       1
Name: 461, dtype: object)
<class 'tuple'>
(462, Team         KCR
League        AL
Year        1997
RS           747
RA           820
W             67
G            161
Playoffs       0
Name: 462, dtype: object)
<class 'tuple'>
(463, Team         LAD
League        NL
Year        1997
RS           742
RA           645
W             88
G            162
Playoffs       0
Name: 463, dtype: object)
<class 'tuple'>
(464, Team         MIL
League        AL
Year        1997
RS           681
RA           742
W             78
G            161
Playoffs       0
Name: 464, dtype: object)
<class 'tuple'>
(465, Team         MIN
League        AL
Year        1997
RS           772
RA           861
W             68
G            162
Playoffs       0
Name: 465, dtype: object)
<class 'tuple'>
(466, Team         MON
League        NL
Year        1997
RS           691
RA           740
W             78
G            162
Playoffs       0
Name: 466, dtype: object)
<class 'tuple'>
(467, Team         NYM
League        NL
Year        1997
RS           777
RA           709
W             88
G            162
Playoffs       0
Name: 467, dtype: object)
<class 'tuple'>
(468, Team         NYY
League        AL
Year        1997
RS           891
RA           688
W             96
G            162
Playoffs       1
Name: 468, dtype: object)
<class 'tuple'>
(469, Team         OAK
League        AL
Year        1997
RS           764
RA           946
W             65
G            162
Playoffs       0
Name: 469, dtype: object)
<class 'tuple'>
(470, Team         PHI
League        NL
Year        1997
RS           668
RA           840
W             68
G            162
Playoffs       0
Name: 470, dtype: object)
<class 'tuple'>
(471, Team         PIT
League        NL
Year        1997
RS           725
RA           760
W             79
G            162
Playoffs       0
Name: 471, dtype: object)
<class 'tuple'>
(472, Team         SDP
League        NL
Year        1997
RS           795
RA           891
W             76
G            162
Playoffs       0
Name: 472, dtype: object)
<class 'tuple'>
(473, Team         SEA
League        AL
Year        1997
RS           925
RA           833
W             90
G            162
Playoffs       1
Name: 473, dtype: object)
<class 'tuple'>
(474, Team         SFG
League        NL
Year        1997
RS           784
RA           793
W             90
G            162
Playoffs       1
Name: 474, dtype: object)
<class 'tuple'>
(475, Team         STL
League        NL
Year        1997
RS           689
RA           708
W             73
G            162
Playoffs       0
Name: 475, dtype: object)
<class 'tuple'>
(476, Team         TEX
League        AL
Year        1997
RS           807
RA           823
W             77
G            162
Playoffs       0
Name: 476, dtype: object)
<class 'tuple'>
(477, Team         TOR
League        AL
Year        1997
RS           654
RA           694
W             76
G            162
Playoffs       0
Name: 477, dtype: object)
<class 'tuple'>
(478, Team         ATL
League        NL
Year        1996
RS           773
RA           648
W             96
G            162
Playoffs       1
Name: 478, dtype: object)
<class 'tuple'>
(479, Team         BAL
League        AL
Year        1996
RS           949
RA           903
W             88
G            163
Playoffs       1
Name: 479, dtype: object)
<class 'tuple'>
(480, Team         BOS
League        AL
Year        1996
RS           928
RA           921
W             85
G            162
Playoffs       0
Name: 480, dtype: object)
<class 'tuple'>
(481, Team         CAL
League        AL
Year        1996
RS           762
RA           943
W             70
G            161
Playoffs       0
Name: 481, dtype: object)
<class 'tuple'>
(482, Team         CHC
League        NL
Year        1996
RS           772
RA           771
W             76
G            162
Playoffs       0
Name: 482, dtype: object)
<class 'tuple'>
(483, Team         CHW
League        AL
Year        1996
RS           898
RA           794
W             85
G            162
Playoffs       0
Name: 483, dtype: object)
<class 'tuple'>
(484, Team         CIN
League        NL
Year        1996
RS           778
RA           773
W             81
G            162
Playoffs       0
Name: 484, dtype: object)
<class 'tuple'>
(485, Team         CLE
League        AL
Year        1996
RS           952
RA           769
W             99
G            161
Playoffs       1
Name: 485, dtype: object)
<class 'tuple'>
(486, Team         COL
League        NL
Year        1996
RS           961
RA           964
W             83
G            162
Playoffs       0
Name: 486, dtype: object)
<class 'tuple'>
(487, Team         DET
League        AL
Year        1996
RS           783
RA          1103
W             53
G            162
Playoffs       0
Name: 487, dtype: object)
<class 'tuple'>
(488, Team         FLA
League        NL
Year        1996
RS           688
RA           703
W             80
G            162
Playoffs       0
Name: 488, dtype: object)
<class 'tuple'>
(489, Team         HOU
League        NL
Year        1996
RS           753
RA           792
W             82
G            162
Playoffs       0
Name: 489, dtype: object)
<class 'tuple'>
(490, Team         KCR
League        AL
Year        1996
RS           746
RA           786
W             75
G            161
Playoffs       0
Name: 490, dtype: object)
<class 'tuple'>
(491, Team         LAD
League        NL
Year        1996
RS           703
RA           652
W             90
G            162
Playoffs       1
Name: 491, dtype: object)
<class 'tuple'>
(492, Team         MIL
League        AL
Year        1996
RS           894
RA           899
W             80
G            162
Playoffs       0
Name: 492, dtype: object)
<class 'tuple'>
(493, Team         MIN
League        AL
Year        1996
RS           877
RA           900
W             78
G            162
Playoffs       0
Name: 493, dtype: object)
<class 'tuple'>
(494, Team         MON
League        NL
Year        1996
RS           741
RA           668
W             88
G            162
Playoffs       0
Name: 494, dtype: object)
<class 'tuple'>
(495, Team         NYM
League        NL
Year        1996
RS           746
RA           779
W             71
G            162
Playoffs       0
Name: 495, dtype: object)
<class 'tuple'>
(496, Team         NYY
League        AL
Year        1996
RS           871
RA           787
W             92
G            162
Playoffs       1
Name: 496, dtype: object)
<class 'tuple'>
(497, Team         OAK
League        AL
Year        1996
RS           861
RA           900
W             78
G            162
Playoffs       0
Name: 497, dtype: object)
<class 'tuple'>
(498, Team         PHI
League        NL
Year        1996
RS           650
RA           790
W             67
G            162
Playoffs       0
Name: 498, dtype: object)
<class 'tuple'>
(499, Team         PIT
League        NL
Year        1996
RS           776
RA           833
W             73
G            162
Playoffs       0
Name: 499, dtype: object)
<class 'tuple'>
(500, Team         SDP
League        NL
Year        1996
RS           771
RA           682
W             91
G            162
Playoffs       1
Name: 500, dtype: object)
<class 'tuple'>
(501, Team         SEA
League        AL
Year        1996
RS           993
RA           895
W             85
G            161
Playoffs       0
Name: 501, dtype: object)
<class 'tuple'>
(502, Team         SFG
League        NL
Year        1996
RS           752
RA           862
W             68
G            162
Playoffs       0
Name: 502, dtype: object)
<class 'tuple'>
(503, Team         STL
League        NL
Year        1996
RS           759
RA           706
W             88
G            162
Playoffs       1
Name: 503, dtype: object)
<class 'tuple'>
(504, Team         TEX
League        AL
Year        1996
RS           928
RA           799
W             90
G            163
Playoffs       1
Name: 504, dtype: object)
<class 'tuple'>
(505, Team         TOR
League        AL
Year        1996
RS           766
RA           809
W             74
G            162
Playoffs       0
Name: 505, dtype: object)
<class 'tuple'>
(506, Team         ATL
League        NL
Year        1993
RS           767
RA           559
W            104
G            162
Playoffs       1
Name: 506, dtype: object)
<class 'tuple'>
(507, Team         BAL
League        AL
Year        1993
RS           786
RA           745
W             85
G            162
Playoffs       0
Name: 507, dtype: object)
<class 'tuple'>
(508, Team         BOS
League        AL
Year        1993
RS           686
RA           698
W             80
G            162
Playoffs       0
Name: 508, dtype: object)
<class 'tuple'>
(509, Team         CAL
League        AL
Year        1993
RS           684
RA           770
W             71
G            162
Playoffs       0
Name: 509, dtype: object)
<class 'tuple'>
(510, Team         CHC
League        NL
Year        1993
RS           738
RA           739
W             84
G            163
Playoffs       0
Name: 510, dtype: object)
<class 'tuple'>
(511, Team         CHW
League        AL
Year        1993
RS           776
RA           664
W             94
G            162
Playoffs       1
Name: 511, dtype: object)
<class 'tuple'>
(512, Team         CIN
League        NL
Year        1993
RS           722
RA           785
W             73
G            162
Playoffs       0
Name: 512, dtype: object)
<class 'tuple'>
(513, Team         CLE
League        AL
Year        1993
RS           790
RA           813
W             76
G            162
Playoffs       0
Name: 513, dtype: object)
<class 'tuple'>
(514, Team         COL
League        NL
Year        1993
RS           758
RA           967
W             67
G            162
Playoffs       0
Name: 514, dtype: object)
<class 'tuple'>
(515, Team         DET
League        AL
Year        1993
RS           899
RA           837
W             85
G            162
Playoffs       0
Name: 515, dtype: object)
<class 'tuple'>
(516, Team         FLA
League        NL
Year        1993
RS           581
RA           724
W             64
G            162
Playoffs       0
Name: 516, dtype: object)
<class 'tuple'>
(517, Team         HOU
League        NL
Year        1993
RS           716
RA           630
W             85
G            162
Playoffs       0
Name: 517, dtype: object)
<class 'tuple'>
(518, Team         KCR
League        AL
Year        1993
RS           675
RA           694
W             84
G            162
Playoffs       0
Name: 518, dtype: object)
<class 'tuple'>
(519, Team         LAD
League        NL
Year        1993
RS           675
RA           662
W             81
G            162
Playoffs       0
Name: 519, dtype: object)
<class 'tuple'>
(520, Team         MIL
League        AL
Year        1993
RS           733
RA           792
W             69
G            162
Playoffs       0
Name: 520, dtype: object)
<class 'tuple'>
(521, Team         MIN
League        AL
Year        1993
RS           693
RA           830
W             71
G            162
Playoffs       0
Name: 521, dtype: object)
<class 'tuple'>
(522, Team         MON
League        NL
Year        1993
RS           732
RA           682
W             94
G            163
Playoffs       0
Name: 522, dtype: object)
<class 'tuple'>
(523, Team         NYM
League        NL
Year        1993
RS           672
RA           744
W             59
G            162
Playoffs       0
Name: 523, dtype: object)
<class 'tuple'>
(524, Team         NYY
League        AL
Year        1993
RS           821
RA           761
W             88
G            162
Playoffs       0
Name: 524, dtype: object)
<class 'tuple'>
(525, Team         OAK
League        AL
Year        1993
RS           715
RA           846
W             68
G            162
Playoffs       0
Name: 525, dtype: object)
<class 'tuple'>
(526, Team         PHI
League        NL
Year        1993
RS           877
RA           740
W             97
G            162
Playoffs       1
Name: 526, dtype: object)
<class 'tuple'>
(527, Team         PIT
League        NL
Year        1993
RS           707
RA           806
W             75
G            162
Playoffs       0
Name: 527, dtype: object)
<class 'tuple'>
(528, Team         SDP
League        NL
Year        1993
RS           679
RA           772
W             61
G            162
Playoffs       0
Name: 528, dtype: object)
<class 'tuple'>
(529, Team         SEA
League        AL
Year        1993
RS           734
RA           731
W             82
G            162
Playoffs       0
Name: 529, dtype: object)
<class 'tuple'>
(530, Team         SFG
League        NL
Year        1993
RS           808
RA           636
W            103
G            162
Playoffs       0
Name: 530, dtype: object)
<class 'tuple'>
(531, Team         STL
League        NL
Year        1993
RS           758
RA           744
W             87
G            162
Playoffs       0
Name: 531, dtype: object)
<class 'tuple'>
(532, Team         TEX
League        AL
Year        1993
RS           835
RA           751
W             86
G            162
Playoffs       0
Name: 532, dtype: object)
<class 'tuple'>
(533, Team         TOR
League        AL
Year        1993
RS           847
RA           742
W             95
G            162
Playoffs       1
Name: 533, dtype: object)
<class 'tuple'>
(534, Team         ATL
League        NL
Year        1992
RS           682
RA           569
W             98
G            162
Playoffs       1
Name: 534, dtype: object)
<class 'tuple'>
(535, Team         BAL
League        AL
Year        1992
RS           705
RA           656
W             89
G            162
Playoffs       0
Name: 535, dtype: object)
<class 'tuple'>
(536, Team         BOS
League        AL
Year        1992
RS           599
RA           669
W             73
G            162
Playoffs       0
Name: 536, dtype: object)
<class 'tuple'>
(537, Team         CAL
League        AL
Year        1992
RS           579
RA           671
W             72
G            162
Playoffs       0
Name: 537, dtype: object)
<class 'tuple'>
(538, Team         CHC
League        NL
Year        1992
RS           593
RA           624
W             78
G            162
Playoffs       0
Name: 538, dtype: object)
<class 'tuple'>
(539, Team         CHW
League        AL
Year        1992
RS           738
RA           690
W             86
G            162
Playoffs       0
Name: 539, dtype: object)
<class 'tuple'>
(540, Team         CIN
League        NL
Year        1992
RS           660
RA           609
W             90
G            162
Playoffs       0
Name: 540, dtype: object)
<class 'tuple'>
(541, Team         CLE
League        AL
Year        1992
RS           674
RA           746
W             76
G            162
Playoffs       0
Name: 541, dtype: object)
<class 'tuple'>
(542, Team         DET
League        AL
Year        1992
RS           791
RA           794
W             75
G            162
Playoffs       0
Name: 542, dtype: object)
<class 'tuple'>
(543, Team         HOU
League        NL
Year        1992
RS           608
RA           668
W             81
G            162
Playoffs       0
Name: 543, dtype: object)
<class 'tuple'>
(544, Team         KCR
League        AL
Year        1992
RS           610
RA           667
W             72
G            162
Playoffs       0
Name: 544, dtype: object)
<class 'tuple'>
(545, Team         LAD
League        NL
Year        1992
RS           548
RA           636
W             63
G            162
Playoffs       0
Name: 545, dtype: object)
<class 'tuple'>
(546, Team         MIL
League        AL
Year        1992
RS           740
RA           604
W             92
G            162
Playoffs       0
Name: 546, dtype: object)
<class 'tuple'>
(547, Team         MIN
League        AL
Year        1992
RS           747
RA           653
W             90
G            162
Playoffs       0
Name: 547, dtype: object)
<class 'tuple'>
(548, Team         MON
League        NL
Year        1992
RS           648
RA           581
W             87
G            162
Playoffs       0
Name: 548, dtype: object)
<class 'tuple'>
(549, Team         NYM
League        NL
Year        1992
RS           599
RA           653
W             72
G            162
Playoffs       0
Name: 549, dtype: object)
<class 'tuple'>
(550, Team         NYY
League        AL
Year        1992
RS           733

Name: 667, dtype: object)
<class 'tuple'>
(668, Team         CHC
League        NL
Year        1987
RS           720
RA           801
W             76
G            161
Playoffs       0
Name: 668, dtype: object)
<class 'tuple'>
(669, Team         CHW
League        AL
Year        1987
RS           748
RA           746
W             77
G            162
Playoffs       0
Name: 669, dtype: object)
<class 'tuple'>
(670, Team         CIN
League        NL
Year        1987
RS           783
RA           752
W             84
G            162
Playoffs       0
Name: 670, dtype: object)
<class 'tuple'>
(671, Team         CLE
League        AL
Year        1987
RS           742
RA           957
W             61
G            162
Playoffs       0
Name: 671, dtype: object)
<class 'tuple'>
(672, Team         DET
League        AL
Year        1987
RS           896
RA           735
W             98
G            162
Playoffs       1
Name: 672, dtype: object)
<class 'tuple'>
(673, Team         HOU
League        NL
Year        1987
RS           648
RA           678
W             76
G            162
Playoffs       0
Name: 673, dtype: object)
<class 'tuple'>
(674, Team         KCR
League        AL
Year        1987
RS           715
RA           691
W             83
G            162
Playoffs       0
Name: 674, dtype: object)
<class 'tuple'>
(675, Team         LAD
League        NL
Year        1987
RS           635
RA           675
W             73
G            162
Playoffs       0
Name: 675, dtype: object)
<class 'tuple'>
(676, Team         MIL
League        AL
Year        1987
RS           862
RA           817
W             91
G            162
Playoffs       0
Name: 676, dtype: object)
<class 'tuple'>
(677, Team         MIN
League        AL
Year        1987
RS           786
RA           806
W             85
G            162
Playoffs       1
Name: 677, dtype: object)
<class 'tuple'>
(678, Team         MON
League        NL
Year        1987
RS           741
RA           720
W             91
G            162
Playoffs       0
Name: 678, dtype: object)
<class 'tuple'>
(679, Team         NYM
League        NL
Year        1987
RS           823
RA           698
W             92
G            162
Playoffs       0
Name: 679, dtype: object)
<class 'tuple'>
(680, Team         NYY
League        AL
Year        1987
RS           788
RA           758
W             89
G            162
Playoffs       0
Name: 680, dtype: object)
<class 'tuple'>
(681, Team         OAK
League        AL
Year        1987
RS           806
RA           789
W             81
G            162
Playoffs       0
Name: 681, dtype: object)
<class 'tuple'>
(682, Team         PHI
League        NL
Year        1987
RS           702
RA           749
W             80
G            162
Playoffs       0
Name: 682, dtype: object)
<class 'tuple'>
(683, Team         PIT
League        NL
Year        1987
RS           723
RA           744
W             80
G            162
Playoffs       0
Name: 683, dtype: object)
<class 'tuple'>
(684, Team         SDP
League        NL
Year        1987
RS           668
RA           763
W             65
G            162
Playoffs       0
Name: 684, dtype: object)
<class 'tuple'>
(685, Team         SEA
League        AL
Year        1987
RS           760
RA           801
W             78
G            162
Playoffs       0
Name: 685, dtype: object)
<class 'tuple'>
(686, Team         SFG
League        NL
Year        1987
RS           783
RA           669
W             90
G            162
Playoffs       1
Name: 686, dtype: object)
<class 'tuple'>
(687, Team         STL
League        NL
Year        1987
RS           798
RA           693
W             95
G            162
Playoffs       1
Name: 687, dtype: object)
<class 'tuple'>
(688, Team         TEX
League        AL
Year        1987
RS           823
RA           849
W             75
G            162
Playoffs       0
Name: 688, dtype: object)
<class 'tuple'>
(689, Team         TOR
League        AL
Year        1987
RS           845
RA           655
W             96
G            162
Playoffs       0
Name: 689, dtype: object)
<class 'tuple'>
(690, Team         ATL
League        NL
Year        1986
RS           615
RA           719
W             72
G            161
Playoffs       0
Name: 690, dtype: object)
<class 'tuple'>
(691, Team         BAL
League        AL
Year        1986
RS           708
RA           760
W             73
G            162
Playoffs       0
Name: 691, dtype: object)
<class 'tuple'>
(692, Team         BOS
League        AL
Year        1986
RS           794
RA           696
W             95
G            161
Playoffs       1
Name: 692, dtype: object)
<class 'tuple'>
(693, Team         CAL
League        AL
Year        1986
RS           786
RA           684
W             92
G            162
Playoffs       1
Name: 693, dtype: object)
<class 'tuple'>
(694, Team         CHC
League        NL
Year        1986
RS           680
RA           781
W             70
G            160
Playoffs       0
Name: 694, dtype: object)
<class 'tuple'>
(695, Team         CHW
League        AL
Year        1986
RS           644
RA           699
W             72
G            162
Playoffs       0
Name: 695, dtype: object)
<class 'tuple'>
(696, Team         CIN
League        NL
Year        1986
RS           732
RA           717
W             86
G            162
Playoffs       0
Name: 696, dtype: object)
<class 'tuple'>
(697, Team         CLE
League        AL
Year        1986
RS           831
RA           841
W             84
G            163
Playoffs       0
Name: 697, dtype: object)
<class 'tuple'>
(698, Team         DET
League        AL
Year        1986
RS           798
RA           714
W             87
G            162
Playoffs       0
Name: 698, dtype: object)
<class 'tuple'>
(699, Team         HOU
League        NL
Year        1986
RS           654
RA           569
W             96
G            162
Playoffs       1
Name: 699, dtype: object)
<class 'tuple'>
(700, Team         KCR
League        AL
Year        1986
RS           654
RA           673
W             76
G            162
Playoffs       0
Name: 700, dtype: object)
<class 'tuple'>
(701, Team         LAD
League        NL
Year        1986
RS           638
RA           679
W             73
G            162
Playoffs       0
Name: 701, dtype: object)
<class 'tuple'>
(702, Team         MIL
League        AL
Year        1986
RS           667
RA           734
W             77
G            161
Playoffs       0
Name: 702, dtype: object)
<class 'tuple'>
(703, Team         MIN
League        AL
Year        1986
RS           741
RA           839
W             71
G            162
Playoffs       0
Name: 703, dtype: object)
<class 'tuple'>
(704, Team         MON
League        NL
Year        1986
RS           637
RA           688
W             78
G            161
Playoffs       0
Name: 704, dtype: object)
<class 'tuple'>
(705, Team         NYM
League        NL
Year        1986
RS           783
RA           578
W            108
G            162
Playoffs       1
Name: 705, dtype: object)
<class 'tuple'>
(706, Team         NYY
League        AL
Year        1986
RS           797
RA           738
W             90
G            162
Playoffs       0
Name: 706, dtype: object)
<class 'tuple'>
(707, Team         OAK
League        AL
Year        1986
RS           731
RA           760
W             76
G            162
Playoffs       0
Name: 707, dtype: object)
<class 'tuple'>
(708, Team         PHI
League        NL
Year        1986
RS           739
RA           713
W             86
G            161
Playoffs       0
Name: 708, dtype: object)
<class 'tuple'>
(709, Team         PIT
League        NL
Year        1986
RS           663
RA           700
W             64
G            162
Playoffs       0
Name: 709, dtype: object)
<class 'tuple'>
(710, Team         SDP
League        NL
Year        1986
RS           656
RA           723
W             74
G            162
Playoffs       0
Name: 710, dtype: object)
<class 'tuple'>
(711, Team         SEA
League        AL
Year        1986
RS           718
RA           835
W             67
G            162
Playoffs       0
Name: 711, dtype: object)
<class 'tuple'>
(712, Team         SFG
League        NL
Year        1986
RS           698
RA           618
W             83
G            162
Playoffs       0
Name: 712, dtype: object)
<class 'tuple'>
(713, Team         STL
League        NL
Year        1986
RS           601
RA           611
W             79
G            161
Playoffs       0
Name: 713, dtype: object)
<class 'tuple'>
(714, Team         TEX
League        AL
Year        1986
RS           771
RA           743
W             87
G            162
Playoffs       0
Name: 714, dtype: object)
<class 'tuple'>
(715, Team         TOR
League        AL
Year        1986
RS           809
RA           733
W             86
G            163
Playoffs       0
Name: 715, dtype: object)
<class 'tuple'>
(716, Team         ATL
League        NL
Year        1985
RS           632
RA           781
W             66
G            162
Playoffs       0
Name: 716, dtype: object)
<class 'tuple'>
(717, Team         BAL
League        AL
Year        1985
RS           818
RA           764
W             83
G            161
Playoffs       0
Name: 717, dtype: object)
<class 'tuple'>
(718, Team         BOS
League        AL
Year        1985
RS           800
RA           720
W             81
G            163
Playoffs       0
Name: 718, dtype: object)
<class 'tuple'>
(719, Team         CAL
League        AL
Year        1985
RS           732
RA           703
W             90
G            162
Playoffs       0
Name: 719, dtype: object)
<class 'tuple'>
(720, Team         CHC
League        NL
Year        1985
RS           686
RA           729
W             77
G            162
Playoffs       0
Name: 720, dtype: object)
<class 'tuple'>
(721, Team         CHW
League        AL
Year        1985
RS           736
RA           720
W             85
G            163
Playoffs       0
Name: 721, dtype: object)
<class 'tuple'>
(722, Team         CIN
League        NL
Year        1985
RS           677
RA           666
W             89
G            162
Playoffs       0
Name: 722, dtype: object)
<class 'tuple'>
(723, Team         CLE
League        AL
Year        1985
RS           729
RA           861
W             60
G            162
Playoffs       0
Name: 723, dtype: object)
<class 'tuple'>
(724, Team         DET
League        AL
Year        1985
RS           729
RA           688
W             84
G            161
Playoffs       0
Name: 724, dtype: object)
<class 'tuple'>
(725, Team         HOU
League        NL
Year        1985
RS           706
RA           691
W             83
G            162
Playoffs       0
Name: 725, dtype: object)
<class 'tuple'>
(726, Team         KCR
League        AL
Year        1985
RS           687
RA           639
W             91
G            162
Playoffs       1
Name: 726, dtype: object)
<class 'tuple'>
(727, Team         LAD
League        NL
Year        1985
RS           682
RA           579
W             95
G            162
Playoffs       1
Name: 727, dtype: object)
<class 'tuple'>
(728, Team         MIL
League        AL
Year        1985
RS           690
RA           802
W             71
G            161
Playoffs       0
Name: 728, dtype: object)
<class 'tuple'>
(729, Team         MIN
League        AL
Year        1985
RS           705
RA           782
W             77
G            162
Playoffs       0
Name: 729, dtype: object)
<class 'tuple'>
(730, Team         MON
League        NL
Year        1985
RS           633
RA           636
W             84
G            161
Playoffs       0
Name: 730, dtype: object)
<class 'tuple'>
(731, Team         NYM
League        NL
Year        1985
RS           695
RA           568
W             98
G            162
Playoffs       0
Name: 731, dtype: object)
<class 'tuple'>
(732, Team         NYY
League        AL
Year        1985
RS           839
RA           660
W             97
G            161
Playoffs       0
Name: 732, dtype: object)
<class 'tuple'>
(733, Team         OAK
League        AL
Year        1985
RS           757
RA           787
W             77
G            162
Playoffs       0
Name: 733, dtype: object)
<class 'tuple'>
(734, Team         PHI
League        NL
Year        1985
RS           667
RA           673
W             75
G            162
Playoffs       0
Name: 734, dtype: object)
<class 'tuple'>
(735, Team         PIT
League        NL
Year        1985
RS           568
RA           708
W             57
G            161
Playoffs       0
Name: 735, dtype: object)
<class 'tuple'>
(736, Team         SDP
League        NL
Year        1985
RS           650
RA           622
W             83
G            162
Playoffs       0
Name: 736, dtype: object)
<class 'tuple'>
(737, Team         SEA
League        AL
Year        1985
RS           719
RA           818
W             74
G            162
Playoffs       0
Name: 737, dtype: object)
<class 'tuple'>
(738, Team         SFG
League        NL
Year        1985
RS           556
RA           674
W             62
G            162
Playoffs       0
Name: 738, dtype: object)
<class 'tuple'>
(739, Team         STL
League        NL
Year        1985
RS           747
RA           572
W            101
G            162
Playoffs       1
Name: 739, dtype: object)
<class 'tuple'>
(740, Team         TEX
League        AL
Year        1985
RS           617
RA           785
W             62
G            161
Playoffs       0
Name: 740, dtype: object)
<class 'tuple'>
(741, Team         TOR
League        AL
Year        1985
RS           759
RA           588
W             99
G            161
Playoffs       1
Name: 741, dtype: object)
<class 'tuple'>
(742, Team         ATL
League        NL
Year        1984
RS           632
RA           655
W             80
G            162
Playoffs       0
Name: 742, dtype: object)
<class 'tuple'>
(743, Team         BAL
League        AL
Year        1984
RS           681
RA           667
W             85
G            162
Playoffs       0
Name: 743, dtype: object)
<class 'tuple'>
(744, Team         BOS
League        AL
Year        1984
RS           810
RA           764
W             86
G            162
Playoffs       0
Name: 744, dtype: object)
<class 'tuple'>
(745, Team         CAL
League        AL
Year        1984
RS           696
RA           697
W             81
G            162
Playoffs       0
Name: 745, dtype: object)
<class 'tuple'>
(746, Team         CHC
League        NL
Year        1984
RS           762
RA           658
W             96
G            161
Playoffs       1
Name: 746, dtype: object)
<class 'tuple'>
(747, Team         CHW
League        AL
Year        1984
RS           679
RA           736
W             74
G            162
Playoffs       0
Name: 747, dtype: object)
<class 'tuple'>
(748, Team         CIN
League        NL
Year        1984
RS           627
RA           747
W             70
G            162
Playoffs       0
Name: 748, dtype: object)
<class 'tuple'>
(749, Team         CLE
League        AL
Year        1984
RS           761
RA           766
W             75
G            163
Playoffs       0
Name: 749, dtype: object)
<class 'tuple'>
(750, Team         DET
League        AL
Year        1984
RS           829
RA           643
W            104
G            162
Playoffs       1
Name: 750, dtype: object)
<class 'tuple'>
(751, Team         HOU
League        NL
Year        1984
RS           693
RA           630
W             80
G            162
Playoffs       0
Name: 751, dtype: object)
<class 'tuple'>
(752, Team         KCR
League        AL
Year        1984
RS           673
RA           686
W             84
G            162
Playoffs       1
Name: 752, dtype: object)
<class 'tuple'>
(753, Team         LAD
League        NL
Year        1984
RS           580
RA           600
W             79
G            162
Playoffs       0
Name: 753, dtype: object)
<class 'tuple'>
(754, Team         MIL
League        AL
Year        1984
RS           641
RA           734
W             67
G            161
Playoffs       0
Name: 754, dtype: object)
<class 'tuple'>
(755, Team         MIN
League        AL
Year        1984
RS           673
RA           675
W             81
G            162
Playoffs       0
Name: 755, dtype: object)
<class 'tuple'>
(756, Team         MON
League        NL
Year        1984
RS           593
RA           585
W             78
G            161
Playoffs       0
Name: 756, dtype: object)
<class 'tuple'>
(757, Team         NYM
League        NL
Year        1984
RS           652
RA           676
W             90
G            162
Playoffs       0
Name: 757, dtype: object)
<class 'tuple'>
(758, Team         NYY
League        AL
Year        1984
RS           758
RA           679
W             87
G            162
Playoffs       0
Name: 758, dtype: object)
<class 'tuple'>
(759, Team         OAK
League        AL
Year        1984
RS           738
RA           796
W             77
G            162
Playoffs       0
Name: 759, dtype: object)
<class 'tuple'>
(760, Team         PHI
League        NL
Year        1984
RS           720
RA           690
W             81
G            162
Playoffs       0
Name: 760, dtype: object)
<class 'tuple'>
(761, Team         PIT
League        NL
Year        1984
RS           615
RA           567
W             75
G            162
Playoffs       0
Name: 761, dtype: object)
<class 'tuple'>
(762, Team         SDP
League        NL
Year        1984
RS           686
RA           634
W             92
G            162
Playoffs       1
Name: 762, dtype: object)
<class 'tuple'>
(763, Team         SEA
League        AL
Year        1984
RS           682
RA           774
W             74
G            162
Playoffs       0
Name: 763, dtype: object)
<class 'tuple'>
(764, Team         SFG
League        NL
Year        1984
RS           682
RA           807
W             66
G            162
Playoffs       0
Name: 764, dtype: object)
<class 'tuple'>
(765, Team         STL
League        NL
Year        1984
RS           652
RA           645
W             84
G            162
Playoffs       0
Name: 765, dtype: object)
<class 'tuple'>
(766, Team         TEX
League        AL
Year        1984
RS           656
RA           714
W             69
G            161
Playoffs       0
Name: 766, dtype: object)
<class 'tuple'>
(767, Team         TOR
League        AL
Year        1984
RS           750
RA           696
W             89
G            163
Playoffs       0
Name: 767, dtype: object)
<class 'tuple'>
(768, Team         ATL
League        NL
Year        1983
RS           746
RA           640
W             88
G            162
Playoffs       0
Name: 768, dtype: object)
<class 'tuple'>
(769, Team         BAL
League        AL
Year        1983
RS           799
RA           652
W             98
G            162
Playoffs       1
Name: 769, dtype: object)
<class 'tuple'>
(770, Team         BOS
League        AL
Year        1983
RS           724
RA           775
W             78
G            162
Playoffs       0
Name: 770, dtype: object)
<class 'tuple'>
(771, Team         CAL
League        AL
Year        1983
RS           722
RA           779
W             70
G            162
Playoffs       0
Name: 771, dtype: object)
<class 'tuple'>
(772, Team         CHC
League        NL
Year        1983
RS           701
RA           719
W             71
G            162
Playoffs       0
Name: 772, dtype: object)
<class 'tuple'>
(773, Team         CHW
League        AL
Year        1983
RS           800
RA           650
W             99
G            162
Playoffs       1
Name: 773, dtype: object)
<class 'tuple'>
(774, Team         CIN
League        NL
Year        1983
RS           623
RA           710
W             74
G            162
Playoffs       0
Name: 774, dtype: object)
<class 'tuple'>
(775, Team         CLE
League        AL
Year        1983
RS           704
RA           785
W             70
G            162
Playoffs       0
Name: 775, dtype: object)
<class 'tuple'>
(776, Team         DET
League        AL
Year        1983
RS           789

Name: 894, dtype: object)
<class 'tuple'>
(895, Team         STL
League        NL
Year        1978
RS           600
RA           657
W             69
G            162
Playoffs       0
Name: 895, dtype: object)
<class 'tuple'>
(896, Team         TEX
League        AL
Year        1978
RS           692
RA           632
W             87
G            162
Playoffs       0
Name: 896, dtype: object)
<class 'tuple'>
(897, Team         TOR
League        AL
Year        1978
RS           590
RA           775
W             59
G            161
Playoffs       0
Name: 897, dtype: object)
<class 'tuple'>
(898, Team         ATL
League        NL
Year        1977
RS           678
RA           895
W             61
G            162
Playoffs       0
Name: 898, dtype: object)
<class 'tuple'>
(899, Team         BAL
League        AL
Year        1977
RS           719
RA           653
W             97
G            161
Playoffs       0
Name: 899, dtype: object)
<class 'tuple'>
(900, Team         BOS
League        AL
Year        1977
RS           859
RA           712
W             97
G            161
Playoffs       0
Name: 900, dtype: object)
<class 'tuple'>
(901, Team         CAL
League        AL
Year        1977
RS           675
RA           695
W             74
G            162
Playoffs       0
Name: 901, dtype: object)
<class 'tuple'>
(902, Team         CHC
League        NL
Year        1977
RS           692
RA           739
W             81
G            162
Playoffs       0
Name: 902, dtype: object)
<class 'tuple'>
(903, Team         CHW
League        AL
Year        1977
RS           844
RA           771
W             90
G            162
Playoffs       0
Name: 903, dtype: object)
<class 'tuple'>
(904, Team         CIN
League        NL
Year        1977
RS           802
RA           725
W             88
G            162
Playoffs       0
Name: 904, dtype: object)
<class 'tuple'>
(905, Team         CLE
League        AL
Year        1977
RS           676
RA           739
W             71
G            161
Playoffs       0
Name: 905, dtype: object)
<class 'tuple'>
(906, Team         DET
League        AL
Year        1977
RS           714
RA           751
W             74
G            162
Playoffs       0
Name: 906, dtype: object)
<class 'tuple'>
(907, Team         HOU
League        NL
Year        1977
RS           680
RA           650
W             81
G            162
Playoffs       0
Name: 907, dtype: object)
<class 'tuple'>
(908, Team         KCR
League        AL
Year        1977
RS           822
RA           651
W            102
G            162
Playoffs       1
Name: 908, dtype: object)
<class 'tuple'>
(909, Team         LAD
League        NL
Year        1977
RS           769
RA           582
W             98
G            162
Playoffs       1
Name: 909, dtype: object)
<class 'tuple'>
(910, Team         MIL
League        AL
Year        1977
RS           639
RA           765
W             67
G            162
Playoffs       0
Name: 910, dtype: object)
<class 'tuple'>
(911, Team         MIN
League        AL
Year        1977
RS           867
RA           776
W             84
G            161
Playoffs       0
Name: 911, dtype: object)
<class 'tuple'>
(912, Team         MON
League        NL
Year        1977
RS           665
RA           736
W             75
G            162
Playoffs       0
Name: 912, dtype: object)
<class 'tuple'>
(913, Team         NYM
League        NL
Year        1977
RS           587
RA           663
W             64
G            162
Playoffs       0
Name: 913, dtype: object)
<class 'tuple'>
(914, Team         NYY
League        AL
Year        1977
RS           831
RA           651
W            100
G            162
Playoffs       1
Name: 914, dtype: object)
<class 'tuple'>
(915, Team         OAK
League        AL
Year        1977
RS           605
RA           749
W             63
G            161
Playoffs       0
Name: 915, dtype: object)
<class 'tuple'>
(916, Team         PHI
League        NL
Year        1977
RS           847
RA           668
W            101
G            162
Playoffs       1
Name: 916, dtype: object)
<class 'tuple'>
(917, Team         PIT
League        NL
Year        1977
RS           734
RA           665
W             96
G            162
Playoffs       0
Name: 917, dtype: object)
<class 'tuple'>
(918, Team         SDP
League        NL
Year        1977
RS           692
RA           834
W             69
G            162
Playoffs       0
Name: 918, dtype: object)
<class 'tuple'>
(919, Team         SEA
League        AL
Year        1977
RS           624
RA           855
W             64
G            162
Playoffs       0
Name: 919, dtype: object)
<class 'tuple'>
(920, Team         SFG
League        NL
Year        1977
RS           673
RA           711
W             75
G            162
Playoffs       0
Name: 920, dtype: object)
<class 'tuple'>
(921, Team         STL
League        NL
Year        1977
RS           737
RA           688
W             83
G            162
Playoffs       0
Name: 921, dtype: object)
<class 'tuple'>
(922, Team         TEX
League        AL
Year        1977
RS           767
RA           657
W             94
G            162
Playoffs       0
Name: 922, dtype: object)
<class 'tuple'>
(923, Team         TOR
League        AL
Year        1977
RS           605
RA           822
W             54
G            161
Playoffs       0
Name: 923, dtype: object)
<class 'tuple'>
(924, Team         ATL
League        NL
Year        1976
RS           620
RA           700
W             70
G            162
Playoffs       0
Name: 924, dtype: object)
<class 'tuple'>
(925, Team         BAL
League        AL
Year        1976
RS           619
RA           598
W             88
G            162
Playoffs       0
Name: 925, dtype: object)
<class 'tuple'>
(926, Team         BOS
League        AL
Year        1976
RS           716
RA           660
W             83
G            162
Playoffs       0
Name: 926, dtype: object)
<class 'tuple'>
(927, Team         CAL
League        AL
Year        1976
RS           550
RA           631
W             76
G            162
Playoffs       0
Name: 927, dtype: object)
<class 'tuple'>
(928, Team         CHC
League        NL
Year        1976
RS           611
RA           728
W             75
G            162
Playoffs       0
Name: 928, dtype: object)
<class 'tuple'>
(929, Team         CHW
League        AL
Year        1976
RS           586
RA           745
W             64
G            161
Playoffs       0
Name: 929, dtype: object)
<class 'tuple'>
(930, Team         CIN
League        NL
Year        1976
RS           857
RA           633
W            102
G            162
Playoffs       1
Name: 930, dtype: object)
<class 'tuple'>
(931, Team         CLE
League        AL
Year        1976
RS           615
RA           615
W             81
G            159
Playoffs       0
Name: 931, dtype: object)
<class 'tuple'>
(932, Team         DET
League        AL
Year        1976
RS           609
RA           709
W             74
G            161
Playoffs       0
Name: 932, dtype: object)
<class 'tuple'>
(933, Team         HOU
League        NL
Year        1976
RS           625
RA           657
W             80
G            162
Playoffs       0
Name: 933, dtype: object)
<class 'tuple'>
(934, Team         KCR
League        AL
Year        1976
RS           713
RA           611
W             90
G            162
Playoffs       1
Name: 934, dtype: object)
<class 'tuple'>
(935, Team         LAD
League        NL
Year        1976
RS           608
RA           543
W             92
G            162
Playoffs       0
Name: 935, dtype: object)
<class 'tuple'>
(936, Team         MIL
League        AL
Year        1976
RS           570
RA           655
W             66
G            161
Playoffs       0
Name: 936, dtype: object)
<class 'tuple'>
(937, Team         MIN
League        AL
Year        1976
RS           743
RA           704
W             85
G            162
Playoffs       0
Name: 937, dtype: object)
<class 'tuple'>
(938, Team         MON
League        NL
Year        1976
RS           531
RA           734
W             55
G            162
Playoffs       0
Name: 938, dtype: object)
<class 'tuple'>
(939, Team         NYM
League        NL
Year        1976
RS           615
RA           538
W             86
G            162
Playoffs       0
Name: 939, dtype: object)
<class 'tuple'>
(940, Team         NYY
League        AL
Year        1976
RS           730
RA           575
W             97
G            159
Playoffs       1
Name: 940, dtype: object)
<class 'tuple'>
(941, Team         OAK
League        AL
Year        1976
RS           686
RA           598
W             87
G            161
Playoffs       0
Name: 941, dtype: object)
<class 'tuple'>
(942, Team         PHI
League        NL
Year        1976
RS           770
RA           557
W            101
G            162
Playoffs       1
Name: 942, dtype: object)
<class 'tuple'>
(943, Team         PIT
League        NL
Year        1976
RS           708
RA           630
W             92
G            162
Playoffs       0
Name: 943, dtype: object)
<class 'tuple'>
(944, Team         SDP
League        NL
Year        1976
RS           570
RA           662
W             73
G            162
Playoffs       0
Name: 944, dtype: object)
<class 'tuple'>
(945, Team         SFG
League        NL
Year        1976
RS           595
RA           686
W             74
G            162
Playoffs       0
Name: 945, dtype: object)
<class 'tuple'>
(946, Team         STL
League        NL
Year        1976
RS           629
RA           671
W             72
G            162
Playoffs       0
Name: 946, dtype: object)
<class 'tuple'>
(947, Team         TEX
League        AL
Year        1976
RS           616
RA           652
W             76
G            162
Playoffs       0
Name: 947, dtype: object)
<class 'tuple'>
(948, Team         ATL
League        NL
Year        1975
RS           583
RA           739
W             67
G            161
Playoffs       0
Name: 948, dtype: object)
<class 'tuple'>
(949, Team         BAL
League        AL
Year        1975
RS           682
RA           553
W             90
G            159
Playoffs       0
Name: 949, dtype: object)
<class 'tuple'>
(950, Team         BOS
League        AL
Year        1975
RS           796
RA           709
W             95
G            160
Playoffs       1
Name: 950, dtype: object)
<class 'tuple'>
(951, Team         CAL
League        AL
Year        1975
RS           628
RA           723
W             72
G            161
Playoffs       0
Name: 951, dtype: object)
<class 'tuple'>
(952, Team         CHC
League        NL
Year        1975
RS           712
RA           827
W             75
G            162
Playoffs       0
Name: 952, dtype: object)
<class 'tuple'>
(953, Team         CHW
League        AL
Year        1975
RS           655
RA           703
W             75
G            161
Playoffs       0
Name: 953, dtype: object)
<class 'tuple'>
(954, Team         CIN
League        NL
Year        1975
RS           840
RA           586
W            108
G            162
Playoffs       1
Name: 954, dtype: object)
<class 'tuple'>
(955, Team         CLE
League        AL
Year        1975
RS           688
RA           703
W             79
G            159
Playoffs       0
Name: 955, dtype: object)
<class 'tuple'>
(956, Team         DET
League        AL
Year        1975
RS           570
RA           786
W             57
G            159
Playoffs       0
Name: 956, dtype: object)
<class 'tuple'>
(957, Team         HOU
League        NL
Year        1975
RS           664
RA           711
W             64
G            162
Playoffs       0
Name: 957, dtype: object)
<class 'tuple'>
(958, Team         KCR
League        AL
Year        1975
RS           710
RA           649
W             91
G            162
Playoffs       0
Name: 958, dtype: object)
<class 'tuple'>
(959, Team         LAD
League        NL
Year        1975
RS           648
RA           534
W             88
G            162
Playoffs       0
Name: 959, dtype: object)
<class 'tuple'>
(960, Team         MIL
League        AL
Year        1975
RS           675
RA           792
W             68
G            162
Playoffs       0
Name: 960, dtype: object)
<class 'tuple'>
(961, Team         MIN
League        AL
Year        1975
RS           724
RA           736
W             76
G            159
Playoffs       0
Name: 961, dtype: object)
<class 'tuple'>
(962, Team         MON
League        NL
Year        1975
RS           601
RA           690
W             75
G            162
Playoffs       0
Name: 962, dtype: object)
<class 'tuple'>
(963, Team         NYM
League        NL
Year        1975
RS           646
RA           625
W             82
G            162
Playoffs       0
Name: 963, dtype: object)
<class 'tuple'>
(964, Team         NYY
League        AL
Year        1975
RS           681
RA           588
W             83
G            160
Playoffs       0
Name: 964, dtype: object)
<class 'tuple'>
(965, Team         OAK
League        AL
Year        1975
RS           758
RA           606
W             98
G            162
Playoffs       1
Name: 965, dtype: object)
<class 'tuple'>
(966, Team         PHI
League        NL
Year        1975
RS           735
RA           694
W             86
G            162
Playoffs       0
Name: 966, dtype: object)
<class 'tuple'>
(967, Team         PIT
League        NL
Year        1975
RS           712
RA           565
W             92
G            161
Playoffs       1
Name: 967, dtype: object)
<class 'tuple'>
(968, Team         SDP
League        NL
Year        1975
RS           552
RA           683
W             71
G            162
Playoffs       0
Name: 968, dtype: object)
<class 'tuple'>
(969, Team         SFG
League        NL
Year        1975
RS           659
RA           671
W             80
G            161
Playoffs       0
Name: 969, dtype: object)
<class 'tuple'>
(970, Team         STL
League        NL
Year        1975
RS           662
RA           689
W             82
G            163
Playoffs       0
Name: 970, dtype: object)
<class 'tuple'>
(971, Team         TEX
League        AL
Year        1975
RS           714
RA           733
W             79
G            162
Playoffs       0
Name: 971, dtype: object)
<class 'tuple'>
(972, Team         ATL
League        NL
Year        1974
RS           661
RA           563
W             88
G            163
Playoffs       0
Name: 972, dtype: object)
<class 'tuple'>
(973, Team         BAL
League        AL
Year        1974
RS           659
RA           612
W             91
G            162
Playoffs       1
Name: 973, dtype: object)
<class 'tuple'>
(974, Team         BOS
League        AL
Year        1974
RS           696
RA           661
W             84
G            162
Playoffs       0
Name: 974, dtype: object)
<class 'tuple'>
(975, Team         CAL
League        AL
Year        1974
RS           618
RA           657
W             68
G            163
Playoffs       0
Name: 975, dtype: object)
<class 'tuple'>
(976, Team         CHC
League        NL
Year        1974
RS           669
RA           826
W             66
G            162
Playoffs       0
Name: 976, dtype: object)
<class 'tuple'>
(977, Team         CHW
League        AL
Year        1974
RS           684
RA           721
W             80
G            163
Playoffs       0
Name: 977, dtype: object)
<class 'tuple'>
(978, Team         CIN
League        NL
Year        1974
RS           776
RA           631
W             98
G            163
Playoffs       0
Name: 978, dtype: object)
<class 'tuple'>
(979, Team         CLE
League        AL
Year        1974
RS           662
RA           694
W             77
G            162
Playoffs       0
Name: 979, dtype: object)
<class 'tuple'>
(980, Team         DET
League        AL
Year        1974
RS           620
RA           768
W             72
G            162
Playoffs       0
Name: 980, dtype: object)
<class 'tuple'>
(981, Team         HOU
League        NL
Year        1974
RS           653
RA           632
W             81
G            162
Playoffs       0
Name: 981, dtype: object)
<class 'tuple'>
(982, Team         KCR
League        AL
Year        1974
RS           667
RA           662
W             77
G            162
Playoffs       0
Name: 982, dtype: object)
<class 'tuple'>
(983, Team         LAD
League        NL
Year        1974
RS           798
RA           561
W            102
G            162
Playoffs       1
Name: 983, dtype: object)
<class 'tuple'>
(984, Team         MIL
League        AL
Year        1974
RS           647
RA           660
W             76
G            162
Playoffs       0
Name: 984, dtype: object)
<class 'tuple'>
(985, Team         MIN
League        AL
Year        1974
RS           673
RA           669
W             82
G            163
Playoffs       0
Name: 985, dtype: object)
<class 'tuple'>
(986, Team         MON
League        NL
Year        1974
RS           662
RA           657
W             79
G            161
Playoffs       0
Name: 986, dtype: object)
<class 'tuple'>
(987, Team         NYM
League        NL
Year        1974
RS           572
RA           646
W             71
G            162
Playoffs       0
Name: 987, dtype: object)
<class 'tuple'>
(988, Team         NYY
League        AL
Year        1974
RS           671
RA           623
W             89
G            162
Playoffs       0
Name: 988, dtype: object)
<class 'tuple'>
(989, Team         OAK
League        AL
Year        1974
RS           689
RA           551
W             90
G            162
Playoffs       1
Name: 989, dtype: object)
<class 'tuple'>
(990, Team         PHI
League        NL
Year        1974
RS           676
RA           701
W             80
G            162
Playoffs       0
Name: 990, dtype: object)
<class 'tuple'>
(991, Team         PIT
League        NL
Year        1974
RS           751
RA           657
W             88
G            162
Playoffs       1
Name: 991, dtype: object)
<class 'tuple'>
(992, Team         SDP
League        NL
Year        1974
RS           541
RA           830
W             60
G            162
Playoffs       0
Name: 992, dtype: object)
<class 'tuple'>
(993, Team         SFG
League        NL
Year        1974
RS           634
RA           723
W             72
G            162
Playoffs       0
Name: 993, dtype: object)
<class 'tuple'>
(994, Team         STL
League        NL
Year        1974
RS           677
RA           643
W             86
G            161
Playoffs       0
Name: 994, dtype: object)
<class 'tuple'>
(995, Team         TEX
League        AL
Year        1974
RS           690
RA           698
W             83
G            161
Playoffs       0
Name: 995, dtype: object)
<class 'tuple'>
(996, Team         ATL
League        NL
Year        1973
RS           799
RA           774
W             76
G            162
Playoffs       0
Name: 996, dtype: object)
<class 'tuple'>
(997, Team         BAL
League        AL
Year        1973
RS           754
RA           561
W             97
G            162
Playoffs       1
Name: 997, dtype: object)
<class 'tuple'>
(998, Team         BOS
League        AL
Year        1973
RS           738
RA           647
W             89
G            162
Playoffs       0
Name: 998, dtype: object)
<class 'tuple'>
(999, Team         CAL
League        AL
Year        1973
RS           629
RA           657
W             79
G            162
Playoffs       0
Name: 999, dtype: object)
<class 'tuple'>
(1000, Team         CHC
League        NL
Year        1973
RS           614
RA           655
W             77
G            161
Playoffs       0
Name: 1000, dtype: object)
<class 'tuple'>
(1001, Team         CHW
League        AL
Year        1973
RS           652
RA           705
W             77
G            162
Playoffs       0
Name: 1001, dtype: object)
<class 'tuple'>
(1002, Team         CIN
League        NL
Year        1973
RS           741
RA           621
W             99
G            162
Playoffs       1
Name: 1002, dtype: object)
<class 'tuple'>
(1003, Team         CLE
League        AL
Year        1973
RS           680

Name: 1115, dtype: object)
<class 'tuple'>
(1116, Team         CHC
League        NL
Year        1967
RS           702
RA           624
W             87
G            162
Playoffs       0
Name: 1116, dtype: object)
<class 'tuple'>
(1117, Team         CHW
League        AL
Year        1967
RS           531
RA           491
W             89
G            162
Playoffs       0
Name: 1117, dtype: object)
<class 'tuple'>
(1118, Team         CIN
League        NL
Year        1967
RS           604
RA           563
W             87
G            162
Playoffs       0
Name: 1118, dtype: object)
<class 'tuple'>
(1119, Team         CLE
League        AL
Year        1967
RS           559
RA           613
W             75
G            162
Playoffs       0
Name: 1119, dtype: object)
<class 'tuple'>
(1120, Team         DET
League        AL
Year        1967
RS           683
RA           587
W             91
G            163
Playoffs       0
Name: 1120, dtype: object)
<class 'tuple'>
(1121, Team         HOU
League        NL
Year        1967
RS           626
RA           742
W             69
G            162
Playoffs       0
Name: 1121, dtype: object)
<class 'tuple'>
(1122, Team         KCA
League        AL
Year        1967
RS           533
RA           660
W             62
G            161
Playoffs       0
Name: 1122, dtype: object)
<class 'tuple'>
(1123, Team         LAD
League        NL
Year        1967
RS           519
RA           595
W             73
G            162
Playoffs       0
Name: 1123, dtype: object)
<class 'tuple'>
(1124, Team         MIN
League        AL
Year        1967
RS           671
RA           590
W             91
G            164
Playoffs       0
Name: 1124, dtype: object)
<class 'tuple'>
(1125, Team         NYM
League        NL
Year        1967
RS           498
RA           672
W             61
G            162
Playoffs       0
Name: 1125, dtype: object)
<class 'tuple'>
(1126, Team         NYY
League        AL
Year        1967
RS           522
RA           621
W             72
G            163
Playoffs       0
Name: 1126, dtype: object)
<class 'tuple'>
(1127, Team         PHI
League        NL
Year        1967
RS           612
RA           581
W             82
G            162
Playoffs       0
Name: 1127, dtype: object)
<class 'tuple'>
(1128, Team         PIT
League        NL
Year        1967
RS           679
RA           693
W             81
G            163
Playoffs       0
Name: 1128, dtype: object)
<class 'tuple'>
(1129, Team         SFG
League        NL
Year        1967
RS           652
RA           551
W             91
G            162
Playoffs       0
Name: 1129, dtype: object)
<class 'tuple'>
(1130, Team         STL
League        NL
Year        1967
RS           695
RA           557
W            101
G            161
Playoffs       1
Name: 1130, dtype: object)
<class 'tuple'>
(1131, Team         WSA
League        AL
Year        1967
RS           550
RA           637
W             76
G            161
Playoffs       0
Name: 1131, dtype: object)
<class 'tuple'>
(1132, Team         ATL
League        NL
Year        1966
RS           782
RA           683
W             85
G            163
Playoffs       0
Name: 1132, dtype: object)
<class 'tuple'>
(1133, Team         BAL
League        AL
Year        1966
RS           755
RA           601
W             97
G            160
Playoffs       1
Name: 1133, dtype: object)
<class 'tuple'>
(1134, Team         BOS
League        AL
Year        1966
RS           655
RA           731
W             72
G            162
Playoffs       0
Name: 1134, dtype: object)
<class 'tuple'>
(1135, Team         CAL
League        AL
Year        1966
RS           604
RA           643
W             80
G            162
Playoffs       0
Name: 1135, dtype: object)
<class 'tuple'>
(1136, Team         CHC
League        NL
Year        1966
RS           644
RA           809
W             59
G            162
Playoffs       0
Name: 1136, dtype: object)
<class 'tuple'>
(1137, Team         CHW
League        AL
Year        1966
RS           574
RA           517
W             83
G            163
Playoffs       0
Name: 1137, dtype: object)
<class 'tuple'>
(1138, Team         CIN
League        NL
Year        1966
RS           692
RA           702
W             76
G            160
Playoffs       0
Name: 1138, dtype: object)
<class 'tuple'>
(1139, Team         CLE
League        AL
Year        1966
RS           574
RA           586
W             81
G            162
Playoffs       0
Name: 1139, dtype: object)
<class 'tuple'>
(1140, Team         DET
League        AL
Year        1966
RS           719
RA           698
W             88
G            162
Playoffs       0
Name: 1140, dtype: object)
<class 'tuple'>
(1141, Team         HOU
League        NL
Year        1966
RS           612
RA           695
W             72
G            163
Playoffs       0
Name: 1141, dtype: object)
<class 'tuple'>
(1142, Team         KCA
League        AL
Year        1966
RS           564
RA           648
W             74
G            160
Playoffs       0
Name: 1142, dtype: object)
<class 'tuple'>
(1143, Team         LAD
League        NL
Year        1966
RS           606
RA           490
W             95
G            162
Playoffs       1
Name: 1143, dtype: object)
<class 'tuple'>
(1144, Team         MIN
League        AL
Year        1966
RS           663
RA           581
W             89
G            162
Playoffs       0
Name: 1144, dtype: object)
<class 'tuple'>
(1145, Team         NYM
League        NL
Year        1966
RS           587
RA           761
W             66
G            161
Playoffs       0
Name: 1145, dtype: object)
<class 'tuple'>
(1146, Team         NYY
League        AL
Year        1966
RS           611
RA           612
W             70
G            160
Playoffs       0
Name: 1146, dtype: object)
<class 'tuple'>
(1147, Team         PHI
League        NL
Year        1966
RS           696
RA           640
W             87
G            162
Playoffs       0
Name: 1147, dtype: object)
<class 'tuple'>
(1148, Team         PIT
League        NL
Year        1966
RS           759
RA           641
W             92
G            162
Playoffs       0
Name: 1148, dtype: object)
<class 'tuple'>
(1149, Team         SFG
League        NL
Year        1966
RS           675
RA           626
W             93
G            161
Playoffs       0
Name: 1149, dtype: object)
<class 'tuple'>
(1150, Team         STL
League        NL
Year        1966
RS           571
RA           577
W             83
G            162
Playoffs       0
Name: 1150, dtype: object)
<class 'tuple'>
(1151, Team         WSA
League        AL
Year        1966
RS           557
RA           659
W             71
G            159
Playoffs       0
Name: 1151, dtype: object)
<class 'tuple'>
(1152, Team         BAL
League        AL
Year        1965
RS           641
RA           578
W             94
G            162
Playoffs       0
Name: 1152, dtype: object)
<class 'tuple'>
(1153, Team         BOS
League        AL
Year        1965
RS           669
RA           791
W             62
G            162
Playoffs       0
Name: 1153, dtype: object)
<class 'tuple'>
(1154, Team         CAL
League        AL
Year        1965
RS           527
RA           569
W             75
G            162
Playoffs       0
Name: 1154, dtype: object)
<class 'tuple'>
(1155, Team         CHC
League        NL
Year        1965
RS           635
RA           723
W             72
G            164
Playoffs       0
Name: 1155, dtype: object)
<class 'tuple'>
(1156, Team         CHW
League        AL
Year        1965
RS           647
RA           555
W             95
G            162
Playoffs       0
Name: 1156, dtype: object)
<class 'tuple'>
(1157, Team         CIN
League        NL
Year        1965
RS           825
RA           704
W             89
G            162
Playoffs       0
Name: 1157, dtype: object)
<class 'tuple'>
(1158, Team         CLE
League        AL
Year        1965
RS           663
RA           613
W             87
G            162
Playoffs       0
Name: 1158, dtype: object)
<class 'tuple'>
(1159, Team         DET
League        AL
Year        1965
RS           680
RA           602
W             89
G            162
Playoffs       0
Name: 1159, dtype: object)
<class 'tuple'>
(1160, Team         HOU
League        NL
Year        1965
RS           569
RA           711
W             65
G            162
Playoffs       0
Name: 1160, dtype: object)
<class 'tuple'>
(1161, Team         KCA
League        AL
Year        1965
RS           585
RA           755
W             59
G            162
Playoffs       0
Name: 1161, dtype: object)
<class 'tuple'>
(1162, Team         LAD
League        NL
Year        1965
RS           608
RA           521
W             97
G            162
Playoffs       1
Name: 1162, dtype: object)
<class 'tuple'>
(1163, Team         MIN
League        AL
Year        1965
RS           774
RA           600
W            102
G            162
Playoffs       1
Name: 1163, dtype: object)
<class 'tuple'>
(1164, Team         MLN
League        NL
Year        1965
RS           708
RA           633
W             86
G            162
Playoffs       0
Name: 1164, dtype: object)
<class 'tuple'>
(1165, Team         NYM
League        NL
Year        1965
RS           495
RA           752
W             50
G            164
Playoffs       0
Name: 1165, dtype: object)
<class 'tuple'>
(1166, Team         NYY
League        AL
Year        1965
RS           611
RA           604
W             77
G            162
Playoffs       0
Name: 1166, dtype: object)
<class 'tuple'>
(1167, Team         PHI
League        NL
Year        1965
RS           654
RA           667
W             85
G            162
Playoffs       0
Name: 1167, dtype: object)
<class 'tuple'>
(1168, Team         PIT
League        NL
Year        1965
RS           675
RA           580
W             90
G            163
Playoffs       0
Name: 1168, dtype: object)
<class 'tuple'>
(1169, Team         SFG
League        NL
Year        1965
RS           682
RA           593
W             95
G            163
Playoffs       0
Name: 1169, dtype: object)
<class 'tuple'>
(1170, Team         STL
League        NL
Year        1965
RS           707
RA           674
W             80
G            162
Playoffs       0
Name: 1170, dtype: object)
<class 'tuple'>
(1171, Team         WSA
League        AL
Year        1965
RS           591
RA           721
W             70
G            162
Playoffs       0
Name: 1171, dtype: object)
<class 'tuple'>
(1172, Team         BAL
League        AL
Year        1964
RS           679
RA           567
W             97
G            163
Playoffs       0
Name: 1172, dtype: object)
<class 'tuple'>
(1173, Team         BOS
League        AL
Year        1964
RS           688
RA           793
W             72
G            162
Playoffs       0
Name: 1173, dtype: object)
<class 'tuple'>
(1174, Team         CHC
League        NL
Year        1964
RS           649
RA           724
W             76
G            162
Playoffs       0
Name: 1174, dtype: object)
<class 'tuple'>
(1175, Team         CHW
League        AL
Year        1964
RS           642
RA           501
W             98
G            162
Playoffs       0
Name: 1175, dtype: object)
<class 'tuple'>
(1176, Team         CIN
League        NL
Year        1964
RS           660
RA           566
W             92
G            163
Playoffs       0
Name: 1176, dtype: object)
<class 'tuple'>
(1177, Team         CLE
League        AL
Year        1964
RS           689
RA           693
W             79
G            164
Playoffs       0
Name: 1177, dtype: object)
<class 'tuple'>
(1178, Team         DET
League        AL
Year        1964
RS           699
RA           678
W             85
G            163
Playoffs       0
Name: 1178, dtype: object)
<class 'tuple'>
(1179, Team         HOU
League        NL
Year        1964
RS           495
RA           628
W             66
G            162
Playoffs       0
Name: 1179, dtype: object)
<class 'tuple'>
(1180, Team         KCA
League        AL
Year        1964
RS           621
RA           836
W             57
G            163
Playoffs       0
Name: 1180, dtype: object)
<class 'tuple'>
(1181, Team         LAA
League        AL
Year        1964
RS           544
RA           551
W             82
G            162
Playoffs       0
Name: 1181, dtype: object)
<class 'tuple'>
(1182, Team         LAD
League        NL
Year        1964
RS           614
RA           572
W             80
G            164
Playoffs       0
Name: 1182, dtype: object)
<class 'tuple'>
(1183, Team         MIN
League        AL
Year        1964
RS           737
RA           678
W             79
G            163
Playoffs       0
Name: 1183, dtype: object)
<class 'tuple'>
(1184, Team         MLN
League        NL
Year        1964
RS           803
RA           744
W             88
G            162
Playoffs       0
Name: 1184, dtype: object)
<class 'tuple'>
(1185, Team         NYM
League        NL
Year        1964
RS           569
RA           776
W             53
G            163
Playoffs       0
Name: 1185, dtype: object)
<class 'tuple'>
(1186, Team         NYY
League        AL
Year        1964
RS           730
RA           577
W             99
G            164
Playoffs       1
Name: 1186, dtype: object)
<class 'tuple'>
(1187, Team         PHI
League        NL
Year        1964
RS           693
RA           632
W             92
G            162
Playoffs       0
Name: 1187, dtype: object)
<class 'tuple'>
(1188, Team         PIT
League        NL
Year        1964
RS           663
RA           636
W             80
G            162
Playoffs       0
Name: 1188, dtype: object)
<class 'tuple'>
(1189, Team         SFG
League        NL
Year        1964
RS           656
RA           587
W             90
G            162
Playoffs       0
Name: 1189, dtype: object)
<class 'tuple'>
(1190, Team         STL
League        NL
Year        1964
RS           715
RA           652
W             93
G            162
Playoffs       1
Name: 1190, dtype: object)
<class 'tuple'>
(1191, Team         WSA
League        AL
Year        1964
RS           578
RA           733
W             62
G            162
Playoffs       0
Name: 1191, dtype: object)
<class 'tuple'>
(1192, Team         BAL
League        AL
Year        1963
RS           644
RA           621
W             86
G            162
Playoffs       0
Name: 1192, dtype: object)
<class 'tuple'>
(1193, Team         BOS
League        AL
Year        1963
RS           666
RA           704
W             76
G            161
Playoffs       0
Name: 1193, dtype: object)
<class 'tuple'>
(1194, Team         CHC
League        NL
Year        1963
RS           570
RA           578
W             82
G            162
Playoffs       0
Name: 1194, dtype: object)
<class 'tuple'>
(1195, Team         CHW
League        AL
Year        1963
RS           683
RA           544
W             94
G            162
Playoffs       0
Name: 1195, dtype: object)
<class 'tuple'>
(1196, Team         CIN
League        NL
Year        1963
RS           648
RA           594
W             86
G            162
Playoffs       0
Name: 1196, dtype: object)
<class 'tuple'>
(1197, Team         CLE
League        AL
Year        1963
RS           635
RA           702
W             79
G            162
Playoffs       0
Name: 1197, dtype: object)
<class 'tuple'>
(1198, Team         DET
League        AL
Year        1963
RS           700
RA           703
W             79
G            162
Playoffs       0
Name: 1198, dtype: object)
<class 'tuple'>
(1199, Team         HOU
League        NL
Year        1963
RS           464
RA           640
W             66
G            162
Playoffs       0
Name: 1199, dtype: object)
<class 'tuple'>
(1200, Team         KCA
League        AL
Year        1963
RS           615
RA           704
W             73
G            162
Playoffs       0
Name: 1200, dtype: object)
<class 'tuple'>
(1201, Team         LAA
League        AL
Year        1963
RS           597
RA           660
W             70
G            161
Playoffs       0
Name: 1201, dtype: object)
<class 'tuple'>
(1202, Team         LAD
League        NL
Year        1963
RS           640
RA           550
W             99
G            163
Playoffs       1
Name: 1202, dtype: object)
<class 'tuple'>
(1203, Team         MIN
League        AL
Year        1963
RS           767
RA           602
W             91
G            161
Playoffs       0
Name: 1203, dtype: object)
<class 'tuple'>
(1204, Team         MLN
League        NL
Year        1963
RS           677
RA           603
W             84
G            163
Playoffs       0
Name: 1204, dtype: object)
<class 'tuple'>
(1205, Team         NYM
League        NL
Year        1963
RS           501
RA           774
W             51
G            162
Playoffs       0
Name: 1205, dtype: object)
<class 'tuple'>
(1206, Team         NYY
League        AL
Year        1963
RS           714
RA           547
W            104
G            161
Playoffs       1
Name: 1206, dtype: object)
<class 'tuple'>
(1207, Team         PHI
League        NL
Year        1963
RS           642
RA           578
W             87
G            162
Playoffs       0
Name: 1207, dtype: object)
<class 'tuple'>
(1208, Team         PIT
League        NL
Year        1963
RS           567
RA           595
W             74
G            162
Playoffs       0
Name: 1208, dtype: object)
<class 'tuple'>
(1209, Team         SFG
League        NL
Year        1963
RS           725
RA           641
W             88
G            162
Playoffs       0
Name: 1209, dtype: object)
<class 'tuple'>
(1210, Team         STL
League        NL
Year        1963
RS           747
RA           628
W             93
G            162
Playoffs       0
Name: 1210, dtype: object)
<class 'tuple'>
(1211, Team         WSA
League        AL
Year        1963
RS           578
RA           812
W             56
G            162
Playoffs       0
Name: 1211, dtype: object)
<class 'tuple'>
(1212, Team         BAL
League        AL
Year        1962
RS           652
RA           680
W             77
G            162
Playoffs       0
Name: 1212, dtype: object)
<class 'tuple'>
(1213, Team         BOS
League        AL
Year        1962
RS           707
RA           756
W             76
G            160
Playoffs       0
Name: 1213, dtype: object)
<class 'tuple'>
(1214, Team         CHC
League        NL
Year        1962
RS           632
RA           827
W             59
G            162
Playoffs       0
Name: 1214, dtype: object)
<class 'tuple'>
(1215, Team         CHW
League        AL
Year        1962
RS           707
RA           658
W             85
G            162
Playoffs       0
Name: 1215, dtype: object)
<class 'tuple'>
(1216, Team         CIN
League        NL
Year        1962
RS           802
RA           685
W             98
G            162
Playoffs       0
Name: 1216, dtype: object)
<class 'tuple'>
(1217, Team         CLE
League        AL
Year        1962
RS           682
RA           745
W             80
G            162
Playoffs       0
Name: 1217, dtype: object)
<class 'tuple'>
(1218, Team         DET
League        AL
Year        1962
RS           758
RA           692
W             85
G            161
Playoffs       0
Name: 1218, dtype: object)
<class 'tuple'>
(1219, Team         HOU
League        NL
Year        1962
RS           592
RA           717
W             64
G            162
Playoffs       0
Name: 1219, dtype: object)
<class 'tuple'>
(1220, Team         KCA
League        AL
Year        1962
RS           745
RA           837
W             72
G            162
Playoffs       0
Name: 1220, dtype: object)
<class 'tuple'>
(1221, Team         LAA
League        AL
Year        1962
RS           718
RA           706
W             86
G            162
Playoffs       0
Name: 1221, dtype: object)
<class 'tuple'>
(1222, Team         LAD
League        NL
Year        1962
RS           842
RA           697
W            102
G            165
Playoffs       0
Name: 1222, dtype: object)
<class 'tuple'>
(1223, Team         MIN
League        AL

**Note** : Sejak `.iterrows()` mengembalikan setiap baris DataFrame sebagai pasangan tuple (indeks, pandas Series), Anda dapat membagi tuple ini dan menggunakan indeks dan nilai-baris secara terpisah (seperti yang Anda lakukan dengan `for i,row in pit_df.iterrows()` ), atau Anda dapat menyimpan hasil `.iterrows()` dalam bentuk tuple (seperti yang Anda lakukan dengan `for row_tuple in pit_df.iterrows()` ).

Jika menggunakan `i,row`, Anda dapat mengakses hal-hal dari baris menggunakan tanda kurung siku (mis. `row['Team']`). Jika menggunakan `row_tuple`, Anda harus menentukan elemen tuple mana yang ingin Anda akses sebelum meraih nama tim (mis., `row_tuple[1]['Team']`).

Dengan pendekatan mana pun, menggunakan `.iterrows()` masih akan jauh lebih cepat daripada menggunakan `.iloc`.

### Practice: Run differentials with .iterrows()

Anda telah disewa oleh San Francisco Giants sebagai analis — selamat! Pemilik tim ingin Anda menghitung metrik yang disebut *run differential* untuk setiap musim dari tahun 2008 hingga 2012. Metrik ini dihitung dengan mengurangi jumlah total run yang diizinkan oleh tim dalam satu musim dari jumlah total run tim yang dicetak dalam suatu musim. `'RS'` berarti *runs scored* dan `'RA'` berarti *runs allowed*.

Fungsi di bawah ini menghitung metrik ini:

In [36]:
def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

In [63]:
giants_df = pit_df[(pit_df['Team'] == 'SFG') & (pit_df['Year'] >= 2008)]

In [64]:
# Create an empty list to store run differentials
run_diffs = []

# Write a for loop and collect runs allowed and runs scored for each row
for i,row in giants_df.iterrows():
    runs_scored = row['RS']
    runs_allowed = row['RA']
    
    # Use the provided function to calculate run_diff for each row
    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    # Append each run differential to the output list
    run_diffs.append(run_diff)

giants_df['RD'] = run_diffs    
print(giants_df)

    Team League  Year   RS   RA   W    G  Playoffs   RD
24   SFG     NL  2012  718  649  94  162         1   69
54   SFG     NL  2011  570  578  86  162         0   -8
84   SFG     NL  2010  697  583  92  162         1  114
114  SFG     NL  2009  657  611  88  162         0   46
144  SFG     NL  2008  640  759  72  162         0 -119

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

**Note** : Lihatlah DataFrame `giants_df` dengan kolom *run differential* yang baru (`'RD'`) yang Anda buat di atas.

Kolom `'Playoffs'` memberi tahu Anda jika suatu tim membuat playoff untuk musim tertentu. `1` berarti tim membuat babak playoff di musim itu dan `0` berarti tim tidak membuat babak playoff di musim itu.

Apakah Anda memperhatikan bahwa di musim dengan *run differentials* tertinggi Giants membuat playoff? Bahkan, di kedua musim ini (2010 dan 2012), San Francisco Giants tidak hanya berhasil lolos tetapi juga memenangkan World Series! Keren!

## Another iterator method: `.itertuples()`

### Team wins data

In [67]:
team_wins_df = baseball_df[['Team', 'Year', 'W']]
team_wins_df = team_wins_df[team_wins_df['Year'] == 2012]

In [69]:
team_wins_df.head()

  Team  Year   W
0  ARI  2012  81
1  ATL  2012  94
2  BAL  2012  93
3  BOS  2012  69
4  CHC  2012  61

In [74]:
for row_tuple in team_wins_df.iterrows():
    print(row_tuple)
    print(type(row_tuple[1]))

(0, Team     ARI
Year    2012
W         81
Name: 0, dtype: object)
<class 'pandas.core.series.Series'>
(1, Team     ATL
Year    2012
W         94
Name: 1, dtype: object)
<class 'pandas.core.series.Series'>
(2, Team     BAL
Year    2012
W         93
Name: 2, dtype: object)
<class 'pandas.core.series.Series'>
(3, Team     BOS
Year    2012
W         69
Name: 3, dtype: object)
<class 'pandas.core.series.Series'>
(4, Team     CHC
Year    2012
W         61
Name: 4, dtype: object)
<class 'pandas.core.series.Series'>
(5, Team     CHW
Year    2012
W         85
Name: 5, dtype: object)
<class 'pandas.core.series.Series'>
(6, Team     CIN
Year    2012
W         97
Name: 6, dtype: object)
<class 'pandas.core.series.Series'>
(7, Team     CLE
Year    2012
W         68
Name: 7, dtype: object)
<class 'pandas.core.series.Series'>
(8, Team     COL
Year    2012
W         64
Name: 8, dtype: object)
<class 'pandas.core.series.Series'>
(9, Team     DET
Year    2012
W         88
Name: 9, dtype: object)
<class 'pandas.core.series.Series'>
(10, Team     HOU
Year    2012
W         55
Name: 10, dtype: object)
<class 'pandas.core.series.Series'>
(11, Team     KCR
Year    2012
W         72
Name: 11, dtype: object)
<class 'pandas.core.series.Series'>
(12, Team     LAA
Year    2012
W         89
Name: 12, dtype: object)
<class 'pandas.core.series.Series'>
(13, Team     LAD
Year    2012
W         86
Name: 13, dtype: object)
<class 'pandas.core.series.Series'>
(14, Team     MIA
Year    2012
W         69
Name: 14, dtype: object)
<class 'pandas.core.series.Series'>
(15, Team     MIL
Year    2012
W         83
Name: 15, dtype: object)
<class 'pandas.core.series.Series'>
(16, Team     MIN
Year    2012
W         66
Name: 16, dtype: object)
<class 'pandas.core.series.Series'>
(17, Team     NYM
Year    2012
W         74
Name: 17, dtype: object)
<class 'pandas.core.series.Series'>
(18, Team     NYY
Year    2012
W         95
Name: 18, dtype: object)
<class 'pandas.core.series.Series'>
(19, Team     OAK
Year    2012
W         94
Name: 19, dtype: object)
<class 'pandas.core.series.Series'>
(20, Team     PHI
Year    2012
W         81
Name: 20, dtype: object)
<class 'pandas.core.series.Series'>
(21, Team     PIT
Year    2012
W         79
Name: 21, dtype: object)
<class 'pandas.core.series.Series'>
(22, Team     SDP
Year    2012
W         76
Name: 22, dtype: object)
<class 'pandas.core.series.Series'>
(23, Team     SEA
Year    2012
W         75
Name: 23, dtype: object)
<class 'pandas.core.series.Series'>
(24, Team     SFG
Year    2012
W         94
Name: 24, dtype: object)
<class 'pandas.core.series.Series'>
(25, Team     STL
Year    2012
W         88
Name: 25, dtype: object)
<class 'pandas.core.series.Series'>
(26, Team     TBR
Year    2012
W         90
Name: 26, dtype: object)
<class 'pandas.core.series.Series'>
(27, Team     TEX
Year    2012
W         93
Name: 27, dtype: object)
<class 'pandas.core.series.Series'>
(28, Team     TOR
Year    2012
W         73
Name: 28, dtype: object)
<class 'pandas.core.series.Series'>
(29, Team     WSN
Year    2012
W         98
Name: 29, dtype: object)
<class 'pandas.core.series.Series'>

### Iterating with .itertuples()

In [77]:
for row_namedtuple in team_wins_df.itertuples():
    print(row_namedtuple)

Pandas(Index=0, Team='ARI', Year=2012, W=81)
Pandas(Index=1, Team='ATL', Year=2012, W=94)
Pandas(Index=2, Team='BAL', Year=2012, W=93)
Pandas(Index=3, Team='BOS', Year=2012, W=69)
Pandas(Index=4, Team='CHC', Year=2012, W=61)
Pandas(Index=5, Team='CHW', Year=2012, W=85)
Pandas(Index=6, Team='CIN', Year=2012, W=97)
Pandas(Index=7, Team='CLE', Year=2012, W=68)
Pandas(Index=8, Team='COL', Year=2012, W=64)
Pandas(Index=9, Team='DET', Year=2012, W=88)
Pandas(Index=10, Team='HOU', Year=2012, W=55)
Pandas(Index=11, Team='KCR', Year=2012, W=72)
Pandas(Index=12, Team='LAA', Year=2012, W=89)
Pandas(Index=13, Team='LAD', Year=2012, W=86)
Pandas(Index=14, Team='MIA', Year=2012, W=69)
Pandas(Index=15, Team='MIL', Year=2012, W=83)
Pandas(Index=16, Team='MIN', Year=2012, W=66)
Pandas(Index=17, Team='NYM', Year=2012, W=74)
Pandas(Index=18, Team='NYY', Year=2012, W=95)
Pandas(Index=19, Team='OAK', Year=2012, W=94)
Pandas(Index=20, Team='PHI', Year=2012, W=81)
Pandas(Index=21, Team='PIT', Year=2012, W=79)
Pandas(Index=22, Team='SDP', Year=2012, W=76)
Pandas(Index=23, Team='SEA', Year=2012, W=75)
Pandas(Index=24, Team='SFG', Year=2012, W=94)
Pandas(Index=25, Team='STL', Year=2012, W=88)
Pandas(Index=26, Team='TBR', Year=2012, W=90)
Pandas(Index=27, Team='TEX', Year=2012, W=93)
Pandas(Index=28, Team='TOR', Year=2012, W=73)
Pandas(Index=29, Team='WSN', Year=2012, W=98)

In [78]:
print(row_namedtuple.Index)

29

In [79]:
print(row_namedtuple.Team)

WSN

### Comparing methods

In [82]:
%%timeit
for row_tuple in team_wins_df.iterrows():
    data = row_tuple

2.63 ms ± 62.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [83]:
%%timeit
for row_namedtuple in team_wins_df.itertuples():
    data = row_namedtuple

396 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [84]:
for row_tuple in team_wins_df.iterrows():
    print(row_tuple[1]['Team'])

ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
HOU
KCR
LAA
LAD
MIA
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN

In [ ]:
# TypeError: tuple indices must be integers or slices, not str
for row_namedtuple in team_wins_df.itertuples():
    print(row_namedtuple['Team'])

In [88]:
for row_namedtuple in team_wins_df.itertuples():
    print(row_namedtuple.Team)

ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
HOU
KCR
LAA
LAD
MIA
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN

### Practice: Iterating with `.itertuples()`

Ingat, `.itertuples()` mengembalikan setiap baris DataFrame sebagai tipe data khusus yang disebut **namedtuple**. Anda dapat mencari atribut dalam sebuah namedtuple dengan sintaks khusus. Mari kita berlatih bekerja dengan namedtuple.

DataFrame pandas telah dimuat sebagai `rangers_df`. DataFrame ini berisi statistik (`'Team'`, `'League'`, `'Year'`, `'RS'`, `'RA'`, `'W'`, `'G'`, dan `'Playoffs'`) untuk tim baseball Liga Utama bernama Texas Rangers (disingkat `'TEX'`).

In [91]:
rangers_df = baseball_df[['Team', 'League', 'Year', 'RS', 'RA', 'W', 'G', 'Playoffs']]
rangers_df = baseball_df[baseball_df['Team'] == 'TEX']

In [94]:
# Loop over the DataFrame and print each row
for row in rangers_df.itertuples():
    print(row)

Pandas(Index=27, Team='TEX', League='AL', Year=2012, RS=808, RA=707, W=93, Playoffs=1, G=162, WP=0.57)
Pandas(Index=57, Team='TEX', League='AL', Year=2011, RS=855, RA=677, W=96, Playoffs=1, G=162, WP=0.59)
Pandas(Index=87, Team='TEX', League='AL', Year=2010, RS=787, RA=687, W=90, Playoffs=1, G=162, WP=0.56)
Pandas(Index=117, Team='TEX', League='AL', Year=2009, RS=784, RA=740, W=87, Playoffs=0, G=162, WP=0.54)
Pandas(Index=147, Team='TEX', League='AL', Year=2008, RS=901, RA=967, W=79, Playoffs=0, G=162, WP=0.49)
Pandas(Index=177, Team='TEX', League='AL', Year=2007, RS=816, RA=844, W=75, Playoffs=0, G=162, WP=0.46)
Pandas(Index=207, Team='TEX', League='AL', Year=2006, RS=835, RA=784, W=80, Playoffs=0, G=162, WP=0.49)
Pandas(Index=237, Team='TEX', League='AL', Year=2005, RS=865, RA=858, W=79, Playoffs=0, G=162, WP=0.49)
Pandas(Index=268, Team='TEX', League='AL', Year=2004, RS=860, RA=794, W=89, Playoffs=0, G=162, WP=0.55)
Pandas(Index=298, Team='TEX', League='AL', Year=2003, RS=826, RA=969, W=71, Playoffs=0, G=162, WP=0.44)
Pandas(Index=328, Team='TEX', League='AL', Year=2002, RS=843, RA=882, W=72, Playoffs=0, G=162, WP=0.44)
Pandas(Index=358, Team='TEX', League='AL', Year=2001, RS=890, RA=968, W=73, Playoffs=0, G=162, WP=0.45)
Pandas(Index=388, Team='TEX', League='AL', Year=2000, RS=848, RA=974, W=71, Playoffs=0, G=162, WP=0.44)
Pandas(Index=418, Team='TEX', League='AL', Year=1999, RS=945, RA=859, W=95, Playoffs=1, G=162, WP=0.59)
Pandas(Index=448, Team='TEX', League='AL', Year=1998, RS=940, RA=871, W=88, Playoffs=1, G=162, WP=0.54)
Pandas(Index=476, Team='TEX', League='AL', Year=1997, RS=807, RA=823, W=77, Playoffs=0, G=162, WP=0.48)
Pandas(Index=504, Team='TEX', League='AL', Year=1996, RS=928, RA=799, W=90, Playoffs=1, G=163, WP=0.55)
Pandas(Index=532, Team='TEX', League='AL', Year=1993, RS=835, RA=751, W=86, Playoffs=0, G=162, WP=0.53)
Pandas(Index=558, Team='TEX', League='AL', Year=1992, RS=682, RA=753, W=77, Playoffs=0, G=162, WP=0.48)
Pandas(Index=584, Team='TEX', League='AL', Year=1991, RS=829, RA=814, W=85, Playoffs=0, G=162, WP=0.52)
Pandas(Index=610, Team='TEX', League='AL', Year=1990, RS=676, RA=696, W=83, Playoffs=0, G=162, WP=0.51)
Pandas(Index=636, Team='TEX', League='AL', Year=1989, RS=695, RA=714, W=83, Playoffs=0, G=162, WP=0.51)
Pandas(Index=662, Team='TEX', League='AL', Year=1988, RS=637, RA=735, W=70, Playoffs=0, G=161, WP=0.43)
Pandas(Index=688, Team='TEX', League='AL', Year=1987, RS=823, RA=849, W=75, Playoffs=0, G=162, WP=0.46)
Pandas(Index=714, Team='TEX', League='AL', Year=1986, RS=771, RA=743, W=87, Playoffs=0, G=162, WP=0.54)
Pandas(Index=740, Team='TEX', League='AL', Year=1985, RS=617, RA=785, W=62, Playoffs=0, G=161, WP=0.39)
Pandas(Index=766, Team='TEX', League='AL', Year=1984, RS=656, RA=714, W=69, Playoffs=0, G=161, WP=0.43)
Pandas(Index=792, Team='TEX', League='AL', Year=1983, RS=639, RA=609, W=77, Playoffs=0, G=163, WP=0.47)
Pandas(Index=818, Team='TEX', League='AL', Year=1982, RS=590, RA=749, W=64, Playoffs=0, G=162, WP=0.4)
Pandas(Index=844, Team='TEX', League='AL', Year=1980, RS=756, RA=752, W=76, Playoffs=0, G=163, WP=0.47)
Pandas(Index=870, Team='TEX', League='AL', Year=1979, RS=750, RA=698, W=83, Playoffs=0, G=162, WP=0.51)
Pandas(Index=896, Team='TEX', League='AL', Year=1978, RS=692, RA=632, W=87, Playoffs=0, G=162, WP=0.54)
Pandas(Index=922, Team='TEX', League='AL', Year=1977, RS=767, RA=657, W=94, Playoffs=0, G=162, WP=0.58)
Pandas(Index=947, Team='TEX', League='AL', Year=1976, RS=616, RA=652, W=76, Playoffs=0, G=162, WP=0.47)
Pandas(Index=971, Team='TEX', League='AL', Year=1975, RS=714, RA=733, W=79, Playoffs=0, G=162, WP=0.49)
Pandas(Index=995, Team='TEX', League='AL', Year=1974, RS=690, RA=698, W=83, Playoffs=0, G=161, WP=0.52)
Pandas(Index=1019, Team='TEX', League='AL', Year=1973, RS=619, RA=844, W=57, Playoffs=0, G=162, WP=0.35)

In [95]:
# Loop over the DataFrame and print each row's Index, Year and Wins (W)
for row in rangers_df.itertuples():
    i = row.Index
    year = row.Year
    wins = row.W
    print(i, year, wins)

27 2012 93
57 2011 96
87 2010 90
117 2009 87
147 2008 79
177 2007 75
207 2006 80
237 2005 79
268 2004 89
298 2003 71
328 2002 72
358 2001 73
388 2000 71
418 1999 95
448 1998 88
476 1997 77
504 1996 90
532 1993 86
558 1992 77
584 1991 85
610 1990 83
636 1989 83
662 1988 70
688 1987 75
714 1986 87
740 1985 62
766 1984 69
792 1983 77
818 1982 64
844 1980 76
870 1979 83
896 1978 87
922 1977 94
947 1976 76
971 1975 79
995 1974 83
1019 1973 57

In [96]:
# Loop over the DataFrame and print each row's Index, Year and Wins (W)
for row in rangers_df.itertuples():
    i = row.Index
    year = row.Year
    wins = row.W
  
    # Check if rangers made Playoffs (1 means yes; 0 means no)
    if row.Playoffs == 1:
        print(i, year, wins)

27 2012 93
57 2011 96
87 2010 90
418 1999 95
448 1998 88
504 1996 90

**Note** : Anda terbiasa menggunakan `.itertuples()`. Ingat, Anda perlu menggunakan sintaks *dot* untuk mereferensikan atribut dalam **namedtuple**.

Anda dapat membuat variabel baru menggunakan referensi titik baris (seperti yang Anda lakukan saat menyimpan `row.Index` sebagai variabel `i`). Atau Anda dapat menggunakan referensi titik baris secara langsung untuk melakukan perhitungan dan pemeriksaan. Perhatikan bahwa Anda tidak harus menyimpan `row.Playoffs` ke variabel baru dalam pernyataan `if` Anda (Anda dapat menggunakan `row.Playoffs` langsung di `if` Anda).

Apakah Anda memperhatikan pola dalam penampilan playoff Texas Rangers? Hanya enam penampilan dan dua kelompok pengelompokan yang berbeda (satu dari 2010 - 2012 dan satu dari 1996 - 1999).

### Practice: Run differentials with `.itertuples()`

New York Yankees telah melakukan perdagangan dengan San Francisco Giants untuk kontrak analis Anda — Anda adalah komoditas panas! Bos baru Anda telah melihat pekerjaan Anda dengan Giants dan sekarang ingin Anda melakukan sesuatu yang mirip dengan data Yankees. Dia ingin Anda menghitung *run differentials* untuk Yankees dari tahun 1962 hingga tahun 2012 dan menemukan musim mana mereka memiliki *run differentials* terbaik.

Anda ingat fungsi yang Anda gunakan saat bekerja dengan Giants :

In [97]:
def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

Mari kita gunakan `.itertuples()` untuk loop DataFrame `yankees_df`.

In [106]:
yankees_df = baseball_df[['Team', 'League', 'Year', 'RS', 'RA', 'W', 'G', 'Playoffs']]
yankees_df = baseball_df[baseball_df['Team'] == 'NYY'].reset_index()

In [114]:
run_diffs = []

# Loop over the DataFrame and calculate each row's run differential
for row in yankees_df.itertuples():
    
    runs_scored = row.RS
    runs_allowed = row.RA

    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    run_diffs.append(run_diff)

# Append new column
yankees_df['RD'] = run_diffs
print(yankees_df)

    index Team League  Year   RS   RA    W  Playoffs    G    WP   RD
0      18  NYY     AL  2012  804  668   95         1  162  0.59  136
1      48  NYY     AL  2011  867  657   97         1  162  0.60  210
2      78  NYY     AL  2010  859  693   95         1  162  0.59  166
3     108  NYY     AL  2009  915  753  103         1  162  0.64  162
4     138  NYY     AL  2008  789  727   89         0  162  0.55   62
5     168  NYY     AL  2007  968  777   94         1  162  0.58  191
6     198  NYY     AL  2006  930  767   97         1  162  0.60  163
7     228  NYY     AL  2005  886  789   95         1  162  0.59   97
8     259  NYY     AL  2004  897  808  101         1  162  0.62   89
9     289  NYY     AL  2003  877  716  101         1  163  0.62  161
10    319  NYY     AL  2002  897  697  103         1  161  0.64  200
11    349  NYY     AL  2001  804  713   95         1  161  0.59   91
12    379  NYY     AL  2000  871  814   87         1  161  0.54   57
13    409  NYY     AL  1999  900  731   98         1  162  0.60  169
14    439  NYY     AL  1998  965  656  114         1  162  0.70  309
15    468  NYY     AL  1997  891  688   96         1  162  0.59  203
16    496  NYY     AL  1996  871  787   92         1  162  0.57   84
17    524  NYY     AL  1993  821  761   88         0  162  0.54   60
18    550  NYY     AL  1992  733  746   76         0  162  0.47  -13
19    576  NYY     AL  1991  674  777   71         0  162  0.44 -103
20    602  NYY     AL  1990  603  749   67         0  162  0.41 -146
21    628  NYY     AL  1989  698  792   74         0  161  0.46  -94
22    654  NYY     AL  1988  772  748   85         0  161  0.53   24
23    680  NYY     AL  1987  788  758   89         0  162  0.55   30
24    706  NYY     AL  1986  797  738   90         0  162  0.56   59
25    732  NYY     AL  1985  839  660   97         0  161  0.60  179
26    758  NYY     AL  1984  758  679   87         0  162  0.54   79
27    784  NYY     AL  1983  770  703   91         0  162  0.56   67
28    810  NYY     AL  1982  709  716   79         0  162  0.49   -7
29    836  NYY     AL  1980  820  662  103         1  162  0.64  158
30    862  NYY     AL  1979  734  672   89         0  160  0.56   62
31    888  NYY     AL  1978  735  582  100         1  163  0.61  153
32    914  NYY     AL  1977  831  651  100         1  162  0.62  180
33    940  NYY     AL  1976  730  575   97         1  159  0.61  155
34    964  NYY     AL  1975  681  588   83         0  160  0.52   93
35    988  NYY     AL  1974  671  623   89         0  162  0.55   48
36   1012  NYY     AL  1973  641  610   80         0  162  0.49   31
37   1036  NYY     AL  1971  648  641   81         0  162  0.50    7
38   1060  NYY     AL  1970  680  612   93         0  163  0.57   68
39   1083  NYY     AL  1969  562  587   80         0  162  0.49  -25
40   1105  NYY     AL  1968  536  531   83         0  164  0.51    5
41   1126  NYY     AL  1967  522  621   72         0  163  0.44  -99
42   1146  NYY     AL  1966  611  612   70         0  160  0.44   -1
43   1166  NYY     AL  1965  611  604   77         0  162  0.48    7
44   1186  NYY     AL  1964  730  577   99         1  164  0.60  153
45   1206  NYY     AL  1963  714  547  104         1  161  0.65  167
46   1226  NYY     AL  1962  817  680   96         1  162  0.59  137

**Question**

Pada tahun berapa di dalam DataFrame Anda, New York Yankees memiliki *run differential* tertinggi?

* Pada tahun 1998 (dengan Run Diferensial 309)

**Note** : Anda menggunakan `.itertuples()` untuk membantu Yankees menghitung *run differential*. Ingat, menggunakan `.itertuples()` sama seperti menggunakan `.iterrows()` kecuali itu cenderung lebih cepat. Anda juga harus menggunakan referensi *dot* ketika mencari atribut dengan `.itertuples()`.

Anda menemukan bahwa *run differential* tertinggi Yankees adalah pada tahun 1998. Apakah Anda tahu mereka benar-benar memegang rekor untuk *run differential* tertinggi dalam musim MLB (411 pada tahun 1939 di mana RS 967 dan RA 556)? Wow!

## pandas alternative to looping

### pandas `.apply()` method

* Mengambil fungsi dan menerapkannya ke DataFrame
  * Harus menentukan sumbu untuk diterapkan ( 0 untuk kolom; 1 untuk baris)
* Dapat digunakan dengan anonymous functions ( `lambda` functions)

Contoh:

In [115]:
baseball_df.apply(lambda row: calc_run_diff(row['RS'], row['RA']), axis=1)

0        46
1       100
2         7
3       -72
4      -146
       ...
1227    -54
1228     80
1229    188
1230    110
1231   -117
Length: 1232, dtype: int64

### Run differentials with `.apply()`

In [117]:
run_diffs_apply = baseball_df.apply(lambda row: calc_run_diff(row['RS'], row['RA']), axis=1)
baseball_df['RD'] = run_diffs_apply
print(baseball_df)

     Team League  Year   RS   RA    W  Playoffs    G    WP   RD
0     ARI     NL  2012  734  688   81         0  162  0.50   46
1     ATL     NL  2012  700  600   94         1  162  0.58  100
2     BAL     AL  2012  712  705   93         1  162  0.57    7
3     BOS     AL  2012  734  806   69         0  162  0.43  -72
4     CHC     NL  2012  613  759   61         0  162  0.38 -146
...   ...    ...   ...  ...  ...  ...       ...  ...   ...  ...
1227  PHI     NL  1962  705  759   81         0  161  0.50  -54
1228  PIT     NL  1962  706  626   93         0  161  0.58   80
1229  SFG     NL  1962  878  690  103         1  165  0.62  188
1230  STL     NL  1962  774  664   84         0  163  0.52  110
1231  WSA     AL  1962  599  716   60         0  162  0.37 -117

[1232 rows x 10 columns]

### Comparing approaches

In [118]:
%%timeit
run_diffs_iterrows = []

for i,row in baseball_df.iterrows():
    run_diff = calc_run_diff(row['RS'], row['RA'])
    run_diffs_iterrows.append(run_diff)
    
baseball_df['RD'] = run_diffs_iterrows

135 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [119]:
%%timeit
run_diffs_apply = baseball_df.apply(lambda row: calc_run_diff(row['RS'], row['RA']), axis=1)
baseball_df['RD'] = run_diffs_apply

29.3 ms ± 406 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

### Analyzing baseball stats with `.apply()`

Tampa Bay Rays ingin Anda menganalisis data mereka.

Mereka menginginkan metrik sebagai berikut:
* Jumlah setiap kolom dalam data
* Jumlah total *runs scored* dalam setahun ( `'RS'` + `'RA'` untuk setiap tahun)
* Kolom `'Playoffs'` dalam format teks daripada menggunakan angka `1` dan `0`

Fungsi di bawah ini dapat digunakan untuk mengonversi kolom `'Playoffs'` menjadi teks:

In [120]:
def text_playoffs(num_playoffs): 
    if num_playoffs == 1:
        return 'Yes'
    else:
        return 'No'

Gunakan `.apply()` untuk mendapatkan metrik ini. DataFrame ( `rays_df` ) telah dimuat. DataFrame ini diindeks pada kolom `'Year'`.

In [135]:
rays_df_filter = baseball_df[baseball_df['Team'] == 'TBR']

In [136]:
rays_df = rays_df_filter[['Year','RS','RA','W','Playoffs']].set_index('Year')

In [141]:
rays_df

       RS   RA   W  Playoffs
Year
2012  697  577  90         0
2011  707  614  91         1
2010  802  649  96         1
2009  803  754  84         0
2008  774  671  97         1

In [138]:
# Gather sum of all columns
stat_totals = rays_df.apply(sum, axis=0)
print(stat_totals)

RS          3783
RA          3265
W            458
Playoffs       3
dtype: int64

In [139]:
# Gather total runs scored in all games per year
total_runs_scored = rays_df[['RS', 'RA']].apply(sum, axis=1)
print(total_runs_scored)

Year
2012    1274
2011    1321
2010    1451
2009    1557
2008    1445
dtype: int64

In [140]:
# Convert numeric playoffs to text
textual_playoffs = rays_df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)
print(textual_playoffs)

Year
2012     No
2011    Yes
2010    Yes
2009     No
2008    Yes
dtype: object

**Note** : Metode `.apply()` memungkinkan Anda menerapkan fungsi ke semua baris atau kolom DataFrame dengan menentukan sumbu/axis.

Jika Anda telah menggunakan pandas untuk beberapa waktu, Anda mungkin telah memperhatikan bahwa cara yang lebih baik untuk menemukan statistik ini adalah menggunakan metode bawaan pandas `.sum()`.

Anda bisa menggunakan `rays_df.sum(axis=0)` untuk mendapatkan jumlah kolom dan `rays_df[['RS', 'RA']].sum(axis=1)` untuk mendapatkan jumlah baris.

Anda juga bisa menggunakan `.apply()` langsung pada Series (atau kolom) dari DataFrame. Misalnya, Anda bisa menggunakan `rays_df['Playoffs'].apply(text_playoffs)` untuk mengkonversi kolom `'Playoffs'` ke text.

### Settle a debate with `.apply()`

Sudah ada kabar sampai ke Arizona Diamondbacks tentang keterampilan analitik Anda yang luar biasa. Mereka ingin Anda membantu menyelesaikan perdebatan di antara para manajer. Satu manajer mengklaim bahwa tim telah membuat babak playoff setiap tahun mereka memiliki persentase kemenangan 0,50 atau lebih besar. Manajer lain mengatakan ini tidak benar.

Mari kita gunakan fungsi di bawah ini dan metode `.apply()` untuk melihat manajer mana yang benar.

In [143]:
def calc_win_perc(wins, games_played):
    
    win_perc = wins / games_played
    return np.round(win_perc, 2)

In [148]:
ari_df_filter = baseball_df[baseball_df['Team'] == 'ARI']
dbacks_df = ari_df_filter[['Team','League','Year','RS','RA','W','G','Playoffs']].reset_index()

In [151]:
# Display the first five rows of the DataFrame
dbacks_df.head()

   index Team League  Year   RS   RA   W    G  Playoffs
0      0  ARI     NL  2012  734  688  81  162         0
1     30  ARI     NL  2011  731  662  94  162         1
2     60  ARI     NL  2010  713  836  65  162         0
3     90  ARI     NL  2009  720  782  70  162         0
4    120  ARI     NL  2008  720  706  82  162         0

In [152]:
# Create a win percentage Series 
win_percs = dbacks_df.apply(lambda row: calc_win_perc(row['W'], row['G']), axis=1)
print(win_percs, '\n')

0     0.50
1     0.58
2     0.40
3     0.43
4     0.51
5     0.56
6     0.47
7     0.48
8     0.31
9     0.52
10    0.60
11    0.57
12    0.52
13    0.62
14    0.40
dtype: float64

In [153]:
# Append a new column to dbacks_df
dbacks_df['WP'] = win_percs
print(dbacks_df, '\n')

# Display dbacks_df where WP is greater than 0.50
print(dbacks_df[dbacks_df['WP'] >= 0.50])

    index Team League  Year   RS   RA    W    G  Playoffs    WP
0       0  ARI     NL  2012  734  688   81  162         0  0.50
1      30  ARI     NL  2011  731  662   94  162         1  0.58
2      60  ARI     NL  2010  713  836   65  162         0  0.40
3      90  ARI     NL  2009  720  782   70  162         0  0.43
4     120  ARI     NL  2008  720  706   82  162         0  0.51
5     150  ARI     NL  2007  712  732   90  162         1  0.56
6     180  ARI     NL  2006  773  788   76  162         0  0.47
7     210  ARI     NL  2005  696  856   77  162         0  0.48
8     241  ARI     NL  2004  615  899   51  162         0  0.31
9     271  ARI     NL  2003  717  685   84  162         0  0.52
10    301  ARI     NL  2002  819  674   98  162         1  0.60
11    331  ARI     NL  2001  818  677   92  162         1  0.57
12    361  ARI     NL  2000  792  754   85  162         0  0.52
13    391  ARI     NL  1999  908  676  100  162         1  0.62
14    421  ARI     NL  1998  665  812   65  162         0  0.40

    index Team League  Year   RS   RA    W    G  Playoffs    WP
0       0  ARI     NL  2012  734  688   81  162         0  0.50
1      30  ARI     NL  2011  731  662   94  162         1  0.58
4     120  ARI     NL  2008  720  706   82  162         0  0.51
5     150  ARI     NL  2007  712  732   90  162         1  0.56
9     271  ARI     NL  2003  717  685   84  162         0  0.52
10    301  ARI     NL  2002  819  674   98  162         1  0.60
11    331  ARI     NL  2001  818  677   92  162         1  0.57
12    361  ARI     NL  2000  792  754   85  162         0  0.52
13    391  ARI     NL  1999  908  676  100  162         1  0.62

**Question**

Manajer mana yang benar dalam klaim mereka?

* Manajer yang mengklaim **tim belum membuat** babak playoff setiap tahun mereka memiliki persentase kemenangan 0,50 atau lebih besar.

**Note** : Menggunakan metode `.apply()` dengan fungsi `lambda` memungkinkan Anda untuk menerapkan fungsi ke DataFrame tanpa perlu menulis `for` loop.

Sayangnya, manajer kedua benar. Pada tahun 2012, 2008, 2003, dan 2000 Arizona Diamondbacks memiliki persentase kemenangan yang lebih besar dari atau sama dengan 0.50, tetapi masih belum mencapai babak playoff.

## Optimal pandas iterating

### pandas internals

* Menghilangkan loop juga berlaku untuk menggunakan pandas
* panda dibangun di atas NumPy
  * Manfaatkan efisiensi NumPy array

In [154]:
wins_np = baseball_df['W'].values
print(type(wins_np))

<class 'numpy.ndarray'>

In [155]:
print(wins_np)

[ 81  94  93 ... 103  84  60]

### Power of vectorization

* Broadcasting (vectorizing) sangat efisien!

In [159]:
baseball_df['RS'].values - baseball_df['RA'].values

array([  46,  100,    7, ...,  188,  110, -117])

### Run differentials with arrays

In [160]:
run_diffs_np = baseball_df['RS'].values - baseball_df['RA'].values
baseball_df['RD'] = run_diffs_np
print(baseball_df)

     Team League  Year   RS   RA    W  Playoffs    G    WP   RD
0     ARI     NL  2012  734  688   81         0  162  0.50   46
1     ATL     NL  2012  700  600   94         1  162  0.58  100
2     BAL     AL  2012  712  705   93         1  162  0.57    7
3     BOS     AL  2012  734  806   69         0  162  0.43  -72
4     CHC     NL  2012  613  759   61         0  162  0.38 -146
...   ...    ...   ...  ...  ...  ...       ...  ...   ...  ...
1227  PHI     NL  1962  705  759   81         0  161  0.50  -54
1228  PIT     NL  1962  706  626   93         0  161  0.58   80
1229  SFG     NL  1962  878  690  103         1  165  0.62  188
1230  STL     NL  1962  774  664   84         0  163  0.52  110
1231  WSA     AL  1962  599  716   60         0  162  0.37 -117

[1232 rows x 10 columns]

### Comparing approaches

In [161]:
%%timeit
run_diffs_np = baseball_df['RS'].values - baseball_df['RA'].values

baseball_df['RD'] = run_diffs_np

149 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

### Replacing .iloc with underlying arrays

Sekarang setelah Anda memiliki pemahaman yang lebih baik tentang internal DataFrame mari memperbarui salah satu analisis Anda sebelumnya untuk memanfaatkan array yang mendasari DataFrame. Anda akan mengunjungi kembali perhitungan persentase kemenangan yang Anda lakukan baris demi baris dengan metode `.iloc`:

In [162]:
def calc_win_perc(wins, games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)

win_percs_list = []

for i in range(len(baseball_df)):
    row = baseball_df.iloc[i]

    wins = row['W']
    games_played = row['G']

    win_perc = calc_win_perc(wins, games_played)

    win_percs_list.append(win_perc)

baseball_df['WP'] = win_percs_list

Mari kita perbarui analisis ini untuk menggunakan array alih-alih metode `.iloc`.

In [168]:
# Use the W array and G array to calculate win percentages
win_percs_np = calc_win_perc(baseball_df['W'].values, baseball_df['G'].values)

# Append a new column to baseball_df that stores all win percentages
baseball_df['WP'] = win_percs_np

baseball_df.head()

  Team League  Year   RS   RA   W  Playoffs    G    WP
0  ARI     NL  2012  734  688  81         0  162  0.50
1  ATL     NL  2012  700  600  94         1  162  0.58
2  BAL     AL  2012  712  705  93         1  162  0.57
3  BOS     AL  2012  734  806  69         0  162  0.43
4  CHC     NL  2012  613  759  61         0  162  0.38

**Question**

Gunakan `timeit` dalam (*cell magic mode*) di dalam konsol IPython Anda untuk membandingkan runtime antara blok kode lama menggunakan `.iloc` dan kode baru yang Anda kembangkan menggunakan NumPy array.

Jangan sertakan kode yang mendefinisikan fungsi `calc_win_perc()` atau pernyataan `print()` saat penghitungan waktu.

Anda harus memasukkan **delapan baris kode** saat menghitung waktu blok kode lama dan **dua baris kode** saat menghitung waktu kode baru yang Anda kembangkan.

In [169]:
%%timeit
win_percs_list = []
for i in range(len(baseball_df)):
    row = baseball_df.iloc[i]
    wins = row['W']
    games_played = row['G']
    win_perc = calc_win_perc(wins, games_played)
    win_percs_list.append(win_perc)
baseball_df['WP'] = win_percs_list

256 ms ± 4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [170]:
%%timeit
win_percs_np = calc_win_perc(baseball_df['W'].values, baseball_df['G'].values)
baseball_df['WP'] = win_percs_np

177 µs ± 8.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**Answer** : Pendekatan `NumPy` array lebih cepat dari pendekatan `.iloc`.

Menggunakan array yang mendasari DataFrame untuk melakukan perhitungan benar-benar dapat mempercepat kode Anda dan menghasilkan beberapa keuntungan efisiensi yang signifikan. Apakah Anda memperhatikan bahwa pendekatan NumPy array tidak hanya lebih cepat, tetapi juga menggunakan lebih sedikit baris kode dan lebih mudah dibaca?

### Bringing it all together: Predict win percentage

Anda ingin mencoba *memprediksi* persentase kemenangan tim untuk musim tertentu dengan menggunakan total skor lari tim dalam satu musim ('RS') dan total lari yang diizinkan dalam satu musim ('RA') dengan fungsi berikut:

In [171]:
def predict_win_perc(RS, RA):
    prediction = RS ** 2 / (RS ** 2 + RA ** 2)
    return np.round(prediction, 2)

Mari kita bandingkan pendekatan yang telah Anda pelajari untuk menghitung prediksi persentase kemenangan untuk setiap musim (atau baris) di DataFrame Anda.

In [172]:
win_perc_preds_loop = []

# Use a loop and .itertuples() to collect each row's predicted win percentage
for row in baseball_df.itertuples():
    runs_scored = row.RS
    runs_allowed = row.RA
    win_perc_pred = predict_win_perc(runs_scored, runs_allowed)
    win_perc_preds_loop.append(win_perc_pred)

# Apply predict_win_perc to each row of the DataFrame
win_perc_preds_apply = baseball_df.apply(lambda row: predict_win_perc(row['RS'], row['RA']), axis=1)

# Calculate the win percentage predictions using NumPy arrays
win_perc_preds_np = predict_win_perc(baseball_df['RS'].values, baseball_df['RA'].values)
baseball_df['WP_preds'] = win_perc_preds_np
print(baseball_df.head())

  Team League  Year   RS   RA   W  Playoffs    G    WP  WP_preds
0  ARI     NL  2012  734  688  81         0  162  0.50      0.53
1  ATL     NL  2012  700  600  94         1  162  0.58      0.58
2  BAL     AL  2012  712  705  93         1  162  0.57      0.50
3  BOS     AL  2012  734  806  69         0  162  0.43      0.45
4  CHC     NL  2012  613  759  61         0  162  0.38      0.39

**Question**

Bagaimana urutan pendekatan dari tercepat ke paling lambat?

In [173]:
%%timeit
win_perc_preds_loop = []
for row in baseball_df.itertuples():
    runs_scored = row.RS
    runs_allowed = row.RA
    win_perc_pred = predict_win_perc(runs_scored, runs_allowed)
    win_perc_preds_loop.append(win_perc_pred)

16.8 ms ± 242 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [174]:
%timeit win_perc_preds_apply = baseball_df.apply(lambda row: predict_win_perc(row['RS'], row['RA']), axis=1)

46.2 ms ± 831 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [175]:
%timeit win_perc_preds_np = predict_win_perc(baseball_df['RS'].values, baseball_df['RA'].values)

37.4 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**Answer**

Menggunakan `NumPy array` adalah pendekatan **tercepat**, diikuti oleh pendekatan `.itertuples()`, dan pendekatan `.apply()` **paling lambat**.

Anda berlatih menggunakan tiga pendekatan berbeda untuk iterate menggunakan DataFrame pandas dan melakukan perhitungan. Apakah Anda memperhatikan bahwa pendekatan `.itertuples()` mengalahkan pendekatan `.apply()`? Meskipun kedua implementasi ini bisa berguna, Anda harus menggunakan default untuk array yang mendasari DataFrame untuk melakukan perhitungan.

Lihatlah prediksi persentase kemenangan Anda (kolom `'WP_preds'`) dan bandingkan dengan persentase kemenangan aktual (kolom `'WP'`). Tidak buruk!

Anda telah melakukan pekerjaan luar biasa selama kursus! Sekarang, Anda sudah siap untuk menulis kode Python dan pandas yang efisien!

## What you have learned

* Definisi kode **efisien** dan **Pythonic**
* Cara menggunakan library bawaan Python yang powerful
* Keuntungan dari NumPy arrays
* Beberapa perintah *magic* yang berguna untuk kode profil
* Cara menggunakan solusi yang efisien dengan `zip()`, `itertools`, `collections`, dan teori `set` .
* *The cost of looping and how to eliminate loops*
* Praktik terbaik untuk iterasi dengan pandas DataFrames